### ISSUE TITLE
support for vacuum and optimize

### ISSUE THREAD

**Issue by ashitabh** [delta-io/delta#10]
do you support vacuum and optimize here ?

**Comment by xbaran** [comment]
+1

**Comment by tomasbartalos** [comment]
+1

**Comment by tdas** [comment]
We will! We are going to release all DMLs in the open source.

**Comment by tdas** [comment]
I have created official issues for each command
- Vacuum - #48 
- Optimize - #49 
We are hoping to more Scala/Java APIs soon. Please vote and discuss on those issues if you are interested. In the meantime, I am closing this issue.
