### ISSUE TITLE
Should the Titel of the documention not be the other why round?

### ISSUE THREAD

**Issue by s-winkelstraeter** [delta-io/delta#1011]
The Titel of the following documenation:

https://docs.delta.io/latest/snowflake-integration.html

is

"Snowflake to Delta Lake integration"

should it not be 

"Delta Lake to Snowflake integration"

because we describe how to move Delta Lake data to Snowflake?

As stated in the first sentence of the doc:
"A Delta table can be read by Snowflake using..."

**Comment by zsxwing** [comment]
Thanks for pointing out this issue. We will fix the doc when Delta Lake 1.2.0 is out.

**Comment by scottsand-db** [comment]
This has been fixed in https://docs.delta.io/1.2.0/snowflake-integration.html
