### ISSUE TITLE
write data to minio got No such file or directory _delta_log 

### ISSUE THREAD

**Issue by allenhaozi** [delta-io/delta#1040]
+ spark-3.2.1-bin-hadoop3.2
+ Scala 3.1.1

I tested it in the local MAC env, write a table to minio, I got this error, but `_delta_log`has been created 
 
```python
 spark.range(5).write.format("delta").save(
        "s3a://deltalake/demo")
```

```
py4j.protocol.Py4JJavaError: An error occurred while calling o47.save.
: java.io.FileNotFoundException: No such file or directory: s3a://deltalake/demo/_delta_log
```

**Comment by allenhaozi** [comment]
upgrade minio, fix it

**Comment by erikdao** [comment]
@allenhaozi Which version of MinIO are you using? I'm having the same problem.

**Comment by allenhaozi** [comment]
> @allenhaozi Which version of MinIO are you using? I'm having the same problem.

try it  `quay.io/minio/mc:RELEASE.2022-04-16T21-11-21Z`
