### ISSUE TITLE
Allow user-specified schemas on read

### ISSUE THREAD

**Issue by guyneedhamcanva** [delta-io/delta#105]
I would like to be able to `spark.read.format("delta").schema(mySchema)`. 

My reason is that I use Delta and another source in tandem and would like to be able to union the Dataset objects from the two sources. My schemas change over time with new fields being added as `Option`s. If the schema is out of date in the Delta lake, I cannot cast the `Row` I have read from Delta lake to the type required using my encoder. This is because the `Row` may lack the recently added column present in the schema, which is also present in the second data source.

Would it be possible in later releases to support user-specified schemas at read time?

**Comment by tdas** [comment]
If columns/fields are only going to be added, then there are two ways to deal with it. 
1. Explicitly add the new/missing columns to the dataframe created by `spark.read.format("delta").load()` (e.g. using `dataframe.withColumn`) and then applying union.
2. Explicitly add the new columns to the delta table's schema whenever there is a schema change. This can be done by `emptyDataFrameWithNewSchema.write.format("mergeSchema", "true").mode("append").save(...)`.

**Comment by guyneedhamcanva** [comment]
Thanks for the tips.
