### ISSUE TITLE
Version inconsistency between PyPI delta-spark (v1.0.0) and latest master release (v1.0.1)

### ISSUE THREAD

**Issue by davidg0mez** [delta-io/delta#1060]
The [delta-spark](https://pypi.org/project/delta-spark/) PyPI package has not been updated with the latest release [v1.0.1](https://github.com/delta-io/delta/releases/tag/v1.0.1).

I have noticed about it when using the [`configure_spark_with_delta_pip`](https://github.com/delta-io/delta/blob/5e2493804725832ec626823fdc7156cd7458b717/python/delta/pip_utils.py#L21) function since the `extra_packages` parameter was added in the v1.0.1 version.

I believe [automating PyPI releases](https://www.caktusgroup.com/blog/2021/02/11/automating-pypi-releases/) can be easily achievable with Github Actions although I haven't tried it myself.

**Comment by zsxwing** [comment]
> I have noticed about it when using the [`configure_spark_with_delta_pip`](https://github.com/delta-io/delta/blob/5e2493804725832ec626823fdc7156cd7458b717/python/delta/pip_utils.py#L21) function since the `extra_packages` parameter was added in the v1.0.1 version.

`extra_packages` is not available in any existing release. It will be available in 1.2.0 which will be available soon.

**Comment by zsxwing** [comment]
Closing this as it's asking an unreleased feature. This will be out in 1.2.0.
