### ISSUE TITLE
[Feature Request] Publish delta-spark to Conda

### ISSUE THREAD

**Issue by boonware** [delta-io/delta#1063]
### Overview

Publish the Python `delta-spark` package to a public Conda channel so that users of Conda can use Delta Lake. As of now, the package is only available at Pypi.

### Motivation

Many users, particularly in data science, leverage Conda for package management.

### Further details

Some packages are already available on Conda Forge, including `delta-sharing`.

### Willingness to contribute

The Delta Lake Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature?

- [ ] Yes. I can contribute this feature independently.
- [x] Yes. I would be willing to contribute this feature with guidance from the Delta Lake community.
- [ ] No. I cannot contribute this feature at this time.

**Comment by boonware** [comment]
@vkorukanti Would this be straightfoward to put in place?

**Comment by vkorukanti** [comment]
> @vkorukanti Would this be straightfoward to put in place?
Sorry I don't have full context on on what is required for publishing to Conda. We already publish to pypi. Can we extend it to do the same for Conda?

**Comment by boonware** [comment]
Conda is a separate package management solution. The following might help you get starte, assuming Conda Forge is the right place to publish the package (?).

1. Install Conda, see [here](https://docs.conda.io/en/latest/).
2. Define the Conda project by creating an environment file called `env.yaml` with the following contents:
```
name: delta-spark
channels:
- conda-forge
dependencies:
- conda-build
```
3. Create the Conda environment for the project: `conda env create -f env.yaml`
4. The above is sufficient for creating a project, but in order to build and publish it we also need a recipe/meta file. Conda Forge mention using `grayskull` to generate a recipe template for you, see [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#getting-started).

**Comment by scholer** [comment]
Having delta-spark available on conda-forge would be fantastic. 

We often use conda-forge to set up environments. The Conda ecosystem still has advantages over plain pypi, particularly for more complex environments, or if the environment requires non-python packages. With conda, I can create a complete environment for running Spark -- including e.g. OpenJVM and other things that are not available on pypi. If I wanted to do the same thing without conda, I would probably have to resort to Docker. And if I am using conda/mamba to set up my environment, it is best if as many packages as possible are available on conda-forge, so conda/mamba can find the best dependency solution.

**Comment by tdas** [comment]
I agree with conda being more powerful than pypi. It would be great if someone can contribute this.

**Comment by MrPowers** [comment]
I agree that it'd be great to have delta-spark in Conda.  In the meantime, just posting an example environment file demonstrating how delta-spark can be installed via pip into a Conda environment:

```
name: pyspark-322-delta-121
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pyspark=3.2.2
  - pip
  - pip:
    - delta-spark==1.2.1
```

**Comment by shubhamp051991** [comment]
The setup.py file references a version.sbt, which is missing from the PyPI delta-spark, and that will create an issue if we create the meta.YAML for conda-forge, any guidance on this would be helpful and I can work on this first issue

**Comment by scottsand-db** [comment]
@MrPowers - do you know the latest status of this? I recall you saying you knew a member of the community that was interested in working on this? Can you follow up with them and/or assign the issue to them?

**Comment by nkarpov** [comment]
I've submitted a PR https://github.com/conda-forge/staged-recipes/pull/21556 for this. It's passing all the tests so just waiting for a review now.

@shubhamp051991 I was able to resolve that issue (and another similar one with another missing file) by adding the required files as additional sources in the conda `meta.yaml` (refer to the PR for more details)

Once the PR is reviewed and active for the most recent release, we can add something in this repo to generate future release conda `meta.yaml`

**Comment by MrPowers** [comment]
Here's the conda-forge link to the package: https://anaconda.org/conda-forge/delta-spark

**Comment by dennyglee** [comment]
Perhaps we should also create a new feature request to publish deltalake to conda as well?

**Comment by scottsand-db** [comment]
@nkarpov isn't this done?

**Comment by zsxwing** [comment]
Closing this. We have published it to conda: https://anaconda.org/conda-forge/delta-spark
