### ISSUE TITLE
[DML] log path garbage collection.

### ISSUE THREAD

**Issue by cfmcgrady** [delta-io/delta#108]
Delta already implements `Vacuum` command for data path garbage collection in the latest version, but I can't find any collection mechanism for log path (default value is `_delta_log`).
otherwise, the delta log file will grow fast in an append Structured Streaming program.
I think is a batter idea to collect these log file when we run `Vaccum` command.

**Comment by marmbrus** [comment]
Log cleanup happens automatically on every commit. By default the retention period is 30 days.

You can find the code in [MetadataCleanup](https://github.com/delta-io/delta/blob/master/src/main/scala/org/apache/spark/sql/delta/MetadataCleanup.scala).

**Comment by cfmcgrady** [comment]
hi, @marmbrus 
`MetadataCleanup.doLogCleanup()` never been invoke by `DeltaLog` in current open source version.
and another question is: if we do log clean up on every commit, and do data clean up on run `Vaccum` command, we maybe got commit info without data or data without commit info, do these operations confuse the user?

**Comment by cfmcgrady** [comment]
should we put log clean up operation and data clean up operation together?

**Comment by zsxwing** [comment]
@cfmcgrady It's called here: https://github.com/delta-io/delta/blob/v0.3.0/src/main/scala/org/apache/spark/sql/delta/Checkpoints.scala#L124
