### ISSUE TITLE
Add pypsark api for Optimize

### ISSUE THREAD

**Issue by kbafna-antuit** [delta-io/delta#1080]
Can we add functions to DeltaTable to perform optimization in pyspark ?
Or is there any other way to do in the delta release 1.2.0 ?

**Comment by vkorukanti** [comment]
Hi @KeertiBafna, currently there are Python APIs for optimize. Scala APIs are being added in https://github.com/delta-io/delta/pull/961. Let us know if you are interested in contributing the Python APIs.

**Comment by burakyilmaz321** [comment]
Hi @vkorukanti 👋 I can work on this if it's ok.

**Comment by burakyilmaz321** [comment]
@vkorukanti I initiated some draft work [here](https://github.com/delta-io/delta/pull/1091). You can check it out and let me what you think. I am planning to test this by building #961 locally. I appreciate any guidance 😅

**Comment by vkorukanti** [comment]
@burakyilmaz321 The python test failures on `master` branch are fixed now. Could you please rebase this PR? Thank you!
