### ISSUE TITLE
[Feature Request] DeltaLake support for Change Data Capture

### ISSUE THREAD

**Issue by lkrishna-cs** [delta-io/delta#1106]
### Overview

Seems like only Databricks version of DeltaLake support Change Data Capture (CDC). This is such a key concept that should be made available in the open source version as well. Curious to know if you have plans to support it in future releases.

### Motivation

Customer need ability to track changes to data using DeltaLake framework as they may not have a licensed version of Databricks.

### Willingness to contribute

The Delta Lake Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature?

- [ ] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the Delta Lake community.
- [ x] No. I cannot contribute this feature at this time.

**Comment by scottsand-db** [comment]
Hi @lkrishna-cs - thanks for making this issue. Funny enough, this past Friday I made the issue #1105 (yours is 1106) which provides exactly what you're asking for - Delta Lake support for Change Data Feed.

Feel free to review that issue, the design doc, proposed APIs, and the project plan.

If that issue #1105 resolves your feature request (I think it does), please close this issue.
