### ISSUE TITLE
[BUG] [unresolved dependency: io.delta#delta-core_2.12;1.2.1: not found]

### ISSUE THREAD

**Issue by allenhaozi** [delta-io/delta#1121]
This dependency package cannot be downloaded online because we are a private cloud environment

Can this dependency package be downloaded in advance and put in the docker image? We are Spark on K8S

**Comment by dnskr** [comment]
This is not a bug. You don't have dependency you use in your code, so you have to add it.
You can build you own docker image on top of pure Spark image with all dependencies you need.
Which exactly docker image do you use?

**Comment by allenhaozi** [comment]
thank u @dnskr 
Now I have downloaded them in advance and put them under $SPARK_HOME/jars . It will work
But I added an $SPARK_HOME/extjar directory and it didn't work

"${SPARK_HOME}/conf/spark-env.sh"
```
"SPARK_CLASSPATH=${SPARK_CLASSPATH}:${SPARK_HOME}/jars/*:${SPARK_HOME}/extjars/*" >> 
```

I need to add deltalake and S3 to the PySpark image
