### ISSUE TITLE
[Feature Request]Add SBT test coverage report

### ISSUE THREAD

**Issue by zsxwing** [delta-io/delta#1123]
### Overview

Currently Delta Lake doesn't have a test coverage report. It would be great to integration with some test coverage SBT plugin so that we can see the test coverage report in every PR.

### Motivation

A test coverage report would help us understand whether we have enough tests to cover changes in a PR.

**Comment by dragongu** [comment]
can you assign it to me? thanks @zsxwing

**Comment by tdas** [comment]
done  @dragongu

**Comment by hedibejaoui** [comment]
@dragongu Are you actively working on this? If not, I could take a stab at it.

**Comment by zsxwing** [comment]
@hedibejaoui I don't see any progress on this. Feel tree to try this
