### ISSUE TITLE
[BUG]How to reduce the delta log size By manually

### ISSUE THREAD

**Issue by kongluo** [delta-io/delta#1130]
My delta lake has been running for more than half a year. I found that the size of the delta lake log is getting bigger and bigger. I have set delta.logRetentionDuration to 1 month to clean up the log regularly, but the size of the log is still increasing

![image](https://user-images.githubusercontent.com/28140815/168234904-fd920a99-7253-44cb-baf7-6c66f15b28f0.png)

Where did the log of more than 800 M come from? I don’t see that many checkpoint logs. Does delta lake read the entire checkpoint and several json files under the current version?

![image](https://user-images.githubusercontent.com/28140815/168240070-3e53cdce-7181-4ebd-8e18-1695bee4ac92.png)

I see that all the operation records of ADD and REMOVE are stored in the delta log. Is there no way to delete this operation record? Our data are basically append operations, can I reduce the size of the delta log with some manual operations?

Because I found that with the increase of logs, the operation time of Compute snapshot for version is also increasing, and even the time of this operation has exceeded the time of our business operation, and this operation is very frequent
![image](https://user-images.githubusercontent.com/28140815/168235619-b8308cc8-fcc1-4574-b0e5-31b8d2214623.png)

* Delta Lake version: 1.0.1
* Spark version: 3.1.1
* Scala version: 2.12.2

**Comment by tdas** [comment]
Increase in time for computing snapshot indicates that the number of parquet data files managed the delta log is increasing. You can see this in the Delta Describe Detail command. If that is large, then you should run Delta Optimize command (released with Delta 1.2 on Spark 3.2) to compact the files in larger 1GB-ish files. That will reduce the number of files and make the snapshot computation faster.

**Comment by kongluo** [comment]
> Increase in time for computing snapshot indicates that the number of parquet data files managed the delta log is increasing. You can see this in the Delta Describe Detail command. If that is large, then you should run Delta Optimize command (released with Delta 1.2 on Spark 3.2) to compact the files in larger 1GB-ish files. That will reduce the number of files and make the snapshot computation faster.

When I was developing at the time, the latest version of Delta lake was 1.0.0. We merged the parquet files in Delta lake by adopting physical isolation, but the number of parquets in the original table was constantly increasing. May I ask you to delete + Can vaccum physically delete parquet files to reduce the size of delta log? Why did I delete in this way, the size of the delta log did not decrease? Is there no way to reduce the size of the delta log by removing the metadata?

**Comment by kongluo** [comment]
> Increase in time for computing snapshot indicates that the number of parquet data files managed the delta log is increasing. You can see this in the Delta Describe Detail command. If that is large, then you should run Delta Optimize command (released with Delta 1.2 on Spark 3.2) to compact the files in larger 1GB-ish files. That will reduce the number of files and make the snapshot computation faster.

I found that it is necessary to configure the time to delete log files through the deletedFileRetentionDuration configuration. When the delete operation is performed, the configuration defaults to 7 days, and the DeltaLog file will be cleaned up after 7 days.

**Comment by tdas** [comment]
Yes, exactly. Glad you found out. :) Did that solve the problem?

**Comment by kongluo** [comment]
> Yes, exactly. Glad you found out. :) Did that solve the problem?

Yes, it solves my problem, thank you very much for your reply

**Comment by allisonport-db** [comment]
Closing this, feel free to reopen as needed.
