### ISSUE TITLE
[Feature Request]Add a check to verify the required Spark confs

### ISSUE THREAD

**Issue by zsxwing** [delta-io/delta#1144]
### Overview

We saw a few reported issues due to missing configs. We can add a check in DeltaLog to verify the following Spark confs.

```
--conf "spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension" --conf "spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog"
```

If these are not set, we can throw a user friendly error.

### Motivation

Provide a user friendly error rather than throwing random weird errors.

### Willingness to contribute

The Delta Lake Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature?

- [ ] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the Delta Lake community.
- [x] No. I cannot contribute this feature at this time.

**Comment by ganeshchand** [comment]
@zsxwing I can work on this feature. Please feel free to assign this to me.

**Comment by ganeshchand** [comment]
It looks like https://github.com/delta-io/delta/pull/1238  will throw a prescrivtive user friendly error if the required spark configs are not provided. Is my understanding correct?

**Comment by zsxwing** [comment]
In addition, if `DeltaSparkSessionExtension` is not set, nothing will be caught.

**Comment by ganeshchand** [comment]
Thanks for the clarification. I am working on it and will send the PR soon.

**Comment by zsxwing** [comment]
@ganeshchand could you open a PR so that we can discuss the details?
