### ISSUE TITLE
Executor Memory Full after multiple merge

### ISSUE THREAD

**Issue by parisni** [delta-io/delta#115]
Hi

I am doing merges on several tables.
when I create a new spark context for each merge, this works fine.

however, when I use the same spark context for sequential merges, the executor memory 
is full and the process breaks.

```
 ERROR YarnScheduler: Lost executor 14 on host: Container killed by YARN for exceeding memory limits. 10 GB on 9 GB
```
how to  release of the executor memory between merges ? 

thanks

**Comment by tdas** [comment]
It is worth investigating what is occupying the memory in the executor. You can look in the Spark UI to investigate. In the merge operation, we dont explicitly cache any RDD/DataFrame that could occupy the executor memory. However, it could be that the merge operation internally is causing a broadcast join and the broadcasted data would occupy the executor memory. However, the broadcasted data should be automatically dropped when there is memory pressure (that is, next merge needs to broadcast something new). So I am not quite sure how it could lead to this error. 

I am not familiar with the YARN setting, but maybe the YARN container memory limit and the executor heap size limit are not correctly configured? Hence the executor is trying to use more memory and YARN is killing it?

**Comment by parisni** [comment]
I managed to overcome the problem by increasing `spark.executor.memoryOverhead`.
I haven't been able to reproduce the sequential problem so i guess the problem was more related to a bad spark executor configuration than a yarn configuration problem or a delta-lake merge problem. thanks
