### ISSUE TITLE
[Question] Usage conflict between Compaction/Vacuum and Time Travel

### ISSUE THREAD

**Issue by Dearkano** [delta-io/delta#1153]
OPTIMIZE (Compaction) will double the table size, if we use VACUUM to release the space after the compaction (maybe after each data ingestion), the time travel will not be available anymore. 
I'm wondering if there's a best practice for combining compaction and time travel, or we have to bare with doubled table size.
Thank you!

**Comment by scottsand-db** [comment]
Hi @Dearkano - thanks for your question. We will get back to you shortly.

**Comment by scottsand-db** [comment]
Hi @Dearkano - as you surmised, this is the inevitable tradeoff between OPTIMIZE and workloads that use time travel. Delta Lake doesn't provide a solution for this right now. Perhaps you could ask in the delta users slack channel and see if there are other customers/users in a similar position as you?
