### ISSUE TITLE
[Question] Create old version manifest file

### ISSUE THREAD

**Issue by mulan101** [delta-io/delta#1159]
I have created a manifest file to retrieve DeltaTable data from athena. 
Is it possible to create a point-in-time manifest file to retrieve old version data without rollback the data?

Thank you

**Comment by zsxwing** [comment]
Currently we don't support this. Delta has a Presto connector which supports time travel: https://prestodb.io/docs/current/connector/deltalake.html Would you be able to push Athena to support it as well? A native support would be much better than the manifest files.

**Comment by mulan101** [comment]
Thanks for your reply. 
We will request it as a new feature through the AWS Support Case. 

thank you

**Comment by zsxwing** [comment]
Cool. Closing this ticket. We will focus on improving the Presto native support rather than improving the manifest files.
