### ISSUE TITLE
[Feature Request] Python APIs for OPTIMIZE ZORDER BY

### ISSUE THREAD

**Issue by vkorukanti** [delta-io/delta#1185]
## Feature request
Currently OPTIMIZE ZORDER can only be triggered using the SQL command. This task is to add a Python API to trigger the same.

Similar task for OPTIMIZE file compaction https://github.com/delta-io/delta/issues/1080

**Comment by ahlag** [comment]
@vkorukanti 
Please assign me. I will work on it.

**Comment by chrimaho** [comment]
Hi Team!

I'd like to set up a much easier way to optimize my `delta` tables. Specifically, I am referring to the `sql` command `OPTIMIZE <table>`.

Let me show you the differences:

**Current:**

First, run:

```python
import pandas as pd
df = spark.createDataFrame(
    pd.DataFrame(
        {'a': [1,2,3,4],
         'b': ['a','b','c','d']}
    )
)
df.write.mode('overwrite').format('delta').save('./folder')
```

Then, once it's saved, run:

```sql
CREATE TABLE df USING DELTA LOCATION './folder'
```

Then, once the table is loaded, run:

```sql
OPTIMIZE df
--or
OPTIMIZE df ZORDER BY (b) 
```

As you can see, there are many steps needed.

**Future:**

I'd like to be able to do something like this:

```python
import pandas as pd
df = spark.createDataFrame(
    pd.DataFrame(
        {'a':[1,2,3,4],
         'b':['a','b','c','d']}
    )
)
df.write.mode('overwrite').format('delta').options(optimize=True).save('./folder')
#or
df.write.mode('overwrite').format('delta').options(optimize=True, zorder_by=('b')).save('./folder') 
```
As you can see, it's much more streamlined, and keeps the code to a higher-level.

Thank you.
 
References:
- https://docs.azuredatabricks.net/_static/notebooks/delta/optimize-python.html
- https://medium.com/@debusinha2009/cheatsheet-on-understanding-zorder-and-optimize-for-your-delta-tables-1556282221d3
- https://www.cloudiqtech.com/partition-optimize-and-zorder-delta-tables-in-azure-databricks/
- https://docs.databricks.com/delta/optimizations/file-mgmt.html
- https://docs.databricks.com/spark/latest/spark-sql/language-manual/delta-optimize.html
- https://stackoverflow.com/questions/65320949/parquet-vs-delta-format-in-azure-data-lake-gen-2-store?_sm_au_=iVV4WjsV0q7WQktrJfsTkK7RqJB10
- https://www.i-programmer.info/news/197-data-mining/12582-databricks-delta-adds-faster-parquet-import.html#:~:text=Databricks%20says%20Delta%20is%2010,data%20management%2C%20and%20query%20serving.

**Comment by vkorukanti** [comment]
@chrimaho There is an [issue](https://github.com/delta-io/delta/issues/815) open to support the use case you mentioned. Basically as part of every write, there will be a compaction job followed. We can't run the Z-Order (as it is an expensive operation and will delay the writes), but compaction can be part of the write. Feel free to provide your usecase requirements on the [issue](https://github.com/delta-io/delta/issues/815).
