### ISSUE TITLE
Can I write data from remote machine? 

### ISSUE THREAD

**Issue by EasyLuck** [delta-io/delta#1196]
Hi~
I have a question:
Can I write my data to the delta lake with a ip and port from a remote machine?
I want to upload data from local machine to delta lake in server machine. Can I do it?

**Comment by zsxwing** [comment]
A delta lake table is just a set of files on the file system. There is no server machine. Do you mean you want to write a server that can accept data from a client and write the data to a Delta lake table?

**Comment by EasyLuck** [comment]
Yes

**Comment by zsxwing** [comment]
Delta Lake is a storage format. We don't provide any service right now.

**Comment by EasyLuck** [comment]
Can we store image data in it?
I have not found this in doc.

**Comment by zsxwing** [comment]
There is an example to store images in https://github.com/delta-io/delta/blob/master/examples/python/image_storage.py

**Comment by EasyLuck** [comment]
Thank you very much.

**Comment by zengyangjie** [comment]
Hi~
When I find this issue, I think you may run this benchmark on server machine but not on S3. 
Can this benchmark run on local server machine?

Thanks.
