### ISSUE TITLE
[Question] Comment mention a non-existing file

### ISSUE THREAD

**Issue by felipepessoto** [delta-io/delta#1204]
### Describe the problem
DeltaScan mention a DataSkippingReaderV2.scala: https://github.com/delta-io/delta/blob/6707b29f58a30989f40478ce40b3200c48bf37ce/core/src/main/scala/org/apache/spark/sql/delta/stats/DeltaScan.scala#L55

Is this part of any work in progress?

**Comment by vkorukanti** [comment]
I think they are not relevant to the code or any future work. The comments can be removed.

**Comment by felipepessoto** [comment]
https://github.com/delta-io/delta/pull/1207
