### ISSUE TITLE
Make replaceWhere work at arbitrary granularity.

### ISSUE THREAD

**Issue by shaharco** [delta-io/delta#121]
The idea here is to be able to use the replaceWhere  syntax without overwriting the entire partition, but only part of the rows.

Thanks

**Comment by tdas** [comment]
For updating an arbitrary subset of the table data, please use the Update or Merge APIs released in [0.3.0](https://docs.delta.io/0.3.0/delta-update.html#update-a-table).

**Comment by shaharco** [comment]
@tdas but this is not exactly the same, Update only update existing rows, and Merge as well plus adding and deleting. What i mean  replacing a bunch of rows with rows from input DF.
For example let's say you partition you data on a weekly date and you have rows for 1/1.
Now you get input file that also contains row for 1/1 (not necessarily the same row count) and you want those rows to replace the table rows from 1/1, but you don't want to replace the whole partition. I hope it makes sense.

**Comment by marmbrus** [comment]
+1, I don't see any reason why we could not support atomic swap of arbitrary subsets of a table. It'll be much much more expensive than partition swaps, but thats already true of our DML implementations.

**Comment by SpaceRangerWes** [comment]
I've been looking into this item and came up with some thoughts. 

https://docs.google.com/document/d/1KnIlzvUayv20EaRrFagBVmgUM7FrNVrfrThMCL0r4_Q/edit?usp=sharing

**Comment by zsxwing** [comment]
This is supported after the following commits:

- https://github.com/delta-io/delta/commit/ae99d7190ad0f74b5126b1a4be7eddae1c7d046f
- https://github.com/delta-io/delta/commit/00a71f225530223515e624df9b254e884a70386a
