### ISSUE TITLE
Issues with non-deterministic behavior when writing to Delta format

### ISSUE THREAD

**Issue by aleksandraangelova** [delta-io/delta#1218]
When doing a regular partition overwrite over large datasets, we are encountering non-deterministic behavior from Delta. 

We have a fairly complex ETL job which extracts, transforms and then loads data from Snowflake to an Azure storage container in Delta format. When executing the job multiple times, we get different results, even though we are loading the same data from Snowflake. We get strange duplicated values which are not supposed to occur:

| version | number of duplicated records |
| ------- | ------- |
| 297 | 18663736 |
| 298 | 1491160 |
| 299 | 7369654 |
| 300 | 36846189 |
| 301 | 8647811 |
| 302 | 0 |

At each iteration we execute the same code and load the same data, yet we get different results and a varying number of duplicated records (desired number is 0).

After each transformation we do .cache().count() of the resulting data frame and no duplicates appear at those stages. It is only after we do the partition overwrite that the duplicated records materialize.

The way we overwrite the partitions is as follows:

```python
def overwrite_delta(updates_df, *, delta_target=None, partition_fields=None, **kwargs):
    """Overwrite Delta table partitions with new data"""
    partition_to_overwrite = get_partition_values(
        updates_df=updates_df, partition_fields=partition_fields, prefix=""
    )
    print(f"Overwriting partition: {partition_to_overwrite}")
    (
        updates_df.write.format("delta")
        .mode("overwrite")
        .option("replaceWhere", partition_to_overwrite)
        .partitionBy(*partition_fields)
        .save(delta_target)
    )
```

I have not yet found a way to reproduce the issue with a small dataframe requiring simple transformations. It seems to be happening when we are loading a very large data frame and performing multiple Spark transformations on top of it, then writing it in Delta format to a specific location. 

### Environment information

* Delta Lake version: 1.0.0
* Spark version: 3.1.2

Running on Databricks Runtime 9.1 LTS.

**Comment by aleksandraangelova** [comment]
Unfortunately I don't have the rights to file a Service Support request in Azure. I am waiting for the required role but it might take some time, so I decided to post here. Will submit a support ticket as soon as possible.

**Comment by bart-samwel** [comment]
@aleksandraangelova For now, here's my thoughts:

* You are reading the dataframe twice: once to determine `partition_to_overwrite` and once to write the actual updates. If the dataframe is extended with new partition key values between those two executions, then the overwriting will not delete data from those new partitions.

* If materializing the `updates_df` into a Parquet really helps, then it is very likely that that dataframe is not deterministic. What is happening in that dataframe? If it is reading from Snowflake, then are you sure that that Snowflake base table is not being _added to_ while you are doing this write? Because that would explain the behavior -- you might get new partition keys that are not in `partition_to_overwrite` but that are being written to.

**Comment by aleksandraangelova** [comment]
Thanks for the feedback @bart-samwel 
In our implementation the data frame could not have been extended during the read to determine the partitions because no other process is writing to this table and it is a data frame loaded in memory. 

For the test, I loaded 3 days from Snowflake into a separate storage container and I know I am always reading those 3 days that I have loaded once - this means that I am always reading the same data.

**Comment by aleksandraangelova** [comment]
And actually saving to intermediate Parquet files does not help :( After running the process again with this workaround, some duplicates reappeared, even though they were gone before that.

**Comment by bart-samwel** [comment]
@aleksandraangelova  So when do you save to parquet? Before determining the partitions to write to, or afterwards?

And what happens in updated_df? Is there a computation happening there or is it a straight-up read from a table?

**Comment by aleksandraangelova** [comment]
In our job we have an extractor, transformers and loaders defined as functions.
The extractor retrieves the data from Snowflake (in my recent runs I've been using a static copy of the data located in an Azure storage container). 
The resulting df then goes through some transformations and then it is finally loaded in Delta format to a destination storage container.

Essentially, the process is as follows:

```
updates_df = extractor()
updates_df = transformer(updates_df)
updated_df.cache().count()
overwrite_delta(updated_df)
```

**Comment by bart-samwel** [comment]
@aleksandraangelova So my concern would be with `transformer`. It may contain operations that are not deterministic. If it gets executed twice (which `overwrite_delta` does), then it may return different results each time.

FWIW, it's very hard to reason about what is deterministic in Spark and what is not. A common reason for nondeterminism include window functions with ORDER BY that don't specify a total order. Or a LIMIT without ORDER BY, or with an ORDER BY that doesn't specify a total order. Those may get executed differently every time, leading to different results.

**Comment by aleksandraangelova** [comment]
Yes, I understand. I have looked at the transformer multiple times and it does not seem to have such operations. However, it is possible that something is messed up there, yet I can't figure out what it could be.
In general, this process runs daily and processes usually 1 day of data without any sort of unexpected results, so it is strange that when I take a bigger time frame and execute it multiple times, it produces different results (including the unexpected duplicates).

**Comment by bart-samwel** [comment]
I think this requires a deeper inspection of the code -- the issue may be very subtle. I expect that it's probably not OK to share that code in this public channel. At this point we should probably take this to a Databricks support ticket for further digging.

**Comment by aleksandraangelova** [comment]
I have found a workaround solution to the problem - when I save the results after each major transformation step in delta format and then I save them again after the last transformation to the final target table, the duplicates seem to disappear.

```updates_df = loader()
updates_df = transformation_1(updates_df)
updates_df.write.format("delta").save("/path1")
updates_df = spark.read.format("delta").load("/path1")
...
```

**Comment by aleksandraangelova** [comment]
I wanted to leave this here in case in might help someone - we are doing a transformation which repartitions the data without using key columns. This could be causing the non-deterministic behavior when we are doing very large loads. 

https://issues.apache.org/jira/browse/SPARK-23207

**Comment by aleksandraangelova** [comment]
Tests confirm that the repartioning command in one of our transformations is causing the diplicates.
Usage of repartition(n) wihout providing key fields to repartition the files by is discouraged.

It's not a problem when it's executed once but it's a problem when the operation is executed multiple times
It's probably something failing - maybe it's running on spot instances - and then the task gets restarted and the files are shuffled in a different order, causing duplicates.

It could be that the plan execution runs out of RAM memory and spills to disk - this itself may change the order the results are sent in.

Thank you, @bart-samwel , for all the help :)
