### ISSUE TITLE
[Feature Request] SparkSQL support TimeTravel

### ISSUE THREAD

**Issue by huzk8** [delta-io/delta#1242]
### Overview

Now we just can use spark dataframe api to query table of history version.

### Motivation

Need support use sparksql to time travel.
### Further details
just like below:
```
SELECT * FROM default.tb1  VERSION AS OF 2

```

### Willingness to contribute

The Delta Lake Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature?

- [ ] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the Delta Lake community.
- [x] No. I cannot contribute this feature at this time.

**Comment by zsxwing** [comment]
Thanks for raising the request. We already have a ticket for this request #128. You can watch it to get the latest update.

**Comment by huzk8** [comment]
> Thanks for raising the request. We already have a ticket for this request #128. You can watch it to get the latest update.

I use delta-core_2.12-2.0.0rc1、Spark3.2.1 for testing.
```
== SQL ==
SELECT * FROM default.people10m_upload TIMESTAMP AS OF '2018-10-18T22:15:12.013Z'
-------------------------------------------------^^^

spark-sql>
```

**Comment by zsxwing** [comment]
@huzk8 I updated the issue #128 to make it clear that the SQL syntax would require Spark 3.3 and Delta Lake doesn't support it yet.
