### ISSUE TITLE
[BUG] Fix Readme and/or Slack Channel SSO

### ISSUE THREAD

**Issue by edmondo1984** [delta-io/delta#1243]
## Bug

If you try to sign up on the Slack Workspace using the link in the README, you get redirect to a page where you can log-in via Google credentials only if you are a Databricks employee. This is a little counter intuitive, and it took me a little to figure out that I couldn't login with my Google credentials, but rather I should have selected "Sign Up with your email" and use my gmail account

If this is the desired behavior, maybe we should add some content to the README. We can probably make the experience more friendly by also adding a welcome message that would have explained me how to use different channels (where to ask for help, for example)

**Comment by dennyglee** [comment]
Thanks @edmondo1984 - as you noted #1270 should resolve this issue and we'll close once we merge it in.  Thanks!

**Comment by zsxwing** [comment]
The slack link has been fixed. Closing this
