### ISSUE TITLE
[Question] Can we use Delta Lake 1.2.0 on Spark 3.1.2?

### ISSUE THREAD

**Issue by tilumi** [delta-io/delta#1258]
Hi, since Azure HDInsight only support up to Spark 3.1.2, & we want to use Optimize Table command only In Scala code, can we use 1.2.0 on Spark 3.1.2? What issues we may encounter if we use this combination?

**Comment by allisonport-db** [comment]
Unfortunately we only support Spark 3.2 currently. I would expect to see some compatibility issues where ever delta code uses Spark code that has changed between the versions.

**Comment by zsxwing** [comment]
Closing this as we don't have any future plan to make 1.2.0 work with Spark 3.1.x
