### ISSUE TITLE
Delta does not support case sensitive column name duplication

### ISSUE THREAD

**Issue by SpaceRangerWes** [delta-io/delta#126]
In catalyst's [SchemaUtils](https://github.com/apache/spark/blob/c80430f5c9189b37ac1209db0453dbd9bb5c767e/sql/catalyst/src/main/scala/org/apache/spark/sql/util/SchemaUtils.scala#L35-L46) the case sensitive flag (spark.sql.caseSensitive) is supported. However, that support is not carried over through Delta's implementation of it https://github.com/delta-io/delta/blob/master/src/main/scala/org/apache/spark/sql/delta/schema/SchemaUtils.scala#L150-L169

This ought to be added due to a loss of functionality as compared to the default implementation.

**Comment by tdas** [comment]
If we are not matching the behavior expectations of Spark queries, then it should be considered as a bug. So that we understand this in more detail, can you explain the end-to-end use case where this is affecting you?

**Comment by brkyvz** [comment]
@SpaceRangerWes Delta doesn't support column names that only differ by case. This was a conscious design decision as we've seen too many bugs around data corruption caused because people don't use the right case when they are querying or saving their data.

**Comment by SpaceRangerWes** [comment]
@brkyvz I'm totally understanding of that. Would this be a good item for the delta.io FAQ?

**Comment by brkyvz** [comment]
Hey @SpaceRangerWes, definitely. This was an oversight in documentation. We will update documentation accordingly. In fact, a blog post should come out within the next two weeks around it as well :)

**Comment by SpaceRangerWes** [comment]
@brkyvz I'll go ahead and close this since it was by design. Thanks.
