### ISSUE TITLE
[BUG] Fix documentation for DeltaTable.forPath

### ISSUE THREAD

**Issue by vkorukanti** [delta-io/delta#1272]
## Bug
Currently the [doc](https://github.com/delta-io/delta/blob/master/core/src/main/scala/io/delta/tables/DeltaTable.scala#L621) for `DeltaTable.forPath` says `Create a DeltaTable for the data at the given `path`.`. This is not correct. This API just instantiates the `DeltaTable` representing the path. 

Also we need to clarify what it means when there is no table exists at the given path.

**Comment by ganeshchand** [comment]
Not sure if this is a bug. Create here doesn't mean  - it is actually persisting a delta table in the storage system. Create here means - it is instantiating a `DeltaTable` class with a given path.

**Comment by zsxwing** [comment]
@ganeshchand as the class name is called `DeltaTable`, it's pretty easy to mislead people to read it as `create a Delta table`. It would be great to improve it a bit 😄

**Comment by yikf** [comment]
Can i fix this problem please, i filed a [pr](https://github.com/delta-io/delta/pull/1275)😄
