### ISSUE TITLE
Updates will report errors

### ISSUE THREAD

**Issue by zhangxinjian123** [delta-io/delta#131]
deltaTable.as("t")
            .merge(
              sparkSql.as("s"),
              "s._row_key = t._row_key")
            .whenMatched().updateAll()
            .whenNotMatched().insertAll()
            .execute()

Why is my update wrong?

Caused by: java.lang.UnsupportedOperationException: Cannot perform MERGE as multiple source rows matched and attempted to update the same target row in the Delta table

**Comment by tdas** [comment]
You probably have multiple rows in `s` that have the same `_row_key`. If multiple rows in the source dataframe that matches a row in the target table, then it is ambiguous and unclear which row should update the target row. Hence this is not allowed. This is the SQL standard behavior for the SQL Merge command and all systems implement this behavior. 

The solution is to preprocess `s` to ensure `_row_key` is unique in the dataframe passed to merge.

**Comment by tdas** [comment]
Here is an actual example to do something like this. 
https://docs.delta.io/latest/delta-update.html#write-change-data-into-a-delta-table

If you want to merge key-value change log into a delta table, then the changes must be preprocessed to pick the latest changes for each key. Only then can you call merge.

**Comment by zhangxinjian123** [comment]
val latestChangeForEachKey = changesDF
  .selectExpr("key", "struct(time, newValue, deleted) as otherCols" )
  .groupBy("key")
  .agg(max("otherCols").as("latest"))
  .selectExpr("key", "latest.*")

What is the method of max("otherCols")，no max method

**Comment by zhangxinjian123** [comment]
+--------+----+---------+------------+----------+---+
|_row_key| Age|timestamp|        Name| partition| id|
+--------+----+---------+------------+----------+---+
|      50|  16| 30198787|       zhang|2019-08-16| 10|
|      50|  16| 30198787|       zhang|2019-08-16| 10|
|      50|  16| 30198787|       zhang|2019-08-16| 10|
|      50|  16| 30198787|       zhang|2019-08-16| 10|



         val  pathToEventsTable="E:\\tmp\\delta\\mysql03";
          val deltaTable = DeltaTable.forPath(spark, pathToEventsTable)

          val latestChangeForEachKey = sparkSql
            .selectExpr("_row_key", "struct(Age,timestamp,Name,partition,id) as otherCols" )
              .groupBy("_row_key")
              .agg(max("otherCols").as("latest"))
              .selectExpr("_row_key","latest.*")


          deltaTable.as("t")
            .merge(
              latestChangeForEachKey.as("s"),
              "s._row_key = t._row_key")
            .whenMatched("s.Name = 'zhang'")
            .delete()
            .whenMatched()
            .updateExpr(Map("_row_key" -> "s._row_key", "Age" -> "s.Age"))
            .whenNotMatched("s.Name= 'xin'")
            .insertExpr(Map("_row_key" -> "s._row_key", "Age" -> "s.Age","timestamp"->"s.timestamp"
            ,"Name"->"s.Name","partition"->"s.partition","id"->"s.id"
            ))
            .execute()


I can't insert or delete data with a code.

**Comment by pranavanand** [comment]
When you say you can't insert or delete data, do you mean you're getting an error? If so, what is the stack trace?

**Comment by zsxwing** [comment]
Closing the stale ticket.
