### ISSUE TITLE
Is Z-Order working with Delta 1.2.0 as well?

### ISSUE THREAD

**Issue by bhadreshshiyal** [delta-io/delta#1313]
I am using Spark 3.2 on Azure Synapse Analytics which includes Delta 1.2.0. As per the documentation here --> [https://docs.delta.io/latest/optimizations-oss.html#z-ordering-multi-dimensional-clustering](https://docs.delta.io/latest/optimizations-oss.html#z-ordering-multi-dimensional-clustering), Z-Order is supported with Delta 2.0.0. and higher. However, we are able to run Z-Order with Delta 1.2.0 as well in Azure Synapse Analytics with Spark 3.2 cluster having Delta 1.2. We tried running the same on Azure Databricks and the outcome was same. Can you please confirm Delta 1.2.0 supports Z-Order or not? 

Thanks!

**Comment by zsxwing** [comment]
z-order was in Azure Databricks. And we recently open source it in Delta 2.0.0. For Azure Synapse Analytics, I think they have their own customized Delta Lake enhancements. I know little about their own Delta Lake enhancements.
