### ISSUE TITLE
[Feature Request] Include period (.) in Delta table name

### ISSUE THREAD

**Issue by ctezna** [delta-io/delta#1320]
### Overview

Allows users to create a Delta table that includes a period when using back ticks in the table DDL. Current error message when trying to create a table with a period:

Error in SQL statement: AnalysisException:`schema.name_of_table` is not a valid name for tables/databases. Valid names only contain alphabet characters, numbers and _.

** Back ticks are not shown in the text above, but the table name contains back ticks.

### Motivation

This feature will simplify migrations and allow a separation of namespaces similar to schemas in traditional databases. Projects that are migrating tables from traditional databases will be allowed to use the same names for the tables. Using an underscore to replace the period is not acceptable, because some table names already contain the underscore and it would not provide a distinction between namespaces.

Common examples of how this could be useful:

 - CREATE TABLE `bronze.product`
 - CREATE TABLE `silver.product`
 - CREATE TABLE `inventory.warehouse_location`
** Back ticks are not shown in the text above, but the table name contains back ticks.
 
I believe the best example is to facilitate the migration from other databases to Delta lake.

### Willingness to contribute

The Delta Lake Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature?

- [ ] Yes. I can contribute this feature independently.
- [x ] Yes. I would be willing to contribute this feature with guidance from the Delta Lake community.
- [ ] No. I cannot contribute this feature at this time.

**Comment by nkarpov** [comment]
Hi @ctezna - confirming that I can reproduce this behavior, 

```
spark.sql("CREATE TABLE `a.b.c` USING DELTA AS SELECT * FROM VALUES (0);")
``` 

There are a few interesting notes,

1. If doing a CTAS like operation, the underlying files actually do get created and just the metadata entry fails due to `validateName` in `org.apache.spark.sql.catalyst.catalog.SessionCatalog`
2. This applies to other formats like PARQUET too, ```CREATE TABLE `a.b.c` (id int) USING PARQUET ``` throws the same error

I think solving this requires changes to Spark and therefore this issue may be more appropriate there, would you agree?

**Comment by ctezna** [comment]
Hi @nkarpov after doing some further analysis, I agree. This should be a feature request for Apache Spark. Thanks for the feedback.
