### ISSUE TITLE
[Feature Request] Make `UPDATE` return the number of updated rows

### ISSUE THREAD

**Issue by scottsand-db** [delta-io/delta#1321]
### Overview

Currently, the `UPDATE` command does not return anything to the user. It would be more useful if we returned the number of updated rows.

### Motivation

The number of updated rows is an obvious metric that users would want from this operation.

### Further details

This should be pretty straight forward to implement - we already have access to `metrics("numUpdatedRows")` inside of `UpdateCommand.scala`. Remember to add tests, please!

**Comment by Silverlight42** [comment]
@scottsand-db can you please assign it to me? Just submitted a PR.

**Comment by allisonport-db** [comment]
Closing this as it has been implemented in #1331 and will be released with Delta 2.1
