### ISSUE TITLE
[QUESTION]Table history timestamp missing timezone information

### ISSUE THREAD

**Issue by boonware** [delta-io/delta#1392]
### Describe the problem
History timestamps are missing timezone information.

#### Steps to reproduce

```
from delta import DeltaTable

table = DeltaTable.forPath(spark_context, backend_url)
timestamp = table.history(depth).first()['timestamp']
```

#### Observed results

Retrieving the last commit timestamp from table history returns a value in the format `2022-09-21 13:45:08.100000`. This timestamp contains no timezone information. Am I to assume this is UTC?

#### Expected results

Timestamp contains timezone information.

### Environment information

delta-spark 1.2.1 and also tried 2.1.0 (Python)

### Willingness to contribute

The Delta Lake Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the Delta Lake code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the Delta Lake community.
- [ ] No. I cannot contribute a bug fix at this time.

**Comment by zsxwing** [comment]
> Retrieving the last commit timestamp from table history returns a value in the format `2022-09-21 13:45:08.100000`. This timestamp contains no timezone information. Am I to assume this is UTC?

No. The timezone is the default timezone you set in Spark. The string you see in the data is just for displaying. Spark itself stores the timezone for a timestamp type, and you don't need to worry about it.

**Comment by boonware** [comment]
@zsxwing Thanks for the clarification. I can think of use cases where having the timezone in the timestamp itself would be useful. For example, consider a batch data processing application (ETL etc.) that wants to read the timestamp to determine when the last commit was to construct a time window for the next batch upload.

**Comment by zsxwing** [comment]
> I can think of use cases where having the timezone in the timestamp itself would be useful.

Timezone information is there. Delta gives Spark the milliseconds since epoch. Then Spark decides how to show it. For example, the following code will show the timezone information:
```
>>> table.history().selectExpr("date_format(timestamp, 'yyyy-MM-dd HH:mm:SS VV') as timestamp_with_timezone").show(truncate=False)
+------------------------------+
|timestamp_with_timezone       |
+------------------------------+
|2022-09-23 09:12:44 US/Pacific|
+------------------------------+
```
You can take a look at the blog post https://www.databricks.com/blog/2020/07/22/a-comprehensive-look-at-dates-and-timestamps-in-apache-spark-3-0.html to understand how this works.

**Comment by zsxwing** [comment]
Closing this as the question is answered. Delta does provide the timezone information to Spark. Users need to pick up the right APIs to retrieve it.
