### ISSUE TITLE
Delta Lake tables do not support dropping of partitions.

### ISSUE THREAD

**Issue by jwsmai** [delta-io/delta#1397]
## support dropping of partitions

The following SQL cannot delete the delta table partition：
`alter table clob_dw.ods_t_task_svc_task_1d drop partition (ds = '20220903')`
how to solve this problem?

**Comment by zsxwing** [comment]
You can just run `delete from clob_dw.ods_t_task_svc_task_1d where ds = '20220903'`. Delta's partitions are decided by the data itself. If the data for a partition doesn't exist in a table, the partition will not exist either.

**Comment by zsxwing** [comment]
Closing this as Delta will not support the hive partition management commands (add/drop partition) as it doesn't match Delta's design.
