### ISSUE TITLE
[QUESTION] spark streaming write to delta table cache growing

### ISSUE THREAD

**Issue by 0xdarkman** [delta-io/delta#1415]
spark 3.2.1
scala 2.12.12
hadoop 3.3.0
delta 1.2.1

I am running Spark with Scala in Kubernetes.
I am running two spark streaming jobs.

kafka >> job1: read stream from kafka, process, write stream to delta_table_1>> job2: read stream from delta_table_1, process, write stream to delta_table_2

job1 processes stream with window 5 minutes and watermark 1 minute
job2 processes stream with window 1 hour and watermark 5 minutes
SparkUI of job2, Storage tab, shows:

ID | RDD Name | Storage Level | Cached Partitions | Fraction Cached | Size in Memory | Size on Disk
-- | -- | -- | -- | -- | -- | --
15 | Delta Table State #116320 - wasbs://CONTAINER@SA1.blob.core.windows.net/TABLE1/_delta_log | Disk Memory Serialized 1x Replicated | 50 | 100% | 3.4 GiB | 0.0 B
113 | Delta Table State #60069 - abfss://CONTAINER@SA2.dfs.core.windows.net/TABLE2/_delta_log | Disk Memory Serialized 1x Replicated | 50 | 100% | 55.8 GiB | 0.0 B

ID	RDD Name	Storage Level	Cached Partitions	Fraction Cached	Size in Memory	Size on Disk
15	[Delta Table State #116320 - wasbs://CONTAINER@SA1.blob.core.windows.net/TABLE1/_delta_log](http://localhost:4040/storage/rdd/?id=15)	Disk Memory Serialized 1x Replicated	50	100%	3.4 GiB	0.0 B
113	[Delta Table State #60069 - abfss://CONTAINER@SA2.dfs.core.windows.net/TABLE2/_delta_log](http://localhost:4040/storage/rdd/?id=113)	Disk Memory Serialized 1x Replicated	50	100%	55.8 GiB	0.0 B

The issue is that most of the batches are processesed fine but every ~30min one batch is being processes 14min and this time growth over time. I noticed the cached tables growth over time also.

can I avoid this caching by spark? 
I guess spark caches in memory latest verion of the table?

when I write to table I use mode "append".

I do partition frame by date, hour before I write it to delta table. I have tried VACUUM with RETAIN 24 hours but I do not delete any data physicaly in the delta table storage.

**Comment by zsxwing** [comment]
If you continuously write data to a Delta table, it will over time accumulate a large number of files, especially if you add data in small batches. This can have an adverse effect on the efficiency of table reads, and it can also affect the performance of your file system. Ideally, a large number of small files should be rewritten into a smaller number of larger files on a regular basis.

We provide an [optimize](https://docs.delta.io/latest/optimizations-oss.html#optimizations) command to do the file compaction.

**Comment by 0xdarkman** [comment]
OPTIMIZE will cause compacting small files into large one but it will not answer: how to avoid growing cache loaded by spark as table growths over time.

I did OPTIMIZE on the table and VACUUM and see:
- still have lots of small files and almost like see no effect of OPTIMIZE
- VACUUM: does not remove any blobs physically from the storage

**Comment by 0xdarkman** [comment]
```
val path = "abfss://CONTAINER@SA.dfs.core.windows.net/TABLE"

spark
  .read
  .format("delta")
  .load(path)
  .repartition(10)
  .write
  .format("delta")
  .mode("overwrite")
  .option("dataChange", false)
  .save(path)
```

If I am writting to this table with `append` mode and now run `repartition` with mode `overwrite` and `dataChange` as `false` THEN will I not break downstream processes reading from this table and NOT affect history (appends?)
