### ISSUE TITLE
[Feature Request] `DeltaTable.toDF(version, timestamp)` - extend toDF() so that it returns a previous version of a delta table as DataFrame

### ISSUE THREAD

**Issue by keen85** [delta-io/delta#1425]
### Overview

I think it would be very useful to have an _easy way_ to **retrieve a _former_ `DeltaTable` version as `DataFrame`**.

### Motivation

Currently, querying a former version of a DeltaTable is limited in some respects when using PySpark:
When the path of a Delta table is know, the following will work
```
df1 = spark.read.format("delta").option("timestampAsOf", timestamp_string).load("/tmp/delta/people10m")
df2 = spark.read.format("delta").option("versionAsOf", version).load("/tmp/delta/people10m")
```
https://docs.delta.io/latest/delta-batch.html#dataframereader-options

However, if only the **_table name_** is known (and not its location), there is no way of retrieving a former version of a Delta table directly.
```
# DOESN'T WORK!
df1 = spark.table(default.people10m).option("timestampAsOf", timestamp_string)
df2 = spark.table(default.people10m).option("versionAsOf", version)
```

Workaround is using Spark SQL:
```
df1 = spark.sql("SELECT * FROM default.people10m TIMESTAMP AS OF '2018-10-18T22:15:12.013Z'")
df2 = spark.sql("SELECT * FROM delta.`/tmp/delta/people10m` VERSION AS OF 123")
```
https://docs.delta.io/latest/delta-batch.html#sql-as-of-syntax

### Further details

I propose extending the functionality of `DeltaTable.toDF()` into 
`DeltaTable.toDF(version: int = None, timestamp: str = None) → pyspark.sql.dataframe.DataFrame`.

This way, a user can either specify `version` or `timestamp` to define which version he is interested in
- `DeltaTable.toDF()` same behaviour as-is
- `DeltaTable.toDF(version=200)` return version 200 of `DeltaTable` as `DataFrame`
- `DeltaTable.toDF(timestamp='2021-01-01 01:01:01')` return `DeltaTable` as of '2021-01-01 01:01:01' as `DataFrame`
- `DeltaTable.toDF(version=200 = timestamp='2021-01-01 01:01:01')` if version and timestamp refer to the same version, return it as `DataFrame`, else trow `exception` that version and timestamp are not consistent

the above example would then look like
```
df1 = DeltaTable.forName(spark, default.people10m).toDF(timestamp=timestamp_string)
df2 = DeltaTable.forPath(spark, '/tmp/delta/people10m').toDF(version=version)
```

### Willingness to contribute

The Delta Lake Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature?

- [ ] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the Delta Lake community.
- [x] No. I cannot contribute this feature at this time.

**Comment by allisonport-db** [comment]
Hey @keen85 you can do
```
df1 = spark.read.option("versionAsOf", version).table(default.people10m)
```
This is preferable to adding any new APIs.

It seems there might be a bug with the "timestampAsOf" for this API I am looking into it and will open an issue if needed.

**Comment by keen85** [comment]
hi @allisonport-db, are there any updates?

**Comment by allisonport-db** [comment]
> ```
> df1 = spark.read.option("versionAsOf", version).table("default.people10m")
> ```

@keen85 Did this work for you?

**Comment by keen85** [comment]
works in Delta Lake 2.2.0:
```python
df1 = spark.read.option("timestampAsOf", timestamp_string).table("default.people10m")
df2 = spark.read.option("versionAsOf", version).table("default.people10m")
```
