### ISSUE TITLE
How to run deltalak in HDFS 

### ISSUE THREAD

**Issue by zhangxinjian123** [delta-io/delta#143]
My delta Lake program can run locally, but writing HDFS errors are as follows:
error
java.lang.ClassNotFoundException: Failed to find data source: delta. Please find packages at http://spark.apache.org/third-party-projects.html

**Comment by pranavanand** [comment]
Hi @zhangxinjian123 , Were you able to make progress?

**Comment by zsxwing** [comment]
Closing the stale ticket.
