### ISSUE TITLE
[Feature Request] Automatically generate partition filters for generated columns using the timestamp trunc function

### ISSUE THREAD

**Issue by allisonport-db** [delta-io/delta#1445]
See #1442 

We can automatically generated partition filters when a partition column is generated by the [TruncTimestamp](https://github.com/delta-io/delta/blob/master/core/src/main/scala/org/apache/spark/sql/delta/SupportedGenerationExpressions.scala#L224) function.

i.e. if t1 < t2 then date_trunc('QUARTER', t1) <= date_trunc('QUARTER', t2)

**Comment by tfabritz** [comment]
I'd like to look into this

**Comment by chridac95** [comment]
@allisonport-db Is this still open? in that case, may I work on this?

**Comment by allisonport-db** [comment]
@chridac95 sorry this has been done. See https://github.com/delta-io/delta/issues/1442 for the parent issue; you can propose another function you think would be beneficial

**Comment by allisonport-db** [comment]
Closed by #1514
