### ISSUE TITLE
[Feature Request] Automatically generate partition filters for generated columns using the trunc date function

### ISSUE THREAD

**Issue by allisonport-db** [delta-io/delta#1446]
See #1442 

We can automatically generated partition filters when a partition column is generated by the [TruncDate](https://github.com/delta-io/delta/blob/master/core/src/main/scala/org/apache/spark/sql/delta/SupportedGenerationExpressions.scala#L223) function.

i.e. if t1 < t2 then trunc(t1, "week") <= trunc(t2, "week")

**Comment by brayanjuls** [comment]
Hi, I would like to start contributing to the delta project and this seems to be a good issue with great explication. Could I get this ticket assigned to me?

**Comment by brayanjuls** [comment]
I just realized that I would not be able to test this feature until this PR is merged, https://github.com/apache/spark/pull/38823, is that right?

**Comment by tdas** [comment]
That spark issue will allows SQL DDLs to generate tables with generated columns. But you can already created tables with generated columns using the Scala/Python API - https://docs.delta.io/latest/delta-batch.html#-deltausegeneratedcolumns

**Comment by brayanjuls** [comment]
Thanks, @tdas. I managed to test it using the test suite. I was also able to create the table using the Scala API.
