### ISSUE TITLE
Support for loading multiple paths?

### ISSUE THREAD

**Issue by AFFogarty** [delta-io/delta#145]
Right now, if you try to load multiple paths using `DataFrameReader.load(paths: String*)`, Delta throws `java.lang.IllegalArgumentException: 'path' is not specified`: 

```
scala> val df = spark.read.format("delta").load("/tmp/delta-table1", "/tmp/delta-table2")
java.lang.IllegalArgumentException: 'path' is not specified
  at org.apache.spark.sql.delta.DeltaErrors$.pathNotSpecifiedException(DeltaErrors.scala:221)
  at org.apache.spark.sql.delta.sources.DeltaDataSource$$anonfun$9.apply(DeltaDataSource.scala:140)
  at org.apache.spark.sql.delta.sources.DeltaDataSource$$anonfun$9.apply(DeltaDataSource.scala:140)
```

`DataFrameReader.load(paths: String*)` is a fairly major API, so it seems strange that Delta doesn't support it.  Is it possible to add support for this API? 

Otherwise, can we make the exception message more explicit in explaining why `load(paths: String*)` isn't supported?  I had to thoroughly dig through the Spark and Delta source to figure out why my calls were failing.

**Comment by mukulmurthy** [comment]
From the public docs of DataFrameReader:
> public Dataset<Row> load(String... paths)
> Loads input in as a DataFrame, for data sources that support multiple paths. Only works if the source is a HadoopFsRelationProvider.

I don't think Delta would work with multiple paths, but I definitely agree this should throw a better error message. Based on your investigation, do you know if there's a nice point where it's possible for Delta to recognize this is happening and throw a better error, or is this something we'd need to fix upstream in Spark (for all data sources that don't support multiple paths)?

**Comment by AFFogarty** [comment]
Line 140 of `DeltaDataSource.scala` is where the current error gets thrown:

```
  override def createRelation(
      sqlContext: SQLContext,
      parameters: Map[String, String]): BaseRelation = {
    val maybePath = parameters.getOrElse("path", {
      throw DeltaErrors.pathNotSpecifiedException
    })
    ...
```

I think here we could check if `parameters.contains("paths")` and throw a specific exception informing the client that `load(paths: String*)` isn't supported by Delta.

**Comment by mukulmurthy** [comment]
Makes sense; I think that's a reasonable way to fix this. I'll happily assign this issue to you if you'd like to fix this.

**Comment by rapoth** [comment]
CC: @imback82 @suhsteve

**Comment by leoneuwald** [comment]
Hi @AFFogarty @mukulmurthy. Can I help with this?

**Comment by mukulmurthy** [comment]
I'm not sure if we want to support loading multiple table paths - we may decide to in the future - but assuming @AFFogarty hasn't started work on it, I'm all in favor of you improving the error message!
