### ISSUE TITLE
[Feature Request] Save with specified compression codec after optimized-based compaction

### ISSUE THREAD

**Issue by xuan1905** [delta-io/delta#1453]
## Feature request
Save data with a user-specified compression codec (like `zstd`) when using `deltaTable.optimize().executeCompaction()`.
### Overview
Currently the default compression format is `snappy `when one wants to compact the data with the built-in function `optimize()`. There is no option for users to choose the compression format at this point.

### Motivation
in specific use cases favoring compression ratio to speeds or the other way round, there exists a need to use different compression formats such as `zstd `and `lzo`.  This request is to offer the feature of allowing the user to input a certain compression format after using `compaction()`.

### Willingness to contribute

The Delta Lake Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature?

- [ ] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the Delta Lake community.
- [ ] No. I cannot contribute this feature at this time.

**Comment by zsxwing** [comment]
Does `spark.sql("set spark.sql.parquet.compression.codec=zstd"` work for you?

**Comment by xuan1905** [comment]
Yeah. It works great! And I think it would be nice to have the compressor set at the optimize() level as my app uses the same spark session to produce different data of two codecs. I need the split the jobs if I set the codec in the spark config at the beginning.

**Comment by zsxwing** [comment]
Spark provides `newSession` for this use case.
```
val newSpark = spark.newSession
newSpark.sql("set spark.sql.parquet.compression.codec=zstd")
val deltaTable = DeltaTable.forPath(newSpark, ...)
deltaTable.optimize()
```

**Comment by xuan1905** [comment]
Beautiful. Thank a lot.

**Comment by sumisr-db** [comment]
Is gzip a supported option?
