### ISSUE TITLE
[Feature Request] Export LogStoreProvider in java api.

### ISSUE THREAD

**Issue by horizonzy** [delta-io/delta#1457]
## Feature request
Some user may need to use `LogStoreProvider.createLogStore` to reuse LogStore function, so export it.

**Comment by scottsand-db** [comment]
@horizonzy can you give some examples of what users may want to do with that function?

Currently all of the LogStore APIs are abstracted away from Delta Lake users .... they are only relevant for contributors wanting to build delta lake connectors (and change/add a LogStore implementation)

**Comment by horizonzy** [comment]
In my case, I will write some particular file to faster the read operation. The delta log store already supports kinds of the storage system. `S3`, `Azure` etc. I want to reuse the logStore, no need to write the file by myself.

Currently, I create the logStore like:
```
        this.deltaLog = DeltaLog.forTable(hadoopConfig, location);
        LogStore logStore = ((DeltaLogImpl) deltaLog).createLogStore(hadoopConfig);
```
It's ugly, It should create the DeltaTable first.

**Comment by zsxwing** [comment]
> In my case, I will write some particular file to faster the read operation.

Please don't use LogStore to write any files outside `_delta_log`. It's not designed for this. If you want to write arbitrary files, you can use Hadoop FileSystem APIs like this:
```
this.deltaLog = DeltaLog.forTable(hadoopConfig, location);
Path path = new Path(your_file_location)
FileSystem fs = path.getFileSystem(hadoopConfig);
fs.create(path, true or false) // Check FileSystem.create for more details
```

**Comment by horizonzy** [comment]
If I use this way to do some operations, are there any problems?
```
        this.deltaLog = DeltaLog.forTable(hadoopConfig, location);
        LogStore logStore = ((DeltaLogImpl) deltaLog).createLogStore(hadoopConfig);
```

All the file prefixes start with `_`.

**Comment by zsxwing** [comment]
`LogStore` is just not designed to read/write arbitrary files. We want to control what files can be read/written by LogStore inside Delta. Allowing arbitrary connectors to use that may block any future extensions we are going to add into LogStore. Since we already have `FileSystem` APIs, it's better to just use it.

**Comment by horizonzy** [comment]
Got it.
