### ISSUE TITLE
[Feature Request] Support `Drop Partition` Syntax

### ISSUE THREAD

**Issue by YannByron** [delta-io/delta#1461]
### Overview

Support SQL like `alter table xxx drop partition (partition_column="partition_value")` to drop partitions.

### Willingness to contribute

The Delta Lake Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature?

- [x] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the Delta Lake community.
- [ ] No. I cannot contribute this feature at this time.

**Comment by zsxwing** [comment]
@YannByron Do you plan to just implement it as `delete from table xxx where partition_column="partition_value"`? I agree this command itself may make sense. However, what should we do for `add partition` command? It's better to discus the behaviors for all partition commands first before adding any command.

**Comment by YannByron** [comment]
No. `delete from table xxx where partition_column="partition_value` can work in current delta, doesn't need to do anything else.
I agree that `better to discus the behaviors for all partition commands`. But i think if we want to support `add partition`, the current delta protocol need to be improved. After all, all the sub-classes implement to `Action` is not enough to describe `partition` info.

**Comment by zsxwing** [comment]
These partition commands are kind of a workaround for Hive tables. For example, users can add a partition to tell a Hive table which directory it should check. However, this may not make sense for Delta. We don't want to allow users adding arbitrary existing files into a Delta table.

**Comment by YannByron** [comment]
So, data can enter a delta table only through the specified DML way, not `ADD PARTITION`, `LOAD DATA`, etc.
Get it.

**Comment by scottsand-db** [comment]
Going to mark this as closed due to inactivity and the response above. Feel free to re-open if you see fit.
