### ISSUE TITLE
[Feature Request] Enable converting from Iceberg to Delta

### ISSUE THREAD

**Issue by scottsand-db** [delta-io/delta#1462]
### Overview

Enable converting parquet-backed Iceberg tables to Delta tables without rewriting parquet files. This new Delta Table will need to be at least protocol version { reader=2, writer=5 } as Column Mapping will be needed during the conversion.

### Motivation

We want to make it easier for users to convert their existing Iceberg tables to Delta tables and start experiencing all the wonderful benefits of Delta! Having a native Iceberg converter that doesn't rewrite parquet files should help smoothen this transition.

### Further details

We will have to think about what this API / module / JAR / artifact, etc. will look like. Would love to hear feedback and thoughts from the community!

**Comment by felipepessoto** [comment]
#1463 mention a couple of limitations. Is it the plan to address them?

> > Are there any limitations on what types/features in Iceberg supported and not supported?
> 
> There are a few remaining things we don't yet support:
> 
> 1. Converting hive based iceberg table
> 2. Converting non-parquet iceberg table
> 3. Converting special partition transformation rules ([ref](https://github.com/delta-io/delta/pull/1463/files#diff-a5bb63f4073eeff36c84d70fc4e0b0b9191eaeed2b6885293da94a4cc5fa8d81R154))
> 4. Converting iceberg with custom name mapping ([ref](https://github.com/delta-io/delta/pull/1463/files#diff-ffa943e0f0f3dca25f431b29932a0ed62ca9a4d80b929e4a0a5e8b94cf6fc71dR132))
> 5. Converting iceberg table with case-sensitive column names ([ref](https://github.com/delta-io/delta/pull/1463/files#diff-ffa943e0f0f3dca25f431b29932a0ed62ca9a4d80b929e4a0a5e8b94cf6fc71dR144))

Thanks

**Comment by tdas** [comment]
Each of these features are pretty complex to translate to Delta protocol. So its tricky to get it done before the next release. We definitely welcome the community to help out.

**Comment by allisonport-db** [comment]
Closed by https://github.com/delta-io/delta/pull/1463
