### ISSUE TITLE
[Feature Request] Shallow clone Iceberg tables

### ISSUE THREAD

**Issue by dennyglee** [delta-io/delta#1464]
### Overview

Enable shallow cloning parquet-backed Iceberg tables following the Delta protocols without the need to copy all of the data.

### Motivation

We want to make it easier for users to read parquet-backed Iceberg tables within the context of Delta pipelines.  While #1462 enables users to convert parquet-backed Iceberg tables to Delta in place, this may interfere with existing pipeline processes.  Propose to use a `SHALLOW CLONE` to create a Delta log that points to the original files. 

### Further details

We will have to think about what this API / module / JAR / artifact, etc. will look like. Would love to hear feedback and thoughts from the community!

**Comment by giucris** [comment]
Hi. Is there any news regarding this feature?

**Comment by allisonport-db** [comment]
Resolved in https://github.com/delta-io/delta/commit/ff805d0a40fc3be377bf16fe01f9096bebad9024 and will be in the next release

**Comment by giucris** [comment]
Thank you @allisonport-db. 
I'm waiting for it
