### ISSUE TITLE
[Feature Request] Improve incorrect FileSystem error when using new fast-list-from feature on S3 writers

### ISSUE THREAD

**Issue by scottsand-db** [delta-io/delta#1472]
### Overview

https://github.com/delta-io/delta/pull/1210 allows `S3SingleDriverLogStore` to use the startAfter param for faster list logStore calls. This feature only works on S3A file systems.

We need to ensure that a `ClassCastException` is thrown when using the wrong file system during the cast, not during the first method invocation.

### Motivation

This will improve the user experience of this feature.

**Comment by MySelfSivaKrishna** [comment]
hi, can you assign this issue to me?

**Comment by allisonport-db** [comment]
@MySelfSivaKrishna assigned you!

**Comment by scottsand-db** [comment]
@MySelfSivaKrishna - any update?

**Comment by scottsand-db** [comment]
Seems like the code already does this, actually. We can close this issue.
