### ISSUE TITLE
[BUG] select query is returning NULL after rename when location is S3

### ISSUE THREAD

**Issue by tvamsikalyan** [delta-io/delta#1477]
## Bug
select query is returning NULL after rename when location is S3
#### Steps to reproduce
1. create table test6 (c1 int, c2 string) using delta location 's3://bucket/path';
2. insert into test6 values (1, '1');
3. alter table test6 set tblproperties ('delta.columnMapping.mode' = 'name', 'delta.minReaderVersion' = '2', 'delta.minWriterVersion' = '5');
 4. alter table test6 rename column c1 to c3;
5. select * from test6;

#### Observed results

returns
NULL    1

#### Expected results

should return
1    1

### Environment information

* Delta Lake version: 2.1.0
* Spark version: EMR 6.8 - Spark 3.3.0
* Scala version: 2.12

### Willingness to contribute

The Delta Lake Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the Delta Lake code base?

- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the Delta Lake community.

**Comment by scottsand-db** [comment]
Can you show some screenshots of you executing these steps? This would be help me verify your commands and the error you receive. Thanks!

**Comment by UrvashiDang123** [comment]
<img width="1599" alt="Screenshot 2022-12-13 at 12 47 30 AM" src="https://user-images.githubusercontent.com/120415842/207134538-2f4b2cb8-551b-487f-97a6-031fe785430a.png">

<img width="1156" alt="Screenshot 2022-12-13 at 12 47 56 AM" src="https://user-images.githubusercontent.com/120415842/207134613-2bc963b1-6418-4c60-9a9e-11f970200e13.png">

**Comment by zsxwing** [comment]
Just to double check. Did you start spark shell with `--conf "spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension" --conf "spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog"`?

**Comment by UrvashiDang123** [comment]
yes 
<img width="1792" alt="Screenshot 2022-12-13 at 10 29 42 AM" src="https://user-images.githubusercontent.com/120415842/207230579-f99b1ebb-d747-41bc-9ded-75add0793147.png">
<img width="1792" alt="Screenshot 2022-12-13 at 10 30 07 AM" src="https://user-images.githubusercontent.com/120415842/207230636-8c94b6d5-991d-46bf-90b3-a19f70169705.png">
<img width="1792" alt="Screenshot 2022-12-13 at 10 30 21 AM" src="https://user-images.githubusercontent.com/120415842/207230673-fac10543-bc67-463e-a76a-c3013158ec22.png">

**Comment by scottsand-db** [comment]
Haven't forgotten about this. Will take a look next week.

**Comment by tvamsikalyan** [comment]
This is AWS EMR specific issue, and we can close it.
Workaround is to use 's3a' scheme in the path.
There is no problem at delta lake side for this issue.
I am closing this issue for now.
Please open it again if required.
