### ISSUE TITLE
[QUESTION] Undocumented SQL `show databases` discrepancy

### ISSUE THREAD

**Issue by justinTM** [delta-io/delta#1484]
## Databricks
`%sql show databases`
![image](https://user-images.githubusercontent.com/9123665/201788219-aff05647-3103-4a16-98b2-e55013d812c0.png)

## local Delta
```python
spark.sql("show databases").collect()
```
```console
[Row(namespace='default')]
```

they should both be `namespace`, or they should both be `databaseName`. but as it exists right now, unit tests are failing due to this discrepancy and blocking merge requests for us.

**Comment by tdas** [comment]
This seems to be a problem specific to the Databricks environment which may have differences in the metastore setup than default Apache Spark. So it would be better to contact Databricks support.

**Comment by justinTM** [comment]
luckily the people working on Delta Tables are databricks employees, and there is a large umbrella initiative already to both remove databricks-specific code from Delta as well as bring the open source Delta repo to parity with what DataBricks offers. hoping to add this to that initiative

**Comment by zsxwing** [comment]
@justinTM `show databases` is not in Delta code. It's better to contact Databricks support in this case as there is nothing to be changed in the open source Delta repo.

**Comment by zsxwing** [comment]
Closing this as this is not a Delta Lake issue
