### ISSUE TITLE
Issue with UPDATE statement for tables with GENERATED columns with Now()

### ISSUE THREAD

**Issue by shahsunil** [delta-io/delta#1496]
I created a Delta table with a timestamp column which is defined as GENERATED ALWAYS AS (now()). As per my understanding, this allows, when inserting new records to the table, to automatically assign the current timestamp to the column.

When I'm trying to use the UPDATE command to update, for a given row, another field (not the aforementioned generated column), I receive an InvariantViolationException error referring to the column.
I find it confusing, as the UPDATE command should only touch the other field.
Am I misinterpreting the documentation? (https://docs.databricks.com/delta/delta-update.html#update-a-table&language-sql)

Minimal code to reproduce the issue:

CREATE or replace TABLE `test_generated_column_update` (
    test_string STRING NOT NULL,
    test_date TIMESTAMP GENERATED ALWAYS AS (now())
    )
    USING DELTA
;

insert into `test_generated_column_update`(test_string) values ('Hello!');

update `test_generated_column_update` set test_string = 'Good bye!' where test_string == 'Hello!';

select * from `test_generated_column_update`;
Error:
Error in SQL statement: InvariantViolationException: CHECK constraint Generated Column (test_date <=> now()) violated by row with values:

Tested on AWS Databricks on a single node cluster using Databricks Runtime 9.1

**Do we have any alternate option to update the other (NON GENERATED columns) columns in a row (by keeping the GENERATED ALWAYS AS (now()) ?**

**Comment by zsxwing** [comment]
See my reply in https://github.com/delta-io/delta/issues/791#issuecomment-1155816575

**Comment by zsxwing** [comment]
> Does it mean, we should not use now() function in generated always? Or is there a way we can update the row even if now() function used as generated always for some column?

Right. `now` should not be used by generated columns. It only supports deterministic expressions. [DEFAULT values for columns](https://github.com/delta-io/delta/issues/1438) is a feature that can allow you to use these expressions. But it's not implemented yet.

**Comment by shahsunil** [comment]
Thanks for the quick reply.
