### ISSUE TITLE
[BUG] VOID type supported by Delta, but is not part of the Delta log protocol specification

### ISSUE THREAD

**Issue by jkylling** [delta-io/delta#1499]
### Describe the problem
Running
```
CREATE TABLE default.void_table (y STRING, x VOID) USING DELTA
```
will create a table with a column of type `VOID`. However `VOID` is not among the primitive types listed in [the protocol specification](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#primitive-types). Not all readers of Delta tables understands the VOID type, since it is not part of the specification, and will be unable to read such tables.

#### Steps to reproduce
```
CREATE TABLE default.void_table (y STRING, x VOID) USING DELTA
```

#### Observed results

Table is created.

#### Expected results

Table is not created, or VOID is among the primitive types of the protocol specification.

### Willingness to contribute

The Delta Lake Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the Delta Lake code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the Delta Lake community.
- [ ] No. I cannot contribute a bug fix at this time.

**Comment by allisonport-db** [comment]
What environment are you running this in?

**Comment by dennyglee** [comment]
Per Trino thread: https://github.com/trinodb/trino/issues/15193#issuecomment-1327914522 - this appears to be happening in Databricks environment.

**Comment by allisonport-db** [comment]
So allowing void columns was initially an oversight when there was only the spark connecter. The issue with this is they now may be in existing tables, so outright blocking void columns going forward is not possible.

For now, we should at least block creating new tables or adding columns with the void type (I will create a follow up issue for this would be great if someone can contribute it!)

And to address the ambiguity in the protocol spec, we can add a note that existing tables may have null type columns and the behavior is undefined, but we recommend dropping/ignoring that column which is what the spark connector does.

**Comment by felipepessoto** [comment]
@allisonport-db we may need to consider a way to fix existing tables.

If one creates a table containing void columns (they may not notice it, since printSchema won't return the column) and later tries to merge, even if the source column is correctly typed now, Integer for example, and autoMerge is set, they will receive an error like:

AnalysisException: The schema of your Delta table has changed in an incompatible way since your DataFrame or
DeltaTable object was created. Please redefine your DataFrame or DeltaTable object.
