### ISSUE TITLE
Bug in Quickstart tutorial Java example

### ISSUE THREAD

**Issue by AFFogarty** [delta-io/delta#150]
In [this section](https://docs.delta.io/latest/quick-start.html#conditional-update-without-overwrite) of the Quickstart tutorial, there is a mismatch between the Scala and Java code examples.

The Java example reads:

```
deltaTable.as("events")
  .merge(
    newData,
    "oldData.id = newData.id")
  .whenMatched()
...
```

but `"events"` should be `"oldData"`.

**Comment by mukulmurthy** [comment]
Thanks for reporting this @AFFogarty. We'll fix this.

**Comment by pranavanand** [comment]
This has been fixed!
