### ISSUE TITLE
[BUG] PySpark version is still 3.3.0 in master

### ISSUE THREAD

**Issue by zsxwing** [delta-io/delta#1546]
https://github.com/delta-io/delta/pull/1382 upgraded Spark version to 3.3.1 but it didn't upgrade PySpark version. Hence, Scala tests are running with Spark 3.3.1 but Python tests are running with Spark 3.3.0.

We need to upgrade the PySpark version in the following files:
- https://github.com/delta-io/delta/blob/master/Dockerfile
- https://github.com/delta-io/delta/blob/master/.github/workflows/test.yaml

**Comment by fuzzy-memory** [comment]
Created PR #1561

**Comment by fuzzy-memory** [comment]
Can the issue be closed now @zsxwing?

**Comment by zsxwing** [comment]
Yep. This issue has been fixed by https://github.com/delta-io/delta/commit/78160ed377d702e52b8d7500f14015f0fe28904a
