### ISSUE TITLE
Can I use the DeltaTable class in python (pyspark)?

### ISSUE THREAD

**Issue by MichalFab** [delta-io/delta#155]
Hi, I am a freshman in delta.io/spark. I would like to use DeltaTable class in python (pyspark) script. 
I found solutions for java/scala in delta.io docs (https://docs.delta.io/latest/quick-start.html#conditional-update-without-overwrite). 
Is it possible to use DeltaTable in python to update table?
Regards,

Michael

**Comment by mukulmurthy** [comment]
Hi @MichalFab,

We're currently working on Python DeltaTable APIs for Merge, Delete, Update, and Vacuum, slated for release in 0.4.0 at the end of this month. Please see https://github.com/delta-io/delta/issues/89 for more details.

Thanks!

**Comment by MichalFab** [comment]
Hi @mukulmurthy ,
Ok, thank You!
