### ISSUE TITLE
Can I use Flink to connect delta？

### ISSUE THREAD

**Issue by z-Dapor** [delta-io/delta#156]
delta's speciality  is very useful；
can we use flink to operate delta file？

**Comment by marmbrus** [comment]
There is no Flink connectivity for Delta that I'm aware of today, but if anyone from the Apache Flink community reads this, I'd be happy to advise on how to build a connector!

**Comment by usopan** [comment]
@marmbrus i am not an active flink contributor but i am willing to give this a try. If you can help me that will be great.If it all works out i will publish the pr in flink.

**Comment by zsxwing** [comment]
We are working on a Delta library to make Delta easy to integrate with other engines. Will post updates in #245.

**Comment by aleksandersumowski** [comment]
Hi @zsxwing, seems that the [connectors](https://github.com/delta-io/connectors) repo that is mentioned in #245 doesn't mention integration with Flink anymore. Is it something you're still considering? Would it be worth to raise a new issue there?

**Comment by jaceklaskowski** [comment]
@aleksandersumowski FYI there's a [Delta Standalone Reader](https://github.com/delta-io/connectors#delta-standalone-reader) to use Delta Lake that (guessing) may be of help here. Never used it though myself.

**Comment by zsxwing** [comment]
@aleksandersumowski Feel free to raise an issue in https://github.com/delta-io/connectors . We put connectors to a separate repo to reduce the project management cost. As @jaceklaskowski mentioned, Delta Standalone Reader is going to make building a Flink connector easier.

**Comment by aleksandersumowski** [comment]
@jaceklaskowski @zsxwing thanks for the answers! 

I've raised the issue in connectors as suggested

**Comment by zsxwing** [comment]
Thanks @aleksandersumowski ! I will close this. Let's move the discussion to https://github.com/delta-io/connectors/issues/74
