### ISSUE TITLE
[BUG] Protocol doesn't explicitly describe what fields are required or optional

### ISSUE THREAD

**Issue by felipepessoto** [delta-io/delta#1566]
## Bug

The [Add File and Remove File](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#add-file-and-remove-file) doesn't explicitly says if the fields are required or optional. Could we add a column in the table saying if a field is required or optional?

For example, size and modificationTime are required? 

### Willingness to contribute

The Delta Lake Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the Delta Lake code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the Delta Lake community.
- [X] No. I cannot contribute a bug fix at this time.

**Comment by scottsand-db** [comment]
Hi @felipepessoto - thanks for making this issue. This seems like a good starter task for someone that wants to begin working on delta and understand the protocol.

**Comment by felipepessoto** [comment]
I sent a PR. I added the information based on Scala source code.
