### ISSUE TITLE
Is there any way to ignore a specific version when delta table is used as streaming data source.

### ISSUE THREAD

**Issue by jbin121867740** [delta-io/delta#1567]
We use spark structured streaming and delta table. We process private data, so we need to delete the data. We have a seperate job to process the customer consent and delete the data when consent is revoked. And this deletion is not on partition level. Then once we purge the data based on customer consent. Huge number of rows are copied. And this takes huge processing time for normal downstream handling. So I would like to know is there any way to skip a version when  delta table is used as streaming data source?
For example,  in commit info, we have {"commitInfo":{"operation":"DELETE", "jobName":"PURGE" ...
Or if there is a way to ignore a specific version. Then we can figure out which version we want to skip and set it when start the streaming.

**Comment by dudzicp** [comment]
Why don't you use cdc as stream source?

**Comment by dudzicp** [comment]
According to the docs https://docs.databricks.com/structured-streaming/delta-lake.html you can ignore deletes. Another approach would be to parse the log manually and then specify the starting version of table

**Comment by scottsand-db** [comment]
Hi @jbin121867740 - I think that the two comments above propose some fair next steps. Can you try them out, or respond and update what is / is not working for you?

**Comment by jbin121867740** [comment]
Hi, Sorry for no response for long time. What I would like to ignore is not only those rows which are deleted, but also the rows were added again due to they are in same file as those deleted rows. Since those newly added rows are copies of old rows which are already been processed by downstream.
if I ignore a specifc version manually, I need the option for startingVersion and endingVersion. For example, if there are V1, 2, 3 and 4. V3 is for deletion, and the rest is adding data. Currently the down stream is commited on V1, then it needs to process V2, ignore V3 and then process V4.
While if there is no endingVersion support, how can I just process V2?
Also it will be much better this kind of scenario can be supported officially. This is one of the pain point we have when we have to delete data (I suppose many companies have this issue if they have to deal with privacy data, and use spark streaming + delta table to do the data processing).

**Comment by jbin121867740** [comment]
Sorry for the mistake of closing the issue.

**Comment by dudzicp** [comment]
Again - why don't you use cdc as a stream source?

**Comment by zsxwing** [comment]
@jbin121867740 We have a recent change to provide a new `skipChangeCommits` option in #1616. Does this work for your case?

**Comment by jbin121867740** [comment]
@zsxwing, thanks so much. This is exactly what we want.

**Comment by zsxwing** [comment]
Thanks! Resolved by #1616
