### ISSUE TITLE
[New Service] Integration of Azure Stream Analytics and Delta Lake

### ISSUE THREAD

**Issue by an-emma** [delta-io/delta#1569]
Hi @dennyglee,

Azure Stream Analytics now provides native support of Delta Lake. We would like to have ASA added to the service list on page https://delta.io/integrations/. 

Here is an example of ASA product page: https://learn.microsoft.com/en-us/azure/stream-analytics/write-to-delta-lake.

Thank you. Please let me know if you need more information.

Best,
Emma

**Comment by dennyglee** [comment]
Thanks @an-emma  - wanted to confirm that below is the correct logo?  If so, could you please create an issue in our [website repo](http://github.com/delta-io/website/) and we'll work in this pronto?  Thanks!  

![asa-logo](https://user-images.githubusercontent.com/1446829/213059227-c38f6e63-f020-4e74-8ac5-09208a6ff5b3.png)

**Comment by an-emma** [comment]
Hi Denny, yes it is the logo. here is the link for the new issue: https://github.com/delta-io/website/issues/218

**Comment by dennyglee** [comment]
Thanks @an-emma - will close this one as duplicate for the website and continue to track that.  thanks!
