### ISSUE TITLE
[Feature Request] add finer granularity to data skipping

### ISSUE THREAD

**Issue by dudzicp** [delta-io/delta#1575]
## Feature request
Add more granularity to data skipping 
### Overview

I know that each commit, min/max values are calculated for each parquet file and are present in the delta log json, but how about adding more granularity to existing data skipping mechanism, by using parquet page skipping?
Relevant links:

https://issues.apache.org/jira/browse/PARQUET-922
https://blog.cloudera.com/speeding-up-select-queries-with-parquet-page-indexes/
Would this be doable?

### Willingness to contribute

The Delta Lake Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature?

- [ ] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the Delta Lake community.
- [x] No. I cannot contribute this feature at this time.

**Comment by Orpheuz** [comment]
Hey @dudzicp, I'm trying to get more used to Delta's code so I dug a little bit into this issue and I think this is already supported.

If you follow [DeltaParquetFileFormat's parquetDataReader](https://github.com/delta-io/delta/blob/1c18c1d972e37d314711b3a485e6fb7c98fce96d/core/src/main/scala/org/apache/spark/sql/delta/DeltaParquetFileFormat.scala#L111) you can see that it internally uses [VectorizedParquetRecordReader](https://github.com/apache/spark/blob/43baed1bbe5077128385dc1acfc61a573ec1e361/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetFileFormat.scala#L265) if the schema is compatible with columnar reads. Spark's `VectorizedParquetRecordReader` was refactored to allow column indexes in [SPARK-34289](https://issues.apache.org/jira/browse/SPARK-34289).

Feel free to correct me on this

**Comment by Orpheuz** [comment]
If you follow [DeltaParquetFileFormat's parquetDataReader](https://github.com/delta-io/delta/blob/1c18c1d972e37d314711b3a485e6fb7c98fce96d/core/src/main/scala/org/apache/spark/sql/delta/DeltaParquetFileFormat.scala#L111) you can see that it internally uses [VectorizedParquetRecordReader](https://github.com/apache/spark/blob/43baed1bbe5077128385dc1acfc61a573ec1e361/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetFileFormat.scala#L265) if the schema is compatible with columnar reads. Spark's `VectorizedParquetRecordReader` was refactored to allow column indexes in [SPARK-34289](https://issues.apache.org/jira/browse/SPARK-34289).

Feel free to correct me on this
