### ISSUE TITLE
Why not use "patch" method for update to avoid rewrite a file for just one row

### ISSUE THREAD

**Issue by LinhongLiu** [delta-io/delta#159]
In current update behavior, delta should: read affected files -> update -> write updated files -> delete old ones.
Here is some other ideas for this update command:
1. create a new action: UpdateFile with the update exprs
2. when update coming, first use predicate and statistics to estimate affected rows
3.1. if affected rows are relatively small, just add a UpdateFile action to DeltaLog
3.2. if affected rows are large, do the real update
4. when read coming, read the files apply UpdateFile actions in DeltaLog
5. provide a command or checkpoint mechanism to materialize the update actions

Can someone check if this idea is worth doing?

**Comment by tdas** [comment]
To generalize your argument, there are essentially two ways to "update" that we could have implemented
1. optimizing for writes over reads by writing a patch or a write-ahead-log, and merge patch on read
2. optimizing for reads over writes by rewriting updated files such that there is no merge during reads.

It's well known that any written data is going to read 10x more times. Hence, in Delta, we have chosen to do the second one, that is, optimize for reads. That said, in the long term, if there are sufficient demands low latency upserts (that is, faster write-optimized updates), we may choose to build the second approach as well. It would require significant changes to how we track updates, hence we are not prioritizing this right now. However, you are absolutely welcome to submit a detailed design and/or patch that can do this.

**Comment by LinhongLiu** [comment]
@tdas thanks for your explain, very clear.
