### ISSUE TITLE
Files are not logged in txn-log for savemode ErrorIfExists

### ISSUE THREAD

**Issue by ShahSunny** [delta-io/delta#16]
Files are not getting logged in the txn-log for savemode, ErrorIfExists. 

- This can hamper the recovery from future partial writes/failed txns.
- Partial/failed writes can also become visible in this case.

**Comment by mukulmurthy** [comment]
Hi Sunny, can you provide a bit more detail or a repro case?

Partial or failed writes should never be committed to Delta's transaction log, and so the files should never logically be part of the table.
