### ISSUE TITLE
[Question] does delta lake generate log file in atomic way?

### ISSUE THREAD

**Issue by guoliqiang** [delta-io/delta#1605]
We have a customized service monitor _delta_log folder, whenever a new 000000XX.json file appears, the service will parse it and find which parquet files are added factually.

In order to avoid any missing data  (e.g. service load a JSON log file while it is still writing, thus service ends up with a partial read), a straight forward question is do we generate JSON log file atomically?

Thanks

**Comment by zsxwing** [comment]
Yep, the log files are created atomically. We have [a few requirements](https://github.com/delta-io/delta#requirements-for-underlying-storage-systems) for the underlying storage systems to achieve this.

**Comment by guoliqiang** [comment]
thanks a lot @zsxwing
