### ISSUE TITLE
IntegerType and BooleanType got incompatible during the migration from 0.6.0 to 2.1.1

### ISSUE THREAD

**Issue by akupchinskiy** [delta-io/delta#1608]
When the configuration spark.databricks.delta.schema.autoMerge.enabled is set to true, the implicit cast from integer to boolean doesn't work after switch to the 2.1.1 version.

```
org.apache.spark.sql.AnalysisException: Failed to merge fields 'enabled' and 'enabled'. Failed to merge incompatible data types BooleanType and IntegerType
at org.apache.spark.sql.delta.schema.SchemaMergingUtils$.$anonfun$mergeSchemas$1(SchemaMergingUtils.scala:201)
```
I believe before the strict schema check  introduction, such cases were being handled by native spark cast and runtime errors were possible only if one tried making incompatible casts.  I am not sure whether it makes sense to introduce a special flag to restore the previous behaviour but it would be awesome to have this compatibility information somewhere in the migration notes. It took quite a while to figure out why our pipelines started failing.

**Comment by scottsand-db** [comment]
Delta 0.6 used a much older Spark version. I wonder if Spark back then generated a different schema.

Also, it seems like implicitly casting from Integer to Boolean could cause some data loss? Seems weird to me. I don't think we want to reintroduce that feature/bug, even with a feature flag.

Are you able to work around this?

**Comment by akupchinskiy** [comment]
Eventually, we overcame it by doing the missing cast on the application side. The root cause of the problem I believe is two different types cast mechanisms existing in the current Spark version which are implicitly being used in delta schema merge:

https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/Cast.scala#L752 - that one was being used in 0.6.0 version 

https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/TypeCoercion.scala#L974 - it is from the 2.1.1 version, though I believe it was introduced somewhere in between 0.6 and 2.1

As a result, the boolean <-> integer conversion stopped working on the way. So did some other type pairs I suspect.
