### ISSUE TITLE
[BUG] Filtering by date doesn't work

### ISSUE THREAD

**Issue by hanna-liashchuk** [delta-io/delta#1629]
### Describe the problem
Filtering dates don't include the last/first date in the range. 
#### Steps to reproduce
```
CREATE TABLE default.test_delta
(
    id       Int,
    birthday date
) using delta 
location '...';
```
```
insert into table default.test_delta
values (1, cast("1999-01-01" as date));
insert into table default.test_delta
values (2, cast("1994-01-01" as date));
insert into table default.test_delta
values (3, cast('1994-04-01' as date));
insert into table default.test_delta
values (4, cast('1999-02-10' as date));
```

```
select * from default.test_delta
where birthday >= to_date('1994-01-01') and birthday < to_date('1999-02-11');
```

#### Observed results

3 rows are returned, with 1994-04-01, 1994-01-01 and 1999-01-01

#### Expected results

4 rows are returned, with 1994-04-01, 1994-01-01, 1999-02-10 and 1999-01-01

#### Further details

If increase filter condition to 
`select * from default.test_delta where birthday >= to_date('1994-01-01') and birthday < to_date('1999-02-12');`
all 4 rows are returned 

### Environment information

* Delta Lake version: 2.2.0
* Spark version: 3.3.2
* Scala version: 2.12
Running on Kubernetes cluster
### Willingness to contribute

The Delta Lake Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the Delta Lake code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [X] Yes. I would be willing to contribute a fix for this bug with guidance from the Delta Lake community.
- [ ] No. I cannot contribute a bug fix at this time.

**Comment by gaurav-rupnar** [comment]
Could you please confirm the Delta Lake version? The latest I see [here](https://mvnrepository.com/artifact/io.delta/delta-core_2.13) is 2.2.0.  [Dec-05]

**Comment by hanna-liashchuk** [comment]
@gaurav-rupnar yes, sorry, it's 2.2.0

**Comment by allisonport-db** [comment]
I'm not able to reproduce this locally.

Can you provide the output for this?
```
explain extended select * from default.test_delta
where birthday >= to_date('1994-01-01') and birthday < to_date('1999-02-11');
```

Also if possible could you re-verify that you're running the exact commands you provided here in the issue? I ran them exactly and got back all 4 rows.

**Comment by hanna-liashchuk** [comment]
@allisonport-db 
the result is
```
== Parsed Logical Plan ==
'Project [*]
+- 'Filter (('birthday >= 'to_date(1994-01-01)) AND ('birthday < 'to_date(1999-02-11)))
   +- 'UnresolvedRelation [default, test_delta], [], false

== Analyzed Logical Plan ==
org.apache.spark.sql.AnalysisException: Table or view not found: default.test_delta; line 1 pos 31;
'Project [*]
+- 'Filter (('birthday >= to_date(1994-01-01, None, Some(Europe/Kiev))) AND ('birthday < to_date(1999-02-11, None, Some(Europe/Kiev))))
   +- 'UnresolvedRelation [default, test_delta], [], false
```

Are you running this in Kubernetes? I think this issue is somehow related to the spark master
Do you have an environment to run test it in k8s?

**Comment by felipepessoto** [comment]
Only a guess, but isn't the time zone the problem?

select to_utc_timestamp('1999-02-11','Europe/Kiev') -> 1999-02-10T22:00:00Z

select to_date(to_utc_timestamp('1999-02-11','Europe/Kiev')) -> 1999-02-10

**Comment by allisonport-db** [comment]
This doesn't seem related to Delta. Can you try it with a parquet table and confirm the behavior is the same?

**Comment by hanna-liashchuk** [comment]
@felipepessoto Nope, I tried changing the timezone and the result is the same
@allisonport-db, yes seems it's a parquet issue, cause I can reproduce it with parquet 
closing this
