### ISSUE TITLE
[Feature Request] Don't collect all files in DeltaSourceSnapshot

### ISSUE THREAD

**Issue by Kimahriman** [delta-io/delta#1699]
### Overview

We have several times hit issues running out of memory starting a new stream on a large Delta table. I finally traced through the code to see what the memory requirements should be and it appears that `SnapshotIterator.iterator` `collect`s all files (including stats) to create an iterator on the list of files. This can take a very large amount of memory on the driver for large tables.

Additionally, it would appear that the final list to create a `TahoeBatchFileIndex` also includes the stats as well? And I don't think anything related to streaming currently uses file stats that I can tell? So it would be helpful to be able to drop the stats for streaming things at least to avoid collecting all that on the driver. 

### Motivation

Starting a stream on a large table requires a lot of driver memory.

### Further details

Any feedback on my assumptions about how stats are used or any ideas for how to not do a collect on the entire snapshot would be welcome.

### Willingness to contribute

The Delta Lake Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature?

- [ ] Yes. I can contribute this feature independently.
- [X] Yes. I would be willing to contribute this feature with guidance from the Delta Lake community.
- [ ] No. I cannot contribute this feature at this time.

**Comment by scottsand-db** [comment]
@Kimahriman wouldn't these stats be useful for the query to perform data skipping during reads?

**Comment by Kimahriman** [comment]
> @Kimahriman wouldn't these stats be useful for the query to perform data skipping during reads?

They theoretically could be but I don't see that currently happening on the streaming path? Might be a separate enhancement to actually use stats for skipping on streaming reads. Either way they should be dropped before creating the final file index like what happens on the non streaming path

**Comment by ryan-johnson-databricks** [comment]
@Kimahriman -- what if the batch file index simply stored `Dataset[AddFile]` instead of `Seq[AddFile]`?

Doing so would guarantee we can create the batch file index without triggering an OOM, thanks to spark's caching and spilling machinery.

It would also allow to prune away the stats column before calling `collect` (to reduce chances of OOM in case a lot of files survive partition pruning), since as you point out [TahoeBatchFileIndex.matchingFiles](https://github.com/delta-io/delta/blob/master/core/src/main/scala/org/apache/spark/sql/delta/files/TahoeFileIndex.scala#L270) ignores `dataFilters`. If that ever changes, we would simply apply the data filters before pruning away the stats column (still before calling `collect`).

**Comment by Kimahriman** [comment]
> @Kimahriman -- what if the batch file index simply stored `Dataset[AddFile]` instead of `Seq[AddFile]`?
> 
> Doing so would guarantee we can create the batch file index without triggering an OOM, thanks to spark's caching and spilling machinery.

The problem is before the TahoeBatchFileIndex is even created in [DeltaSourceSnapshot.iterator](https://github.com/delta-io/delta/blob/master/core/src/main/scala/org/apache/spark/sql/delta/files/DeltaSourceSnapshot.scala#L86). Files info needs to be available in the driver for it to figure out batches based on batch limits like `maxBytesPerTrigger`. It seems like a two stage process of
1. iterate through the files to figure out what the next offset is
2. iterate through the files to create the TahoeBatchFileIndex based DataFrame with data for that batch

I'm messing around with alternatives to just `.collect`'ing the whole thing there but getting some weird issues.

**Comment by Kimahriman** [comment]
I made https://github.com/delta-io/delta/pull/1703 to at least drop the stats before files are collected and put into a file index

**Comment by Kimahriman** [comment]
Created https://github.com/delta-io/delta/pull/1721 to try to fix things, let me know what you think.
