### ISSUE TITLE
Plans to support ADLS gen 2 ?

### ISSUE THREAD

**Issue by desaiak** [delta-io/delta#17]
Since ADLS gen 2 provides HDFS compatibility I am thinking it should be possible to use it without the list after write issues related to s3.

**Comment by zsxwing** [comment]
Yep. HDFSLogStore can be used with ADLS Gen2 as long as your Hadoop version has the patch for https://issues.apache.org/jira/browse/HADOOP-15086

**Comment by zsxwing** [comment]
Sorry. I didn't realize Azure ADLS Gen2 doesn't support new Hadoop FileContext APIs. So it's not working right now. We will check its FileSystem implementation and see if we can support it or not.

**Comment by tdas** [comment]
@desaiak I have made an official issue #40 for azure file systems. I am closing this issue in favor of that, please have any follow up discussions on that issues.
