### ISSUE TITLE
Bug in the comments for vacuum

### ISSUE THREAD

**Issue by constzhou** [delta-io/delta#171]
The comment for vacuum says "note: This will use the default retention period of 7 hours."
But actually the default value is 7 days.

**Comment by tdas** [comment]
@constzhou thank you for catching that. can you link to the comments in the code?
@rahulsmahadev probably you should take a look.

**Comment by tdas** [comment]
This PR fixes it, along with making Python APIs for vacuum - https://github.com/delta-io/delta/pull/173
