### ISSUE TITLE
Convert to Delta SQL support

### ISSUE THREAD

**Issue by zsxwing** [delta-io/delta#175]
Add the following SQL support for `Convert to Delta`:

```
CONVERT TO DELTA parquet.`path/to/table` [PARTITIONED BY (col_name1 col_type1, col_name2 col_type2, ...)]
```

**Comment by cfmcgrady** [comment]
hi, @zsxwing 
spark SQL is doing support DML(`delete`/`update`) in the latest version, and I also find that delta is adding DML(`describe`/`Convert`/`Vacuum`) support now, is there any plan for add `delete/update` grammar support for spark-2.4.x?

**Comment by zsxwing** [comment]
@cfmcgrady we have looked at how to support `merge/delete/update` for Spark 2.4 in Delta Lake. However, we found out it would require to fork almost the whole Spark SQL parser and it would be pretty hard to maintain. Hence we decided to wait for Spark 3.0 instead. For Spark 2.4, we will just add several SQL utility commands (vacuum, describe history and convert to delta) to Delta Lake.

**Comment by pranavanand** [comment]
Completed as part of https://github.com/delta-io/delta/commit/b624209cb802e600a9419b2a75e13c54c24eec7d
