### ISSUE TITLE
[Test] Check for operation type in Optimize Metrics tests

### ISSUE THREAD

**Issue by vkorukanti** [delta-io/delta#1756]
Follow up from review comment [here](https://github.com/delta-io/delta/pull/1753#discussion_r1191754440). Add operation type check for tests in [OptimizeMetricsSuite.scala](https://github.com/delta-io/delta/blob/master/core/src/test/scala/org/apache/spark/sql/delta/optimize/OptimizeMetricsSuite.scala)

**Comment by felipepessoto** [comment]
Sent a PR: https://github.com/delta-io/delta/pull/1758
