### ISSUE TITLE
code snippets error in official website.

### ISSUE THREAD

**Issue by phoeph** [delta-io/delta#178]
"Table Deletes, Updates, and Merges"
    |--Use merge in streaming queries with foreachBatch

`val deltaTable = io.delta.tables.DeltaTable.forName("aggregates")`

object DeltaTable only has forPath() method.
Can not find this API in below maven dependencies:

<dependency>
            <groupId>io.delta</groupId>
            <artifactId>delta-core_2.11</artifactId>
            <version>0.3.0</version>
</dependency>

**Comment by MrPowers** [comment]
I noticed some errors [here](https://docs.delta.io/latest/delta-update.html).

Need to change this:

```
deltaTable.update(                // predicate using Spark SQL functions and implicits
  $"eventType" = "clck"),
  Map("eventType" -> lit("click"));
```

To this:

```
deltaTable.update(
  col("eventType") === "clck",
  Map("eventType" -> lit("click"))
)
```

If there is an open source version of the HTML docs, I'll be happy to make a PR.  Couldn't find them so maybe they're still closed source.

**Comment by tdas** [comment]
@phoeph  That is a mistake. I will fix it. Thank you.
@MrPowers That is a better example. Thank you.

**Comment by phoeph** [comment]
I am new here.
May I know the next step is to close this issue？
