### ISSUE TITLE
Wiki link error in official website.

### ISSUE THREAD

**Issue by phoeph** [delta-io/delta#179]
Can not open wiki link page in "Optimistic concurrency control" that the link name is the same.

**Comment by mukulmurthy** [comment]
Hi @phoeph,

Can you please link to the page where this error is?

**Comment by phoeph** [comment]
Hi @mukulmurthy ,

please see error link below:

https://en.wikipedia.org/wiki/Optimistic_concurrency_control

**Comment by tdas** [comment]
@phoeph I checked out the link in the page https://docs.delta.io/latest/delta-concurrency.html and it seems to work for me.

**Comment by phoeph** [comment]
Maybe I am on site China?
Ok, and I will close it.
