### ISSUE TITLE
[Feature Request] Checkpoint V2 Format

### ISSUE THREAD

**Issue by prakharjain09** [delta-io/delta#1793]
## Feature request

This is an umberella issue for _Checkpoint V2_ Support.

### Motivation

The current semantics to decide a valid checkpoint and its corresponding files in DeltaLog are weak. Delta relies on directory listing and file naming scheme to decide what a checkpoint consists of (corresponding files, number of parts etc). This slows down the directory listing, and can also lead to bugs around checkpoints being corrupted due to concurrent checkpoint writers.
    In addition to this, the current checkpoint format doesn’t allow sharing of checkpoint files across different checkpoints, which guarantees storage bloat and blocks any potential optimizations that might reduce that bloat.
The current Delta Protocol also forbids us from doing checkpoint meta-clustering. As per [Delta Protocol](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#checkpoints-1):
_When writing multi-part checkpoints, the data must be clustered (either through hash or range partitioning) by the 'path' of an added or removed file, or null otherwise. This ensures deterministic content in each part file in case of multiple attempts to write the files._
The above clause in the spec is for handling zombie write tasks e.g. when spark tries to rerun the checkpoint write job, old tasks might still be running and compete with the new task. So a deterministic partitioning scheme is necessary to avoid corruption in this scenario and so delta spec doesn’t allow any non-deterministic clustering algorithms. But even with the above constraint, there could still be corruption when there are two concurrent checkpoint  writers from different delta clients where one of them chose range partitioning and another chose hash partitioning. In such a scenario, the end result might have files partially from writer-1 and partially from writer-2.

### Proposal

The proposal is to comeup with a new checkpoint format called Checkpoint _V2_ which overcomes all the above mentioned issue and is flexible enough to incorporate more optimizations.
 - The format allows checkpoints to be published atomically using sidecars which are linked to a unique parent checkpoint file.

### Further details

The detail proposal and the required protocol changes are sketched out [in this doc](https://docs.google.com/document/d/18D4SiI0_t7ak8sgvyQtH9lBUyGJIp8hyZi2-399uByQ/edit?usp=sharing).

**Comment by vigneshc** [comment]
This is a great feature!

> Delta relies on directory listing and file naming scheme to decide what a checkpoint consists of (corresponding files, number of parts etc). 

Doesn't the [Last Checkpoint File](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#last-checkpoint-file) contain number of parts? Why does delta rely on directly listing and file naming scheme for checkpoints?

**Comment by vigneshc** [comment]
Added comments in the doc.

**Comment by ryan-johnson-databricks** [comment]
> > Delta relies on directory listing and file naming scheme to decide what a checkpoint consists of (corresponding files, number of parts etc).
> 
> Doesn't the [Last Checkpoint File](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#last-checkpoint-file) contain number of parts? Why does delta rely on directly listing and file naming scheme for checkpoints?

The file is best-effort only. It could be stale or even not exist at all. But it makes a much better starting point than listing from 0. And since we anyway have to LIST to find the latest commit, we may as well get any newer checkpoint while we're at it.

**Comment by prakharjain09** [comment]
This is implemented as part of following PRs:
1. https://github.com/delta-io/delta/pull/1946 - Protocol changes for supporting V2 Checkpoints
2. https://github.com/delta-io/delta/pull/1983 - [Spark] Introduce V2 Checkpoint actions, table feature
3. https://github.com/delta-io/delta/pull/2031 - [Spark] Add support for writing V2 Checkpoints
4. https://github.com/delta-io/delta/pull/2056 - [Spark] Read side changes for V2 Checkpoints
5. https://github.com/delta-io/delta/pull/2102 - Add support for V2 Checkpoint metadata cleanup

Closing the issue.
