### ISSUE TITLE
[QUESTION] Merge operation exhausting driver memory. Delta 2.3.0 - Spark 3.3.0

### ISSUE THREAD

**Issue by mvalleavila** [delta-io/delta#1803]
Hello,

We're trying a simple Merge operation between ~450k and ~1k records, but the operation doesn't finish, throwing a Java Heap Memory exception on my local machine. Trying to launch the same operation with a cluster of 10 machines, result in the same behaviour.

The strange thing is that launching the same code with Delta version 2.4.0 and Spark 3.4.0 it finishes in a few seconds on my local system. Unfortunately we doesn't have the possibility to upgrade to Delta 2.4.0 and Spark 3.4.0 in our production cluster.

I've tried to zOrdering the join column, or tune some Spark parameters as shuffle.partitions or join thresholds, but I did't have luck.

@PawaritL, we've already talked about this issue in other opened thread, but I decided to open one new to avoid talking a bit different topic.

Thank you in advance!

**Comment by vkorukanti** [comment]
@johanl-db any insights here?

**Comment by mvalleavila** [comment]
Update:

After doing several tests with Delta 2.3.0 we've found a workaround that seems to work.

Originally we were doing an union between 2 Dataframes before Delta Merge operation:

The following code produce the issue:
```
inserts = get_inserts_df(delta_df, source_df)
updates = get_updates(delta_df, source_df)
union = inserts.unionByName(updates, allowMissingColumns=True)

delta_table.alias('current') \
                .merge(
                union.alias('updates'),
                f'current.{id_column_name} = updates.{id_column_name}'
            ) \
                .whenMatchedUpdateAll() \
                .whenNotMatchedInsertAll() \
                .execute()
```


We've tried to avoid the union, and to launch twice the Delta Merge:

The following code works fine and fast:
```
updates = get_updates(delta_df, source_df)

delta_table.alias('current') \
                .merge(
                updates.alias('updates'),
                f'current.{id_column_name} = updates.{id_column_name}'
            ) \
                .whenMatchedUpdateAll() \
                .whenNotMatchedInsertAll() \
                .execute()

inserts = get_inserts_df(delta_df, source_df)

delta_table.alias('current') \
                .merge(
                inserts.alias('updates'),
                f'current.{id_column_name} = updates.{id_column_name}'
            ) \
                .whenMatchedUpdateAll() \
                .whenNotMatchedInsertAll() \
                .execute()
```

The curious thing is with Delta 2.4 both codes works fine, but with Delta 2.3 only the last one does.

As in last version the behaviour is not being reproduced, maybe the issue can be closed. 

Regards!

**Comment by johanl-db** [comment]
I'm wondering if this may be related to https://github.com/delta-io/delta/issues/1749 somehow. Can you try disabling source materialization: `spark.databricks.delta.merge.materializeSource = "none"`.
From your example it doesn't seem source materialization is being used (it's usually triggered when there's a non-delta scan or non-deterministic operator) but it's worth a try.

**Comment by mvalleavila** [comment]
Hello @johanl-db,

setting `spark.databricks.delta.merge.materializeSource = "none"` made works as fast as using version 2.4.0.

No issues after disabling source materialization, merge was super fast and no high memory consumption of the Driver.

Thank you very much for the help and the solution.

Kind regards.

**Comment by juliuszsompolski** [comment]
> From your example it doesn't seem source materialization is being used (it's usually triggered when there's a non-delta scan or non-deterministic operator) but it's worth a try.

I believe the `union` makes it use materialization; the non-determinism check does not handle union I believe. This is a small tweak that could be improved.

**Comment by mani-sethu** [comment]
@juliuszsompolski Still I don't understand why materialization is spiking driver memory. Any thoughts
