### ISSUE TITLE
Merge Delta Connector code into this repo

### ISSUE THREAD

**Issue by tdas** [delta-io/delta#1824]
We have proposed for the Delta Connectors code to be merged in this repo. See more detailed in the Delta Connectors issue - https://github.com/delta-io/connectors/issues/556

This issue is to track the work that needs to be done. I am thinking of breaking down the work as follows: 

- [x] Merge all the code (with full history) in a connectors/ directory - #1837 
- [ ] Integrate the connector subproject to the main build.sbt so that they can all be compiled together with existing subprojects in this repo, and tested together - https://github.com/delta-io/delta/pull/1845
- [ ] Integrate unidoc, syntax check, mima binary compatibility check, etc.

**Comment by kristoffSC** [comment]
@tdas there is one PR missing for Flink connector - what would be action plan now, after [#18237 is merged?](https://github.com/delta-io/delta/pull/1837).

Issue I've created: https://github.com/delta-io/connectors/issues/561
PR that solves issue for original connectors repo: https://github.com/delta-io/connectors/pull/559

**Comment by tdas** [comment]
The moving the change any connectors PR to this repo should be simple. 
- Create a patch file with the diff of the PR by appending `.patch` after the PR link. For example: `https://github.com/delta-io/connectors/pull/559.patch`
- Update the file paths in the patch file by prepending a "connectors/" in each path. 
- Apply this updated patch to the master branch of this repo

**Comment by tdas** [comment]
follow up PR to integrate all connector modules to the main build - https://github.com/delta-io/delta/pull/1845

**Comment by scottsand-db** [comment]
@tdas I've marked this as done, since I believe all the unidoc, mima, syntax work etc. has been completed? Please re-open if that isn't the case.
