### ISSUE TITLE
how to update multiple row

### ISSUE THREAD

**Issue by sanjiv1980** [delta-io/delta#189]
@marmbrus @tdas 
let's say i have bunch of records and i want to update multiple row , how do i do that , could u please guide me.

example
 ``` 
id,name,email,city
san-100,sanjiv,sanji@gmail.com,patna
aar-101,aarush,aarush@gmail.com,Ranchi
kal-103,kalindi,kalindi@gmail.com,Bangalore
kun-104,kunal,kunal@gmail.com,kolkata
kun-105,kundan,kundan@gmail.com,Delhi
```
i want to update the ids like san-100--->san-1000,kun-104 ----->kun-1004

note : I can update single row by below syntax
```
DeltaTable deltaTable = DeltaTable.forPath("delta-table");
Map<String,String> updateRecords = new HashMap<String, String>();	
updateRecords.put("id", "'Hello-world'");
deltaTable.updateExpr("id == \"san-100\"", updateRecords );
```

thanks

**Comment by tdas** [comment]
@sanjiv1980 apologies for not responding to this issue. You can do this sort multi-key update using the merge operation. 
1. Create a table/view/dataframe with all the needed changes. 
```
oldId,newId
san-100,san-1000
kun-104, kun-1004
```
2. Perform a merge operation using the source table/dataframe on the delta table. 
```
Dataset[Row] sourceDF = ...
DeltaTable deltaTable = DeltaTable.forPath("delta-table");
Map<String,String> updateRecords = new HashMap<String, String>();	
updateRecords.put("id", "s.newId");
deltaTable.merge(
    sourceDF.as("s")   
    "id == s.oldId")
  .whenMatched()
  .updateExpr(updateRecords)
  .execute();
```
See more about merge in https://docs.delta.io/0.4.0/delta-update.html#upsert-into-a-table-using-merge

**Comment by phoeph** [comment]
Hi @tdas
Happy for your feedback.
May I know how to update rows based on the conditions like below?

whenMatched(num = 1)
.updateExpr(updateRecords1)
.whenMatched(num = 2)
.updateExpr(updateRecords2)

But There can be at most one `update` action and one `delete` action in `whenMatched` clauses.
Two update action are not allowed.
Is there a way to solve such a thing？
or just merge twice?

Wish for your feedback :)
