### ISSUE TITLE
[BUG] Delta Standalone 3.0.0rc1 shades Delta Storage 3.0.0rc1 classes

### ISSUE THREAD

**Issue by dnskr** [delta-io/delta#1892]
## Bug
Delta Standalone 3.0.0rc1 shades Delta Storage 3.0.0rc1 and also depends on it at compile time.
It causes the issue, because a 3rd party project dependent on Delta Standalone has two sets of Delta Storage classes.

#### Steps to reproduce

1. Unzip [delta-standalone_2.12-3.0.0rc1.jar](https://repo1.maven.org/maven2/io/delta/delta-standalone_2.12/3.0.0rc1/delta-standalone_2.12-3.0.0rc1.jar) to check that storage classes are there.
2. Check that [delta-standalone_2.12-3.0.0rc1.pom](https://repo1.maven.org/maven2/io/delta/delta-standalone_2.12/3.0.0rc1/delta-standalone_2.12-3.0.0rc1.pom) has Delta Storage dependency.

#### Observed results

Comparison of Delta Standalone 0.6.0 and Delta Standalone 3.0.0rc1
![Standalone_shade_Storage](https://github.com/delta-io/delta/assets/36439732/e501c33d-cb10-439d-bd3a-aeb508cdb781)

#### Expected results

Delta Standalone shades Delta Storage **OR** Delta Standalone depends on Delta Storage

### Environment information

* Delta Lake version: 3.0.0rc1
* Spark version: -
* Scala version: 2.12

### Willingness to contribute

The Delta Lake Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the Delta Lake code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the Delta Lake community.
- [x] No. I cannot contribute a bug fix at this time.

**Comment by scottsand-db** [comment]
Thanks for bringing this to our attention! Seems like you could look at the build.sbt diff between the delta-connectors repo 0.6.0 and the delta-lake repo 3.0.0 to spot the issue?

**Comment by dnskr** [comment]
There seems to be a similar issue for Iceberg jar https://github.com/delta-io/delta/issues/1903.
I changed "Willingness to contribute" to "No", because after some exploration I found that unfortunately I don't have necessary experience with sbt.
