### ISSUE TITLE
[BUG] Iceberg JAR contains the spark and storage packages

### ISSUE THREAD

**Issue by felipepessoto** [delta-io/delta#1903]
### Describe the problem
I think this may be a build config issue. Why does iceberg jar contains the other Delta packages code?
<img width="1141" alt="image" src="https://github.com/delta-io/delta/assets/1336227/1b861ad8-2cbf-42f1-a0a3-14d126fdb4d0">

#### Steps to reproduce
You can use the https://repo1.maven.org/maven2/io/delta/delta-iceberg_2.12/3.0.0rc1/delta-iceberg_2.12-3.0.0rc1.jar

### Environment information

* Delta Lake version: 3.0.0 RC1
* Spark version:
* Scala version:

### Willingness to contribute

The Delta Lake Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the Delta Lake code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the Delta Lake community.
- [ ] No. I cannot contribute a bug fix at this time.

**Comment by scottsand-db** [comment]
This is indeed a bug! Thanks for bringing this to our attention!

**Comment by felipepessoto** [comment]
I'm trying to understand how this shaded build works, it is completely new to me. Not sure if I can fix before 3.0.0 final.

Do you know when 3.0.0 will be released?

**Comment by scottsand-db** [comment]
> Do you know when 3.0.0 will be released?

Won't be for a little while! The 3.0.0 preview was ... just a preview :p So some changes/commits may be coming.

**Comment by felipepessoto** [comment]
Oh ok. I was expecting it soon, based on previous versions where final was released days after RC

**Comment by dnskr** [comment]
It's similar to https://github.com/delta-io/delta/issues/1892, right?

**Comment by felipepessoto** [comment]
I think so, probably the fix be applied to both cases.

 @scottsand-db, there is any discussion explaining why shaded assembly was used, and if this is a temporary workaround to an iceberg bug? I'm still trying to understand how this work

**Comment by scottsand-db** [comment]
> Oh ok. I was expecting it soon, based on previous versions where final was released days after RC

Yup! Those were release candidates, this was a preview :p 

> there is any discussion explaining why shaded assembly was used, and if this is a temporary workaround to an iceberg bug?

Universal Format is its own Delta feature that, currently, converts and writes Iceberg. We didn't want Iceberg metadata cleanup (gc) to go and destroy your table, so for example we had to comment out parts of the Iceberg src code. Same for `SetSchema`. Perhaps someone smarter than me can figure out the best way to update the iceberg schema (it is inherently iterative not all-at-once) ... but the easiest thing I could think of was doing it all at once.

**Comment by scottsand-db** [comment]
We should be able to use a solution similar to https://github.com/delta-io/delta/pull/2018

**Comment by scottsand-db** [comment]
Note: it also is including the delta-storage jars ...
