### ISSUE TITLE
_delta_log fetching

### ISSUE THREAD

**Issue by PavelKuropatin** [delta-io/delta#1925]
Hello

Probably github is not the right place to ask this question, because it's open source delta.
So, is there any way to monitor/fetch _delta_log (which will be written into _delta_log) before/after recording? without using delta history api
Env: databricks. and the last one has its own private implementation for LogStore classes, so it's a little bit risky to change it on my implementations.

I hope you know the code better then me and will be able to remenber smth or point to some place

(don't hate<3)
Thanks

**Comment by allisonport-db** [comment]
Hi @PavelKuropatin I'm not sure I understand what you're asking. Are you saying you want to inspect the delta log files (and not use the delta history API)? What do you want to learn or retrieve from them? And what do you mean by "before/after recording"?

**Comment by PavelKuropatin** [comment]
Hi @allisonport-db. if I am not mistaken the delta log file contains 3 json records. and these records are being generated somehow before being written. And I would like to know if some events+listeners, logs, etc can contain this _delta_log or similar one.
At least I want to duplicate it in an another place.
Simple case - collect some info/stats from _delta_log after any action on a table/path

**Comment by schuermannator** [comment]
the `_delta_log` directory contains commits (json files) and checkpoints (parquet files) among a few other things. you are correct they are generated by Delta and then written out to storage. if you would like to 'monitor' the changes that are occurring to the log manually you can always directly monitor the underlying storage. regarding duplication, you can duplicate the directory. and for the simple case you mentioned, you will be able to detect any new actions on the table by simply monitoring the `_delta_log` directory for new commits (which will be new json files). let me know if this helps!

**Comment by tdas** [comment]
The [Delta Standalone project](https://docs.delta.io/latest/delta-standalone.html) was created for interacting with the Delta log directly (for building connectors that read/write the log).

**Comment by PavelKuropatin** [comment]
@schuermannator yes, this helps. Probably I also found the github project 'delta-oms' based on concept you mentioned. monitoring `_delta_log` (via steraming+checkpoints and following enrichment). it can be used as a workaround.
Thanks all for your assistance!
