### ISSUE TITLE
[Feature Request] Identity Column

### ISSUE THREAD

**Issue by felipepessoto** [delta-io/delta#1959]
#### Which Delta project/connector is this regarding?
- [X] Spark
- [ ] Standalone
- [ ] Flink
- [ ] Kernel
- [ ] Other (fill in here)

### Overview

Identity Column (writer version 6) as defined by https://github.com/delta-io/delta/blob/master/PROTOCOL.md#identity-columns. 

Design doc:  https://docs.google.com/document/d/1G8Vj6wOxswMx1JklllLoSn-obEpJ-iE_Lhpbd-RfIr4/edit?usp=sharing

PR:
- #2857 
- #2859 
- #2915 
- #2916 
- #3005
- #3023 
- #3404
- #3457
- #3459
- #3525
- #3526
- #3558
- #3568
- #3566
- #3594
- #3598

### Motivation

This is probably the biggest missing part in Open Source Spark Delta.

### Willingness to contribute
@c27kwan volunteered to work on this feature and posted a design doc [here]( https://docs.google.com/document/d/1G8Vj6wOxswMx1JklllLoSn-obEpJ-iE_Lhpbd-RfIr4/edit?usp=sharing).

**Comment by felipepessoto** [comment]
@dennyglee, @allisonport-db, do you have any update about this? This feature probably is the most important missing feature in OSS Delta.

Thanks.

**Comment by felipepessoto** [comment]
@tdas any chance this can be prioritized for next release?

Thanks.

**Comment by keen85** [comment]
duplicate of https://github.com/delta-io/delta/issues/1072?

**Comment by felipepessoto** [comment]
I think so. But I would update #1072 to be broader. The way the request is made it seems the Identity feature is already done, and it is only the DeltaTableBuilder API that is missing.

**Comment by c27kwan** [comment]
I'm interested on working on this!

**Comment by c27kwan** [comment]
I can't modify the main comment because i'm not a maintainer. Here's the design doc : https://docs.google.com/document/d/1G8Vj6wOxswMx1JklllLoSn-obEpJ-iE_Lhpbd-RfIr4/edit?usp=sharing

**Comment by felipepessoto** [comment]
@c27kwan that is great.

Have you discussed with any of the maintainers about your intention to contribute? I’m asking because this is a big feature and I just want to make sure they aren’t internally working on it and they are open to accept your implementation. 

Thanks.

**Comment by vkorukanti** [comment]
Hi @felipepessoto, we don't have anyone else working on this feature. Had an offline chat with @c27kwan before assigning the issue to @c27kwan. Feel free to look at the design doc and post any questions you have.

**Comment by c27kwan** [comment]
Sorry for the lack of update in 2.5 months -- I was on vacation for a month and haven't had opportunity to return to this. I've been talking to @zhipengmao-db and he volunteered to pick up the remainder of the implementation so we can make progress again. 🎉

**Comment by tigerhawkvok** [comment]
Very exciting! Will this make it to the 3.2.1 release?

**Comment by zhipengmao-db** [comment]
> Very exciting! Will this make it to the 3.2.1 release?

It will be in 3.3 release.

**Comment by felipepessoto** [comment]
@zhipengmao-db do you know the ETA to release 3.3.0?

If you are not planning additional changes, should we close this as done?

Thanks

**Comment by zhipengmao-db** [comment]
@felipepessoto The ETA for 3.3.0 is 11/20. We could close it as done already. Thanks!

**Comment by felipepessoto** [comment]
Completed #3598
