### ISSUE TITLE
[Feature Request] [Kernel] Selectively choose whether to or not to read the AddFile stats during LogReplay

### ISSUE THREAD

**Issue by scottsand-db** [delta-io/delta#1961]
We want to have the thinnest, most-lightweight read schema during LogReplay (parsing AddFiles and RemoveFiles, to yield the active add files in the table).

Thus, we should only read the AddFile statistics field when
1) there exists a query filter, and
2) the connector is able to evaluate the stats-min/max etc. query (used to perform data skipping for that input query filter)

If either of 1 or 2 is false, then we should skip reading the add file stats column during LogReplay json/checkpoint parsing.

**Comment by scottsand-db** [comment]
This doesn't yet seem relevant for 3.0 since the 3.0 delta-kernel release won't contain any stats-based column pruning. Thus there's no reason to read the stats in the first place, which is what delta-kernel is currently doing.

**Comment by allisonport-db** [comment]
Closed in 09b6dc5 and 1f7a475
