### ISSUE TITLE
Power BI Connector using fn_ReadDeltaTable present duplicated data record[BUG]

### ISSUE THREAD

**Issue by Aaron-monoova** [delta-io/delta#1978]
## Bug

This is a bug for Power BI connector using fn_ReadDeltaTable. I have been using this connector for almost 2 years, however, lately the dataflow using this connector was showing data duplication issue meanwhile the delta table in azure data lake is completely normal. The issue seems to exist for delta tables that have existed for a long time with delta logs. If I delete the delta table folder and recreate the table from scratch, the issue goes away, but I don't know how long it would last normally. Now I have to resort to the native databricks connector to refresh the delta table.

Due to the nature of the issue, it's hard to recreate the issue as a new delta table won't have the duplication issue. I was wondering if anyone else has similar issue related to the power BI connector to access delta tables in the azure data lake gen 2.

Thanks.

**Comment by vkorukanti** [comment]
@Aaron-monoova Is the duplicate rows problem only with the PowerBI connector? For example, do you know if your query using the Delta-Spark returns the correct rows? I want to narrow down where the problem is.

**Comment by Aaron-monoova** [comment]
> @Aaron-monoova Is the duplicate rows problem only with the PowerBI connector? For example, do you know if your query using the Delta-Spark returns the correct rows? I want to narrow down where the problem is.

Hi Venki, thanks for getting back, as far as I know, it's only with the PowerBI connector as the duplicated rows only exist within dataflow. If I query the table within databricks or using databricks connector on Power BI, it will return the correct results. The Power BI connector was working til the 1st August 2023. I tried to duplicate the issue in the dev environment, but to no avail with the same source datasets because the delta table in dev doesn't have as much delta history as the prod ( because prod delta table was overwritten everyday, but not for delta tables in dev).

**Comment by Aaron-monoova** [comment]
> @Aaron-monoova Is the duplicate rows problem only with the PowerBI connector? For example, do you know if your query using the Delta-Spark returns the correct rows? I want to narrow down where the problem is.

I'm not certain about the Delta-Spark connector you were referring to, is that another type of connector under the development? Could you share a link to it for me to test? Many thanks!

**Comment by dominikpeter** [comment]
I have the same issue. It can be reproduced with the attached dataset.

With delta-rs it looks good:

```python
from deltalake import DeltaTable

dt = DeltaTable("dataset")
ds = dt.to_pyarrow_table()

#print(ds.to_pandas())
print(f"Number of rows: {len(ds.to_pandas())}")

# Number of rows: 13
```

In PowerBI I have duplicate rows:
![powerbiresult](https://github.com/delta-io/delta/assets/7950597/699b06be-6f68-4d3d-a325-d684c991b6b0)

I guess the error was introduced with Databricks Runtime 13.3.

[dataset.zip](https://github.com/delta-io/delta/files/12643228/dataset.zip)

**Comment by dominikpeter** [comment]
The problem seems to be the `.compacted.json`. By ignoring it, it works again.

I can do a PR if you like?

**Comment by dominikpeter** [comment]
@Aaron-monoova PR is up. You can test this version: 
https://github.com/dominikpeter/delta/blob/e683d458f9aa02b984aa79abff8e523db42a050c/connectors/powerbi/fn_ReadDeltaTable.pq

I have a lot of Pipelines running and they all work again. I hope it fixes your issue too.

**Comment by Aaron-monoova** [comment]
> @Aaron-monoova PR is up. You can test this version: https://github.com/dominikpeter/delta/blob/e683d458f9aa02b984aa79abff8e523db42a050c/connectors/powerbi/fn_ReadDeltaTable.pq
> 
> I have a lot of Pipelines running and they all work again. I hope it fixes your issue too.

Hi Dominik, it has been tested, solved my issue, thanks so much!
