### ISSUE TITLE
when to support upsert and delete ?

### ISSUE THREAD

**Issue by sampan-dong** [delta-io/delta#20]
when to support upsert and delete ?

**Comment by mukulmurthy** [comment]
Hi there,

Supporting upsert and delete requires SQL DML support, which we are actively working on. You can expect a preview version of this in the next couple months.

**Comment by tdas** [comment]
We have started working on Scala APIs for merge/update/delete. I have created official issues to track their work (e.g. Merge is #42 and delete is #44 ). I am closing this ticket in favor of those. Please have any further discussion on those relevant threads.
