### ISSUE TITLE
Possibly eliminate nested directories in partitioned lakes

### ISSUE THREAD

**Issue by MrPowers** [delta-io/delta#213]
When we run `partitionBy` on a Delta lake, it creates a nested directory structure, similar to `partitionBy` for Parquet/CSV lakes.  For Parquet/CSV, we need the nested directory structure to apply the partition filters.  For Delta lake, we don't need the nested directory structure because the partition metadata is stored in the transaction log.

Here's some code that writes out a partitioned Delta lake:

```scala
df
  .write
  .format("delta")
  .partitionBy("country")
  .save(outputPath)
```

The data will be stored in the filesystem like this:

```
some_folder/
  _delta_log/
    00.json
  country=Argentina/
    file1.snappy.parquet
  country=Russia/
    file2.snappy.parquet
```

We could also store this data like this:

```
some_folder/
  _delta_log/
    00.json
  file1.snappy.parquet
  file2.snappy.parquet
```

We know that `file1` contains the Argentina data and `file2` contains the Russia data from the transaction log.

**Comment by SpaceRangerWes** [comment]
Would this be a feature flag or a default behavior? I have many reservations if this would be default behavior.

**Comment by MrPowers** [comment]
@SpaceRangerWes - Can you let me know your reservations?  I'm interested.  Do the nested directories in partitioned Delta lakes add anything that I might not be seeing?

**Comment by SpaceRangerWes** [comment]
@MrPowers a lot of it is in the value of partition pruning. Delta uses a lot of the spark internals for partition predicate logic. Even though it is tracking partition metadata in the delta log, much of the physical optimizations are still based on paths. So the removal of partitioning in the "hive way" would mean rewriting a lot of this logic. 

I'm not necessarily against the idea, but I am biased to having a more meaningful layout to my larger datasets instead of a single subdirectory. That last point is far more subjective.

**Comment by MrPowers** [comment]
@SpaceRangerWes - thanks for responding.  I don't know how the Spark or Delta partition readers / writers work under the hood, so take my thoughts with heaps of salt.  I'm still on the fence about this.  I was looking at a transaction log and looks like the partition information is getting stored in 3 separate places and that's why I figured it'd be good to open an issue.

Thanks for letting me know about this "Delta uses a lot of the spark internals for partition predicate logic. Even though it is tracking partition metadata in the delta log, much of the physical optimizations are still based on paths. So the removal of partitioning in the "hive way" would mean rewriting a lot of this logic." but we might actually want to avoid the Spark implementation in Delta.

I have a partitioned Parquet lake and the benchmarks I ran a few months ago showed the read times were 83X faster when I just grabbed the partitions I wanted directly rather than relying on Spark partition filtering.  `df.where($"country" === "Colombia")` was much slower than `val df = spark.read.parquet("/mnt/some_path/country=Colombia")`.

I am guessing that any implementation that relies on the filesystem structure in any way will be way slower than a transaction-log based solution.

Looking forward to digging into this more and learning more about the internals from you!

**Comment by SpaceRangerWes** [comment]
@SpaceRangerWes That is really interesting experimental results. Was the data large or small? If it is small, I imagine the optimizer building a logic plan is adding the additional time. If it is a larger dataset (5+ GB), then these results are much more serious.

**Comment by MrPowers** [comment]
@SpaceRangerWes - Just replicated the result to confirm and looks like I am remembering correctly.  I ran these computations on a partitioned data lake that has a lot more than 5GB of data (the partition key is made up here - the partitioned lake I work with has a lot more distinct values that the number of distinct countries in the world).

* `spark.read.parquet("/mnt/some_path/country=Colombia")` took 1.9 seconds
* `spark.read.parquet("/mnt/some_path").where($"country" === "Colombia")` took 7.8 minutes.

If you have a partitioned data lake lying around, run these calculations and let me know if you get something similar.

I'm guessing Spark is performing a file listing operation that isn't needed.  We should probably look into this.

**Comment by zsxwing** [comment]
@SpaceRangerWes Spark needs to list all file paths under `/mnt/some_path` for the query `spark.read.parquet("/mnt/some_path").where($"country" === "Colombia")`. The partition pruning avoids reading files but Spark still needs to list files.

Nested directory structure is not necessary to Delta but we try to make the structure friendly to other systems. E.g., a user can run `vacuum` to clean up garbage files and use Hive to read the table. In this case, nested directory structure will be helpful.

**Comment by SpaceRangerWes** [comment]
Thank you for the clarification @zsxwing.

**Comment by zsxwing** [comment]
@MrPowers The file listing is happening in `spark.read.parquet("/mnt/some_path")` when Spark tries to build the SQL plan. For example, it needs to list files to figure out the file schema and partition schema. At this moment, Spark has not seen `.where($"country" === "Colombia")"` yet.

**Comment by ZoharMeir** [comment]
Just wanted to list a couple of potential benefits to changing the storage layout:
1. Altering the partitioning of an existing table becomes relatively easier, and can be implemented so that it will not be data changing (i.e. can run with `.option("dataChange", "false")`). This can be very helpful for streams that rely on the repartitioned table as a source.
2. Keeping the partitioning information only as part of the metadata opens up the possibility of implementing "hidden partitions" like in [Apache Iceberg](https://iceberg.apache.org/partitioning/#what-does-iceberg-do-differently). I think this notion goes very will with the concept of schema evolution, because it's not uncommon for data distribution and use cases to change over time, requiring us to rethink the partitions of the table to optimise our workloads.

**Comment by MrPowers** [comment]
Thanks for the comment @ZoharMeir.  

@zsxwing @SpaceRangerWes - even if we don't change the layout, can we at least brainstorm solutions to eliminate the directory listing that's not necessary?  [Other users](https://stackoverflow.com/questions/51851827/spark-predicate-pushdown-performance/61333704#61333704) are asking about this too.  With Parquet lakes, we can fetch the directories we want directly to bypass the file listing, but this isn't possible for Delta.  

This file listing issue performance issue has made it so I can't use partitioned Delta data lakes.  I think it'll be possible to build some work-around cause the partition data is stored in the transaction log.  Let me know what you think!

Thanks again for the great work on this project!

**Comment by zsxwing** [comment]
> even if we don't change the layout, can we at least brainstorm solutions to eliminate the directory listing that's not necessary?

Could you clarify what is `the directory listing` here? Delta Lake doesn't list the data (parquet) files. It just needs to list the transaction logs to find out the data file paths. Then it will load them using the file paths without listing the directories.
