### ISSUE TITLE
[Kernel] Move precondition checks from DefaultKernelUtils to a separate pre-conditions class

### ISSUE THREAD

**Issue by allisonport-db** [delta-io/delta#2148]
#### Which Delta project/connector is this regarding?

- [ ] Spark
- [ ] Standalone
- [ ] Flink
- [X] Kernel
- [ ] Other (fill in here)

### Overview

`DefautKernelUtils` has a bunch of `checkArgument` methods which should be in their own class instead.
https://github.com/delta-io/delta/blob/master/kernel/kernel-defaults/src/main/java/io/delta/kernel/defaults/internal/DefaultKernelUtils.java#L75

### Motivation

Clean up code

**Comment by rpinzon** [comment]
hi @allisonport-db, can I work on this?

**Comment by vkorukanti** [comment]
> hi @allisonport-db, can I work on this?

Sounds good. Assigned the issue to you. Let us know if you need any help.
