### ISSUE TITLE
[Kernel] Implement assertLogFilesBelongToTable for LogReplay

### ISSUE THREAD

**Issue by allisonport-db** [delta-io/delta#2150]
#### Which Delta project/connector is this regarding?

- [ ] Spark
- [ ] Standalone
- [ ] Flink
- [x] Kernel
- [ ] Other (fill in here)

### Overview

Implement the function [here](https://github.com/delta-io/delta/blob/master/kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/LogReplay.java#L242) which can be based off of the Spark implementation [here](https://github.com/delta-io/delta/blob/4f9c8b9cc294ec7b321847115bf87909c356bc5a/spark/src/main/scala/org/apache/spark/sql/delta/Snapshot.scala#L430)

**Comment by PatrickLeahey** [comment]
@allisonport-db FYI I have opened a PR that defines this method + adds test coverage
