### ISSUE TITLE
[Kernel][Testing] Refactor LogReplaySuite to use TestUtils

### ISSUE THREAD

**Issue by allisonport-db** [delta-io/delta#2151]
#### Which Delta project/connector is this regarding?

- [ ] Spark
- [ ] Standalone
- [ ] Flink
- [x] Kernel
- [ ] Other (fill in here)

### Overview

Refactor LogReplaySuite to use TestUtils
https://github.com/delta-io/delta/blob/master/kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/LogReplaySuite.scala

### Motivation

Use common test utilities

**Comment by rpinzon** [comment]
hi @allisonport-db, can I give this a try?

**Comment by vkorukanti** [comment]
> hi @allisonport-db, can I give this a try?

Sounds good. Just assigned the issue.

**Comment by allisonport-db** [comment]
@rpinzon Hey I actually already did this as a part of #2212 since the `TestUtils` was needed for the other tests. Feel free to help review the PR if you'd like

**Comment by rpinzon** [comment]
> @rpinzon Hey I actually already did this as a part of #2212 since the `TestUtils` was needed for the other tests. Feel free to help review the PR if you'd like

Oh great. I'll take a look at the PR
