### ISSUE TITLE
[BUG]shadedDelta not found in 3.0.0rc2 distro

### ISSUE THREAD

**Issue by bvkiran** [delta-io/delta#2165]
## Bug
I am trying to use the rc2 build with this sbt
ThisBuild / scalaVersion := "2.13.12"

resolvers +=
  "Delta OSS Snapshots" at "https://oss.sonatype.org/content/repositories/iodelta-1120/"

lazy val sparkVersion = "3.5.0"

lazy val root = (project in file("."))
  .settings(
    name := "TestDelta"
  )
val scalatestVersion = "3.2.17"

libraryDependencies ++= Seq(
  "org.apache.spark" %% "spark-core" % sparkVersion,
  "org.apache.spark" %% "spark-sql" % sparkVersion,
  "org.scalatest" %% "scalatest" % scalatestVersion % "test",
  "io.delta" %% "delta-spark" % "3.0.0rc2" withSources(),
  "io.delta" %% "delta-iceberg" % "3.0.0rc2" withSources()
)

When I run with iceberge compatability, I get
java.lang.NoClassDefFoundError: shadedForDelta/org/apache/iceberg/types/Type$PrimitiveType

#### Which Delta project/connector is this regarding?

- [ ] Spark
- [ ] Standalone
- [ ] Flink
- [ ] Kernel
- [ ] Other (fill in here)

### Environment information

* Delta Lake version:
* Spark version:
* Scala version:

### Willingness to contribute

The Delta Lake Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the Delta Lake code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the Delta Lake community.
- [ ] No. I cannot contribute a bug fix at this time.

**Comment by scottsand-db** [comment]
Closed by https://github.com/delta-io/delta/pull/2166
