### ISSUE TITLE
[Feature Request][Kernel] Run unidoc for all changes

### ISSUE THREAD

**Issue by vkorukanti** [delta-io/delta#2209]
#### Which Delta project/connector is this regarding?

- [ ] Spark
- [ ] Standalone
- [ ] Flink
- [x] Kernel
- [ ] Other (fill in here)

### Overview
Currently the Kernel or Connector CI job just runs the tests and doesn't generate any docs to make sure there are no errors introduced in the PRs. Doc generation is [done as part of the `delta-spark` tests](https://github.com/delta-io/delta/blob/master/run-tests.py#L72) which are not run if the PR just contains Kernel only changes. 

May be it is better to separate out the unidoc generation into a separate CI workflow that always runs?

**Comment by sokolat** [comment]
Hello @vkorukanti, i am new to open source project project.
Can I get assigned to this as my first contribution ?

**Comment by allisonport-db** [comment]
> May be it is better to separate out the unidoc generation into a separate CI workflow that always runs?

This SGTM

**Comment by sokolat** [comment]
[Here](https://github.com/delta-io/delta/blob/8639c411890a5c77386f04e2282fcf4caa401eff/run-tests.py#L51C5-L51C27) we are only checking wether `test_group`  is not specified or it is spark. Hence unidoc is just generated for spark group [here](https://github.com/delta-io/delta/blob/master/run-tests.py#L72).
So I think allowing also `test_group` to be kernel group might fix the issue and correct me please if I am wrong.

**Comment by vkorukanti** [comment]
@sokolat Here is one plan: Don't run `unidoc` as part of the `run-tests.py`. Instead create a new `workflow` [here](https://github.com/delta-io/delta/tree/master/.github/workflows) that just runs `build/sbt unidoc`. This new workflow will be run for every PR (@allisonport-db Any idea to make the PR updates run the new workflow?)

**Comment by allisonport-db** [comment]
If you add a workflow to the `.github/worflows/` directory it should run on the PR

**Comment by sokolat** [comment]
hello @allisonport-db, in the job steps can I have a hint on what actions I need to to use ?
