### ISSUE TITLE
[Feature Request][Kernel] Exceptions framework

### ISSUE THREAD

**Issue by vkorukanti** [delta-io/delta#2231]
### Overview
The currently the exceptions thrown by the `kernel-api` or `kernel-defaults` module are arbitary and there is no easy way to distinguish between user (in this case connector) errors vs Delta table reading issues.

### Further details
Goals
* Want to define an exception where user (connector) errors are clearly distinguishable from the Kernel errors
* Error codes?

Tasks:
* Design and discussion - 2days
* Implementation of exception infra - 3days
   * We won’t be updating all of the existing code as part of this task.

**Comment by allisonport-db** [comment]
`DataTypeParser` added in #2282 throws a bunch of `IllegalArgumentExceptions` --> consider what exception should be thrown instead. Should we create an exception class that gives the overall schema and highlights the specific part that is wrong?

**Comment by allisonport-db** [comment]
This has been done! See EXCEPTION_PRINCIPLES.md for details
