### ISSUE TITLE
[Kernel] Investigate when we throw TableNotFoundException (snapshot creation vs table creation etc)

### ISSUE THREAD

**Issue by allisonport-db** [delta-io/delta#2253]
#### Which Delta project/connector is this regarding?

- [ ] Spark
- [ ] Standalone
- [ ] Flink
- [X] Kernel
- [ ] Other (fill in here)

### Overview

We throw a `TableNotFoundException` in a couple of scenarios (empty _delta_log folder, not a delta table, etc) on snapshot creation but sometimes on table creation (invalid path). Spend a small amount of time deciding when we should throw these errors (and maybe update the error messages to be more informative).

https://github.com/delta-io/delta/pull/2211#discussion_r1366515844

**Comment by vkorukanti** [comment]
This is resolved as part of https://github.com/delta-io/delta/pull/2949. @allisonport-db Let me know if there are issues that remained to be addressed.
