### ISSUE TITLE
[Question][delta-standalone] Delta protocol to delta-standalone version compatibility

### ISSUE THREAD

**Issue by rajagopr** [delta-io/delta#2254]
What would be the supported reader and writer versions of the delta protocol that the delta-standalone library supports? Running into the issue `Delta protocol version (3,7) is too new for this version of Delta Standalone Reader/Writer (1,2)`. The `delta-standalone` library version used was `delta-standalone_2.12-3.0.0`. Please clarify.

**Comment by vkorukanti** [comment]
The latest version of the standalone support protocol version(1, 2). It isn't up to date with the latest protocol changes. Currently, the community is focussing on the [Delta Kernel](https://github.com/delta-io/delta/tree/master/kernel) to support the latest protocol versions and provide a simpler APIs for connectors. 

How are you using the standalone? Can you check if [Delta Kernel](https://github.com/delta-io/delta/tree/master/kernel)  supports your use case?

**Comment by tdas** [comment]
@rajagopr +100 to what @vkorukanti  said.  Delta Kernel is the ground-up, rebuilt, superior successor of Delta Standalone that will provide a more future-proof way to build connectors for Delta. And for existing connectors on Delta Standalone, we want to work with the community to help them migrate from Delta Standalone. Super super interested in understanding your situation and help you out.

**Comment by rajagopr** [comment]
Closing as duplicate of https://github.com/delta-io/delta/issues/2243
