### ISSUE TITLE
donating to linux foundation means all features now available?

### ISSUE THREAD

**Issue by kaushikCanada** [delta-io/delta#226]
Are the following functions available on the delta lake donated to linux foundation? so now anyone can use these utilities?
Convert To Delta
Delete From
Fsck Repair Table
Merge Into 
Optimize 
Update

**Comment by marmbrus** [comment]
As we [mention in the README](https://github.com/delta-io/delta#roadmap), its our goal to open source all APIs of Delta Lake.

> Convert To Delta
> Delete From
> Fsck Repair Table
> Merge Into
> Update

Check [our release page](https://github.com/delta-io/delta/releases) for details on which of these is already available.

> Optimize

This is a pure performance / cost optimization that is deeply tied to features in the Databricks Runtime (not an API that is required to correctly run a program). There are [no plans to open source optimize](https://github.com/delta-io/delta/issues/49#issuecomment-526343434), but you can do [basic file compaction with easily Delta Lake (thanks to the power of ACID transactions)](https://docs.delta.io/latest/best-practices.html#compact-files).

**Comment by kaushikCanada** [comment]
Thank you. got it.

**Comment by kaushikCanada** [comment]
Thank you. Got my answer.
