### ISSUE TITLE
[Feature Request][Kernel] Support getting snapshot by version id

### ISSUE THREAD

**Issue by vkorukanti** [delta-io/delta#2275]
#### Which Delta project/connector is this regarding?

- [ ] Spark
- [ ] Standalone
- [ ] Flink
- [x] Kernel
- [ ] Other (fill in here)

### Overview
Currently Kernel only supports reading the latest snapshot in a table (API [here](https://docs.delta.io/latest/api/java/kernel/io/delta/kernel/Table.html)) This task is to add support for fetching a snapshot by version id. 

```
interface Table
{
  /**
   * Get the snapshot with given {@code versionId}.
   */
  Snapshot getSnapshotAtVersion(long versionId)
}
```

### Willingness to contribute

The Delta Lake Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature?

- [ ] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the Delta Lake community.
- [x] No. I cannot contribute this feature at this time.

**Comment by Silverlight42** [comment]
Hello! Can I offer to help with this task?
