### ISSUE TITLE
[BUG][Kernel] Remove the `MixedDataType` from Kernel data types

### ISSUE THREAD

**Issue by vkorukanti** [delta-io/delta#2277]
#### Which Delta project/connector is this regarding?

- [ ] Spark
- [ ] Standalone
- [ ] Flink
- [x] Kernel
- [ ] Other (fill in here)

### Describe the problem
Delta 3.0 version of Kernel APIs have data type ([MixedDataType](https://github.com/delta-io/delta/blob/master/kernel/kernel-api/src/main/java/io/delta/kernel/internal/types/MixedDataType.java#L24)) that is not part of the spec, but was added to get around the issues with table schema encoded in JSON. More details refer [here](https://github.com/delta-io/delta/blob/master/kernel/kernel-api/src/main/java/io/delta/kernel/internal/types/MixedDataType.java#L24).

We should get rid of this class as it causes confusion on list of data type supported by the Kernel.

### Willingness to contribute

The Delta Lake Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the Delta Lake code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the Delta Lake community.
- [ ] No. I cannot contribute a bug fix at this time.

**Comment by allisonport-db** [comment]
Decision doc on how to deserialize delta schemas: https://docs.google.com/document/d/1UOlw498twX0OME1T4e66lV9daZz7OjY4YCw0WxK2Jzs/edit?usp=sharing
