### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by SeXySaRaH1986** [delta-io/delta#2285]
#### Which Delta project/connector is this regarding?

- [ Journey of a Dream] Spark
- [ ] Standalone
- [ ] Flink
- [ ] Kernel
- [ ] Other (fill in here)

### Willingness to contribute

The Delta Lake Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature?

- [ ✓] Yes. I can contribute this feature independently.
- [x] Yes. I would be willing to contribute this feature with guidance from the Delta Lake community.
- [ ] No. I cannot contribute this feature at this time.

**Comment by allisonport-db** [comment]
Closing this as there are no details or title. Feel free to reopen with further information about a feature request.
