### ISSUE TITLE
Multi threading support  on delta table

### ISSUE THREAD

**Issue by pawankumarshukla** [delta-io/delta#23]
We faced issue the Parquet table was not compatible with Multi thread processing(Parallel insert in table). Dose delta table is compatible with Multi thread processing(Parallel insert/upsert, delete)?

**Comment by tdas** [comment]
the current version 0.1.0 does not support concurrent writes, but we are going to relax the conflict checks soon to allow concurrent writes. soon.

**Comment by liwensun** [comment]
Thanks for trying out Delta Lake and sharing your use case. To better manage and track concurrency control support in Delta Lake, we have created an official issue that references this issue.
