### ISSUE TITLE
Can we able to write _delta_log on some specific place.

### ISSUE THREAD

**Issue by sanjiv1980** [delta-io/delta#230]
Can we able to write _delta_log on some specific place. 
Lets say I want to keep my processed data here  :"/delta-table/year/month/day".  
and I need my _delta_log should be on common place like "/delta-table/_delta_log".

Is it possible to do like that. ?

**Comment by tdas** [comment]
I dont fully understand your scenario. If you want to keep your data in `/delta-table/year/month/day`, then you can create a single delta table at location `/delta-table/` partitioned by 3 columns - year, month and day. Well, it will create the directory structure as `/delta-table/year=2019/month=11/day=30` so its slightly different. But does that exact directory structured matter to you?

**Comment by sanjiv1980** [comment]
Let me explain my scenario : Actually in my table there is only date column (yyyy-mm-dd), lets say (2019-10-31), based on our requirements we are storing our data in below format like 
`(/delta-table/year=2019/month=10/day=31/....list of files)`
`(/delta-table/year=2019/month=11/day=01/....list of files)`

coming to the delta lake, lets say we processed the same data by  delta lake APIs , then _delta_log will sit under 'day' , so when we process the data for next day (2019-11-01) then again _delta_log will be creating and will sit under next 'day' . 
so I wanted like _delta_log should be in one place (/delta-table/._delta_log) so that it can load data from there  .

Hope you understand my requirements.

**Comment by mukulmurthy** [comment]
There should be only one _delta_log folder for the table, under the root `delta-table/` in your case. If you're seeing a _delta_log in each day directory, then whatever you're using to add data to the table is treating each folder as a separate table. Can you paste your code where you're writing data using delta?

**Comment by sanjiv1980** [comment]
Here is my code 
```
Dataset<Row> pData = dataFrameReader.load("/Users/kumars3/Documents/workspace-sts/deltalake/input-data/06/*");
		
		pData.write()
		.mode("append").
		format("delta").
		partitionBy("hit_date_utc").
		save("/Users/kumars3/Documents/workspace-sts/espn-deltalake/output-data/delta-table/clickstream/year/month/day/");```

Actually , `year`, `month` and `day` is variable which is getting evaluated on runtime and because of that _deltaLog is getting created for each day . So I thought to ask , is there any api, which help me to give the the location of .`deltaLog` , so that It can create at one place

**Comment by mukulmurthy** [comment]
The Delta log folder is always in the table root, so you'd have to just save your data under /Users/kumars3/Documents/workspace-sts/espn-deltalake/output-data/delta-table/clickstream.

Assuming you want to end up with a table partitioned by year, month, and day, you can do `.partitionBy("year", "month", "day"). If your source data doesn't have those columns, you can use `.withColumn("year", ...)` to add them to your dataset. Spark SQL has some functions that can help you extract the right info from a timestamp or date column, for example https://spark.apache.org/docs/latest/api/sql/index.html#dayofmonth.

**Comment by sanjiv1980** [comment]
Thank you @mukulmurthy , Thanks for your help., going to close this ticket.
