### ISSUE TITLE
Update columns referenced in the merge's on condition

### ISSUE THREAD

**Issue by ronflomin** [delta-io/delta#236]
Hi,
I was wondering what is delta's behavior if I try to update a column that is referenced in the merge on condition.

**Comment by tdas** [comment]
It is the same behavior as merge in any sql engine. With multi-version concurrency control, delta will read the latest version of the table to find out what to update, and then write the next version of the table (not the entire table, just few files selectively as needed). So you get full serializability over the entire table.
