### ISSUE TITLE
Support orc?

### ISSUE THREAD

**Issue by melin** [delta-io/delta#238]
the orc community has developed faster and more performance

**Comment by it-sceptic** [comment]
Agree with @melin

**Comment by tdas** [comment]
This is definitely something that would be a good addition. However, there are a few things to consider before building this as pointed out as questions by @marmbrus in this issue -https://github.com/delta-io/delta/issues/87#issuecomment-509730048

**Comment by zsxwing** [comment]
Closing this as duplicate of #87
