### ISSUE TITLE
Shaded version of local mode for Delta

### ISSUE THREAD

**Issue by zsxwing** [delta-io/delta#245]
Today Delta requires a Spark cluster to run. However, Delta is actually a storage format but happens to use Spark to process its logs. The user should be able to use Delta in other engines. The goal of this issue is to create a shaded version of the Delta library to help integration with other JVM based engines (presto, hive, etc).

**Comment by ChethanUK** [comment]
Presto connector will be great!.

**Comment by xianyinxin** [comment]
Thanks @zsxwing it's really a great feature we want. I wonder is there a roadmap, or can you elaborate some info how it is designed?

**Comment by zsxwing** [comment]
We created a repo for all connectors including this one: https://github.com/delta-io/connectors All further work of this issue will be put into this new repo.

**Comment by tdas** [comment]
Closing this issue. The repo mentioned above has the uber jar to read Delta log files.
