### ISSUE TITLE
[Kernel][Feature Request] Support data skipping using min/max file statistics for TIMESTAMP type columns

### ISSUE THREAD

**Issue by allisonport-db** [delta-io/delta#2462]
#### Which Delta project/connector is this regarding?

- [ ] Spark
- [ ] Standalone
- [ ] Flink
- [X] Kernel
- [ ] Other (fill in here)

### Overview

In #2433 we block skipping using file statistics on timestamp columns. This is because timestamps are truncated to milliseconds when written to JSON statistics, and thus we cannot safely use the MAX statistics since we may see microsecond precisions.

To use the timestamp MAX statistic we need to add a millisecond to it as we do in [DataSkippingReader](https://github.com/delta-io/delta/blob/master/spark/src/main/scala/org/apache/spark/sql/delta/stats/DataSkippingReader.scala#L646).

### Further details

To do this we need to support time addition first.

**Comment by sebastian2296** [comment]
Hi! I would like to work on this issue.

**Comment by vkorukanti** [comment]
@sebastian2296 sounds good. Let us know if you have any questions.
