### ISSUE TITLE
Structured streaming read from kafka interactive with Delta?

### ISSUE THREAD

**Issue by phoeph** [delta-io/delta#249]
Structured streaming read from kafka,how can I join Delta table and just insert into Delta table?
One way that I think is :

val source = spark.readStream.format("kafka")
val table = DeltaTable.forPath(path)
source.join(table.toDF()).writeStream.format("delta").start()

There have another update/insert/delete after JOIN func.
So I prefer use foreachBatch to do this.But another problem appears.
How can I insert datas into Delta table?

Could you please help to provide me an idea?

**Comment by phoeph** [comment]
How can I streaming insert data into table after join?
Use upsert? use "whenNotMatched("1 = 0").insert"?

**Comment by phoeph** [comment]
What I am using now is as below.Am I in right way?

old.as("old")
            .merge(
            maxTimeDF.filter("code in (1701, 11928)").as("new"),
            "1 = 0")
            .whenNotMatched()
            .insert

**Comment by marmbrus** [comment]
The docs show how to append to a table using [batch](https://docs.delta.io/latest/delta-batch.html#append-using-dataframes) and [streaming](https://docs.delta.io/latest/delta-streaming.html#append-mode).

If those are not working for you, please state what error you are encountering.

> `whenNotMatched("1 = 0").insert`

This does not look right to me.  Its likely much more expensive than just using the append code linked to above.

**Comment by phoeph** [comment]
Thank you for your reply :)
I got your point, and will try batch append in foreachBatch method.
