### ISSUE TITLE
How to update rows based on more than one condtitions?

### ISSUE THREAD

**Issue by phoeph** [delta-io/delta#251]
May I know how to update rows based on the conditions like below?

deltaTable
.merge(
    sourceDF.as("s")   
    "id == s.oldId")
.whenMatched(num = 1)
.updateExpr(updateRecords1)
.whenMatched(num = 2)
.updateExpr(updateRecords2)

But There can be at most one update action and one delete action in whenMatched clauses.
Two update actions are not allowed.
Is there a way to solve such a thing？
or just merge twice?

Wish for your feedback :)

**Comment by phoeph** [comment]
For example:

val selectedLimit = 
          when($"new.code" === 15271, expr("new.loanAmount"))
          .when($"new.code" === 15272, expr("new.loanAmountCash"))

//first update
deltaTable.as("old")
          .merge(
            crossDF.filter("code in (15271, 15272)").as("new"),
            "old.id_person = new.personId")
          .whenMatched("Initial_limit is null")
          .update(Map("Initial_limit" -> selectedLimit))
          .execute()

//second update
deltaTable.as("old")
          .merge(
            crossDF.filter("code in (15271, 15272)").as("new"),
            "old.id_person = new.personId")
          .whenMatched()
          .update(Map("selected_limit" -> selectedLimit))
          .execute()

Can I combine these two merge to below?

deltaTable.as("old")
          .merge(
            crossDF.filter("code in (15271, 15272)").as("new"),
            "old.id_person = new.personId")
          .whenMatched()
          .update(
            Map("Initial_limit" -> when($"old.Initial_limit".isNotNull, selectedLimit)
                                             .otherwise($"old.Initial_limit"),//otherwise value means no need to update
              "selected_limit" -> selectedLimit)
          )
          .execute()

May I know it is in the right way?

**Comment by phoeph** [comment]
Sorry for the format, the "Insert code" is not valid now.

**Comment by tdas** [comment]
Yes. That is the ideal way to combine multiple conditional updates into 1 update.

**Comment by phoeph** [comment]
Many Thanks.
:)
