### ISSUE TITLE
[Kernel][Data skipping] Add support data skipping for IS_NULL and NOT(IS_NULL)

### ISSUE THREAD

**Issue by allisonport-db** [delta-io/delta#2530]
#### Which Delta project/connector is this regarding?

- [ ] Spark
- [ ] Standalone
- [ ] Flink
- [X] Kernel
- [ ] Other (fill in here)

### Overview

Currently Kernel supports a limited set of expressions. We should use file statistics to prune files based on the `IS_NULL` expression.

### Motivation

Better file pruning.

### Further details

This means we should
1) add IS_NULL to the Kernel [Predicate](https://github.com/delta-io/delta/blob/master/kernel/kernel-api/src/main/java/io/delta/kernel/expressions/Predicate.java) and support it in the kernel-defaults project (completed as part of #2651).
2) Generate a data skipping filter according to the [same rules](https://github.com/delta-io/delta/blob/master/spark/src/main/scala/org/apache/spark/sql/delta/stats/DataSkippingReader.scala#L467) we use in delta-spark

### Willingness to contribute

The Delta Lake Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature?

- [ ] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the Delta Lake community.
- [x] No. I cannot contribute this feature at this time.

**Comment by vkorukanti** [comment]
@tlm365 Are you interested in this issue? This is a follow-up to the `IS_NULL` PR that you worked on. If you are interested, let us know if you have any questions/help getting started.

**Comment by tlm365** [comment]
> @tlm365 Are you interested in this issue? This is a follow-up to the `IS_NULL` PR that you worked on. If you are interested, let us know any questions/help getting started.

@vkorukanti take it easy, I will take a look soon.
