### ISSUE TITLE
Checkpoint is preventing application from accessing previous delta table versions newer than logRetentionDuration

### ISSUE THREAD

**Issue by ffmmjj** [delta-io/delta#255]
## Example scenario
Suppose I have a Delta table with a single version (v0) created 30 days ago (considering that the current date is 2019-11-13) and I perform 9 writes today in this same table. The table's history will look something like this:
```
+-------+-------------------+------+--------+---------+--------------------+----+--------+---------+-----------+--------------+-------------+
|version|          timestamp|userId|userName|operation| operationParameters| job|notebook|clusterId|readVersion|isolationLevel|isBlindAppend|
+-------+-------------------+------+--------+---------+--------------------+----+--------+---------+-----------+--------------+-------------+
|      9|2019-11-13 18:14:46|  null|    null|    WRITE|[mode -> Overwrit...|null|    null|     null|          8|          null|        false|
|      8|2019-11-13 18:14:41|  null|    null|    WRITE|[mode -> Overwrit...|null|    null|     null|          7|          null|        false|
|      7|2019-11-13 18:14:37|  null|    null|    WRITE|[mode -> Overwrit...|null|    null|     null|          6|          null|        false|
|      6|2019-11-13 18:14:32|  null|    null|    WRITE|[mode -> Overwrit...|null|    null|     null|          5|          null|        false|
|      5|2019-11-13 18:14:29|  null|    null|    WRITE|[mode -> Overwrit...|null|    null|     null|          4|          null|        false|
|      4|2019-11-13 18:14:25|  null|    null|    WRITE|[mode -> Overwrit...|null|    null|     null|          3|          null|        false|
|      3|2019-11-13 18:14:22|  null|    null|    WRITE|[mode -> Overwrit...|null|    null|     null|          2|          null|        false|
|      2|2019-11-13 18:14:19|  null|    null|    WRITE|[mode -> Overwrit...|null|    null|     null|          1|          null|        false|
|      1|2019-11-13 18:14:17|  null|    null|    WRITE|[mode -> Overwrit...|null|    null|     null|          0|          null|        false|
|      0|2019-10-13 18:14:17|  null|    null|    WRITE|[mode -> Overwrit...|null|    null|     null|       null|          null|        false|
+-------+-------------------+------+--------+---------+--------------------+----+--------+---------+-----------+--------------+-------------+
```
At this point, it's still possible to select version 0 of this table via time travel, as expected.

If I perform another write in this table, it will trigger the creation of a checkpoint and a metadata cleanup of the delta files that are older than `logRetentionPeriod` (30 days by default), which will remove version 0 from the history:
```
+-------+-------------------+------+--------+---------+--------------------+----+--------+---------+-----------+--------------+-------------+
|version|          timestamp|userId|userName|operation| operationParameters| job|notebook|clusterId|readVersion|isolationLevel|isBlindAppend|
+-------+-------------------+------+--------+---------+--------------------+----+--------+---------+-----------+--------------+-------------+
|     10|2019-11-13 18:14:53|  null|    null|    WRITE|[mode -> Overwrit...|null|    null|     null|          9|          null|        false|
|      9|2019-11-13 18:14:46|  null|    null|    WRITE|[mode -> Overwrit...|null|    null|     null|          8|          null|        false|
|      8|2019-11-13 18:14:41|  null|    null|    WRITE|[mode -> Overwrit...|null|    null|     null|          7|          null|        false|
|      7|2019-11-13 18:14:37|  null|    null|    WRITE|[mode -> Overwrit...|null|    null|     null|          6|          null|        false|
|      6|2019-11-13 18:14:32|  null|    null|    WRITE|[mode -> Overwrit...|null|    null|     null|          5|          null|        false|
|      5|2019-11-13 18:14:29|  null|    null|    WRITE|[mode -> Overwrit...|null|    null|     null|          4|          null|        false|
|      4|2019-11-13 18:14:25|  null|    null|    WRITE|[mode -> Overwrit...|null|    null|     null|          3|          null|        false|
|      3|2019-11-13 18:14:22|  null|    null|    WRITE|[mode -> Overwrit...|null|    null|     null|          2|          null|        false|
|      2|2019-11-13 18:14:19|  null|    null|    WRITE|[mode -> Overwrit...|null|    null|     null|          1|          null|        false|
|      1|2019-11-13 18:14:17|  null|    null|    WRITE|[mode -> Overwrit...|null|    null|     null|          0|          null|        false|
+-------+-------------------+------+--------+---------+--------------------+----+--------+---------+-----------+--------------+-------------+
```

### Expected behavior
At this point, should I be able to select version 1 from this table via time travel (from my understanding of the documentation) since it still appears in the table's history and this version is newer than `logRetentionPeriod`.

### Observed behavior
Right now, if I try to do this, I get the following error:
```
pyspark.sql.utils.AnalysisException: 'Cannot time travel Delta table to version 1. Available versions: [10, 10].;'
```

### Script to reproduce this scenario 
Here's a script that can replicate this result locally using PySpark (I've also noticed this same behavior in the cloud using Azure Databricks):
```
import os
import time

from pyspark.sql import SparkSession


if __name__ == '__main__':
    saved_data_path = 'data/delta/test'
    spark = (
        SparkSession.builder.appName("TestTimeTravelWithCheckPoint")
            .master("local[*]")
            .config('spark.jars.packages', 'io.delta:delta-core_2.11:0.4.0')
            .getOrCreate()
    )
    a_df = spark.sparkContext.parallelize([
        ["1", "x"],
        ["2", "y"] ,
        ["3", "z"]
    ]).toDF(["COL1", "COL2"])

    # Create version 0
    a_df.write.format("delta").mode("overwrite").save(saved_data_path)

    # Update the timestamp of this version to more than 30 days ago
    os.utime('data/delta/test/_delta_log/00000000000000000000.json', (time.time(), time.time() - (31*24*60*60)))

    # Create versions 1-9 with having the current day as timestamp
    for i in range(9):
        a_df.write.format("delta").mode("overwrite").save(saved_data_path)

    # History shows versions 0-9
    spark._jvm.io.delta.tables.DeltaTable.forPath(saved_data_path).history().show()
    # Still possible to retrieve version 0
    print('Version 0:')
    spark.read.format('delta').option('versionAsOf', '0').load(saved_data_path).show()

    # Create a new version (10) which triggers checkpointing and removal of
    # versions based on logRetentionPeriod (30 days by default)
    a_df.write.format("delta").mode("overwrite").save(saved_data_path)

    # History now shows only versions 1-10 - version 0 was removed
    spark._jvm.io.delta.tables.DeltaTable.forPath(saved_data_path).history().show()
    
    # Possible to retrieve latest version (10)
    print('Version 10:')
    spark.read.format('delta').option('versionAsOf', '10').load(saved_data_path).show()
    # Not possible to retrieve earliest version (1) despite the fact that its timestamp difference
    # is less than logRetentionPeriod (30 days)
    print('Version 1:')
    spark.read.format('delta').option('versionAsOf', '1').load(saved_data_path).show()
```

**Comment by mukulmurthy** [comment]
hi @ffmmjj , thank you for the nicely formatted + detailed issue! I agree that this is not ideal behavior. Would you like to propose a fix for this? If not, we can see if we can schedule some time to fix it, but I'm not sure it'll be before the 0.5.0 release.

> I've also noticed this same behavior in the cloud using Azure Databricks

Azure Databricks has a slightly better log cleanup algorithm that's able to take advantage of some other pieces of the Databricks runtime. This issue should not happen there (unless you're on a very old version, like from more than a year ago). If you see it there, please feel free to file a support ticket or contact us on the Delta Slack channel.

**Comment by ffmmjj** [comment]
Thanks for the response, @mukulmurthy . I saw this happening in an Azure Databricks cluster that uses runtime version 5.5 - I tried to replicate the scenario above in a cluster using runtime 6.1 but I can't set it up since it's not possible to change the timestamps of the versions like I did in that test script (because all the files are written to DBFS and I couldn't find a way to write the delta files into the cluster's local filesystem).

The issue itself seems to be caused by how `org.apache.spark.sql.delta.DeltaHistoryManager#getEarliestReproducibleCommit` is implemented: it scans the `_delta_log` directory files in lexicographic order keeping track of the smallest delta version that it found and, as soon as it finds a checkpoint file whose version is greater than or equal to the smallest delta version found _so far_, it returns that checkpoint version (which will be considered the oldest version that can be selected using time travel).
In the scenario that I described, this method is traversing all the delta files (with versions from 1 to 10) before finding the checkpoint corresponding to version 10. At that point, the minimum delta version that it found is 1, so it will return version 10 since it is already greater than that minimum delta version found so far. 

it's still not clear to me why it must return the checkpoint version instead of the min delta version in this case - I presume it has something to do with transactional guarantees during concurrent writes/deletes, but I'd need to get a better understanding of how checkpoints are supposed to behave in these scenarios in order to suggest any fixes... I'll try to take some time throughout the next week to take a deeper look at this and submit a PR if I manage to find a way to fix this without affecting delta's transactional behavior.

**Comment by ffmmjj** [comment]
Also, I'm just curious about the choice of words, btw: you said `I agree that this is not ideal behavior`, so is this behavior actually expected (albeit undesirable)?

**Comment by mukulmurthy** [comment]
A log delta (*.json) is created in the _delta_log folder on every commit; a checkpoint is created every 10 (by default) commits that describes the entire state of the table.

The behavior you described earlier (in DeltaHistoryManager) is trying to find the earliest  version we can reconstruct a snapshot of. If we're missing one of the earlier logs (like 0.json or 1.json), it can't construct any of the versions after that until the next checkpoint (10.checkpoint.parquet).

I suspect the more likely explanation is that our log cleanup logic is a little overzealous (you can verify if this is true by seeing if, in fact, any of the log files 0-9 are deleted). That behavior is controlled by https://github.com/delta-io/delta/blob/master/src/main/scala/org/apache/spark/sql/delta/MetadataCleanup.scala.

I said "this is not ideal" because I wasn't (and am still not) sure whether to consider this a bug or an enhancement. If it's DeltaHistoryManager not listing the right version, that would definitely be a bug. If it's the cleanup, feel free to suggest any changes to that logic! We'd be happy to look at either a mini design proposal or a PR to improve the cleanup.

**Comment by NastasiaSaby** [comment]
Hello, I think I might be facing the same issue using Azure Databricks 7.3 LTS ML. Do you know if there's a workaround? Thank you for your help!

**Comment by dennyglee** [comment]
Will update this issue upon assessment the attached PR #627. Thanks!

**Comment by zsxwing** [comment]
Closing this as we have improved the doc in https://docs.delta.io/latest/delta-batch.html#data-retention
