### ISSUE TITLE
bug on injecting into roblox

### ISSUE THREAD

**Issue by susmann784** [delta-io/delta#2560]
Delta Error Log 1/23/2024 6:42:48 PM

File Name: C:\Users\razaa\AppData\Roaming\delta_core\error_logs\ERROR_LOG_52968583.0615.txt
HResult: -2147467259
Exception Data: System.Collections.ListDictionaryInternal
Causing Func: GetModuleInfos
Target Site: System.Diagnostics.ModuleInfo[] GetModuleInfos(Int32, Boolean)
Outer Exception Message: A 32 bit processes cannot access modules of a 64 bit process.
Outer Exception Source: System

**Comment by Jaztehboi33355** [comment]
how do i fix

**Comment by LNLenost** [comment]
lil bro this ain't the repository for the executor delta 💀
