### ISSUE TITLE
Is that Merge can be apply partition-wise 

### ISSUE THREAD

**Issue by sanjiv1980** [delta-io/delta#257]
I have around more than 50TB of delta table which has partitioned based on `year | month| day` . when I executed merge statement on 20-node cluster , It is taking too much time . What could be the best strategy .? 

Earlier when I ran for single day It took only 15 mins to complete on same cluster. So I thought ,Is it possible to execute merge statement partition-wise .? 

Please let me know the possible solution.

Thanks.

**Comment by tdas** [comment]
If you know your source data will match with a certain date range of the target table, then you can add that as a condition in the merge statement
```
MERGE INTO target_table 
USING source
ON source.key = target_table.key AND (target_table.date BETWEEN date1 AND date2)
...

```
Merge operates by trying to scan the target table for matches with the source table, so the more conditions you add to limit the search space in the target table, the faster your query will be.

**Comment by sanjiv1980** [comment]
Thank you .!!!
