### ISSUE TITLE
[Kernel][Snapshots] Kernel Table API to read arbitrary snapshots

### ISSUE THREAD

**Issue by abhishekrb19** [delta-io/delta#2581]
#### Which Delta project/connector is this regarding?

Related to the Druid-Delta Lake connector https://github.com/apache/druid/pull/15755. Currently in 3.0.0, the `Table` interface only supports reading the [latest](https://docs.delta.io/3.0.0/api/java/kernel/io/delta/kernel/Table.html#getLatestSnapshot-io.delta.kernel.client.TableClient-) snapshot. I see the same for the pre-release version [3.1.0](https://docs.delta.io/3.1.0/api/java/kernel/index.html). How feasible would it be to add support for reading arbitrary snapshots in the Delta Kernel?

- [ ] Spark
- [ ] Standalone
- [ ] Flink
- [x] Kernel
- [ ] Other (fill in here)

### Willingness to contribute

The Delta Lake Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature?

- [ ] Yes. I can contribute this feature independently.
- [x] Yes. I would be willing to contribute this feature with guidance from the Delta Lake community.
- [ ] No. I cannot contribute this feature at this time.

**Comment by allisonport-db** [comment]
Hey @abhishekrb19 I'm actually working on this now, I'll link you on the PR when it's ready.

Cross-linking this with #2275 for reference.

**Comment by abhishekrb19** [comment]
Thank you, @allisonport-db! Looking forward to that functionality.

**Comment by tdas** [comment]
@abhishekrb19 can i ask what is your interest this feature? or Kernel in general? Are you planning to integrate with Kernel?

**Comment by tdas** [comment]
@abhishekrb19 Actually, never mind my questions, I looked at the PR https://github.com/apache/druid/pull/15755 you linked. This is amazing, you have already used Delta Kernel to integrate Delta Lake support in Apache Druid! 

Can I ask how and when this support is going to be released?

**Comment by abhishekrb19** [comment]
@tdas, thanks! We plan to include this in the upcoming Druid 29 release (date TBD).

**Comment by tdas** [comment]
@abhishekrb19 thank you for the info. in 3.1, we made a few API changes, and added data skipping support. are you interested in using 3.1? If so, we can chat and help out. Would love to get your feedback in general about using Kernel the APIs.

**Comment by abhishekrb19** [comment]
@tdas, yes, 3.1.0 looks exciting, the PR to upgrade the connector in Druid is here: https://github.com/apache/druid/pull/15842 
I will share some feedback on the APIs once I'm done plumbing in scan filters. Thanks!

**Comment by abhishekrb19** [comment]
https://github.com/delta-io/delta/pull/2607
