### ISSUE TITLE
[Feature Request][Kernel] Add support for `IS_NULL` expression

### ISSUE THREAD

**Issue by vkorukanti** [delta-io/delta#2632]
#### Which Delta project/connector is this regarding?

- [ ] Spark
- [ ] Standalone
- [ ] Flink
- [x] Kernel
- [ ] Other (fill in here)

### Overview
Add support for `IS_NULL` expression. The semantics of the expression are similar to SQL (examples [here](https://www.w3schools.com/sql/sql_isnull.asp))

[Here](https://github.com/delta-io/delta/pull/2360) is an example PR that added the support for `IS_NOT_NULL` which can be used as template to add the support for `IS_NULL`.

### Willingness to contribute

The Delta Lake Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature?

- [ ] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the Delta Lake community.
- [ ] No. I cannot contribute this feature at this time.

**Comment by robertkossendey** [comment]
@vkorukanti I haven't worked on Delta yet & I am not a professional Scala dev, but I'd love to contribute.

**Comment by vkorukanti** [comment]
> @vkorukanti I haven't worked on Delta yet & I am not a professional Java dev, but I'd love to contribute.

Thank you @robertkossendey for your interest. Do you want with [this](https://github.com/delta-io/delta/issues/2636) issue?

**Comment by robertkossendey** [comment]
@vkorukanti Oh, okay! Sure, I'd like to work on the issue :)
