### ISSUE TITLE
[Kernel][Java to Scala test conversion] Convert and refactor `TestParquetBatchReader`

### ISSUE THREAD

**Issue by vkorukanti** [delta-io/delta#2638]
Convert the tests written in Java to Scala. Scala suites have better test framework and takes few lines to write a test compared to Java.

Java suite: [TestParquetBatchReader](https://github.com/delta-io/delta/blob/master/kernel/kernel-defaults/src/test/java/io/delta/kernel/defaults/internal/parquet/TestParquetBatchReader.java)

Target Scala suite [ParquetFileReaderSuite](https://github.com/delta-io/delta/tree/master/kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/parquet) (create new file).

As part of the conversion, make use of the spark based reader to verify the returned results. The example code is [here](https://github.com/delta-io/delta/blob/master/kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/parquet/ParquetFileWriterSuite.scala#L247).

**Comment by vkorukanti** [comment]
> @vkorukanti Can you recheck? I found file [ParquetBatchReaderSuite](https://github.com/delta-io/delta/blob/master/kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/ParquetBatchReaderSuite.scala) exists already

You are right. It already exists.

**Comment by vkorukanti** [comment]
One more point. When you are moving the Java tests, the current expected result verification code is too large. Instead we can now use `spark` in tests to verify the expected results. [Here](https://github.com/delta-io/delta/blob/master/kernel/kernel-defaults/src/test/scala/io/delta/kernel/defaults/internal/parquet/ParquetFileWriterSuite.scala#L247) is an example of how to do that.

If it helps, move the `verifyUsingSparkReader` into `TestUtils` or create a new file `ParquetSuiteBase.scala` and move there. This can be a separate PR.

**Comment by tlm365** [comment]
@vkorukanti thank you, I think it might be better if we create a new `ParquetSuiteBase` then move all logic handler, i/o utils... unrelated to the test here, and keep only unit tests in `ParquetFileReaderSuite`/`ParquetFileWriterSuite`.
I will create a PR for this task soon.
