### ISSUE TITLE
[Kernel] Remove the reference to `Engine` in `LogReplay`

### ISSUE THREAD

**Issue by vkorukanti** [delta-io/delta#2641]
Currently `LogReplay` [stores a reference](https://github.com/delta-io/delta/blob/master/kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/LogReplay.java#L118) to `Engine` instance. We shouldn't store a reference and always get as part of the call which needs something from the `LogReplay`.

**Comment by rachana-uniyal** [comment]
Hi, @vkorukanti I would like to work on this issue.
