### ISSUE TITLE
[Kernel] Clarify the `ScanBuilder.withFilter` API

### ISSUE THREAD

**Issue by vkorukanti** [delta-io/delta#2703]
Clarify the API documentation of https://github.com/delta-io/delta/blob/master/kernel/kernel-api/src/main/java/io/delta/kernel/ScanBuilder.java#L33.

It should mention about the remaining filter and how the client should get it from `Scan.getRemainingFilter`.

**Comment by krishnanravi** [comment]
Happy to pick this up.
