### ISSUE TITLE
[Feature Request] Improve UniForm Hudi support for Lists/Maps and Schema Evolution

### ISSUE THREAD

**Issue by the-other-tim-brown** [delta-io/delta#2738]
#### Which Delta project/connector is this regarding?

- [ ] Spark
- [ ] Standalone
- [ ] Flink
- [ ] Kernel
- [ ] Other (Unfiorm)

### Overview

The UniForm support for Hudi does not properly translate Map & List fields and the testing does not validate that the schema can be evolved in the source Delta Lake table and properly reflected in the Hudi table.

### Motivation

UniForm users will benefit from a more complete translation between Delta Lake and Hudi.

### Further details

The [XTable](https://github.com/apache/incubator-xtable/blob/main/core/src/main/java/io/onetable/avro/AvroSchemaConverter.java) project has already handled such translations and the approach can be ported over to this repo.

### Willingness to contribute

The Delta Lake Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature?

- [ ] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the Delta Lake community.
- [ ] No. I cannot contribute this feature at this time.

**Comment by anniewang-db** [comment]
List/map support has been added in #3320

**Comment by MrPowers** [comment]
Great, looks like this one has been completed!
