### ISSUE TITLE
[BUG] Generate does not update manifest if delete all data from unpartitioned table

### ISSUE THREAD

**Issue by lswyyy** [delta-io/delta#275]
**Describe**
As in the title, on Delta Lake 0.5.0 and Spark 2.4.4:

1.  write data into delta table
2. deltaTable.generate("symlink_format_manifest")
3. execute deltaTable.delete()
4. deltaTable.generate("symlink_format_manifest")

manifest does not update in step4

**Comment by tdas** [comment]
Are you sure you are using Delta Lake 0.4.0? The manifest generation is in Delta Lake 0.5.0.

**Comment by lswyyy** [comment]
> Are you sure you are using Delta Lake 0.4.0? The manifest generation is in Delta Lake 0.5.0.

Sorry, it is 0.5.0，I updated the description
