### ISSUE TITLE
Replicate MySQL Tables to Delta Tables

### ISSUE THREAD

**Issue by liangrui1988** [delta-io/delta#278]
delta lake There is no such example implementation. thank you
Read mysql data in real time

spark.readStream
  .format("preview-cdcFromMysql")
  .option("host", <host>)
  .option("username", <username>)
  .option("password", dbutils.secrets.get(<scope>, <mysql_password>)
  .option("database",  <database>)
  .option("table", <table>)
  .load()
  .writeStream
  .format("preview-cdcToDelta")
  .option("checkpointLocation", <checkpoint location>)
  .start(<path to Delta table target>)

**Comment by marmbrus** [comment]
This is a not really a API of Delta, but rather just a connector built by a vendor that glues together Debezium and the MERGE INTO command (which is available in OSS Delta Lake).
