### ISSUE TITLE
Slack Register link complains: "This invite link is no longer active."

### ISSUE THREAD

**Issue by dongxuwang** [delta-io/delta#283]
After redirecting to the "register here" link, slack complains "This invite link is no longer active." so long as not logging in slack.

**Comment by mukulmurthy** [comment]
Thanks for reporting @dongxuwang. https://github.com/delta-io/delta/pull/273 fixes it; we are merging this PR along with some other ones very soon.

**Comment by mukulmurthy** [comment]
Link is fixed. Thanks!
