### ISSUE TITLE
When does the kernel support the write operation.

### ISSUE THREAD

**Issue by horizonzy** [delta-io/delta#2869]
I read the kernel read process code, it's convinient for the java user, and it's so great. But the kernel doesn't support write operation, I want to introduce kernel library to take place of the standalone library,  but the writer operation is the blocker. 

Does the community is working on write development？And when can I use the write feature？Thanks!

**Comment by scottsand-db** [comment]
Hey @horizonzy - kernel write support is coming in Delta Lake 3.2!

**Comment by horizonzy** [comment]
> Hey @horizonzy - kernel write support is coming in Delta Lake 3.2!

Great work!
