### ISSUE TITLE
Why `org.apache.spark.sql.delta.DeleteJavaSuite` is in package `test.com.databricks.sql.transaction.tahoe`?

### ISSUE THREAD

**Issue by xianyinxin** [delta-io/delta#290]
See part of the code,

```
package test.com.databricks.sql.transaction.tahoe;

import xxx

public class DeleteJavaSuite {

xxx
```

but it's under folder org/apache/spark/sql/delta.

The same with `MergeIntoJavaSuite` and `UpdateJavaSuite`.

**Comment by mukulmurthy** [comment]
Thanks for reporting, that's definitely not the right package for this test. We'll fix it.
