### ISSUE TITLE
Is Delta supports update mapType structure too ?

### ISSUE THREAD

**Issue by Alberne** [delta-io/delta#293]
i have delta table , parquet format, the df.printSchema() detail as below

root
 |-- part: string (nullable = true)
 |-- day: date (nullable = true)
 |-- object_type: string (nullable = true)
 |-- object_id: string (nullable = true)
 |-- sys: map (nullable = true)
 |    |-- key: string
 |    |-- value: string (valueContainsNull = true)

how can i update sys.one_of_key field value?

**Comment by pranavanand** [comment]
Do you mean update the type of the key or the value of one of the keys? 
For the former: that is an unsupported operation.
For the latter you can do something like `$"sys".getField("somefield"))`
