### ISSUE TITLE
[Storage System] Support for Google Cloud

### ISSUE THREAD

**Issue by mukulmurthy** [delta-io/delta#294]
This is the official issue for tracking the work for supporting Delta Lake over Google Cloud Storage.

Here are the requirements for the underlying storage system in order to maintain ACID guarantees:
https://github.com/delta-io/delta#requirements-for-underlying-storage-systems

HDFS over Google Cloud will work out of the box. We haven't yet investigated whether Google Cloud Storage satisfies these guarantees. If they don't, we will need a custom LogStore implementation similar to what we did for AWS and Azure (see below). 

Related issues:
https://github.com/delta-io/delta/issues/39
https://github.com/delta-io/delta/issues/40
https://github.com/delta-io/delta/issues/134

**Comment by brkyvz** [comment]
This blog post seems to suggest it works out of the box:
https://cloudblog-withgoogle-com.cdn.ampproject.org/c/s/cloudblog.withgoogle.com/products/data-analytics/getting-started-with-new-table-formats-on-dataproc/amp/

**Comment by gkatzioura** [comment]
Hi all!

I am interested on using Delta Lake on Google Cloud so I did start to write an implementation for this one. It seems that unlike on S3 as mentioned on #39
Google Cloud Storage object listing is consistent `Object listing is also strongly consistent` as mentioned [here](https://cloud.google.com/storage/docs/consistency).
Also provides a `put if not present` atomic mechanism as mentioned [here](https://cloud.google.com/storage/docs/holding-objects).
As far as I can see the last one was recently announced.
Is it ok if my implementation imports the Google Cloud Storage Java library and interacts directly with the Google Cloud buckets?

**Comment by sap1ens** [comment]
Regarding atomic `put if not present` operation, object holds can be used as mentioned above, but [preconditions](https://cloud.google.com/storage/docs/generations-preconditions#_JSONAPI) seem to be a simpler option:

> If you use 0 instead of a generation number in ifGenerationMatch, the request only succeeds if there is no live object in your bucket matching the object named in the request.

**Comment by fr-ashikaumagiliya** [comment]
this is GCS supported now ? I found this article : https://cloud.google.com/blog/products/data-analytics/getting-started-with-new-table-formats-on-dataproc

**Comment by tdas** [comment]
Looks like they support it but it's unclear whether they have customized the LogStore implementation in their platform to get the correct semantics for writing delta log files. Without that, concurrent workloads will not provide ACID guarantees.

**Comment by fr-ashikaumagiliya** [comment]
> Some object stores on other cloud providers do not provide a consistent listing, which could lead to data loss. So, in some cases Delta Lake only allows one single Spark session to write to the transaction log on the object store at a time. For the same reason, Delta Lake also disallows multiple writers, further limiting the concurrency and throughput of Delta Lake.
> 
> **Cloud Storage allows multiple writers to the transaction log and guarantees consistency , allowing you to use Delta Lake to its full potential.** 

looks like they have implemented a custom LogStore ?

**Comment by tdas** [comment]
Even though they have not explicitly say, it indicates that they have done
it. It would be good to get a confirmation from their support staff, etc.
If you (or anyone) are in contact with GCS or DataProc support, then please
ask them to confirm this.

**Comment by jaceklaskowski** [comment]
What a timing! They've just expressed interest in this "closed" development in [spark-bigquery-connector](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/issues/247) so there seem to be a mutual opportunity for both companies for a small exchange of goods / experience for the benefit of Apache Spark and Delta Lake communities 😎

**Comment by fr-ashikaumagiliya** [comment]
I received a comment from Google Support :

> The internal ticket was routed to the engineer working on Delta Lake support in Dataproc. 
> 
> GCS provides atomic operation for writing and listing [1], so it may not require custom LogStore. But, I'll double-check the behavior with the product team.

**Comment by fr-ashikaumagiliya** [comment]
> A specialist for Delta Lake support in Dataproc confirmed that GCS Connector 2.1.x works with Delta Lake concurrency. Dataproc clusters install GCS connector by default [1], so you don’t need to install additional dependency. You can use HDFSLogStore.
And this

**Comment by ranu010101** [comment]
I have raised a [PR][1] to address this.

Kindly review. Please suggest if I'm missing something.

[1]: https://github.com/delta-io/delta/pull/560

**Comment by zsxwing** [comment]
We have added the support in #560
