### ISSUE TITLE
ipad support

### ISSUE THREAD

**Issue by y1rn** [delta-io/delta#2971]
#### Which Delta project/connector is this regarding?

- [ ] Spark
- [ ] Standalone
- [ ] Flink
- [ ] Kernel
- [ ] Other (fill in here)

### Willingness to contribute

The Delta Lake Community encourages new feature contributions. Would you or another member of your organization be willing to contribute an implementation of this feature?

- [ ] Yes. I can contribute this feature independently.
- [ ] Yes. I would be willing to contribute this feature with guidance from the Delta Lake community.
- [* ] No. I cannot contribute this feature at this time.

**Comment by tdas** [comment]
What does this mean?
