### ISSUE TITLE
Is there any plan for compaction?

### ISSUE THREAD

**Issue by allwefantasy** [delta-io/delta#30]
Compaction is very important when working with stream jobs.  So the delta community have any plan for compaction?  The core team will implement it or just wait third-party to contribute?

**Comment by mukulmurthy** [comment]
Sorry for the delayed response on this. We have https://github.com/delta-io/delta/issues/49 tracking the OPTIMIZE command to compact data, though this work is not currently scheduled. Feel free to 👍 that issue!
