### ISSUE TITLE
Merge adding empty parquet files

### ISSUE THREAD

**Issue by XRayA4T** [delta-io/delta#304]
I was testing the merge functionality with the following files:
[people.zip](https://github.com/delta-io/delta/files/4107318/people.zip)

Using Spark 2.4.4 and io.delta:delta-core_2.11:0.5.0

In spark-shell with files in HDFS:
```
import io.delta.tables._
val df = spark.read.option("header", "true").csv("/path/to/people.base.csv")
df.write.format("delta").save("/path/to/people")
val peopledeltatbl = DeltaTable.forPath("/path/to/people")
val updatesDF =  spark.read.option("header", "true").csv("/path/to/people.cdc.1.csv")
peopledeltatbl.as("people").merge(updatesDF.as("updates"),"people.id = updates.id").whenMatched("updates.action = 'delete'").delete.whenMatched("updates.action = 'update'").updateExpr(Map("name" -> "updates.name","email" -> "updates.email")).whenNotMatched("updates.action = 'insert'").insertExpr(Map("id" -> "updates.id","name" -> "updates.name","email" -> "updates.email")).execute()
val updatesDF =  spark.read.option("header", "true").csv("/user/abrb554/people.cdc.2.csv")
peopledeltatbl.as("people").merge(updatesDF.as("updates"),"people.id = updates.id").whenMatched("updates.action = 'delete'").delete.whenMatched("updates.action = 'update'").updateExpr(Map("name" -> "updates.name","email" -> "updates.email")).whenNotMatched("updates.action = 'insert'").insertExpr(Map("id" -> "updates.id","name" -> "updates.name","email" -> "updates.email")).execute()
val updatesDF =  spark.read.option("header", "true").csv("/user/abrb554/people.cdc.3.csv")
peopledeltatbl.as("people").merge(updatesDF.as("updates"),"people.id = updates.id").whenMatched("updates.action = 'delete'").delete.whenMatched("updates.action = 'update'").updateExpr(Map("name" -> "updates.name","email" -> "updates.email")).whenNotMatched("updates.action = 'insert'").insertExpr(Map("id" -> "updates.id","name" -> "updates.name","email" -> "updates.email")).execute()
```
This is the Delta Lake produced: 
[people.deltalake.zip](https://github.com/delta-io/delta/files/4107322/people.deltalake.zip)

### Expected behaviour:
After merge with people.cdc.1.csv:
- 1 parquet file added for the inserted record
- 00000000000000000001.json to contain the added file

After merge with people.cdc.2.csv:
- 1 parquet file added for the updated record to replace the changed file
- 00000000000000000002.json to contain the added file and remove of the changed

After merge with people.cdc.3.csv:
- 1 parquet file added for the deleted record to replace the changed file
- 00000000000000000003.json to contain the added file and remove of the changed

### Actual behaviour:
After merge with people.cdc.1.csv:
- In 00000000000000000001.json there are 2 parquet files added
- 1 parquet file added for the inserted record
- 1 parquet file added that contains 0 rows

After merge with people.cdc.2.csv:
- In 00000000000000000002.json there are 4 parquet files added and 1 removed
- parquet file added for each unchanged record (I think this relates to [Issue 239](https://github.com/delta-io/delta/issues/239))
- 1 parquet file added that contains 0 rows

After merge with people.cdc.3.csv:
- In 00000000000000000003.json there are 1 parquet files added and 1 removed
- The parquet file removed matches the file that contains the remove row
- 1 parquet file added that contains 0 rows

**Comment by tdas** [comment]
Generating empty files is indeed possible when there are deletes. The merge write is done using an outer join that joins the source data with the target table for matches and non-matches. After this join, the rows are processed with the update/delete/insert actions based on whether the rows matched or not. In some of the tasks that compute this join, its possible that all the rows that the task happened to have matched the delete condition and therefore got deleted (that is not written to the output file). Hence the file generated by such a task may have no rows at all.

It is semantically correct for the Delta table to commit and track empty files. But yes, it is not ideal. In production, with large files having millions of rows, this is very unlikely to happen.

Just so that we are sure, can you confirm that the table is fully readable even with the 0 byte files in the snapshot?

**Comment by XRayA4T** [comment]
The delta table readable and correct even with the empty files. The full set of files produced is attached to the original post.

**Comment by tdas** [comment]
@XRayA4T thank you for confirming that. This is not a bug but at expected behavior. This is unlikely to happen when there is lots of data.

**Comment by nyehia-onica** [comment]
Hi @tdas, I have the same issue but we are using append mode to add history records to the delta table and no deletion at all. what could be the cause of this? and is there anything to avoid this? can this affect our performance? Thanks
