### ISSUE TITLE
[BUG][Kernel] Delta kernel read checkpoint parquet file failed with exception "list not found in optional group readerFeatures (LIST)"

### ISSUE THREAD

**Issue by Youngwb** [delta-io/delta#3082]
#### Which Delta project/connector is this regarding?

- [ ] Spark
- [ ] Standalone
- [ ] Flink
- [x] Kernel
- [ ] Other (fill in here)

### Describe the problem
When use delta kernel to read delta lake table encountered such an error
```
list not found in optional group readerFeatures (LIST) {
  repeated group bag {
    optional binary array (STRING);
  }
}
```

and the schema of parquet file is 
<img width="724" alt="image" src="https://github.com/delta-io/delta/assets/9495145/08341074-03bf-4bcc-a2e6-b248d608261b">

And I think delta kernel currently does not supports reading this legacy array type.

### Environment information

* Delta Lake version:
* Spark version:
* Scala version:

### Willingness to contribute

The Delta Lake Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the Delta Lake code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the Delta Lake community.
- [ ] No. I cannot contribute a bug fix at this time.

**Comment by vkorukanti** [comment]
@Youngwb Thanks for reporting. Currently, the default Parquet reader is not handling the legacy list physical format. Will post a PR shortly.
