### ISSUE TITLE
Why does executeVacuum() return empty DataFrame?

### ISSUE THREAD

**Issue by AFFogarty** [delta-io/delta#309]
Is there a design reason why `executeVacuum()` [returns an empty `DataFrame`?](https://github.com/delta-io/delta/blob/master/src/main/scala/io/delta/tables/execution/DeltaTableOperations.scala#L110)  This seems even less useful than just returning `Unit`.

Could we modify it to return some useful stats?

**Comment by marmbrus** [comment]
I believe the idea here was to have a stable public signature when we did add additional stats.

+1 to doing that.

cc @rahulsmahadev

**Comment by rahulsmahadev** [comment]
Agreed,

We shouls return metrics containing number of files deleted and size stats
of those files instead of the empty dataframe.

Regards,
Rahul Mahadev

**Comment by zsxwing** [comment]
Closing this. Vacuum now returns the files to be deleted in the dry run mode.
