### ISSUE TITLE
Operation metrics in Delta history

### ISSUE THREAD

**Issue by tdas** [delta-io/delta#312]
The community has often requested for programmatic access to the metrics of various operations (e.g., # number of rows updete/deleted/inserted in Merge) after they have completed. These metrics are visible in the SQL tab of the Spark UI, but there is no easy way to programmatically access to those values. 

A simple idea is to record the operation metrics in history. We already record operation parameters in the history (e.g., delete query condition) in json format, so it is easy to extend it to store the operation metrics as well (in json).

**Comment by ekoifman** [comment]
:thumbsup:

**Comment by rahulsmahadev** [comment]
Operation metrics for writes and merge - 54643efc07dfaa9028d228dcad6502d59e4bdb3a
Update and delete - 9dd54242f4a6c64385e3841b133e21f6cf2f129d
streaming update - adc03b860fc7ac11fe652e961ed5c570b606427e

**Comment by tdas** [comment]
Marking this as done. To be released with 0.6.0
