### ISSUE TITLE
Support for Redshift Spectrum format manifest

### ISSUE THREAD

**Issue by tdas** [delta-io/delta#313]
We have already added manifests formatted according to the `SymlinkTextInputFormat` for Presto/Athena support (#250). Redshift Spectrum also recognizes manifest files but using a different format. This issue is to track the work to add support for Redshift Spectrum formatted manifest.

**Comment by pandeesh** [comment]
Is it JSON formatted manifest for Redshift spectrum?

**Comment by tdas** [comment]
Yes. Actually this has been successfully done by GoIbibo folks. See there blog - https://tech.goibibo.com/delta-spectrum-connector-83b3c01e3294

**Comment by yogyang** [comment]
Great to see this issue, we've done the same thing by combining the `GoIbibo folks things` and the open-source [GenerateSymlinkManifest](https://github.com/delta-io/delta/blob/master/src/main/scala/org/apache/spark/sql/delta/hooks/GenerateSymlinkManifest.scala).
Actually we just need to change the schema we wrote the s3 to generate the manifest JSON file, little effort. It would be much faster than the join solution provided by the databricks doc.

So my questions are
1. beyond generating the JSON manifest for Redshift spectrum, will it support to add the CatalogPartition in Glue for each new-added partition
2. Is there a plan to expose the [PostCommitHook](https://github.com/delta-io/delta/blob/master/src/main/scala/org/apache/spark/sql/delta/hooks/PostCommitHook.scala), to enable users to register their own post hook for each transaction?

**Comment by rockpunk** [comment]
+1. As my coworker Yujia said, we implemented a pretty simple batch method using a modified version of GenerateSymlinkManifest and AWS Glue service calls to create / update the Glue partitions, but it would be nice if we could add it as a PostCommitHook for streaming jobs to update in a near time fashion automatically.  We can help with PR efforts if you'd like.

**Comment by tdas** [comment]
@rockpunk @yogyang thank you for your interest, and validating that this is a useful feature! I think, for now, we are going to add only the manifest file generation in the delta lake project, not the updating the Glue part since it is custom aws code and its odd add aws dependency to the core project. 

But I do like the general idea of allowing users to write their custom post-commit hooks, with which custom code can be written to update the glue metastore. The main challenge to make PostCommitHooks a stable API. Right it exposes A LOT of the internal classes which were never meant to be public APIs. So this is something that needs a lot more work. In the meantime, another approach for building such post-operation-updates is as follows.

1. Run the operation.
2. After the operation, read the table history to find the commit number the operation got (say, X).
3. Read the json-formatted committed transaction log file, that is, 0000000X.json to find all the operations. This json format is defined in our [protocol spec](https://github.com/delta-io/delta/blob/master/PROTOCOL.md)  and is therefore stable, future compatible. Reading the file you can find out the touched partitions (from the field "partitionValues"), and accordingly do the necessary updates.

In the absensce of post commit hook, this is probably the most stable approach to hook in custom logic to update partitions in glue.

**Comment by tdas** [comment]
This is not needed any more as Redshift has added support for our existing manifest format. Yay!

https://aws.amazon.com/about-aws/whats-new/2020/09/amazon-redshift-spectrum-adds-support-for-querying-open-source-apache-hudi-and-delta-lake/
