### ISSUE TITLE
Support custom commit metadata in write / merge

### ISSUE THREAD

**Issue by changpingc** [delta-io/delta#321]
This is a feature request. I wish I can record additional metadata as part of DataFrameWriter / MERGE transaction. 

For example, I have a spark job that runs a deterministic transformation periodically on some source delta table and write to output delta table. I want to track data lineage (source table version) and runtime parameters in each commit, such that I can understand how new versions of data propagate through a pipeline and replay the exact transformation for debugging. 

Maybe the API is like:
```
df.write.format("delta").option("metadata", r'{"source_table_version": "...", "runtime_params": ...}').save(...)
```

Maybe `metadata` gets put into `commitInfo` and we expose it in `describe history`?

**Comment by tdas** [comment]
This is definitely a good feature request. This is should be pretty easy to implement. I think the tricky part is figuring out the right APIs for specifying the metadata for non-DataFrameWriter operations like merge/update/delete. However, we can definitely start with DataFrameWriter options. It would awesome if you can build this feature, just make a PR!

**Comment by schuermannator** [comment]
This is implemented in b7eee5b2fbe6c668329ca55025e0e8edb4529104. Usage: 
```scala
df.write.format("delta")
  .option("userMetadata", "...")
  .save(...)
```

**Comment by schuermannator** [comment]
@carldonsbach For all cases outside the Dataframe API, you can use the `SparkSession` config to set/unset `userMetadata`. For example:

```scala
spark.conf.set("spark.databricks.delta.commitInfo.userMetadata", "test")

// all operations now have "test" as userMetadata
table.merge(...).execute()

table.history().select("userMetadata").show()
```

**Comment by GeekSheikh** [comment]
This still lacks full scenario coverage though. Often times a single spark session is performing multiple writes simultaneously and when this is the case, manipulating the spark session still doesn't provide the ability to pass metadata to the table. Could we find a way to ensure metadata writes to tables at the writer level even when using the following syntax?

```
DeltaTable.forPath(target.tableLocation).alias("target")
  .merge(updatesDF, mergeCondition)
  .whenMatched
  .updateAll()
  .whenNotMatched
  .insertAll()
  .execute()
```

Thank you

**Comment by zsxwing** [comment]
@GeekSheikh could you create a new issue? This is a good feature request.
