### ISSUE TITLE
[BUG][Spark]  Logs are not compacted

### ISSUE THREAD

**Issue by Minashraf** [delta-io/delta#3245]
#### Which Delta project/connector is this regarding?

- [X] Spark
- [ ] Standalone
- [ ] Flink
- [ ] Kernel
- [ ] Other (fill in here)

### Describe the problem
Logs don't seem to be deleted after retention or after checkpoint
#### Steps to reproduce
I am using zeppelin notebook and loading my data from HDFS do an update I ran this command many times and I have a lot of checkpoints on hdfs but none of the logs are deleted
![image](https://github.com/delta-io/delta/assets/46136768/87d7b2a0-a17a-4559-ad88-2a128b1051d4)
Here is my table description
![image](https://github.com/delta-io/delta/assets/46136768/c1b9e1a7-ff5a-4cc7-bb00-f0387f852183)

#### Observed results

None of the logs are deleted +100 files
#### Expected results

older logs to be deleted especially the ones before the checkpoint
### Environment information

* Delta Lake version: delta-core_2.12-2.0.2.jar
* Spark version: 3.2.1
* Scala version:

### Willingness to contribute

The Delta Lake Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the Delta Lake code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [X] Yes. I would be willing to contribute a fix for this bug with guidance from the Delta Lake community.
- [ ] No. I cannot contribute a bug fix at this time.

**Comment by Minashraf** [comment]
Found the solution minimum retention is 1 day and can't be converted to hours or minutes

**Comment by felipepessoto** [comment]
For reference:

https://github.com/delta-io/delta/blob/97439835a4a667ac2ad86ec6054f0e85e8214760/spark/src/main/scala/org/apache/spark/sql/delta/DeltaConfig.scala#L356C1-L362C28

> The shortest duration we have to keep delta files around before deleting them. We can only delete delta files that are before a compaction. **We may keep files beyond this duration until the next calendar day.**
