### ISSUE TITLE
[Feature Request] [Docs] Show a table of Delta Lake Release Version x Supported Table Features

### ISSUE THREAD

**Issue by scottsand-db** [delta-io/delta#3284]
#### Which Delta project/connector is this regarding?

- [ ] Spark
- [ ] Standalone
- [ ] Flink
- [ ] Kernel
- [X] Other (Docs)

### Overview

Show a table of Delta Lake Release Version x Supported Table Features

### Motivation

Make it easier to tell which table feature is in which delta lake version

**Comment by allisonport-db** [comment]
Closing this since it's available at https://docs.delta.io/latest/versioning.html
