### ISSUE TITLE
FileContext.rename does not always throw FileAlreadyExistsException

### ISSUE THREAD

**Issue by windpiger** [delta-io/delta#332]
FileSystem.rename(HDFSLogStore) can also throw IOException when the destination File already exists:
https://github.com/apache/hadoop/blob/trunk/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FileSystem.java#L1594 

So we can not handle this when in OptimisticTransaction.doCommit to checkAndRetry
https://github.com/delta-io/delta/blob/778cc6923bb3985122062f7ce4af4cd58a15f849/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala#L397

We should use the same logic in HadoopFileSystemLogStore.writeWithRename
https://github.com/delta-io/delta/blob/778cc6923bb3985122062f7ce4af4cd58a15f849/src/main/scala/org/apache/spark/sql/delta/storage/HadoopFileSystemLogStore.scala#L103-L107

If I missing something, please correct me, thanks!

**Comment by tdas** [comment]
HDFSLogStore uses the new FileContext implementation for HDFS, not the FileSystem implementation.

**Comment by windpiger** [comment]
> HDFSLogStore uses the new FileContext implementation for HDFS, not the FileSystem implementation.

Yes, but in FileContext ,it also call FileSystem.rename by DelegateToFileSystem.renameInternal
https://github.com/apache/hadoop/blob/trunk/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/DelegateToFileSystem.java#L206

**Comment by tdas** [comment]
Maybe I am misunderstanding something. As far as I understand, 

1. the default AbstractFileSystem implementation (FileContext delegates to AbstractFileSystem) used for `hdfs` scheme is `org.apache.hadoop.fs.Hdfs` as [shown](https://hadoop.apache.org/docs/r2.9.1/hadoop-project-dist/hadoop-common/core-default.xml) in the default conf file for conf `fs.AbstractFileSystem.hdfs.impl`. 

2. HDFSLogStore [calls](https://github.com/delta-io/delta/blob/master/src/main/scala/org/apache/spark/sql/delta/storage/HDFSLogStore.scala#L101) `FileContext.rename(... Options.Rename.OVERWRITE)` which [calls](https://github.com/apache/hadoop/blob/branch-2.9/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FileContext.java#L975) `AbstractFileSystem.rename(...)`. 

3. `AbstractFileSystem.rename(...)` always [delegates](https://github.com/apache/hadoop/blob/branch-2.9/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/AbstractFileSystem.java#L699) to `AbstractFileSystem.renameInternal(...)` which is overridden by `org.apache.hadoop.fs.Hdfs` to [call](https://github.com/apache/hadoop/blob/branch-2.9/hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/fs/Hdfs.java#L344) `DFSClient.rename()`.

4. `DFSClient.rename(...)` can only [throw](https://github.com/apache/hadoop/blob/branch-2.9/hadoop-hdfs-project/hadoop-hdfs-client/src/main/java/org/apache/hadoop/hdfs/DFSClient.java#L1540) only a few types of exceptions of which FileAlreadyExists is only type of exception that is concretely worth retrying.

Am I missing something in this tracing of the call?

**Comment by pranavanand** [comment]
@windpiger do you have any other concerns about this?

**Comment by windpiger** [comment]
> @windpiger do you have any other concerns about this?
no ,thanks very much!!
