### ISSUE TITLE
General question: removing optimized/deleted data files without VACUUM

### ISSUE THREAD

**Issue by keenanwells-tatari** [delta-io/delta#3389]
I have a general question regarding whether it's advisable or not to remove files that have been removed via OPTIMIZE or DELETE without running VACUUM. 

We are running pyspark jobs on databricks and have delta external tables. Because the tables are external, data is not automatically removed after OPTIMIZE or DELETE queries are run. 

We are writing automation that would detect where there are many left over files no longer in use in our tables. The choice is between running a full VACUUM or doing targeted deletes of files that are identified as removed in the `_delta_log`. 

Would anyone be able to advise whether we might encounter issues doing the data deletion without VACUUM? Thank you

**Comment by keenanwells-tatari** [comment]
Some to add to this question

upon testing and examining delta history in `_delta_log` it seems like it might not present any issue to remove files from s3 that have been optimized or deleted via delta transactions, so long as we are careful not to remove data that should still be retained according to history retention. 

Running a VACUUM after deleting files in s3 that were removed via optimize/delete does not raise an error, even if we enable `spark.databricks.delta.vacuum.logging.enabled` and the delta log is updated to include vacuum information, delta does not care that the files are no longer present in the file system when it goes to remove them. 

This would only present an issue if we were going to time travel back to a version where files were still present in S3, because delta would try to refer to data files that are no longer present. 

I think so long as the process removing data were to respect the retention period set on the tables set via `delta.logRetentionDuration` and `delta.deletedFileRetentionDuration` then there would be no issue deleting files that show as removed in `_delta_log`.  

Does this sound correct?

**Comment by MrPowers** [comment]
Thanks for raising this question.

I think it's best to use VACUUM rather than manually deleting files to make sure that you don't accidentally corrupt your table.  

Here's a blog post on the topic so you can learn more: https://delta.io/blog/remove-files-delta-lake-vacuum-command/

In general it just seems better to remove the files with VACUUM rather than manually deleting them.

**Comment by keenanwells-tatari** [comment]
Thanks for the response on this @MrPowers

**Comment by MrPowers** [comment]
Of course!  Closing this for now, but feel free to reach back out at any time!
