### ISSUE TITLE
[Databricks Delta Lake] dataframe losing rows when using window function

### ISSUE THREAD

**Issue by Chr96er** [delta-io/delta#340]
I'm questioning my sanity right now, it looks to me like a very apparent bug. I have the following code

```
//returns 200648
(delta_table.count) - (delta_table.withColumn("MaxUpdateDate", max('UpdateDate).over(Window.partitionBy('id))).count)

delta_table.write.saveAsTable("foo")

// returns 0
(spark.read.table("foo").count) - (spark.read.table("foo").withColumn("MaxUpdateDate", max('UpdateDate).over(Window.partitionBy('id))).count)
```

The only difference I can see between the two tables is that the first one is a delta table that is continuously updated and partitioned by "UpdateDate". I ran vacuum before running the code above with the same result.

As you can see, I cannot explain the behvaiour in my delta table when using the window function to add a column. Speaking of explain, here is the execution plan for the window function:

```
InMemoryTableScan [id#23370, UpdateDate#23378, MaxUpdateDate#25199]
   +- InMemoryRelation [id#23370, UpdateDate#23378, MaxUpdateDate#25199], StorageLevel(disk, memory, deserialized, 1 replicas)
         +- Window [id#243, UpdateDate#251, max(UpdateDate#251) windowspecdefinition(id#243, specifiedwindowframe(RowFrame, unboundedpreceding$(), unboundedfollowing$())) AS MaxUpdateDate#10529], [id#243]
            +- Sort [id#243 ASC NULLS FIRST], false, 0
               +- Exchange hashpartitioning(id#243, 200), [id=#8639]
                  +- *(1) FileScan parquet [id#243,UpdateDate#251] Batched: true, DataFilters: [], Format: Parquet, Location: PreparedDeltaFileIndex[dbfs.....]
```

I do not understand how this can happen at all. Adding columns should in my understanding never ever decrease the amount of rows.

**Comment by tdas** [comment]
do you have the table stuff cached? if so, remove the caching and try it.

**Comment by Chr96er** [comment]
Indeed, I had delta cache enabled. I ran the same query again today and now it returned zero, as expected. I'm on databricks runtime 6.1 though which I thought automatically detected changes according to https://docs.databricks.com/delta/optimizations/delta-cache.html#delta-cache-consistency

Also, I'm certain that the partitions in the delta table have never been overwritten with different data but only ever with the same existing data, so I don't get the inconsistency. Could it be that the cached table doesn't detect when new partitions are being added?

For now I'll have to make do with disabling the cache until I understand why this is happening and can be avoided.

**Comment by tdas** [comment]
If you have cached the table, the expectation is that you want to use the cache for read queries and not use the latest data in the files. This is true for parquet files, as well as for Delta. That leads to such corner cases, which can again happen in both parquet and delta. So it is generally caching the Delta table is not recommended.

**Comment by tdas** [comment]
@Chr96er i am closing this ticket. if you have any more questions, feel free to reopen it.
