### ISSUE TITLE
Add option to repartition by partition column in merge to reduce the number of files 

### ISSUE THREAD

**Issue by tdas** [delta-io/delta#349]
Currently, merge can produce a very large number of files when the table is partitioned. Reducing # shuffle partitions can reduce the # files but also reduce the parallelism of the operation, making it slower.
 
Reports
- https://delta-users.slack.com/archives/CJ70UCSHM/p1582931151094700
- https://github.com/delta-io/delta/issues/345

As discussed in the above slack thread, a solution is the add an additional conf that optionally repartitions the data to be written by the partitioning column.

**Comment by tdas** [comment]
Done in this commit - https://github.com/delta-io/delta/commit/6d9420539e9b00f8df8d5bc80ce6aa7a5a9f3b7d

**Comment by Evgeny-ubrr** [comment]
Awesome feature! But how to use it?
Example needed where in merge statment repartition option can be used.
