### ISSUE TITLE
Delta log missing records for the files which are wrote into S3 bucket

### ISSUE THREAD

**Issue by Mxdcq** [delta-io/delta#355]
Hi, we are using delta and PySpark to manage our schemas on AWS. 

We faced a situation where the file has been persisted on the S3 bucket, but the updating process did not record in the delta log. As a consequence, when we want to load the data, it will returns an empty data frame. It seems that the load process will first checking the delta log, if there is no matching record, it will skip the load process even the file is actually existing. 

So, I guess there might be some inconsistent between the file writing process and the delta log refreshing process. 

Please help me to find out the reason behind this.

**Comment by tdas** [comment]
This is quite possible due to S3's list inconsistency. 
https://forums.aws.amazon.com/thread.jspa?messageID=687028&#687028

So it's possible that the one cluster writes outs the 9th operation as table/_delta_log/9.json but another cluster does not see that new file 9.json when listing the _delta_log directory. So

**Comment by SreeramGarlapati** [comment]
@tdas - given that file listing problem is fairly common with object stores - is there a plan to design for file listing problem? for example one solution for this could be - to store - where the latest table version information is stored & let any reader - to resolve the latest table version from this file:
```
/s3_path_to_delta_table
                 /actual_table_data
                       ......
                 /_delta_log
                          /latest_table_version.txt
                          /0000000000NNNNN.json
                          ........
```

& the latest_table_version.txt can contain the version to read
```
00000000000296.json
```

**Comment by SreeramGarlapati** [comment]
@tdas - AWS S3 announced `strong read after write consistency` for `LIST` operations. So, the workaround that I mentioned above for "S3 file listing problem" - is no longer required! https://aws.amazon.com/s3/consistency/

**Comment by nkarpov** [comment]
@SreeramGarlapati just double checking with you, I think we're OK to close this one?
