### ISSUE TITLE
S3: simultaneous streaming insert and compaction 

### ISSUE THREAD

**Issue by mixam24** [delta-io/delta#356]
I would like to know if it is safe to compact old partitions in parallel to streaming insert process in DeltaLake + S3 storage configuration.

I want to make sure that there will be no data loss or duplicates due to race conditions.      

It is not very clear for me from [Delta Storage](https://docs.delta.io/latest/delta-storage.html#amazon-s3) which writes must originate from a single Spark driver (writes of the data files or writes of the delta log entries).

**Comment by tdas** [comment]
1. It is safe to do streaming insert and compaction in parallel. 
2. For S3, using the S3SingleDriverLogStore, ALL "write operations" have to be done through the same driver. Data writes always go through executors, and log entry writes always go through the driver. What really matters for the ACID guarantees is all the log entry writes be made from the same driver, which basically means that all write operations from the same driver.

**Comment by mixam24** [comment]
@tdas thanks for the clarification. Perhaps, it's a good idea to mention at [Concurrency Control](https://docs.delta.io/latest/concurrency-control.html) page something about that because this statement is not 100% correct (at least in S3 case):

> Delta Lake provides ACID transaction guarantees between reads and writes. This means that:
> Multiple writers, across multiple clusters, can simultaneously modify a table partition and see a consistent snapshot view of the table and there will be a serial order for these writes.
