### ISSUE TITLE
No partition directory

### ISSUE THREAD

**Issue by zhangxinjian123** [delta-io/delta#363]
I use the structured streaming architecture. Datafame specifies the partition to write to HDFS. Why does HDFS have no partition directory
tableNameToEventRDD.writeStream
      .format("delta")
      .foreachBatch {
        (batchDF: Dataset[(String, Event)], batchId: Long) =>
          batchDF.persist()

           batchDF    .write
                  .format("delta")
                  .mode("append")
                  .option("mergeSchema", "true")
                  .partitionBy("delta_processing_date")
                  .save(tablePath)

}

**Comment by btbbass** [comment]
Do you have a spark version >= 2.4.2  ?

I had some issue, changing the position of the partitionBy;
Just try with: 

`
batchDF    
              .write
              .format("delta")
              .partitionBy("delta_processing_date")
              .mode("append")
              .option("mergeSchema", "true")
              .save(tablePath)
`

**Comment by zhangxinjian123** [comment]
spark version=2.4.0
changing the position of the partitionBy,But still not
