### ISSUE TITLE
How delta do Garbage collection?

### ISSUE THREAD

**Issue by cfmcgrady** [delta-io/delta#37]
Hi, delta team.

We can run a new job to merge small files in hdfs which generate by our Structured Streaming application. But how can I do Garbage collection with delta?

---
I find `VACUUM` command in databricks delta document.
but I can't find any code about Garbage collection in open source version.

**Comment by tdas** [comment]
Unfortunately, for 0.1.0, there are no OSS APIs for doing it. We are working on making the Vacuum APIs in the open source.

**Comment by tdas** [comment]
I have created a specific official issue for tracking our work to provide scala APIs for Vacuum - #48 . Please vote and discuss this on that issue. I am closing this issue for now.
