### ISSUE TITLE
How to merge too many small files

### ISSUE THREAD

**Issue by zhangxinjian123** [delta-io/delta#379]
If the setting partition is set, the write speed will be very slow, if the partition is not set. A lot of small files will be generated. How to solve this problem

**Comment by tdas** [comment]
what table operation are you running?

**Comment by zhangxinjian123** [comment]
yes，Synchronize MySQL data use delta.

**Comment by tdas** [comment]
sorry, i dont get you. Are you running `dataframe.write` or `deltaTable.merge()` ...which operation?

**Comment by zhangxinjian123** [comment]
I use structured streaming to synchronize MySQL data because delta supports update operations. Synchronize once in 10 minutes. But there will be many small files under the table, which will cause a lot of pressure on HDFS

**Comment by zhangxinjian123** [comment]
val deltaTable = DeltaTable.forPath(sparks, updatePath)

                  
descDeltaLakeUpdate
                    .coalesce(1)
                    .write
                    .format("delta")
                    .mode("overwrite")
                    .partitionBy("delta_processing_date")
                    .save(updatePath)
If I write directly, I can know the number of partitions.

deltaTable.as("events")
                    .merge(
                      descDeltaLakeUpdate.as("updates"),
                      "events.delta_pk_value = updates.delta_pk_value")
                    .whenMatched().updateAll()
                    .whenNotMatched()
                    .insertAll()
                    .execute()
If I use the updated API, I can't know the number of partitions, which will generate a large number of small files

**Comment by tdas** [comment]
This is a known problem. In the next release, 0.6.0, we are releasing a fix for this - https://github.com/delta-io/delta/issues/349

**Comment by tdas** [comment]
Please try out version 0.6.0, it has the option of repartitioning the data before writing the merge result - https://docs.delta.io/0.6.0/delta-update.html#performance-tuning
