### ISSUE TITLE
New Delta Lake benchmark for Renaissance

### ISSUE THREAD

**Issue by Fithos** [delta-io/delta#38]
As the people behind the freshly released Renaissance Benchmark Suite (https://renaissance.dev/), the announcement of Delta Lake open sourcing caught our attention. Indeed, a Delta Lake benchmark could be a very interesting addition to Renaissance, since performing many ACID transactions on top of Apache Spark looks like a relevant use case with enough abstraction layers and complexity. Moreover, such a benchmark would drive attention to the framework and would also be used by GC or compiler developers to make sure that they properly deal with this kind of workloads.

We would be very happy if you could [contribute to Renaissance](https://github.com/renaissance-benchmarks/renaissance/blob/master/CONTRIBUTION.md) with a workload that you feel is important. Adding such a workload should be a very easy task if you have a minimal demo app. It's not more complicated than adding a scala class to our `apache-spark` subproject and write a `runIteration` function with the actual workload. See this example of a [naive bayes classifier](https://github.com/renaissance-benchmarks/renaissance/blob/master/benchmarks/apache-spark/src/main/scala/org/renaissance/apache/spark/NaiveBayes.scala#L99-L105). Of course, we will be happy to help with the integration if necessary. 

Issue on our GitHub repo: https://github.com/renaissance-benchmarks/renaissance/issues/126

**Comment by tdas** [comment]
@Fithos Thank you very much for the suggestion. This is interesting. However, we are right now focusing on high-priority and community demanded features like cloud storage support and DML support. It would be great if someone in the community could build this.

**Comment by Fithos** [comment]
@tdas Thank you for the reply! Currently, is there any Delta Lake sample application that could be used as a benchmark? 
If not, we could write a benchmark ourself. Would it be possible to give us indications on a relevant workload that is representative of a realistic Delta Lake usage? If possible, we would greatly appreciate if somebody from the Delta Lake team could have a look at the PR once done, to give us confidence that the benchmark is correct and representative.

**Comment by dennyglee** [comment]
Closing this issue for now, please re-open if anyone is interested in building a Delta Lake benchmark sample application.
