### ISSUE TITLE
Unable to write delta data into s3a

### ISSUE THREAD

**Issue by saranyaeu2987** [delta-io/delta#384]
Hi,
I wanted to write delta data into s3a and encountering the following issue

`filterDF.write().format("delta").mode("overwrite").option("overwriteSchema", "true").save("s3a://selumalai/myTable");
`
tried with following versions and results in same error

- hadoop-aws - 2.7.3, 2.8.0
- delta-core_2.12 - 0.5.0 , 0.2.0
- aws-java-sdk - 1.7.4
- spark - 2.4.5

hadoop-aws 2.8.0 didnt help as mentioned in https://github.com/delta-io/delta/issues/68.

Exception in thread "main" java.util.concurrent.ExecutionException: **org.apache.hadoop.fs.UnsupportedFileSystemException: fs.AbstractFileSystem.s3a.impl=null: No AbstractFileSystem configured for scheme: s3a**
	at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:306)
.......

Any suggestions?

**Comment by jose-torres** [comment]
Hmm, it's hard to say what could be going wrong - that seems like the right configuration. Can you write files to that path directly through the Hadoop APIs?

**Comment by tdas** [comment]
Have you configured the LogStore based on S3? 
https://docs.delta.io/latest/delta-storage.html#amazon-s3

**Comment by tdas** [comment]
@saranyaeu2987 any updates?

**Comment by ayazabbas** [comment]
I'm seeing the same issue with this configuration
```
spark = pyspark.sql.SparkSession.builder.appName("test") \
    .config("spark.jars.packages", "io.delta:delta-core_2.12:0.7.0,org.apache.hadoop:hadoop-aws:2.7.7") \
    .config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension") \
    .config("spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog") \
    .config("spark.delta.logStore.class","org.apache.spark.sql.delta.storage.S3SingleDriverLogStore") \
    .getOrCreate()
```
