### ISSUE TITLE
Thousands of Delta stages accumulating at the end of writing, after writing to S3

### ISSUE THREAD

**Issue by Antauri** [delta-io/delta#387]
Hello guys,

We're ingesting to Delta tables (OSS variant, evaluating it against Hudi/Iceberg) and are storing data partitioned by y/m/d/h in S3 via Spark SQL given the "delta" format when writing out. When we initially started, we had about <10 or <15 stages to wait before Delta would ingest a batch of 30 minute data for us. As days went on and we put it to long-running tests, we now currently see a growing number of stages, in the thousands, coming from some code in the Delta logging.

Attached screenshots and our EMR configs for Spark. Any ideas on how to tackle this ever-growing list of jobs/stages? (note we are doing ephemeral, on-demand EMR and each ingestion is done, 15m apart, on a new EMR cluster, but only one single writer at any given time).

[Link to OneDrive public folder for this issue as Github refuses to upload the screenshots](https://1drv.ms/u/s!AvNsBemTe-EZgYkKLhlEenzVItqXCQ?e=F6Laue)

EMR configs:
```
"applicationConfigs": {
    "emrfs-site":{
      "properties": {
        "fs.s3.consistent": "true",
        "fs.s3.consistent.retryPolicyType": "fixed",
        "fs.s3.consistent.retryPeriodSeconds": "6",
        "fs.s3.consistent.retryCount": "100",
        "fs.s3.consistent.fastList.prefetchMetadata": "true",
        "fs.s3.consistent.notification.SQS": "true",
        "fs.s3.consistent.notification.SQS.queueName": "emrfs-inconsistency",
        "fs.s3.consistent.metadata.tableName": "EmrFSMetadata",
        "fs.s3.consistent.metadata.read.capacity": "500",
        "fs.s3.consistent.metadata.write.capacity": "500"
      }
    },
    "yarn-site": {
      "properties": {
        "yarn.nodemanager.vmem-check-enabled": "false",
        "yarn.nodemanager.pmem-check-enabled": "false"
      }
    },
    "presto-connector-hive": {
      "properties": {
        "hive.metastore": "glue",
        "hive.metastore.glue.datacatalog.enabled": "true"
      }
    },
    "spark-hive-site": {
      "properties": {
        "hive.metastore.client.factory.class": "com.amazonaws.glue.catalog.metastore.AWSGlueDataCatalogHiveClientFactory"
      }
    },
    "hive-site": {
      "properties": {
        "hive.metastore.warehouse.dir": "s3://somebucket/someprefix",
        "hive.metastore.client.factory.class": "com.amazonaws.glue.catalog.metastore.AWSGlueDataCatalogHiveClientFactory",
        "hive.metastore.schema.verification": "false"
      }
    },
    "spark": {
      "properties": {
        "maximizeResourceAllocation": "true"
      }
    },
    "spark-defaults": {
      "properties": {
        "spark.rdd.compress": "false",
        "spark.shuffle.compress": "false",
        "spark.shuffle.spill.compress": "false",
        "spark.kryo.unsafe": "true",
        "spark.sql.shuffle.partitions": 1024,
        "spark.sql.sources.partitionOverwriteMode": "dynamic",
        "spark.sql.parquet.compression.codec": "gzip",
        "spark.sql.parquet.fs.optimized.committer.optimization-enabled": "true",
        "spark.sql.columnVector.offheap.enabled": "true",
        "spark.sql.parquet.recordLevelFilter.enabled": "true",
        "spark.sql.hive.convertMetastoreParquet": "false",
        "spark.hadoop.pathoutputcommit.reject.fileoutput": "true",
        "spark.serializer": "org.apache.spark.serializer.KryoSerializer",
        "spark.delta.logStore.class": "org.apache.spark.sql.delta.storage.S3SingleDriverLogStore",
        "spark.executor.extraJavaOptions": "-XX:+UseG1GC -XX:MaxGCPauseMillis=600",
        "spark.driver.extraJavaOptions": "-XX:+UseG1GC -XX:MaxGCPauseMillis=600"
      }
    }
  }
```

Our writing code is something simple:
```
        // Go
        eventsDataset
            .write ()
                .format (TABLE_FORMAT)
                .partitionBy ("year", "month", "day", "hour")
            .mode (SaveMode.Append)
        .save (s3Path);

        // Obtain the reference
        DeltaTable currentTable = DeltaTable.forPath (jobContext.sparkSession (), s3Path);

        // Clean-up on isle 5, cause we must
        currentTable.vacuum (10d * 24d); // 7 days by 24h each

        // Generate manifests after cleaning of course
        currentTable.generate ("symlink_format_manifest");
```

**Comment by Antauri** [comment]
From the looks of the source code, line 77 in DatabricksLogging.scala is something benign. https://github.com/delta-io/delta/blob/master/src/main/scala/com/databricks/spark/util/DatabricksLogging.scala

Help understanding why this issue occurs would help and how to deactivate it (if it's not required)!

**Comment by tdas** [comment]
DatabricksLogging is just for recording operation runtimes. It wraps around any code whose runtime needs to be logged. It does not start any new operation or affect the run time of any operation that it records. How did you determine that the culprit is DatabricksLogging? If you looked at the stack trace, what really matters is what is running after recordOperation has been called. Can you share those stack traces?

Furthermore, you code seems quite simple. Can you narrow down which of the three operations are creating the jobs - save, vacuum, or generate? you can try by dropping one of those operations and see how many jobs does it create.

**Comment by Antauri** [comment]
Narrowed it down to vacuum, through correlation with our code and recent commits which introduced this line between save and generate (which was working fine). Why would vacuum enter such a loop?

We've reset our test data to practically starting from the beginning and write the first few partitions and it behaves the same, entering this long loop of jobs/stages, a few milliseconds long each, as you can see in the screenshots.

Our "resolve" for this situation would be to move "vacuuming" out of this code path (and run it async whenever we need, like once per day) but we'd like to understand if this is normal behavior (eg. vacuuming passing through each file/operation in the log) or there's something odd with our use-case.

We can provide more details of the environment if needed. What would you need?

**Comment by tdas** [comment]
Yes, vacuum generally does not need to be run on every write. it is typically run every day. vacuum can be expensive because it does the following
1. List all the files in the directory (recursively if partitioned)
1. Find out all files needed by all the retained table versions. 
1. Join these to find which files are not needed and then delete them. 

Its (2) that can take longer as the number of table versions grows until the number of retained table versions stabilize. So it is recommended that its run separately once a day at most.

**Comment by pranavanand** [comment]
Btw @Antauri your vacuum is:
        `currentTable.vacuum (10d * 24d); // 7 days by 24h each`
did you mean `24h` instead of `24d`?

**Comment by Antauri** [comment]
@pranavanand it's "d" from "double" in Java to make our Sonarqube happy :) (since vacuum accepts a double, giving it 10 * 24 makes Sonarqube unhappy). It's 10 days by 24h expressed in a way that passed code quality complaints.

@tdas will move to one per day vacuuming. Generating so many stages (thousands) I've confused it for a bug. If I look at the Vacuum command https://github.com/delta-io/delta/blob/master/src/main/scala/org/apache/spark/sql/delta/commands/VacuumCommand.scala#L92 the function in question is called "gc" same as in the screenshots. It seems this is how vacuuming works, instead of a single job + stages, generating a kind of "recursive" list of thousands of jobs and stages.

Thank you for clarifications.
