### ISSUE TITLE
Getting java.lang.UnsupportedOperationException: null when trying to run sbt it:test from databricks cluster

### ISSUE THREAD

**Issue by spachari** [delta-io/delta#388]
Can anyone please tell me what it is missing?

[error] ! 
[error]  java.lang.UnsupportedOperationException: null (DeltaTable.scala:626)
[error] io.delta.tables.DeltaTable$.forPath(DeltaTable.scala:626)
[error] com.activision.etl.allspark.DimUserMergeWriterTest.testSetup(DimUserMergeWriterTest.scala:85)
[error] com.activision.etl.allspark.DimUserMergeWriterTest.beforeAll(DimUserMergeWriterTest.scala:29)

Here is my code

DeltaTable.forPath(spark,
      tablePath )
      .as("dim_user")
      .merge(
        df_with_timestamp.as("updates"),
        "dim_user.key == updates.key")
      .whenMatched("updates.last_activity_date > dim_user.last_activity_date")
      .updateAll()
      .whenNotMatched
      .insertAll()
      .execute()

I am using 

"com.databricks" %% "dbutils-api" % "0.0.4" % "provided" version databricks

**Comment by rahulsmahadev** [comment]
Hey @spachari  are you running open source delta lake or Delta Lake on Databricks

**Comment by tdas** [comment]
I agree with @rahulsmahadev your set up sounds very confusing. Are running sbt in a Databricks cluster or running it locally, but trying to run Spark jobs on a Databricks cluster? For the second one, you have to use DBConnect - https://docs.databricks.com/dev-tools/databricks-connect.html

**Comment by zsxwing** [comment]
Closing the stale ticket.
