### ISSUE TITLE
[Storage System] Support for AWS S3 (single cluster/driver)

### ISSUE THREAD

**Issue by tdas** [delta-io/delta#39]
This is the official issue for tracking support for AWS S3. Specifically, we want to enable Delta Lake to operate on AWS S3 with transactional guarantees when all writes go through a single Spark driver (that is, it must be a single SparkContext in a single Spark driver JVM process). 

The major challenges for operating on S3 with transactional guarantees are as follows: 
1. Lack of atomic "put if not present" - Delta Lake's atomic visibility of transactional changes depends on committing to the transaction log atomically by creating a version file X only if it is not present. S3 file system does not provide a way to perform "put if absent", hence multiple concurrent writers can easily commit the same version file multiple times, thus overwriting another set of changes.

2. Lack of consistent directory listing - Delta Lake relies on file directory listing to find the latest version file in the transactional log. S3 object listing does not provide the guarantee that listing attempts will return all the files written out in a directory. This, coupled with 1. can further lead to overwriting of the same version. 

In this issue, we are going to solve the above problems for a single Spark cluster - if all the concurrent writes to a table go through a single cluster, then we can do the necessary locking and tracking latest version needed to avoid the above issues.

**Comment by binary132** [comment]
What about going through a locking interface which could be implemented within Spark or by a service, such as DynamoDB?

**Comment by tdas** [comment]
Using something like DynamoDB as locking service is definitely one of ideas we will be playing with to implement the multi-cluster mode (tracked by #41 ). For this issue, we are focusing on releasing something quickly that enables the community to start using Delta Lake with S3.

**Comment by gourav-sg** [comment]
with EMR 5.24.0 we can have multiple master nodes (obviously they are fail-safe ones, but will be interesting to test).

**Comment by zsxwing** [comment]
This is resolved by https://github.com/delta-io/delta/commit/c8169bd106e1a509d4138c5d1655457aa11179c5

**Comment by gourav-sg** [comment]
What should be the best way to start testing this in AWS S3? I can also start updating few documentation around it so that others can refer to it as well, please do let me know.

**Comment by zsxwing** [comment]
@gourav-sg We are working the document right now. Once we update it, I will ping you in this ticket. Thanks!

**Comment by wendigo** [comment]
Since the S3 now supports conditional writes, is there a plan to support it as a reconciliation mechanism in delta?
