### ISSUE TITLE
Support "versionAsFor" for streaming from delta table

### ISSUE THREAD

**Issue by vitalvi** [delta-io/delta#391]
It seems currently there is no good way how to start streaming from table from particular batch or timestamp. It is possible to apply filtering after reading, like: 
```
spark.readStream
      .format("delta")      
      .load(tablePath)
      .where(col("dateColumn") >= today)
      .writeStream...
```

but it would really useful to be able to set starting batchId or timestamp streaming should be started from. Sort of:

```
spark.readStream
      .format("delta")
      .option("versionAsOf", "5")  
```

**Comment by tdas** [comment]
This is a great feature request. Would be great if someone in the community adds this feature.

**Comment by zsxwing** [comment]
This looks useful. Since this is not time traveling, I'd suggest to use `startingVersion` instead.

**Comment by windpiger** [comment]
#474 has been released
