### ISSUE TITLE
Deltatable does not recognise the newly created spark table

### ISSUE THREAD

**Issue by spachari** [delta-io/delta#392]
I created a table like this and inserted some data

spark.sql(s"create table if not exists test " +
"(key String," +
"name String," +
"address String," +
"inserted_at TIMESTAMP) " +
s"  using delta  LOCATION 's3://test/user/'")
I can view the table via

spark.table("test").show()
But when I do

DeltaTable.forPath(spark,"s3://test/user/" ).toDF.show(false)
I cannot see the data. But when i try this method

DeltaTable.isDeltaTable("s3://test/user/")
it is true. Can anyone please explain what I am missing?

Further, when I want to do a merge operation, I am getting this error.

[error] ! 
[error]  java.lang.UnsupportedOperationException: null (DeltaTable.scala:639)
[error] io.delta.tables.DeltaTable$.forPath(DeltaTable.scala:639)

**Comment by rahulsmahadev** [comment]
Hey @spachari have you tried using `DeltaTable.forName(spark, "test")`

**Comment by tdas** [comment]
@spachari are you using Databricks Delta or OSS delta? I would expect this error to happen with OSS Delta because OSS does not support Hive metastore defined tables and related DDL commands yet. It's blocked on Apache Spark 3.0 release. See #85

**Comment by tdas** [comment]
@spachari any updates on this issue?
