### ISSUE TITLE
Automatic schema evolution documentation incorrect for 0.6.0 docs

### ISSUE THREAD

**Issue by gpongracz** [delta-io/delta#397]
Under the delta.io document https://docs.delta.io/0.6.0/delta-update.html#automatic-schema-evolution first paragraph in the documentation for Automatic schema evolution it states to set spark.databricks.delta.schema.autoMerge to true rather than spark.delta.schema.autoMerge.

I would be happy to assist with this issue if someone might direct me to any instructions on how to update the docs. I am having trouble locating them.

**Comment by tdas** [comment]
Actually, you are correct that it is wrong. But it should be `spark.databricks.delta.schema.autoMerge.enabled`. 

There is `databricks` in all our spark session confs due to legacy reasons.

**Comment by tdas** [comment]
I have updated the website. Thank you for catching it.

**Comment by gpongracz** [comment]
Thanks for clarifying
However this would seem to be inconsistent with the setting spark.delta.logStore.class which I have been using since 0.4.0 (which seems to work)
Should I change this also to include the databricks moniker?

**Comment by tdas** [comment]
Nooo! That is indeed correct. The logstore conf we added after open-sourcing and hence we did it without databricks in it. But this autoMerge conf has been there since the beginning of Delta before open-sourcing, hence has "databricks" in it and is now much harder to change.

**Comment by gpongracz** [comment]
aliasing is not possible?

**Comment by tdas** [comment]
Conceptually yes, technically a little tricky but feasible. However, semantically, it introduces the complexity of which one takes priority if both `spark.databricks.delta.x` and `spark.delta.x` are specified and the values are different.
