### ISSUE TITLE
[Storage System] Support for Azure filesystems

### ISSUE THREAD

**Issue by tdas** [delta-io/delta#40]
This is the official issue for tracking the work for supporting Azure File System. 
Delta Lake version (0.1.0) does not support Azure File Systems because the default implementation is based on Hadoop's new FileContext and AbstractFileSystem APIs (gives atomic renames for HDFS) which Azure does not support yet. The plan is to build File System based LogStore implementation.

**Comment by zsxwing** [comment]
This was added in https://github.com/delta-io/delta/commit/a98550011591d78d55bd6e003ce455b9a9f7a232
