### ISSUE TITLE
OptimisticTransaction.commitStartNano is always -1

### ISSUE THREAD

**Issue by zsxwing** [delta-io/delta#406]
It should be the time when a commit (the commit method is called) starts. https://github.com/delta-io/delta/blob/38fa6dc8daaa03cbab86eb9df62ecc8a12626741/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala#L167

**Comment by SpaceRangerWes** [comment]
@zsxwing I'll take it up.

**Comment by zsxwing** [comment]
Cool. Thanks!

**Comment by zsxwing** [comment]
Fixed by #411
