### ISSUE TITLE
isDeltaTable returns true against an empty Delta table path containing only an empty _delta_log directory

### ISSUE THREAD

**Issue by alextmeyer** [delta-io/delta#407]
Encountered  while trying to vacuum an empty delta table through an automated vacuum that lists out a database path and checks if any underlying table paths are delta tables. 

All that exists under this example table path is an empty _delta_log directory
```
>>> table_path
's3://<some_db_path>/<table>'
>>> DeltaTable.isDeltaTable(spark, table_path)
True
>>> deltaTable = DeltaTable.forPath(spark, table_path)
>>> deltaTable.vacuum(24)                                                       
Traceback (most recent call last):
  File "/usr/lib/spark/python/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o71.vacuum.
: java.lang.IllegalArgumentException: requirement failed: No state defined for this table. Is this really a Delta table? Refusing to garbage collect.```

**Comment by zsxwing** [comment]
If a table path has an empty _delta_log directory, is it a Delta table? IMO, it should be no because it doesn’t have a schema and most of operations won't work in this case. Most of people will use `DeltaTable.isDeltaTable` to check whether they can use Delta operations. What do you think?

**Comment by alextmeyer** [comment]
Sorry @zsxwing  just saw this.

I agree that with an empty _delta_log directory that it shouldn't be considered a delta table. 

To work around the issue in my automated script I utilize the isDeltaTable check and actually just check if the delta_log folder was the only object under the table location. If it was then I skipped the vacuum process.

Empty _delta_log path and/or empty table path besides _delta_log I think would be considered not delta tables. If other delta table commands fail on the path (outside of corruption) then IMO it should not be considered a delta table

**Comment by zsxwing** [comment]
This has been fixed by https://github.com/delta-io/delta/commit/667a999bf42e3ba8551bddb62d4ca6ab4adbcf1e in 0.8.0
