### ISSUE TITLE
Spark implicits do not work on com.databricks.backend.daemon.dbutils.FileInfo

### ISSUE THREAD

**Issue by spachari** [delta-io/delta#410]
import spark.implicits._
dbutils.fs.ls(folderName).toDF

throws an error of 

 value toDF is not a member of Seq[com.databricks.backend.daemon.dbutils.FileInfo]

But it works fine in databricks notebook. Can anyone advice what I am missing?

I am using the following library
"com.databricks" %% "dbutils-api" % "0.0.4"

**Comment by tdas** [comment]
This is unrelated to delta lake. Please contact Databricks Support for non-DeltaLake Databricks issues.
