### ISSUE TITLE
`forName` in Python API

### ISSUE THREAD

**Issue by JCZuurmond** [delta-io/delta#412]
Could we have the `forName` [method](https://github.com/delta-io/delta/blob/ee0719577fd38f61c5b9b1d55bcb577c43d4ee1b/src/main/scala/io/delta/tables/DeltaTable.scala#L659) in the Python API? 

Main motivation: I have to pass the path through my code a lot, I would like to use the table name instead.

**Comment by tdas** [comment]
We are working on it. Its currently blocked on having the testing framework set up for Python tests with metastore tables and @brkyvz is actively working on it. Soon we will have it.

**Comment by JCZuurmond** [comment]
Great, thank you! I'll keep an eye out here and for 0.7.0.

**Comment by tdas** [comment]
This has been added to master - https://github.com/delta-io/delta/blob/master/python/delta/tables.py#L321
