### ISSUE TITLE
[DML] Scala/Java APIs for MERGE

### ISSUE THREAD

**Issue by tdas** [delta-io/delta#42]
This tracks the ongoing work and discussions for building the Scala/Java APIs for SQL MERGE (that is, upserts) on Delta Lake tables.

**Comment by tdas** [comment]
Here is the proposed programming APIs for MERGE, DELETE, UPDATE. Please share your thoughts in comments.

https://docs.google.com/document/d/1gU6G7XJSg3wuQDLIJVM1_FLKSj2KoLW0kcOu5HicYQM/edit?usp=sharing

**Comment by V-Lamp** [comment]
Hi everyone,
Seeing the tickets in this 0.3 milestone left me a bit confused: What is the current way to do a MERGE (or UPDATE for that matter) in Delta? My impression was that this functionality is already there.
Thank you!

**Comment by marmbrus** [comment]
@V-Lamp there is still quite a bit of functionality that only exists in Managed Delta Lake on Databricks, but not in OSS yet. It is our goal to open up all of these APIs so that any delta program can run in OSS, but its going to take some time. These tickets are tracking that effort :)

**Comment by V-Lamp** [comment]
@marmbrus thanks for clarifying! 

Indeed opening up this functionality should help adoption in the classic "support over OSS" model, thanks for all the good work.

**Comment by tdas** [comment]
Added merge in commit https://github.com/delta-io/delta/commit/526982101e2aeade3e9e98968312403d42bbdc12
