### ISSUE TITLE
Unexpected full table scan

### ISSUE THREAD

**Issue by mrk-its** [delta-io/delta#424]
- spark 2.4.4
- delta 0.6.0

Let's create partitioned test table and load it:
```
from pyspark.sql import functions as F

spark.range(16).withColumnRenamed("id", "a").crossJoin(
    spark.range(16)
).write.format("delta").partitionBy("a").save("test")

df = spark.read.format("delta").load("test")
```

Following query works like expected, touching only single partition:
```
q1 = (F.col("a") == 1) & (F.col("id")==1)
df.filter(q1).explain()
   ...
   +- *(1) FileScan ... PartitionCount: 1 ...
```
But following one does full table scan:
```
q1 = (F.col("a") == 1) & (F.col("id")==1)
q2 = (F.col("a") == 2) & (F.col("id")==2)

df.filter(q1 | q2).explain()
   ...
   +- *(1) FileScan ... PartitionCount: 16 ...
```

Of course we can do some workarounds:
```
df.filter(q1).union(df.filter(q2)).explain()
...
:     +- *(1) FileScan ... PartitionCount: 1
      +- *(2) FileScan ... PartitionCount: 1
```
or:
```
df.filter(F.col("a").isin([1,2]) & (q1 | q2)).explain()
   ...
   +- *(1) FileScan ... PartitionCount: 2 ...
```

The question is: is full table scan expected for this simple query:
```
df.filter(q1 | q2)
```
or it is a bug?

**Comment by liwensun** [comment]
@mrk-its Yes, this is expected. Two reasons for this:

1) Spark SQL can separate the entire filter (on `AND`)  into a set of conjunctive filters, but not `OR`, so the filter `q1 | q2` you had there is considered as a single filter and cannot be further broken down.

2) Data skipping can only be applied on "partition-only" filters, i.e., the filters that only refer to partition columns, no data columns. The filter `q1 | q2` is not "partition-only", so it can't be used for data skipping.

**Comment by mrk-its** [comment]
It makes sense, thanks!
