### ISSUE TITLE
What Presto version can read delta lake data?

### ISSUE THREAD

**Issue by tooptoop4** [delta-io/delta#427]
I see
https://docs.delta.io/0.5.0/presto-integration.html
https://databricks.com/blog/2020/01/29/query-delta-lake-tables-presto-athena-improved-operations-concurrency-merge-performance.html

But Prestosql 332 has a commit that explicitly disallows reading Delta data, they mention it never worked anyway:
https://github.com/prestosql/presto/pull/3366#issuecomment-610540663

**Comment by tdas** [comment]
You can read Delta tables using any version of Presto using the generated manifest files - https://docs.delta.io/latest/presto-integration.html

**Comment by tooptoop4** [comment]
did u see the commit denying it?

**Comment by zsxwing** [comment]
@tooptoop4 the commit you posted here is to disallow tables whose `spark.sql.sources.provider` property is `delta`.  These tables are Spark data source tables which are created by Spark.

If you follow the instructions in https://docs.delta.io/latest/presto-integration.html to create a table, such as
```
CREATE EXTERNAL TABLE mytable ( ... )   -- same schema as the Delta table
PARTITIONED BY ( ... )  -- optional, must be the same as the Delta table
ROW FORMAT SERDE 'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
STORED AS INPUTFORMAT 'org.apache.hadoop.hive.ql.io.SymlinkTextInputFormat'
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION '<pathToDeltaTable>/_symlink_format_manifest/'  -- location of the generated manifest
```
It won't have the table property `spark.sql.sources.provider`. Hence it should still work.

**Comment by tdas** [comment]
@tooptoop4 did you try this out? did it work?
