### ISSUE TITLE
[DML] Scala/Java API for UPDATE

### ISSUE THREAD

**Issue by tdas** [delta-io/delta#43]
This tracks the ongoing work and discussions for building the Scala/Java APIs for SQL UPDATE Delta Lake tables.

**Comment by xianyinxin** [comment]
@tdas Thanks. Would you pls provide a design doc?

**Comment by tdas** [comment]
Yes, I will make one soon.

**Comment by tdas** [comment]
Here is the proposed programming APIs for MERGE, DELETE, UPDATE. Please share your thoughts in comments.

https://docs.google.com/document/d/1gU6G7XJSg3wuQDLIJVM1_FLKSj2KoLW0kcOu5HicYQM/edit?usp=sharing

**Comment by tdas** [comment]
this has been completed with https://github.com/delta-io/delta/commit/5bf990d1a4ce4d429212118fa2d6008d982820bf
