### ISSUE TITLE
Hardcoded "_delta_log" dir name

### ISSUE THREAD

**Issue by rambabu-posa** [delta-io/delta#463]
Any reason to hardcode transaction log's root folder name "_delta_log" in DeltaLog.scala file?

**Comment by tdas** [comment]
So that given the table directory (from Dataframe API or from location in metastore), it is obvious where the log files are.

**Comment by jaceklaskowski** [comment]
It could be an option, but what would that flexibility give? It simply easier to assume it's `_delta_log` and consider it a "magic number" (so external tools know it's a delta table immediately).
