### ISSUE TITLE
Vacuuming on S3 + EMRFS leaving behind marker files, not cleaning-up all directories empty of data

### ISSUE THREAD

**Issue by Antauri** [delta-io/delta#466]
On a partition lake by year=a/month=b/day=c/hour=d/minute=e ... when using Delta Lake on EMR clusters withe EMRFS enabled (for strong consistency) the vacuuming operation leaves behind the marker files from EMRFS of the form:

- minute=00_$folder$
- minute=01_$folder$
- minute=02_$folder$
- minute=03_$folder$
- minute=04_$folder$
- etcetera ...

The "hour" prefixes are not deleted (because of non-empty directories most probably) neither are "day", "month" prefixes as time rolls on and vacuuming continues.

A few questions:

Is this a bug? Intended behavior? 
Is running Delta Lake directly on S3 without EMRFS safe? (which would avoid these leftovers). 

What could be a safe workaround (eg. implemented by us using Hadoop file-system API) that would solve this issue? For example, is there something wrong if we "delete" using the Delta API to mark the files for deletion/vacuuming, but we never run vacuum, but delete the files ourselves? (eg. using AWS Java SDK).

Info here @ https://aws.amazon.com/premiumsupport/knowledge-center/emr-s3-empty-files/ on these types of files. We run AWS EMR 5.30/Spark jobs (via Livy).

**Comment by brkyvz** [comment]
If these marker files are of 0 size and have no impact on your storage costs, do you even care?

**Comment by Antauri** [comment]
Yes, as it seems they are preventing the clean-up of empty directories (as hour directories have minute_$folder$ marker files in them) and the partitions are not cleaned-up, though they're logically empty (as all the data past a certain time point has been deleted and then physically vacuumed).

That's why the source of this "bug". Probably the code is making an expectation of empty directories which is prevented on S3, with EMRFS by these marker files.

**Comment by Antauri** [comment]
I am closing this issue. It is indeed cleaning the marker files also but after more vacuuming (so at the 2nd, 3rd iteration). It starts first by emptying the minute folders which then leave behind the minute_$folder$ markers. Then on the next run, it cleans those and the hour_$folder$ markers remain and so on. After a few runs it was able to clean-up partitions that were empty from previous days. It just needs to run a couple of more times over the hierarchy to incrementally clean-up these markers on the next runs.
