### ISSUE TITLE
KMS encrypted bucket gives 403

### ISSUE THREAD

**Issue by alexmnyc** [delta-io/delta#47]
KMS encrypted bucket gives 403

```
  df.write.format("delta").save(s"s3a://$s3BucketName/$tableName")

java.nio.file.AccessDeniedException: s3a://bucket/table/_delta_log: innerMkdirs on s3a://bucket/table/_delta_log: com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; 
```

**Comment by tdas** [comment]
@alexmnyc Do you have any more information how you have set up the authentication and what is the stack trace you are seeing.

**Comment by bartosz25** [comment]
@alexmnyc 
To complete @tdas question, take a look at your IAM policy statements and:
* check whether they are authorized to use the associated KMS keys. You can find some examples here https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kms-key.html (search '"Sid": "Allow use of the key",')
* also verify whether your role is authorized to write (create object) to your S3 bucket

**Comment by zsxwing** [comment]
@alexmnyc Could you try to replace `delta` with `parquet` to see if the error still happens?

**Comment by pranavanand** [comment]
@alexmnyc were you able to try out the write with `parquet` to see if the error happens with both formats?

**Comment by zsxwing** [comment]
Closing the stale ticket.
