### ISSUE TITLE
Support starting streams on Delta tables from a given version or timestamp

### ISSUE THREAD

**Issue by brkyvz** [delta-io/delta#474]
Support streaming source options `startingVersion` or `startingTimestamp` to start processing a stream (in its first micro-batch) from a given version onwards. In this mode, we should not create a Snapshot at that version, but start tailing the transaction log at that version onwards. If a checkpoint is available, we should continue from the state that is in the checkpoint.

**Comment by SpaceRangerWes** [comment]
I got it.

**Comment by sivasai-quartic** [comment]
Will we expect this next release?

**Comment by SpaceRangerWes** [comment]
> Will we expect this next release?

I'm not sure what their release cycle is. It may not be in 0.8.0 depending on how soon it is cut.
