### ISSUE TITLE
[DML] Scala/Java API for VACUUM

### ISSUE THREAD

**Issue by tdas** [delta-io/delta#48]
This tracks the ongoing work and discussions for building the Scala/Java APIs for *vacuuming* old-version-files and other unnecessary files from the Delta table directory.

**Comment by cfmcgrady** [comment]
Hi, @tdas, Is there any update or design document on this issue?

**Comment by tdas** [comment]
We are focussing right now on the basic DML apis like Merge, update and
delete. Once those are out of the door we will work on vacuum. I am hoping
that once we have the basic API structure in place with those operations
adding vacuum operation will be easy.

**Comment by Nixonite** [comment]
Hi all,

So I just got started looking into delta this week. Is the vacuum feature currently only available in the proprietary version of delta lake?

**Comment by tdas** [comment]
As of now, yes. But soon we will have programmatic APIs for that in OSS.

**Comment by tdas** [comment]
vaccum has been added by this commit - https://github.com/delta-io/delta/commit/73f4a64284f7e971be4a5238aa4b3f310360df85

will be released next week.
