### ISSUE TITLE
Why DeltaTableV2 not support SupportsRead

### ISSUE THREAD

**Issue by LantaoJin** [delta-io/delta#488]
Why `DeltaTableV2` not support `SupportsRead`?
`DeltaTableV2` has supported `SupportsWrite`, but didn't support `SupportsRead`.
I see `BATCH_READ` has been in the `capabilities()` of `DeltaTableV2`.

If `DeltaTableV2` supports `SupportsRead`, when read a delta table, we can get a `DataSourceV2Relation` instead of `loadV1Source`

**Comment by brkyvz** [comment]
@LantaoJin We don't use the DataSourceV2 APIs (Scan, Batch, etc) for reading Delta files. Therefore we don't `SupportsRead`

**Comment by zsxwing** [comment]
Closing this as this is answered.

**Comment by MasterDDT** [comment]
@brkyvz is there a plan to use DataSourceV2 at some point? Wont v1 be removed in a future Spark 3.x release? [Iceberg](https://github.com/apache/iceberg/blob/9a0d154b0ba5e6d10d79e30470295c91c89c1e09/spark2/src/main/java/org/apache/iceberg/spark/source/IcebergSource.java#L48) and [Hudi](https://github.com/apache/hudi/blob/c350d05dd3301f14fa9d688746c9de2416db3f11/hudi-spark-datasource/hudi-spark2/src/main/java/org/apache/hudi/internal/DefaultSource.java#L41) both use it.

**Comment by brkyvz** [comment]
@MasterDDT I really doubt V1 will be removed anytime soon. It is a migration effort, and we won't get too much benefits from migrating to it at this moment
