### ISSUE TITLE
[feature request] automatic synchronize new partitions with hive catalog 

### ISSUE THREAD

**Issue by rubenssoto** [delta-io/delta#494]
Hi, how are you?

A great feature that Hudi has and I would like to suggest to Delta, is automatic synchronize new partitions with glue hive catalog, if possible Delta could automatic create the hive catalog table too and update new columns.

It will be very helpful!

Thank you.

**Comment by simonvanderveldt** [comment]
@tdas Do you know if any progress has been made around this?
We're running in a federated setup and some places are using delta lake on databricks but other are running the regular/open-source Hive Metastore and they are currently unable to do things like `SHOW PARTITIONS` when using delta tables. It would be great if that would be possible.

**Comment by zsxwing** [comment]
@simonvanderveldt the issue of `SHOW PARTITIONS` is tracked by #996 which doesn't need to save partitions in Hive Metastore/Glue.

I'm going to close this issue right now as we don't  have any plan to write partitions to Hive Metastore/Glue. That would cause a lot of stability issues when the number of partitions is huge. Feel free to reopen this if you have further comments for this.
