### ISSUE TITLE
API to get max version number and  latest/earliest time travel timestamp?

### ISSUE THREAD

**Issue by frank-dkvan** [delta-io/delta#50]
in some real use cases, I want to get data from the designated version and timestamp

**Comment by CyborgDroid** [comment]
Try describe with max mins.

```python
df = spark.sql('DESCRIBE HISTORY mytable')\
        .groupby()\
        .agg(max('version'), min('version'), max('timestamp'), min('timestamp'))
```

https://docs.databricks.com/delta/quick-start.html

**Comment by marmbrus** [comment]
`DESCRIBE HISTORY` has not been open sourced (yet!).

You can do this with internal APIs, but please note these are subject to change without warning.

`DeltaLog.forTable(...).snapshot.version`

**Comment by frank-dkvan** [comment]
> `DESCRIBE HISTORY` has not been open sourced (yet!).
> 
> You can do this today with internal APIs, but please note these are subject to change without warning.
> 
> `DeltaLog.forTable(...).snapshot.version`

it works! thx!

**Comment by gauravbrills** [comment]
Wont this work 
```python
import databricks.koalas as ks
latest_version = deltaTable.history(1).select("version").to_koalas().iloc[0].iloc[0]
print(latest_version)
```
