### ISSUE TITLE
Broken Link on "Getting Started" button (on Home Page)

### ISSUE THREAD

**Issue by CreativeSlave** [delta-io/delta#502]
On the **Delta Lake home page**, there is a **broken link** for the **Getting Started** button.
https://delta.io/

**Get Started**: Links to: (has 'http://' at the end)
https://docs.delta.io/latest/delta-intro.htmlhttp://

**Should be**: 
https://docs.delta.io/latest/delta-intro.html

**Comment by tdas** [comment]
We are looking into it. Thanks so much for reporting.

**Comment by dennyglee** [comment]
Thanks @CreativeSlave for catching this - this has been now fixed.  You may need to refresh to clear out the cache for it take effect.

**Comment by tdas** [comment]
I double checked, and it seems to work now. i am closing this issue.
