### ISSUE TITLE
Checkpoint file size keeps on increasing 

### ISSUE THREAD

**Issue by ashokblend** [delta-io/delta#507]
Dear community
We have spark structured streaming ingestion pipeline which writes data to 10k(cardinality)/day partitions. As time passes by size of checkpoint file increases and so the time for job which read/writes checkpoint file increases. 

I understand, once we do compaction no of files will get reduced but as time pass by this file size will grow (as i understand). 

Is my understanding correct. If yes, is there any future plan to control this.

I see this configuration in delta.io but didn't find its being used anywhere.
https://github.com/delta-io/delta/blob/3ed57d0668b09d48172b0eb7221f647811657972/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSQLConf.scala#L225

**Comment by ashokblend** [comment]
There was some bug in our deduplication code which was causing memory leak and thus frequent GC. We fixed it.

But however this checkpoint issue is still there. Its size grows everytime checkpoint is created. I don't know whether its read or write operation, as i see in spark UI (as mentioned in problem description also) Time to create this checkpoint is more than 2 minutes. 
I don't know how delta.io handle this as ingestion continues and size of checkpoint files grows. May you guys share us any document link which discuss about this scenario.

**Comment by liwensun** [comment]
Yes checkpoint size is linear to current # files and file compaction definitely helps reduce it. We don't have plans for improving the checkpoint performance right now, but feel free to make a request. 

I'd consider reducing the number of partitions - 10k sounds pretty big unless you have at least several hundreds of MBs, ideally several GB's data per partition.

**Comment by zsxwing** [comment]
@Naveen1453 We added the [optimize](https://docs.delta.io/latest/optimizations-oss.html#optimize-performance-with-file-management) command in 1.2.0 to allow users to compact small files to larger files if your table is not over partitioned. If your table is over partitioned, you will need to pick up a smaller set of partition columns.

**Comment by GrigorievNick** [comment]
@zsxwing I don't understand how compaction help reduce the size of the checkpoint(delta log in parquet). Can you explain it?

Any operation over the log. Deleting data, compacting data, or rewriting data will grow checkpoint size.
Compaction help only to reduce the size of the latest Snapshot.
But checkpoint has a history of all operations, so every new function just increases its size.
Do I miss something?

**Comment by zsxwing** [comment]
> But checkpoint has a history of all operations, so every new function just increases its size.

Checkpoint doesn't contain the entire history. It contains the table states in the checkpoint version. For example, let's say [delta.deletedFileRetentionDuration](https://docs.delta.io/latest/table-properties.html) is using the default value 7 days and we compacted file A and file B to file C 7 days ago. Now if we create a checkpoint, it will not contain any information for file A and file B. You will only see file C in this new checkpoint.

**Comment by GrigorievNick** [comment]
@zsxwing but this is happen only if call compaction? or Every time when checkpoint performed?
