### ISSUE TITLE
Policy: cherry-picking changes into branch-0.6?

### ISSUE THREAD

**Issue by AFFogarty** [delta-io/delta#516]
Hello,

Does the Delta Lake team have a policy about whether you will accept PRs to cherry-pick changes from `master` into `branch-0.6`?  Can community members port bugfixes or features to enable them in Spark 2.4.x (regardless of whether there will be any official Delta 0.6.x releases in the future)?

Thanks,

Andrew

cc: @imback82 @rapoth

**Comment by zsxwing** [comment]
Generally, we will backport critical fixes to 0.6. For example, we made 0.6.1 to fix a regression. But we don't backport new features. Do you have any changes you would like to backport to 0.6?

**Comment by zsxwing** [comment]
This is answered. Closing the issue.
