### ISSUE TITLE
Storage configuration docs for Azure do not work.

### ISSUE THREAD

**Issue by AlexDHoffer** [delta-io/delta#519]
The docs here: https://docs.delta.io/latest/delta-storage.html

When using ``hadoop-azure-3.3.0.jar`` and ``delta-core_2.12-0.7.0.jar`` with Spark 3, the following error causes PySpark to fail upon the call:

``df = spark.read.format("delta").load("wasbs://{0}@{1}.blob.core.windows.net/{2}".format(container, storage_account_name, table)).limit(100)``

``py4j.protocol.Py4JJavaError: An error occurred while calling o81.load.
: java.lang.NoClassDefFoundError: org/apache/hadoop/fs/StreamCapabilities``

Any suggestions? Is there an older version of the jars I should use or something?

**Comment by zsxwing** [comment]
How did you get your Spark distribution? It looks like your Spark is built with a lower Hadoop version (probably Hadoop 2.7).

**Comment by zsxwing** [comment]
Looks like it's using Hadoop 2 as per the file name `gcs-connector-latest-hadoop2.jar` in https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/236d6f5bb2b6a058d65fa0959a326e036411b01f/spark-docker/Dockerfile#L28

**Comment by zsxwing** [comment]
@AlexDHoffer Maybe you can ask if Spark Operator for Kubernetes supports Hadoop 3.2 in https://github.com/GoogleCloudPlatform/spark-on-k8s-operator

**Comment by AlexDHoffer** [comment]
@zsxwing I will do that. Thank you. Alternatively, which set of Delta Core jars would work with Hadoop 2?

**Comment by zsxwing** [comment]
Delta Core jar should work with both hadoop 2 and hadoop 3. The issue you hit is hadoop-azure-3.3.0.jar is using some hadoop 3 APIs, so you need to make sure you are using hadoop 3 jars. By the way, I don't know whether hadoop-azure-3.3.0.jar works for all hadoop 3 versions or not. It's better to use the same hadoop version for other hadoop-xxx jars if possible.
