### ISSUE TITLE
[Feature Request] Log Api For python

### ISSUE THREAD

**Issue by rubenssoto** [delta-io/delta#520]
Hi Guys,

I need to retrieve some log information to help to make some decisions on compact operation, I made my own Delta Log reader, but will be great if I could use Delta log reader, today is only available for scala, is it possible to make an API to python?

https://github.com/delta-io/delta/blob/master/src/main/scala/org/apache/spark/sql/delta/DeltaLog.scala

thank you.

**Comment by zsxwing** [comment]
Could you try to use https://www.py4j.org/ to call Scala codes? Py4j is already in Spark. Calling it in your codes should be possible.

**Comment by manabian-** [comment]
I didn't work well with the Py4j method, so I chose the `describe detail` method.

```python
table_name = 'flights_summary_data'
table_size = spark.sql(f'describe detail {table_name}').select('sizeInBytes').first()[0]
print(f"Total file size (bytes): {table_size}")
```
![image](https://user-images.githubusercontent.com/10123723/127757090-7561ec35-4e99-4198-b82e-30008fe0347f.png)

**Comment by iam-nagarajan** [comment]
Tried with py4j like below
` dl = sc._jvm.org.apache.spark.sql.delta.DeltaLog.forTable(spark, 's3a://path_table')`

and it gives following error
`AttributeError: 'SparkSession' object has no attribute '_get_object_id'`

@zsxwing any suggestions to fix this?

**Comment by zsxwing** [comment]
could you try this?

```
dl = sc._jvm.org.apache.spark.sql.delta.DeltaLog.forTable(spark._jsparkSession, 's3a://path_table')
```

**Comment by zsxwing** [comment]
By the way, since DeltaLog is a private API, we don't have any plan to provide a Python API. Closing this.
