### ISSUE TITLE
Exception thrown while trying to use DeltaTable.forPath

### ISSUE THREAD

**Issue by RazvanMorarescu** [delta-io/delta#531]
Hello, 

I am trying to use the DeltaTable.forPath and i get an exception 
`py4j.protocol.Py4JJavaError: An error occurred while calling z:io.delta.tables.DeltaTable.forPath. : java.lang.UnsupportedOperationException`

Background:

- Databricks-connect 7.1.0 from VS Code
- Databricks Cluster is using runtime 7.1
- Python 3.7.5
- Scala 2.12.10
- Java 1.8.0_261
- PySpark 3.0.1-SNAPSHOT

The configuration of the spark session if the one from the Quick Start Guide for delta.io
`from pyspark.sql import SparkSession`
`spark = SparkSession.builder.config("spark.jars.packages", "io.delta:delta-core_2.12:0.7.0") \`
`                            .config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension") \`
`                            .config("spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog") \`
`                            .getOrCreate()`
`from delta.tables import *`

When calling the DeltaTable.forPath method, it throws the exception, but when calling the DeltaTable.isDeltaTable it works. I also tried using the same code in a databricks notebook and from there it works. I already tried using the forName method and the exception pops up.

This is somewhat the same error as in this issue #392 , unfortunately the person who opened it did not reply.

Also i check the cluster logs and this error is in the logs, at the exact time the forPath is executed from VS code
`ERROR DatabricksCatalogManager: Fail to instantiate the custom v2 session catalog: org.apache.spark.sql.delta.catalog.DeltaCatalog`

**Comment by brkyvz** [comment]
@RazvanMorarescu Can you please open a ticket with Databricks support. This is an issue with Databricks-Connect. I believe Databricks-Connect doesn't support Delta through the Python APIs. You should be able to use all SQL operations with
`spark.sql("...")`

**Comment by awong2635** [comment]
@RazvanMorarescu, so did you manage to use other way to modify/update the delta table(s) via databricks-connect? I'm facing a similar situation, running my notebook in VSCode, but using databricks-connect to talk to a databricks cluster. Any pointer would be greatly appreciated.

**Comment by tdas** [comment]
Databricks Connect does not support programmatic Delta APIs in Scala/Python. Its documented. https://docs.databricks.com/dev-tools/databricks-connect.html#limitations

**Comment by Varun3713-creator** [comment]
i am trying to use delta table with pyspark in jupyter notebook
i have spark-3.5.4 and delta-spark-3.3.0
but i am facing the issue 
Py4JJavaError: An error occurred while calling o249.showString.
: org.apache.spark.SparkException: Cannot find catalog plugin class for catalog 'spark_catalog': org.apache.spark.sql.delta.catalog.DeltaCatalog.

for the below code:

from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("DeltaExample") \
    .config("spark.jars.packages", "io.delta:delta-core_2.12:3.3.0") \
    .config("spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog") \
    .config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension") \
    .getOrCreate()
    # Sample data
data = [(1, "Alice", 23), (2, "Bob", 34)]
column = ['id', 'name', 'age']
df = spark.createDataFrame(data, column)

# Display data
df.show()
