### ISSUE TITLE
Delta small file size grows unexpectedly, not respecting spark.sql.shuffle.partitions?

### ISSUE THREAD

**Issue by arnehuang** [delta-io/delta#546]
I want to merge DF2 into DF1. DF2 is small and has only one partition, i.e. I call DF2 = DF2.repartition(1).persist() before merging. 

When I call `DF1.merge(DF2, ...).execute()` it works fine. However when I check the delta log, something unexpected happens: 
```
"operationMetrics":{"numTargetRowsCopied":"2253483",
"numTargetRowsDeleted":"0",
"numTargetFilesAdded":"21",
"numTargetRowsInserted":"14",
"numTargetRowsUpdated":"12",
"numOutputRows":"2253509",
"numSourceRows":"26",
"numTargetFilesRemoved":"12"}}}
```

Note that `numTargetFilesAdded` is > `NumTargetFilesRemoved`. Over time, the number of files becomes unmanageable (Millions)

Any advice on how to proceed? Is this happening because my spark.sql.shuffle.partitions is greater than the rows in my batch? I have `"spark.sql.shuffle.partitions":"50"`. 

version 0.6.1, spark2.4.5

**Comment by zsxwing** [comment]
Depend on how many partitions you have in the table, the worst case you may get `#partitions of table * #spark.sql.shuffle.partitions`.

You can enable `spark.databricks.delta.merge.repartitionBeforeWrite.enabled` to reduce the number of output files. See https://docs.delta.io/latest/delta-update.html#performance-tuning

**Comment by arnehuang** [comment]
Thank you
