### ISSUE TITLE
Concurrent append and overwrite breaks isolation (duplicating data)

### ISSUE THREAD

**Issue by tomasbartalos** [delta-io/delta#550]
**Problem**
When running concurrent append and overwrite to delta, the overwrite transaction reads data that is committed after its snapshot read version. This breaks isolation and duplicates data. The metadata (delta log) is handled properly with respect to read version, however the data read from delta is not properly isolated.

**Steps to reproduce**
I've created a test app, which manifests the problem: [delta-concurrency-bug](https://github.com/tomasbartalos/delta-concurrency-bug)

You need to run 2 spark apps:
- **[test.ConcurrentAppend](https://github.com/tomasbartalos/delta-concurrency-bug/blob/master/src/main/scala/test/ConcurrentAppend.scala)** - will continuously append data to delta `/tmp/concurrent_delta/`
- **[test.ConcurrentCompactor](https://github.com/tomasbartalos/delta-concurrency-bug/blob/master/src/main/scala/test/ConcurrentCompactor.scala)** - will reorganize data (overwrite with `dataChange = false`)

**Steps:**

1. start test.ConcurrentAppend, which will continuously append 700 rows to delta, let it run for a while
2. start test.ConcurrentCompactor, which will reorganize data with 20s sleep (so ConcurrentAppend will produce several commits before compaction finishes)
3. when ConcurrentCompactor finishes, kill the ConcurrentAppend app and check the results

**Failed Assertions:**

1. **Delta can't have duplicated data**. Every append inserts 700 records so following must be true:
spark.read.format("delta").load("/tmp/concurrent_delta").groupBy('batchId).count.where('count > 700).collect.isEmpty
res0: Boolean = false

2. **Data inserted by test.ConcurrentCompactor can have as many records as its read version**:
Let's find compactor transaction: 
`grep '"mode":"Overwrite"' /tmp/concurrent_delta/_delta_log/*`
```
{"commitInfo":{"timestamp":1605255834581,"operation":"WRITE","operationParameters":{"mode":"Overwrite","partitionBy":"[\"part\"]","predicate":"part = 0"},"readVersion":410,"isBlindAppend":false,"operationMetrics":{"numFiles":"1","numOutputBytes":"42615","numOutputRows":"289100"}}}
{"add":{"path":"part=0/part-00191-a69fc44e-12aa-46ca-9459-3790b580d94d.c000.snappy.parquet","partitionValues":{"part":"0"},"size":42615,"modificationTime":1605255832000,"dataChange":false}}
{"remove":{"path":"
```
You can see that read version = 410. Now let's time travel to that version in delta and compare counts with AddFile parquet generated by compactor:

```
scala> spark.read.format("delta").option("versionAsOf", 410).load("/tmp/concurrent_delta").count
res2: Long = 287700

scala> spark.read.format("parquet").load("/tmp/concurrent_delta/part=0/part-00191-a69fc44e-12aa-46ca-9459-3790b580d94d.c000.snappy.parquet").count
res4: Long = 289100
```
**As you can see there are 1400 duplicated records (2 * 700 appends)**

This proves that data read by compactor (version 410) is not properly isolated, because there is interference with later commits from ConcurrentAppend transactions. The delta log is handled properly as of version 410 and this is why the extra commits are not included in RemoveFiles of compactor transaction.

**Comment by tdas** [comment]
what file system are you using?

**Comment by tomasbartalos** [comment]
> what file system are you using?

I'm using local POSIX filesystem

**Comment by zsxwing** [comment]
The local file system is not safe to use in multiple Spark applications. The rename method in Hadoop's FileSystem implementation RawLocalFileSystem doesn't guarantee mutual exclusion. Although we use it in Delta Lake's unit tests, we have a hack here as a workaround to ensure mutual exclusion in a single JVM: https://github.com/delta-io/delta/blob/v0.7.0/src/main/scala/org/apache/spark/sql/delta/storage/HDFSLogStore.scala#L54

We will update our doc to highlight this.

**Comment by tomasbartalos** [comment]
Thank you for pointing this out, however I don't understand how a failing rename would cause the "phantom read phenomenon".
I think a failing rename would cause a missing transaction (rename fails, but exception is not thrown). This would mean missing data, but I don't understand how it could duplicate data.

Here the problem is that compactor claims to read version X, but apparently according to data it writes, it reads version X+n. So compactor is generating more data than it should.

**I've tried to debug compactor flow:** It tried to commit version 92, but latest was 127, so it correctly failed with `FileAlreadyExistsException` here:  https://github.com/delta-io/delta/blob/60c65a10ff69e90cd6be92254f536d008fc526a9/src/main/scala/org/apache/spark/sql/delta/storage/HDFSLogStore.scala#L79
Afterwards it successfully retried the commit with version 128. So it seems delta commits and mutual exclusion works correctly. However the parquet it added contained data from version 92 and 93 (when its read version was 91).
Also the **number of commits  = number of appends + 1 compactor commit**, so there was no missing commit.

Next I've tried to simulate mutual exclusion where another tx commited after the check: https://github.com/delta-io/delta/blob/60c65a10ff69e90cd6be92254f536d008fc526a9/src/main/scala/org/apache/spark/sql/delta/storage/HDFSLogStore.scala#L79

And it failed with: 
```org.apache.hadoop.fs.FileAlreadyExistsException: Rename destination file:/tmp/concurrent_delta/_delta_log/00000000000000000261.json already exists.```
Here: https://github.com/delta-io/delta/blob/60c65a10ff69e90cd6be92254f536d008fc526a9/src/main/scala/org/apache/spark/sql/delta/storage/HDFSLogStore.scala#L100

**Comment by tomasbartalos** [comment]
an important addition. **I've tested the issue on HDFS and also HDFS is creating duplicates**.
Same [testing code](https://github.com/tomasbartalos/delta-concurrency-bug), just used hdfs as delta target.

**Comment by tomasbartalos** [comment]
Hello,

I've added scripts, which simplifies reproducing the bug.
For local FS just run:
`run-local.sh` and check for `Test Result: ` string

For HDFS your need to have docker installed and run:
`run-docker.sh` and check for `Test Result: ` string in `docker logs -f compactor` output

**Comment by zsxwing** [comment]
Thanks a lot for the great testing project! We found an issue in file compaction. Working on a fix for this.
