### ISSUE TITLE
Way too tight coupling with spark

### ISSUE THREAD

**Issue by koertkuipers** [delta-io/delta#551]
currently delta is an project that is independent from apache spark, but it uses stuff deep inside the bowels of spark that is not part of spark's public or stable api. this makes you wonder if spark has perhaps extensibility issue (one shouldn't have to use internal apis to add a data source). it is also practically somewhat problematic: once you depend on delta it is nearly impossible to upgrade spark without also having to upgrade delta in complete lockstep.

once your project depends on delta trying out the latest spark master branch becomes very difficult, since its up to you to compile delta against it (which usually means fixing at least a few breaking changes in delta's usage of catalyst, and also fixing a bunch of broken unit tests). this is not good for the spark community as the community depends on contributors being able to test the latest spark master and report back issues. it now seems we have to chose between being able to test latest spark or using delta (or becoming an expert in delta's internals to maintain our own version against spark master).

to make delta less coupled some options are:
1) use less spark internal/unstable apis
2) always have a public branch for delta that is build against latest spark master
3) move delta into spark so the two projects are developed together
4) make more of the apis that delta uses in spark stable and/or public

best,
koert

**Comment by zsxwing** [comment]
Totally agree that this is painful. However, as Spark today doesn't have enough public APIs to allow Delta building all of its features, we have to depend on internal/unstable apis.

> 1. use less spark internal/unstable apis

This is a good point. We are always trying to avoid depending on Spark's internal/unstable apis. Feel free to submit PRs to improve this if you find any internal API usages can be replaced.

> 2. always have a public branch for delta that is build against latest spark master

This is hard to maintain. Spark has dozens of commits every week. Instead, we prefer to do a one-time work when a new Spark release RC comes out.

> 3. move delta into spark so the two projects are developed together

This sounds an interesting idea, but this may not be easy given that Delta Lake now is owned by Linux Foundation and there would be a lot of non technical work to merge it to an Apache project. In addition, Delta Lake as a separate project would allow us releasing Delta more frequently for users to use new features/bug fixes faster.

> 4. make more of the apis that delta uses in spark stable and/or public

This is the same as point 1?

Given we don't have action items right now for this, I'm closing the issue. Feel free to re-open this if you have any better suggestions!
