### ISSUE TITLE
Clarity on multiple Spark Contexts vs Spark drivers on S3

### ISSUE THREAD

**Issue by ReubenTheDS** [delta-io/delta#564]
Quotes from the [Delta Lake on Amazon S3 doc ](https://docs.delta.io/latest/delta-storage.html#amazon-s3)
1) _Delta Lake supports concurrent reads from multiple clusters, but concurrent writes to S3 must originate from a single Spark driver in order for Delta Lake to provide transactional guarantees_
2) _Concurrent writes to the same Delta table from multiple Spark drivers can lead to data loss._

Background:
Scenario 1: 
2 or more users might connect to a Spark(Standalone or Yarn) cluster running remotely using [sparkmagic](https://github.com/jupyter-incubator/sparkmagic) & [Apache Livy](https://livy.apache.org/) & write to the same DeltaLake table. (Apache Livy provides functionality for sharing SparkContexts between users.)
Scenario 2:
2 or more scheduled (long-running) Spark jobs might write to the same Delta Lake table

Questions:
1) In both these scenarios, are we looking at the possibility of data loss? If yes, is that solved by having just 1 SparkContext **always** running, using Livy to share that context & & then writing to the (same) Delta Lake?
2) Or, does the referenced doc mean we could have problems when 2 Spark clusters, say 1 of them running at  
spark://172.31.1.88:7077    & the other running at    spark://3.5.11.2:7077    happen to write to the same Delta Lake table **at the same time**
3) Isn't the point of multiple Spark Contexts in a single JVM moot, since it is anyway discouraged, and only for running intrinsic Spark tests?

**Comment by borislitvak** [comment]
I have additional questions: 
1. With AWS announcement on S3 consistency, does this relax the requirements in any way?
2. Is a compaction process, namely df.write.option("dataChange", "false"), considered a write? Can we do compaction from a different spark driver?

**Comment by ReubenTheDS** [comment]
@tdas and @rahulsmahadev apologies in advance for directly tagging you. Can you please provide guidance on the queries?

**Comment by zsxwing** [comment]
> * In both these scenarios, are we looking at the possibility of data loss? If yes, is that solved by having just 1 SparkContext **always** running, using Livy to share that context & & then writing to the (same) Delta Lake?

Yep as long as you can ensure there are not multiple JVMs writing to the same Delta table.

> 2\. Or, does the referenced doc mean we could have problems when 2 Spark clusters, say 1 of them running at
>     spark://172.31.1.88:7077    & the other running at    spark://3.5.11.2:7077    happen to write to the same Delta Lake table **at the same time**

You may hit data loss issue in this scenario.


> 3\. Isn't the point of multiple Spark Contexts in a single JVM moot, since it is anyway discouraged, and only for running intrinsic Spark tests?

Multiple active Spark Contexts in a single JVM is not supported Spark since 3.0. You can still stop an active SparkContext and start a new one as long as you can ensure they are not active at the same time.

**Comment by zsxwing** [comment]
> * With AWS announcement on S3 consistency, does this relax the requirements in any way? https://aws.amazon.com/blogs/aws/amazon-s3-update-strong-read-after-write-consistency/

Yep. Currently we combine the results from S3 and the local cache. It means we can trust the S3 result and we can remove this method: https://github.com/delta-io/delta/blob/v0.7.0/src/main/scala/org/apache/spark/sql/delta/storage/S3SingleDriverLogStore.scala#L94

But S3 still doesn't support `putIfAbsent` so we still need to use `S3SingleDriverLogStore`.

> 2\. Is a compaction process, namely df.write.option("dataChange", "false"), considered a write? Can we do compaction from a different spark driver?

It's considered a write.

**Comment by ReubenTheDS** [comment]
> > * In both these scenarios, are we looking at the possibility of data loss? If yes, is that solved by having just 1 SparkContext **always** running, using Livy to share that context & & then writing to the (same) Delta Lake?
> 
> Yep as long as you can ensure there are not multiple JVMs writing to the same Delta table.
> 
> > 2. Or, does the referenced doc mean we could have problems when 2 Spark clusters, say 1 of them running at
> > spark://172.31.1.88:7077    & the other running at    spark://3.5.11.2:7077    happen to write to the same Delta Lake table **at the same time**
> 
> You may hit data loss issue in this scenario.
> 
> > 3. Isn't the point of multiple Spark Contexts in a single JVM moot, since it is anyway discouraged, and only for running intrinsic Spark tests?
> 
> Multiple active Spark Contexts in a single JVM is not supported Spark since 3.0. You can still stop an active SparkContext and start a new one as long as you can ensure they are not active at the same time.

Thank you for the clarifications!
