### ISSUE TITLE
some errors in Docs

### ISSUE THREAD

**Issue by monkeyboy123** [delta-io/delta#576]
in the [doc](https://docs.delta.io/0.7.0/delta-utility.html#describe-detail)
```
DESCRIBE DETAIL '/data/events/'

DESCRIBE HISTORY delta.`/data/events/`

DESCRIBE HISTORY eventsTable
```
mybe it should like this:
```
DESCRIBE DETAIL '/data/events/'

DESCRIBE DETAIL delta.`/data/events/`

DESCRIBE DETAIL eventsTable
```

**Comment by zsxwing** [comment]
Good catch. Will update it soon.

**Comment by nkarpov** [comment]
Was addressed a while ago https://docs.delta.io/latest/delta-utility.html#retrieve-delta-table-details

Closing
