### ISSUE TITLE
Simplify Redshift Spectrum docs

### ISSUE THREAD

**Issue by groodt** [delta-io/delta#578]
I am unable to find the source code that generates the online documentation here:
https://docs.delta.io/latest/redshift-spectrum-integration.html

The docs should be updated now that Redshift Spectrum supports Delta format (SymlinkTextInputFormat):
https://docs.aws.amazon.com/redshift/latest/dg/c-spectrum-external-tables.html

The approach for Athena and Spectrum are then broadly the same. There is no need for the extra View using SymlinkTextInputFormat.

**Comment by zsxwing** [comment]
Thanks for the new information. We will update our doc.

**Comment by gpongracz** [comment]
Here is the direct link to the integration:
https://docs.aws.amazon.com/redshift/latest/dg/c-spectrum-external-tables.html

**Comment by vkorukanti** [comment]
@groodt Docs are updated. Let us know if anything else is missing.
