### ISSUE TITLE
Question: Why is delta requiring so much off-heap memory?

### ISSUE THREAD

**Issue by walmaaoui** [delta-io/delta#586]
Hello, after writing my dataset, the jobs fails while delta metadata processing.

- Env: Dataproc
- Delta-lake version: 0.6.1
- Executor-Memory: 11G (memory-overhead 1,1G)
- Executor-cores: 4 
- yarn.nodemanager.vmem-check-enabled = false
 
<img width="1427" alt="Screenshot 2021-01-26 at 12 21 51" src="https://user-images.githubusercontent.com/43953326/105839154-598abc00-5fd1-11eb-887e-e82e3df006f9.png">

My questions: 
- Any recommandations for the value of `spark.yarn.executor.memoryOverhead` ?
- Is this normal? Are you aware of similar problems?

Thanks you in Advance

**Comment by zsxwing** [comment]
This is a Spark issue rather than a Delta issue. I'd say 1.1G seems too small considering the native memory used by Netty (Spark uses this network library) and JVM. I suggest to try to increase the memory overhead to 2G or 3G.

In addition, could you check if you enable `spark.memory.offHeap.enabled`? If so, I suggest to disable it.

**Comment by walmaaoui** [comment]
ok thank you for your quick response!

I though about delta, since the main job treats much more data and do complex logic and there were no problems. The problem occurs only on the commit phase of delta. Yes with 2GB of memory overhead it passed.

`spark.memory.offHeap.enabled` is disabled.

I wanted just to know if there are any off-heap special usage in delta.

**Comment by zsxwing** [comment]
@walmaaoui Delta doesn't use any off-heap memory itself. One different thing than parquet is Delta needs to load its transaction logs. If your table is large, loading the transaction logs may consume significant of the heap memory and cause the container pass the physical memory limit.

**Comment by walmaaoui** [comment]
Ok! thank you for your reactivity :) 

I close the issue so.
