### ISSUE TITLE
Feature Request - Drop Columns

### ISSUE THREAD

**Issue by kristofve** [delta-io/delta#589]
Currently, Delta Lake doesn't seem to support dropping columns without loading the entire dataset into Spark, dropping the columns from the DataFrame and overwriting the original table. If I correctly understand the way the transaction log works, it seems like it could support such a statement by making certain columns unavailable and altering the schema from the drop commit onwards.

Especially in combination with shallow cloning on Databricks (which is a brilliant feature, by the way) this could lead to big efficiency gains, for example when you want to do some dimensional modeling on a shallow clone of a (very denormalized) source table, where you replace multiple columns with one reference ID column without touching the original data.

**Comment by tdas** [comment]
This has been added to current master. cc @vkorukanti

**Comment by vkorukanti** [comment]
This is implemented in 58b25108e1e275fa7e2ff4ba758184a19270cf15

**Comment by MrPowers** [comment]
This [blog post](https://delta.io/blog/2022-08-29-delta-lake-drop-column/) explains how to drop columns in Delta Lake if you'd like more details.
