### ISSUE TITLE
Too frequently delta log scans.

### ISSUE THREAD

**Issue by xianyinxin** [delta-io/delta#59]
We observed delta logs are scanned many times during the running of a SQL, which submits too many small queries to spark. The main query was even been blocked by waiting for the scheduler being ready. We'd better make the metadata processing (or get current snapshot) more efficient.

**Comment by marmbrus** [comment]
How many executor slots does your cluster have?  The snapshot should be cached after the first read, so I would expect most of these log queries to be very fast (for real tables often faster than listing the files in the table). If you have a small cluster / table you might consider decreasing the number of snapshot partitions using the config `spark.databricks.delta.snapshotPartitions`.

**Comment by xianyinxin** [comment]
Thanks, @marmbrus , very valuable comments. Indeed, the scheduler blocking was on local mode which make the situation worse. However, on my 18 nodes cluster, I found about 70% queries were such log queries, all of them were very fast, but the amount is huge. I guess this would also bring pressure on the scheduler.

And as my investigation, the log scans originate from, 1, when the relation was resolved, where the DeltaLog is instanced, and 2, the `TahoeLogFileIndex#listFiles` was called. The second part would save time compared to listFiles from HDFS, but the first part would make the plan analyzation time long?

Pls correct me if I'm wrong.

**Comment by marmbrus** [comment]
I would expect 1 log query for every real query. Scanning / filtering the log is done each time the table is read. In our internal benchmark (TPC-DS and others) this cost is comparable to the work required to list files or contact the metastore (including any extra scheduler work).

The first one you see when the relation is resolved is likely the most expensive one.  This query is caching a snapshot of the table for all future queries. This will only happen when the table changes, so generally does not affect the time required for analysis.

**Comment by xianyinxin** [comment]
Close it temporarily.  Will investigate it more and reopen if necessary.
