### ISSUE TITLE
feature request : update and delete in streaming mode

### ISSUE THREAD

**Issue by xmehaut** [delta-io/delta#591]
Hello,
up to now as I understand , streaming on delta table doesn't permit update and delete merges, only append ones.
It could be interesting to be able to update and delete rows too.  My use case is the following ; I've debezium which sends cdc in kafka ; I would like to stream kafka and update continuously my delta table. 
It is possible with Matereialize (https://materialize.com/materialize-under-the-hood/). for instance.

Regards
xavier

**Comment by NidhalSAADAOUI** [comment]
Hello,
interesting use case ! We faced the same issue and this is how we solved it using [Delta Streams](https://databeans-blogs.medium.com/simplify-your-streaming-cdc-architecture-using-delta-streams-a61c2ae4543e)

**Comment by carasue** [comment]
but how u deal with the missing of delete changes

________________________________
发件人: Nidhal SAADAOUI <notifications@github.com>
发送时间: Saturday, February 6, 2021 10:26:12 PM
收件人: delta-io/delta <delta@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [delta-io/delta] feature request : update and delete in streaming mode (#591)


Hello,
interesting use case ! We faced the same issue and this is how we solved it using Delta Streams<https://databeans-blogs.medium.com/simplify-your-streaming-cdc-architecture-using-delta-streams-a61c2ae4543e>

―

**Comment by NidhalSAADAOUI** [comment]
@carasue i didn't get you question, could you explain more.

**Comment by xmehaut** [comment]
Thanks Nidhal. Where can we find the delta streams project?
Regards

Envoyé de mon iPhone

**Comment by nkarpov** [comment]
@xmehaut this is now possible with change data feed as part of Delta 2.0

https://docs.delta.io/latest/delta-change-data-feed.html
https://github.com/delta-io/delta/issues/1105

Closing
