### ISSUE TITLE
Slack: This link is no longer active

### ISSUE THREAD

**Issue by ahuret** [delta-io/delta#597]
Hi ! 

The delta lake Slack link [Register here](https://delta-users.slack.com/join/shared_invite/zt-auesqgi8-~Euf18vybLdQkFCaSDjJ9Q#/) (found [here](https://github.com/delta-io/delta#community)) is "no longer active".
Is it replaced by another one ? If so, what is the new link ?
Thank you :)

**Comment by zsxwing** [comment]
Thanks! The slack link has been fixed. Closing this.
