### ISSUE TITLE
Issue after apgrade to delta 0.8 : java.io.InvalidClassException

### ISSUE THREAD

**Issue by xhuyvn** [delta-io/delta#604]
Hi.
I got error to read delta table after upgrade from 0.7 to 0.8.
I had upgrade pyspark3.0.2, spark 3.0.2, and I got this :
_java.io.InvalidClassException: org.apache.spark.broadcast.TorrentBroadcast; local class incompatible: stream classdesc serialVersionUID = 3291767831129286585, local class serialVersionUID = 4804550167553929379
org.apache.spark.broadcast.TorrentBroadcast; local class incompatible: stream classdesc serialVersionUID = 3291767831129286585, local class serialVersionUID = 4804550167553929379_

Here my code, this code work fine with 0.7 version.

`spark = SparkSession.builder.appName("loadata") \
    .master("spark://localhost:7077") \
    .config("spark.jars.packages", "io.delta:delta-core_2.12:0.8.0") \
    .config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension") \
    .config("spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog") \
    .config("spark.sql.mapKeyDedupPolicy", "LAST_WIN") \
    .config("spark.sql.execution.arrow.pyspark.enable", "true") \
    .config("spark.sql.execution.arrow.pyspark.fallback.enabled", "true") \
    .config("spark.executor.memory", "2g") \
    .config("spark.executor.cores", "2") \
    .enableHiveSupport() \
    .getOrCreate()

spark.sql("select count(*) from testable").show()`

**Comment by zsxwing** [comment]
Could you explain a little bit about your spark Cluster? Are you using the standalone mode? This sounds like you were using a standalone mode but the cluster version and the driver version was not the same.

**Comment by xhuyvn** [comment]
> Could you explain a little bit about your spark cluster? Are you using the standalone mode? This sounds like you were using a standalone mode but the cluster version and the driver version was not the same.

Hi @zsxwing

Thank you for your reply, I have solved the problem. I forgot to copy the MySQL connector jar file to spark_home/jars.
I had created a folder to store all jar driver files like MySQL, SqlServer, Kafka.... add it to spark-defaults.conf for easy upgrade.
