### ISSUE TITLE
delta schema is not campatible with Hive

### ISSUE THREAD

**Issue by jiaorenyu** [delta-io/delta#609]
spark version:3.0.1
hive version: 2.3.7
delta version: 0.7.0

I test this refer: https://docs.delta.io/latest/delta-batch.html#create-a-table

config:
```
spark.sql.extensions	io.delta.sql.DeltaSparkSessionExtension	
spark.sql.catalog.spark_catalog	org.apache.spark.sql.delta.catalog.DeltaCatalog
```

I create a delta table with spark sql below:

```
CREATE  TABLE default.sales_1 (
  id STRING,
  brand STRING,  
  name STRING,   
  phone STRING,
  date_id STRING
) USING delta
PARTITIONED BY (date_id)
LOCATION 'hdfs://adhnamenode/path/to/sales_delta'
```

Then I execute a hive sql on beeline: 
```
show create table sales_1
```

It shows below which is not right.

```
+----------------------------------------------------+
|                   createtab_stmt                   |
+----------------------------------------------------+
| CREATE EXTERNAL TABLE `sales_1`(                   |
|   `col` array<string> COMMENT 'from deserializer') |
| ROW FORMAT SERDE                                   |
|   'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe'  |
| WITH SERDEPROPERTIES (                             |
|   'path'='hdfs://adhnamenode/path/to/sales_delta')  |
| STORED AS INPUTFORMAT                              |
|   'org.apache.hadoop.mapred.SequenceFileInputFormat'  |
| OUTPUTFORMAT                                       |
|   'org.apache.hadoop.hive.ql.io.HiveSequenceFileOutputFormat' |
| LOCATION                                           |
|   'hdfs://adhnamenode/withwinds/hive/warehouse/sales_1-__PLACEHOLDER__' |
| TBLPROPERTIES (                                    |
|   'spark.sql.create.version'='3.0.1',              |
|   'spark.sql.partitionProvider'='catalog',         |
|   'spark.sql.sources.provider'='delta',            |
|   'spark.sql.sources.schema.numParts'='1',         |
|   'spark.sql.sources.schema.part.0'='{"type":"struct","fields":[]}',  |
|   'transient_lastDdlTime'='1612495665')            |
+----------------------------------------------------+
```

Any suggestion?

**Comment by zsxwing** [comment]
@jiaorenyu you need to use https://github.com/delta-io/connectors to create a table in order to access it in Hive.

**Comment by jiaorenyu** [comment]
> @jiaorenyu you need to use https://github.com/delta-io/connectors to create a table in order to access it in Hive.

I write a delta table to hive with the new feature of delta: 

[way to create a table](https://docs.delta.io/latest/delta-batch.html#create-a-table)

So， what is the relationship between  https://github.com/delta-io/connectors  and this way?

**Comment by zsxwing** [comment]
@jiaorenyu if you use Spark to read the table, you need to use [delta-core](https://docs.delta.io/latest/delta-batch.html#create-a-table) to create the table. If you use Hive to read the table, you need to use https://github.com/delta-io/connectors to create the table.

**Comment by tdas** [comment]
Closing the issue. please reopen if this is still an  issue.
