### ISSUE TITLE
I receive the error “Cannot time travel Delta table to version X” whereas I can see the version X when looking at the history

### ISSUE THREAD

**Issue by NastasiaSaby** [delta-io/delta#616]
I have a table in delta lake which has these tblproperties: 
![image](https://user-images.githubusercontent.com/8245071/110609530-98459180-818d-11eb-8cd5-a18cef24f3e7.png)

I'm trying to access a version which was there last month, the 322.

When I look at the history, I can see it:

![image](https://user-images.githubusercontent.com/8245071/110609509-924fb080-818d-11eb-9f58-7f79bb6fdcd6.png)

But when I try to access it with such a command:

```
spark.read.format("delta").option("versionAsOf", 322).load(path)
```

I receive this error:

```
AnalysisException: Cannot time travel Delta table to version 322. Available versions: [330, 341].;
I can't understand the problem. I think that it might be an issue.
```

I'm using the Azure Databricks platform: 7.3 LTS ML, Spark 3.0.1, Scala 2.12.
Then I think the version of DeltaLake (according to the documentation) is  0.7.0.

Thank you for your help.

**Comment by tdas** [comment]
This is the expected behavior. Now all the versions that are visible in the history will be queryable. We maintain metadata history of the previous operations a lot longer than the actual data. Whether the data will be visible or not will be determined by the retention in the Vacuum command. So log history is controlled by the log retention confs, but data history is controlled by Vacuum command params.

**Comment by NastasiaSaby** [comment]
Thank you for your answer @tdas. I'm not sure to understand. We didn't launch any vaccum command. And I've just seen in the documentation that "Azure Databricks does not automatically trigger VACUUM operations on Delta tables" (https://docs.microsoft.com/en-us/azure/databricks/spark/latest/spark-sql/language-manual/delta-vacuum). Then, I don't understand why I'm not able to get an older version.

**Comment by JassAbidi** [comment]
@NastasiaSaby Vacuum command is not triggered automatically on the table. Users need to run it and specify a retention period for it ( the default retention period is 7 days). Only the Metadata Cleanup is triggered automatically after each checkpoint. 
@tdas seems like this is related to this [bug](https://github.com/delta-io/delta/issues/255). I quickly checked the code and I see that it's cleaning all the commit files before the last checkpoint. This way the time travel is only possible to versions before the last checkpoint right ?

**Comment by NastasiaSaby** [comment]
Thank you very much for your answers.

It could be linked to the bug you speak about @JassAbidi. I'm using Azure Databricks 7.3 LTS ML. Twice a day, we write new data in the folder. Again, we don't run any vacuum command. This morning, I discovered that now, we can only access: the versions from 340 to 352.
I'm surprised. Is it a bug/expected behaviour that others are facing or am I the only one who wants to restore a version older than 1 month? 

@tdas Is there a workaround? Thank you for your help?

**Comment by JassAbidi** [comment]
@NastasiaSaby, I don't think it's a bug but it's the metadata cleanup behavior that is not ideal. As a workaround, you can increase the log retention duration (should be safe since you are writing twice per day to the delta table).

**Comment by NastasiaSaby** [comment]
@JassAbidi Thank you very much for your help! I have already increased the log retention duration using:

```
ALTER TABLE delta.`{table_path}`
            SET TBLPROPERTIES (
                delta.logRetentionDuration = '{nb_days} days',
                delta.deletedFileRetentionDuration = '{nb_days} days'
            )
```

I have set 365 days. Isn't supposed to be enough as a workaround?

**Comment by JassAbidi** [comment]
hmm, yes it is. what's your checkpoint interval conf ? what's the min .json file and .checkpoint file you have in the _delta_log ?

**Comment by NastasiaSaby** [comment]
The min .json file I have is 309. I haven't changed the checkpoint interval conf. Then, I guess it's 10. I have one checkpoint for the 350 version and one for the 340 version. That's all. 
As a process is launched twice a day to write data, now I can load the versions from 340 and 356. Then something is removing my data :(.

```
Available versions: [340, 356]
```

I really appreciate your help.

**Comment by NastasiaSaby** [comment]
Hello @tdas and @JassAbidi, thank for your help. I noticed that I have only 2 checkpoints files in my folder. Every 10 commits, a new checkpoint is created and the older one is removed. 
For instance this morning, I had 2 checkpoints: 340 and 350. I was available to time travel from 340 to 359.
Now, after a "write" action, I have 2 checkpoints: 350 and 360. I'm now able to time travel from 350 to 360.

What can remove the old checkpoints?

**Comment by NastasiaSaby** [comment]
A person from Databricks gave me a workaround: set delta.checkpointRetentionDuration to X days. That will keep your checkpoints enough longer to have access to older versions.

Then, you must launch something like that in your delta table:

spark.sql(        f"""
        ALTER TABLE delta.`path`
            SET TBLPROPERTIES (
                delta.logRetentionDuration = 'interval X days',
                delta.deletedFileRetentionDuration = 'interval X days',
                delta.checkpointRetentionDuration = 'X days'
            )
        """
)
It will keep your versions until X days.

**Comment by magrathj** [comment]
@NastasiaSaby  thanks for posting the workaround - facing a similar issue

**Comment by zsxwing** [comment]
Closing this. This is expected and increasing the checkpoint retention is the right solution.

**Comment by Stefanos-Arampatzis** [comment]
Hi,
I would like to ask a couple of questions, thus I reopen the topic:
1. Increasing the **retention interval** means that we can access older versions? Or is starts working for the upcoming versioned data?
2. e.g. In Nastasia's case how can we still get the data from version 300 (Available versions: [340, 356])

Thanks in advance :)

**Comment by combinatorist** [comment]
I was sold on delta on the promise that I could "always go back". But, this issue and the responses lowers my confidence. Will I have to modify default configurations (e.g. for log retention) in order to realize the original promise of delta lake?

Why isn't infinite log retention just the default? I thought this was the point of cheap storage like S3.

**Comment by scottsand-db** [comment]
Hi @combinatorist, thanks for your comment.

I assure you, Delta Lake never intended to mislead you. If you want infinite log retention, you can enable it on your table by setting the `delta.logRetentionDuration` table property. Does this solve your problem?

We landed on the default log retention of 30 days due to years of valuable user feedback(and, yours is another data point we will add to the equation!) who want to balance storage costs with time travel availability.

**Comment by asen-git** [comment]
Hi,

We’re facing a similar issue with some Delta tables. After increasing the file and log retention periods to 450 days at the table level, we started seeing these errors. The affected range shifts after a few new commits.

We tried updating the checkpoint retention period as suggested by @NastasiaSaby, but this doesn’t let us time travel beyond the last available version mentioned in the error.

@NastasiaSaby, could you clarify if you were able to query older files after this change, or does it only prevent the issue going forward?

<img width="1012" height="30" alt="Image" src="https://github.com/user-attachments/assets/c367968c-4d38-468a-9b11-4c1dd5a2f3d5" />

P.S. - The problem became frequent post changing the default values (7 & 30) of the TableLevel Properties. We haven't run any vacuum statements in the recent past & can physically see & read the poast parquet & json logs from the actual folder location.

**Comment by ghata-saraiya** [comment]
Hi, we’re seeing a similar issue. Our table has delta.logRetentionDuration set to 90 days, and after the first checkpoint was created at version 10, none of the earlier versions are time-travel readable anymore. We haven’t run VACUUM, and we can still physically see (and read) the older .json and .crc files under _delta_log/ in S3.

@asen-git  — were you able to find a resolution or workaround for this?
