### ISSUE TITLE
FeatureAsk: are there plans to support PRODUCING Change Data Capture from Delta Tables?

### ISSUE THREAD

**Issue by SreeramGarlapati** [delta-io/delta#621]
I am aware of a Solution that we can build on top of DeltaLake - proposed here: https://www.youtube.com/watch?v=7y0AAQ6qX5w

But, given that, generally speaking, emitting change data capture is a storage level feature - is there a plan to support this?

**Comment by rahulsmahadev** [comment]
Hi @SreeramGarlapati , we are currently working on it and it is available for preview on Databricks, we will eventually open source it once it is stable.

**Comment by SreeramGarlapati** [comment]
good to hear that. thanks a lot for the response @rahulsmahadev 
are there connectors/sinks available to firehose cdc into - for ex: Kafka?
is there a place - where I can learn more about this? I couldn't locate it in the engine documentation: https://docs.databricks.com/delta/index.html
truly appreciate any help!

**Comment by rahulsmahadev** [comment]
We do not have documentation on this yet on the Delta docs or on the Databricks docs as it a feature in preview. To answer your question about the sinks for CDC. The output is a DataFrame and regular Spark connectors can be used to write that DataFrame.

**Comment by jaceklaskowski** [comment]
Hi,

I've just found out about a brand new AddCDCFile action which seems a part
of the feature (and unused in 0.8.0).

https://github.com/delta-io/delta/blob/b9cb93e5c53605c6d2067f122fd0a033f13b6d07/src/main/scala/org/apache/spark/sql/delta/actions/actions.scala#L292-L305

Pozdrawiam,
Jacek Laskowski
----
https://about.me/JacekLaskowski
"The Internals Of" Online Books <https://books.japila.pl/>
Follow me on https://twitter.com/jaceklaskowski

<https://twitter.com/jaceklaskowski>
