### ISSUE TITLE
Add getOrCreate for deltatable API

### ISSUE THREAD

**Issue by gdoron** [delta-io/delta#624]
When creating a new job that requires a merge function from the second run forward, I need to use this kind of code:

    if DeltaTable.isDeltaTable(spark, OUTPUT_PATH):
        deltaTable = DeltaTable.forPath(spark, OUTPUT_PATH)
        merge_join_condition = ' ... not important ...'
        (
            deltaTable.alias("old").merge(
                df.alias("new"),
                merge_join_condition)
            .whenMatchedUpdateAll()
            .whenNotMatchedInsertAll()
            .execute()
        )
    else:
        df.write.format('delta').partitionBy('year', 'month', 'day').save(OUTPUT_PATH)

It would be nice if we could have something like:

    deltaTable = DeltaTable.getOrCreate(spark, OUTPUT_PATH, 'year', 'month', 'day') # partition column
    merge_join_condition = ' ... not important ...'
    (
        deltaTable.alias("old").merge(
            df.alias("new"),
            merge_join_condition)
        .whenMatchedUpdateAll()
        .whenNotMatchedInsertAll()
        .execute() # Here write or create the table using the partition columns above.
    )

What do you think?
Doron

**Comment by zsxwing** [comment]
@gdoron Yep, this would be useful. How about calling it `createIfNotExists` to be consistent with SQL CREATE TABLE IF NOT EXISTS statement?

We are working on a table creation Scala/Python API right now for [Generated Columns](https://github.com/delta-io/delta/commit/30c8939415b8904f54cc4625e77cf147aed9bda1) feature. Definitely will add this to the table creation API.

**Comment by tdas** [comment]
This has been added to the Delta 1.0 release. Please checkout https://github.com/delta-io/delta/releases/tag/v1.0.0
Closing this issue. Please reopen if this does not satisfy the requirements.
