### ISSUE TITLE
delta-io AWS S3 consistency  

### ISSUE THREAD

**Issue by emanuelh-cloud** [delta-io/delta#645]
It is defined in the documentation that "Concurrent writes to the same Delta table from multiple Spark drivers can lead to data loss." in the https://docs.delta.io/latest/delta-storage.html#id13
Was this changed after the AWS S3 became "strongly consistent" ? see the AWS doc reference below
https://aws.amazon.com/blogs/aws/amazon-s3-update-strong-read-after-write-consistency/

**Comment by zsxwing** [comment]
No, it's not changed. S3 still doesn't provide the mutual exclusion. Here are the requirements for the storage:

1. Atomic visibility: There must be a way for a file to be visible in its entirety or not visible at all.
2. Mutual exclusion: Only one writer must be able to create (or rename) a file at the final destination.
3. Consistent listing: Once a file has been written in a directory, all future listings for that directory must return that file.

S3 meets 1 and 3 now. But 2 is still missing.

**Comment by emanuelh-cloud** [comment]
Using EMRFS from a single cluster but different drivers (spark jobs) should meets 1,2 and 3. Correct?  Thanks

**Comment by zsxwing** [comment]
I'm not familiar with EMRFS. But from [this page ](https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-fs.html):

```
If you turn on Spark speculative execution and write data to Amazon S3 using EMRFS direct write, you may experience intermittent data loss. When you write data to HDFS, or write data in Parquet using the EMRFS S3-optimized committer, Amazon EMR does not use direct write and this issue does not occur.

If you need to write data in formats that use EMRFS direct write from Spark to Amazon S3 and use speculative execution, we recommend writing to HDFS and then transferring output files to Amazon S3 using S3DistCP.
```

I feel it doesn't meet 2. Spark speculative execution requires mutual exclusion as well.

**Comment by emanuelh-cloud** [comment]
Thank you @zsxwing  for you answer.
My use case is that I have one spark job that inserting and updating delta-io partitioned table on AWS s3 using AWS EMR.
And additional spark job that compacting the partition table "old" partition using delta OVERWRITE.replaceWhere and dataChange=false.  Do I need "Mutual exclusion" in my use case? 
Thank you for the help.

**Comment by tdas** [comment]
Each delta table has a SINGLE transaction log with a linear history, and no matter what partitions you are updating, all write operations need write to that one transaction log. To avoid breaking the linear history of the log, the log must be updated with mutual exclusion. So even if you are writing to disjoint partitions, you need mutual exclusion to update the log.

**Comment by emanuelh-cloud** [comment]
Thank you @tdas  for you replay. 
I do understand that the _delta_log folder is one for the whole table.

My point is that if the two spark jobs updating the same table, the first job adding the data and the second job is compacting the data (replacing the small files with bigger files for the table) using OVERWRITE and dataChange=false,
NO data will be lost if the compaction job will override the "adding data" job commit json log file and vise versa. 
Am I correct?
