### ISSUE TITLE
Public LogStore API

### ISSUE THREAD

**Issue by zsxwing** [delta-io/delta#646]
LogStore is designed to be extended by developers for storage systems. But it's currently in a private package. We should make it become a public API.

In addition, currently the user can only set one LogStore class for the entire application. It's pretty common that an application may need to access multiple storages and we should improve the LogStore configuration to support specifying LogStore class for each storage.

**Comment by ioanluca** [comment]
This sounds great! Will this also decouple the `LogStore` API from the file system interface? What I mean is, will it be possible to implement a `LogStore` that stores the Delta log files in something other than `.json` and `checkpoint.parquet` files? For example,  in a Database?

**Comment by zsxwing** [comment]
@ioanluca Even if we decoupled LogStore from the file system interface, many places in Delta would still couple with the file system interface currently. For example, when we read the log files to create a table Snapshot, we will use Spark's file format APIs to read these files. In addition, `.json` and `checkpoint.parquet` files can be very large, and database is probably not a proper system to host the content.

Could you explain a bit why you would like to decouple the Delta transaction logs from file system interface?

**Comment by ioanluca** [comment]
That makes sense - thanks for the explanation! 

The Delta log json files are fairly small and in a world like HDFS where small files can become a problem, perhaps storing the information of the `json` and `checkpoint.parquet` files in some other storage system would be desirable.

**Comment by jaceklaskowski** [comment]
Just to add a rather important feature of Delta Lake = it's a [HadoopFsRelation](https://github.com/delta-io/delta/blob/1f7a911cbef12e1e964e2940e92f028b2b67029f/src/main/scala/org/apache/spark/sql/delta/DeltaLog.scala#L352
) after all and among the features is to know what files are loaded which is crucial for [state reconstruction](https://github.com/delta-io/delta/blob/9e3a44df8b313ae9dc981e462e58ad6d2c55604a/src/main/scala/org/apache/spark/sql/delta/Snapshot.scala#L102). That makes Delta Lake impossible as non-file-based IMHO.

**Comment by ioanluca** [comment]
Did not know that @jaceklaskowski. Cheers for pointing that one out.

**Comment by zsxwing** [comment]
This is done in https://github.com/delta-io/delta/commit/b7cb203dd23a9a225fbcc414bc075916bd32a817
