### ISSUE TITLE
It seems I have 76 failure

### ISSUE THREAD

**Issue by Azaretdodo** [delta-io/delta#65]
Hello,

I have 76 failure as the copy / paste :

**[info] Tests: succeeded 71, failed 76, canceled 0, ignored 0, pending 0
[info] *** 76 TESTS FAILED ***
[error] Failed tests:
[error]         org.apache.spark.sql.delta.DeltaRetentionSuite
[error]         org.apache.spark.sql.delta.DeltaTimeTravelSuite
[error]         org.apache.spark.sql.delta.LocalLogStoreSuite
[error]         org.apache.spark.sql.delta.AzureLogStoreSuite
[error]         org.apache.spark.sql.delta.HDFSLogStoreSuite
[error]         org.apache.spark.sql.delta.DeltaSinkSuite
[error]         org.apache.spark.sql.delta.DeltaLogSuite
[error]         org.apache.spark.sql.delta.DeltaSuite
[error]         org.apache.spark.sql.delta.DeltaSourceSuite
[error]         org.apache.spark.sql.delta.EvolvabilitySuite
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 409 s, completed 13 juin 2019 à 16:36:45
**

Thank you in advance to help me repair It failures,

Regards.

Dorian ROSSE.

**Comment by zsxwing** [comment]
@Azaretdodo What are the error messages in these failed tests? Looks like some environment issue since there are so many failed tests. Could you also provide the steps to reproduce these errors?

**Comment by Azaretdodo** [comment]
It was when I do the last command line which two options :

build/sbt test -deprecation -feature

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Shixiong Zhu <notifications@github.com>
Envoyé : Thursday, June 13, 2019 7:15:13 PM
À : delta-io/delta
Cc : Azaretdodo; Mention
Objet : Re: [delta-io/delta] It seems I have 76 failure (#65)


@Azaretdodo<https://github.com/Azaretdodo> What are the error messages in these failed tests? Looks like some environment issue since there are so many failed tests. Could you also provide the steps to reproduce these errors?

**Comment by zsxwing** [comment]
@Azaretdodo are you using Windows? Could you post the error stack trace?

**Comment by Azaretdodo** [comment]
I use Ubuntu server

what is the the error stack trace ?

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Shixiong Zhu <notifications@github.com>
Envoyé : Thursday, June 13, 2019 7:42:14 PM
À : delta-io/delta
Cc : Azaretdodo; Mention
Objet : Re: [delta-io/delta] It seems I have 76 failure (#65)


@Azaretdodo<https://github.com/Azaretdodo> are you using Windows? Could you post the error stack trace?

**Comment by zsxwing** [comment]
@Azaretdodo did the failed tests print something?

**Comment by Azaretdodo** [comment]
I have print the last of the command line which errors print by the end of the command line

I can say the window of the command line print a lot of red line type

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Shixiong Zhu <notifications@github.com>
Envoyé : Thursday, June 13, 2019 8:09:11 PM
À : delta-io/delta
Cc : Azaretdodo; Mention
Objet : Re: [delta-io/delta] It seems I have 76 failure (#65)


@Azaretdodo<https://github.com/Azaretdodo> did the failed tests print something?

**Comment by zsxwing** [comment]
> I can say the window of the command line print a lot of red line type

Could you also post them?

**Comment by Azaretdodo** [comment]
It take too moster time to spend time for It

The command line print a lot of red line which sometimes green line

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Shixiong Zhu <notifications@github.com>
Envoyé : Thursday, June 13, 2019 8:44:39 PM
À : delta-io/delta
Cc : Azaretdodo; Mention
Objet : Re: [delta-io/delta] It seems I have 76 failure (#65)


I can say the window of the command line print a lot of red line type

Could you also post them?

**Comment by Azaretdodo** [comment]
Just fo say :

I know the p2p.rules of snort

I think It rules hijacks yours bad Streams

I install the rules for noizy healthy

Thank you in advance to feel my secure setup

Regards.


Dorian ROSSE.

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Shixiong Zhu <notifications@github.com>
Envoyé : Thursday, June 13, 2019 8:44:39 PM
À : delta-io/delta
Cc : Azaretdodo; Mention
Objet : Re: [delta-io/delta] It seems I have 76 failure (#65)


I can say the window of the command line print a lot of red line type

Could you also post them?

**Comment by zsxwing** [comment]
Could you post those red lines?

**Comment by Azaretdodo** [comment]
I install freshly the Raid 1 system also I losen delta

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by Azaretdodo** [comment]
I have just to say on the fresher system I received gstream updates 😉

But I have too installed p2p snort rules 😉

Have a nice Week-end 😊

Regards.


Dorian ROSSE.

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Shixiong Zhu <notifications@github.com>
Envoyé : Friday, June 28, 2019 8:20:55 PM
À : delta-io/delta
Cc : Azaretdodo; Mention
Objet : Re: [delta-io/delta] It seems I have 76 failure (#65)


Closed #65<https://github.com/delta-io/delta/issues/65>.
