### ISSUE TITLE
Can I run VACCUM command while running data update job?

### ISSUE THREAD

**Issue by vinura** [delta-io/delta#657]
I am trying to evaluate Delta for our organisation. Is it possible to run the VACCUM command when there are active Data Engineering jobs happening on cluster? Do I need to wait till there are no jobs?

**Comment by jaceklaskowski** [comment]
Please use the [google group](https://groups.google.com/g/delta-users) or (better) [StackOverflow](https://stackoverflow.com/questions/tagged/delta-lake) for questions like yours.

**Comment by dennyglee** [comment]
Closing this issue per resolution in the email thread in google groups; please re-open if this is not correct. Thanks!
