### ISSUE TITLE
Symlink with delta.compatibility.symlinkFormatManifest.enabled=true

### ISSUE THREAD

**Issue by irisshainsky** [delta-io/delta#658]
I use delta lake 0.8.0 with spark structured streaming on spark 3.0.1, we write the delta lake both on s3 and google storage.
We query our tables in presto, therefore I created a table on our metastore pointing to the symlink folder on my delta table location, altered the table to  delta.compatibility.symlinkFormatManifest.enabled=true 
and run once a generate symlink. as described here: https://docs.databricks.com/delta/presto-integration.html.

I expected that each time the structured streaming cycle is done I will have all the partitions manifests under the symlink folder.

what happens is that in each structured streaming cycle it overrides all the partitions with the partitions that exist in the current stream input.
We are implementing a CDC with structured streaming and delta lake as described here:
https://delta.io/blog-gallery/simplifying-change-data-capture-with-databricks-delta/

In the final table, the one that the symlink are defined on I write into the delta table in overwrite mode but my spark is configured with spark.sql.sources.partitionOverwriteMode=dynamic, I would expect delta table to treat the symlinks  partitions in the same way spark does when writing data in Override mode with spark.sql.sources.partitionOverwriteMode=dynamic (updating only the partitions in the batch without touching other partitions. 
It happens on AWS & google cloud storage
Thanks

**Comment by christophergrant** [comment]
The reason that the table is overwritten is because Delta Lake does not currently support dynamic partition overwrites.

A better way to accomplish this could be to use MERGE, see more details here: [https://databricks.com/blog/2019/03/19/efficient-upserts-into-data-lakes-databricks-delta.html](https://databricks.com/blog/2019/03/19/efficient-upserts-into-data-lakes-databricks-delta.html), particularly **Updating session information from streaming pipelines** should be helpful.

**Comment by dennyglee** [comment]
In addition to @christophergrant callout, note that the blog is referring to an older way of doing CDC with an older version of Delta.   A more recent one would be [Using Delta as a Change Data Capture Source](https://youtu.be/7y0AAQ6qX5w).

**Comment by irisshainsky** [comment]
df.write
  .format("delta")
  .mode("overwrite")
  .option("replaceWhere", "date >= '2017-01-01' AND date <= '2017-01-31'")
  .save("/delta/events")

the "replaceWhere" option solves this

**Comment by tdas** [comment]
Closing this issue for now. Please reopen if the question has not been answered
