### ISSUE TITLE
Spark hive tables mapped to delta lake tables shows no columns

### ISSUE THREAD

**Issue by jevvz** [delta-io/delta#662]
With Apache Spark you can create a hive table and map it to a delta lake table. You can read (SELECT) and write (INSERT) to the table. Executing a DESCRIBE TABLE table_identifier statement returns metadata information, but if you query a statement like SHOW COLUMNS table_identifier it shows no columns.

BI tools connect with the STS (Spark Thrift Server) which uses hive tables and not showing columns has problems with not loading tables because of error messages like: "table has no visible columns and cannot be queried".

This has been tested with Spark 3.0.1 and the Delta Lake package "delta-core_2.12-0.8.0".

**Comment by dennyglee** [comment]
What is your current setup out of curiosity?  It appears that `SHOW COLUMNS IN <table_identifier>` works but perhaps my configuration is different.

**Comment by jevvz** [comment]
I had my doubts there could be a problem with the metastore or Delta Lake package so I tried this with different setups (all in standalone mode).

Apache Spark:

spark-3.0.1-bin-hadoop2.7

Delta Lake:

delta-core_2.12-0.8.0
delta-core_2.12-0.7.0

Metastore:

Embedded Derby
MySQL 8.0.15 (Production)
MariaDB 5.5.68

Tested the proposed interactively setups for Spark (docs.delta.io) and copied the downloaded delta package inside the Spark jars path.

Any setup simply testing with spark-sql shell or beeline I can create a delta table, query data like SELECT * FROM table_identifier but a SHOW COLUMNS IN table_identifier shows no columns.

**Comment by jevvz** [comment]
What's the Spark (with/without hadoop) version you're testing?  Does it use the builtin Hive metastore or an external Hive with a superior version (3.0.0/3.1.2)?

I also tested the latest version spark-3.1.1-bin-hadoop3.2 with the same configuration and it gives me an exception when I execute the statement SHOW COLUMNS in table_identifier which didn't show in the previous version "spark-3.0.1-bin-hadoop2.7" I tested. This is the exception:

Error: org.apache.hive.service.cli.HiveSQLException: Error running query: org.apache.spark.sql.AnalysisException: SHOW COLUMNS is not supported for v2 tables.
at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.org$apache$spark$sql$hive$thriftserver$SparkExecuteStatementOperation$$execute(SparkExecuteStatementOperation.scala:361)

Also when you create a table you can see inside the log that columns are written inside the fieldSchema but when it creates a delta table this is empty: "StorageDescriptor(cols:[FieldSchema(name:col, type:array<string>, comment:from deserializer)]".

**Comment by jevvz** [comment]
Works with Spark 3.0.0 (spark-3.0.0-bin-hadoop2.7). Seems it ain't working since version 3.0.1.

**Comment by dennyglee** [comment]
Spark 3.1.1 isn't currently supported for Delta Lake 0.8.0 but will be for the next upcoming release.  

Thanks for doing all of this testing!  Let me try to reproduce the issue using Spark 3.0.1 with Delta 0.8.  Will get back to you shortly!

**Comment by nousot-cloud-guy** [comment]
I'm running into this with Delta 1.1.0 and Spark 3.2.0. Is there any workaround at the moment?

**Comment by zsxwing** [comment]
`SHOW COLUMNS` is currently not supported. I'm closing this in favor of #1027 . Feel free to re-open if this is discussing a different issue.
