### ISSUE TITLE
How to use vacuum to delete old files created by compaction without losing ability to time travel?

### ISSUE THREAD

**Issue by Priyanshu-Mittal** [delta-io/delta#664]
I am running some operations for compaction of files. Now I want to delete the old files left out after compaction to avoid redundancy of same data. But if I use vacuum command, then I am not able to do time travel as all the old states of data get deleted. So, what is the better way to delete old files left out due to compaction without losing ability to time travel?

**Comment by tdas** [comment]
You need the pre-compaction files to read the versions before the old version .. isnt it?

**Comment by Priyanshu-Mittal** [comment]
Yes, I'll need the pre-compaction files

**Comment by ottok92** [comment]
I have the same question. @Priyanshu-Mittal have you found a solution to this?

**Comment by tdas** [comment]
This is currently not possible. To make this possible we would have to do fine-grained tracking of which version ranges each data file is valid for... which is a lot more metadata and a lot of complexity to keep track of.

**Comment by zsxwing** [comment]
Closing this as currently Delta transaction logs don't provide the enough information to support this feature request. Feel free to re-open it if you have any suggestion to support this.
