### ISSUE TITLE
Vaccum deleted versions are not visible in the deltalake history / describe syntax?

### ISSUE THREAD

**Issue by varadhvi** [delta-io/delta#665]
Vacuum deleted versions are not visible in the deltalake history / describe syntax, how to identify what all versions has been deleted by vaccum for audit purpose?

**Comment by dennyglee** [comment]
Note, when you run a vacuum, you're removing the older versions of the data.  If your table has multiple insertions, updates, and deletions (let's say version 8), the vacuum at most will remove older data files and it will not impact any current data.  Could you clarify the context of auditing older versions of the data? 

For more information, please check out the [Diving into Delta Lake Tech Talk Series](https://databricks.com/discover/diving-into-delta-lake-talks).

**Comment by tdas** [comment]
The simple answer, there isn't any way right now to identify which versions have been vacuumed.
