### ISSUE TITLE
Databricks-Connect DeltaTable.forPath() throwing exception

### ISSUE THREAD

**Issue by tanudua** [delta-io/delta#667]
Getting following exception while using DeltaTable.forPath() in databricks-connect . 
spark.read().format("delta") works.

Following is the configuration  -
Cluster - Databricks 8.1
Java 1.8
IntelliJ 

Exception in thread "main" java.lang.UnsupportedOperationException
	at io.delta.tables.DeltaTable$.forPath(DeltaTable.scala:625)
	at io.delta.tables.DeltaTable.forPath(DeltaTable.scala)
	at com.spgmi.ca.TestJob.triggerJob(TestJob.java:80)
	at com.spgmi.ca.TestJob.main(TestJob.java:33)

**Comment by tdas** [comment]
The DeltaTable programmatic APIs are not supported through dbconnect - https://docs.databricks.com/dev-tools/databricks-connect.html#limitations

**Comment by tanudua** [comment]
> The DeltaTable programmatic APIs are not supported through dbconnect - https://docs.databricks.com/dev-tools/databricks-connect.html#limitations
Thanks and apologise , I should read the documentation before posting.

**Comment by dennyglee** [comment]
Closing this issue as it appears to be addressed; please re-open if in error.
