### ISSUE TITLE
SBT plugin sbt-spark-package unavailable

### ISSUE THREAD

**Issue by AFFogarty** [delta-io/delta#669]
Hello, 

Delta Lake versions <= 0.8.0 have a compile-time dependency on the SBT plugin `sbt-spark-package` which is currently unavailable because requests to `https://dl.bintray.com/spark-packages/maven` are returning 403 Forbidden.  I think this is due to Bintray being sunset since May 1st.

Is there a workaround?  There is an issue tracking this on the `sbt-spark-package` repo [here](https://github.com/databricks/sbt-spark-package/issues/50).

Thanks!

**Comment by zsxwing** [comment]
@AFFogarty do you build the Delta Lake by yourself? Could you take the latest build.sbt script and see if you can backport the changes that remove `sbt-spark-package`?

**Comment by AFFogarty** [comment]
Thanks @zsxwing, I was able to get unblocked by cherry-picking this commit:  https://github.com/delta-io/delta/commit/b4897984f7cfc9b3b2e6215042aa42069e444d50
