### ISSUE TITLE
How to show table constraints

### ISSUE THREAD

**Issue by PakhomovAlexander** [delta-io/delta#677]
Hi! I'm trying to show table constraints. Describe table does not show them. Can you help? 

Example to reproduce:

CREATE TABLE test_fb.test_table(i int,s string) 
USING DELTA ;

ALTER TABLE test_fb.test_table CHANGE COLUMN s SET NOT NULL;

**Comment by jaceklaskowski** [comment]
Since it does not seem to be an issue with Delta Lake itself but more with understanding how it works, please use [StackOverflow](https://stackoverflow.com/questions/tagged/delta-lake) or [Delta Lake Users and Developers](https://groups.google.com/g/delta-users) group for this question.
