### ISSUE TITLE
Why LOCATION property disable physical filesystem delete?

### ISSUE THREAD

**Issue by PakhomovAlexander** [delta-io/delta#678]
Hi! Why LOCATION property set explicitly changes DROP TABLE behaviour ?

```sql

CREATE TABLE test.t19(i int,s string)
USING DELTA;

-- Delta log is located here: dbfs:/warehouse/tablespace/managed/hive/test.db/t19

DROP TABLE IF EXISTS test.t19;
```

Delta log is deleted.

But in this case

``` sql
CREATE TABLE test.t19(i int,s string)
USING DELTA
LOCATION 'dbfs:/warehouse/tablespace/managed/hive/test.db/t19';

DROP TABLE IF EXISTS test.t19;
```

Delta log is not deleted from dbfs. Is it expected behaviour ?

**Comment by jaceklaskowski** [comment]
Since it does not seem to be an issue with Delta Lake itself but more with understanding how it works, please use [StackOverflow](https://stackoverflow.com/questions/tagged/delta-lake) or [Delta Lake Users and Developers](https://groups.google.com/g/delta-users) group for this question.
