### ISSUE TITLE
Need clone database for archiving productionized environment 

### ISSUE THREAD

**Issue by tharunponduru** [delta-io/delta#680]
Currently, delta lake supports various types of cloning on tables. There are many use-cases where we need to replicate the environment on a database level as of now I've been using a separate notebook that creates a specified database, generates tables from the specified database, and clones based on shallow or deep argument ( here shallow or deep applied to all tables although I use deep all time ). It would be great if there is a utility that supports database cloning.

**Comment by rahulsmahadev** [comment]
Hi @tharunponduru , Clone is a feature of Delta on Databricks, I would contact Databricks support with this question for more details.

**Comment by tharunponduru** [comment]
Hey @rahulsmahadev Is the clone available on database level ?
