### ISSUE TITLE
Python DeltaTableBuilder API - `partitionBy` doesn't create output partitions

### ISSUE THREAD

**Issue by ZoharMeir** [delta-io/delta#682]
When using the new `DeltaTableBuilder`, I noticed that when I specify a partitioning column with `partitionBy`, the underlying table isn't actually partitioned:
```python
from pyspark.sql.function import col
(DeltaTable.createOrReplace(spark)
  .location("/tmp/test_partitioning_new_api")
  .addColumn("id", "long")
  .addColumn("par", "long")
  .partitionedBy("par")
  .execute())
spark.range(10).withColumn("par", col("id") % 2).write.format("delta").mode("append").save("/tmp/test_partitioning_new_api")
```
<img width="1423" alt="image" src="https://user-images.githubusercontent.com/33152084/119449494-65964880-bd3b-11eb-90f6-5edcd98f7ffe.png">

For comparison, this is how it looked with the DataFrameWriter API:
```python
from pyspark.sql.function import col
spark.range(10).withColumn("par", col("id") % 2).write.format("delta").partitionBy("par").save("/tmp/test_partitioning_write_api")
```
<img width="599" alt="image" src="https://user-images.githubusercontent.com/33152084/119449843-ccb3fd00-bd3b-11eb-8e2b-b51409f7d3b3.png">

Tested on Databricks Runtime 8.3 Beta

**Comment by tdas** [comment]
Aaaah! Thank you for testing it out so quickly! We are going to take a look at it.

**Comment by mikita-sakalouski** [comment]
Have the same issue: 

`from delta import DeltaTable

from pyspark.sql.session import SparkSession
from pyspark.sql.types import StringType

spark = (SparkSession
         .builder
         .config('spark.jars.packages', 'io.delta:delta-core_2.12:1.0.0,org.apache.hadoop:hadoop-aws:3.2.0')
         .config('spark.sql.extensions', 'io.delta.sql.DeltaSparkSessionExtension')
         .config('spark.sql.catalog.spark_catalog', 'org.apache.spark.sql.delta.catalog.DeltaCatalog')
         .config('spark.hadoop.fs.s3a.aws.credentials.provider',
                 'com.amazonaws.auth.DefaultAWSCredentialsProviderChain')
         .getOrCreate())

location = '<table_path>'

(DeltaTable
 .create(sparkSession=spark)
 .tableName(identifier='<table_name>')
 .addColumn(colName='_id', dataType=StringType(), nullable=False)
 .addColumn(colName='_partition', dataType=StringType(), nullable=False)
 .partitionedBy(col='_partition')
 .location(location=location)
 .execute()
 )
print(f'\n Partitions columns:{spark.sql(f"DESCRIBE DETAIL delta.`{location}`").collect()[0]["partitionColumns"]}')`

**Comment by yijiacui-db** [comment]
Thank you for reporting it! We have a bug in that partitionedBy and are working on the fix for it.

In the meantime, you can use the following workaround for partitioning:

`from pyspark.sql.column import _to_seq
from delta import DeltaTable
table_builder = DeltaTable.create(spark).location("...").addColumn("id", "long").addColumn("par", "long")
table_builder._jbuilder = table_builder._jbuilder.partitionedBy(_to_seq(table_builder._spark._sc, ["par"]))
table_builder.execute()`

**Comment by zsxwing** [comment]
Fixed by https://github.com/delta-io/delta/commit/59aa330c403f8a71b3eef0e90bd61cd54aab108c

**Comment by dexianta** [comment]
when is this fix going to be available for release?
