### ISSUE TITLE
Need database level clone

### ISSUE THREAD

**Issue by tharunponduru** [delta-io/delta#685]
Currently, delta lake supports various types of cloning on tables. There are many use-cases where we need to replicate the environment on a database level as of now I've been using a separate notebook that creates a specified database, generates tables from the specified database, and clones based on shallow or deep argument ( here shallow or deep applied to all tables although I use deep all time ). It would be great if there is a utility that supports database cloning.

**Comment by tharunponduru** [comment]
Clearly can this be enhancement?

**Comment by Yaohua628** [comment]
What do you mean by a database-level clone? Do you mean clone the env/config of DB? Or clone all delta tables within one DB?

**Comment by tharunponduru** [comment]
Yes - replicate a DB or replicate all tables works too if it can be done on a single command.

**Comment by Yaohua628** [comment]
It might be a good use case. If using Delta, could you just have a utility function that iterates all second-level dirs, check if it is Delta, and then clone?
I just feel like this kind of DB-level clone is not part of Delta's responsibility (?).

**Comment by zsxwing** [comment]
@tharunponduru Delta table clone is a Databricks feature. Could you raise this feature request to Databricks Support instead? The GitHub repo is for discussing OSS Delta features.

**Comment by tharunponduru** [comment]
Thank you for clarifying on this.

**Comment by Yaohua628** [comment]
Close it: clarified, not a part of Delta OSS feature.
