### ISSUE TITLE
ANTLR Tool version 4.7 used for code generation does not match the current runtime version 4.8ANTLR

### ISSUE THREAD

**Issue by QuintinTao** [delta-io/delta#686]
environment：  delta 1.0.0  spark-3.1.1-bin-hadoop2.7
there is a antlr4-runtime-4.8-1.jar in  SPARK_HOME/jars
I got this error when I executed the sql in spark-shell
spark-shell yarn --driver-memory 1G --num-executors 2 --executor-memory 1G --executor-cores 4 --deploylient --conf "spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension" --conf "spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog" --packages io.delta:delta-core_2.12:1.0.0

spark.sql("CREATE IF NOT EXISTS TABLE events_sql (date DATE,eventId STRING,eventType STRING,data STRING)USING DELTA")

How to deal with it?

**Comment by QuintinTao** [comment]
I think I had resoved this problem already.

I modifyed the file in
.ivy2/cache/io.delta/delta-core_2.12
ivy-1.0.0.xml
I modified the dependency  version
 <dependency org="org.antlr" name="antlr4" rev="4.8" f    from 4.7 to 4.8
and then fix this problem.

But I still can't execute 
CREATE IF NOT EXISTS TABLE events_sql (date DATE,eventId STRING,eventType STRING,data STRING)USING DELTA

I changed it  to CREATE  TABLE events_sql (date DATE,eventId STRING,eventType STRING,data STRING)USING DELTA
and then it is ok now

**Comment by zsxwing** [comment]
`ANTLR Tool version 4.7 used for code generation does not match the current runtime version 4.8ANTLR` should be a waring in the log. This will be fixed by #676.

**Comment by QuintinTao** [comment]
> `ANTLR Tool version 4.7 used for code generation does not match the current runtime version 4.8ANTLR` should be a warning in the log. This will be fixed by #676.

thanks alot！！ by the way  the syntax here is not working well
CREATE IF **NOT EXISTS** TABLE events_sql (date DATE,eventId STRING,eventType STRING,data STRING)USING DELTA

**Comment by zsxwing** [comment]
> CREATE IF **NOT EXISTS** TABLE events_sql (date DATE,eventId STRING,eventType STRING,data STRING)USING DELTA

The syntax should be CREATE **TABLE** IF NOT EXISTS.

**Comment by QuintinTao** [comment]
> > CREATE IF **NOT EXISTS** TABLE events_sql (date DATE,eventId STRING,eventType STRING,data STRING)USING DELTA
> 
> The syntax should be CREATE **TABLE** IF NOT EXISTS.

thank you for your help
