### ISSUE TITLE
Corrupted JSON record for nullable partition values in delta lake transaction log

### ISSUE THREAD

**Issue by jovanpop-msft** [delta-io/delta#687]
Delta Lake transaction log files might contain corrupted JSON records if the data set is partitioned and one partition column is nullable.

If there is a NULL value in the partition column, the _delta_lake transaction log contains JSON record, but it is not properly formatted.

Here is the example of JSON transaction log record:
```
{
"path":"AccountId=__HIVE_DEFAULT_PARTITION__/ExtractDateKey=20191215/part-00002-f1ed87af-cb70-4fdf-8f19-269dfa9bdd65.c000.snappy.parquet",
"partitionValues":{"AccountId":"ExtractDateKey","20191215"},
"size":16303,"modificationTime":1600477317000,"dataChange":0,"stats":...
```

The structure `{"AccountId":"ExtractDateKey","20191215"}` is not a valid JSON object and cannot be parsed using standard JSON parsers.

**Comment by jovanpop-msft** [comment]
The minimal content of Delta Lake folder with the corrupted record is attached.
- .json transaction log file is valid and contains the following JSON object `"partitionValues":{"AccountId":null,"ExtractDateKey":"20191215"}`
- .parquet checkpoint file contains invalid JSON `"partitionValues":{"AccountId":"ExtractDateKey","20191215"}`

[BUG687.zip](https://github.com/delta-io/delta/files/6576012/BUG687.zip)

```
val data = Seq(("1","20191215", "Contoso"), (null:String,"20191215", "Adventure Works"), ("2":String,"20191215", "Nothwind"))

val df = data.toDF("AccountId","ExtractDateKey","Data")
df.write.format("delta").partitionBy("AccountId","ExtractDateKey").mode("overwrite").save(path)
```
at this point there is only one .json file with valid JSON content. Creating a checkpoint writes invalid JSON in Parquet file:
```
import org.apache.spark.sql.delta.DeltaLog 
DeltaLog.forTable(spark,path).checkpoint()
```

**Comment by Yaohua628** [comment]
Hi, thanks for reporting this! But I am unable to reproduce by following your steps. Here is what I got:
```
{"path": "AccountId=__HIVE_DEFAULT_PARTITION__/ExtractDateKey=20191215/part-00001-b2321183-30b7-4b9a-8802-af8466e31b9c.c000.snappy.parquet", "partitionValues": {"AccountId": null, "ExtractDateKey": "20191215"}, "size": 627,...
```
Do I miss something? May I know what version you are running?

**Comment by jovanpop-msft** [comment]
@Yaohua628 I apologize, I'm closing the issue. It seems that the tool that I used had a presentation issue.
