### ISSUE TITLE
The schema of your delta table has changed in an incompatible way since your dataframe or deltatable object was created. please redefine your dataframe or deltatable object.

### ISSUE THREAD

**Issue by absognety** [delta-io/delta#689]
Hi There

when I am trying to read data from delta into spark using `spark.read.format('delta').load(mount_path)` there is an intermittent issue mentioned below is occurring but not all the time
```
The schema of your delta table has changed in an incompatible way since your dataframe or deltatable object was created. please redefine your dataframe or deltatable object.
```
but when we use ```spark.table("delta.`{}`".format(mount_path))``` it seems to be stable - Is there a reason this could happen? 
`spark.databricks.delta.checkLatestSchemaOnRead` is `true` by default, the full exception is suggesting to configure it as `false`

**Comment by Yaohua628** [comment]
This exception is thrown when the schema of the latest version of the table is incompatible with the schema at the time of DataFrame creation. Could you share more details about how to reproduce?

**Comment by absognety** [comment]
The issue is not reproducible it is intermittent, however i know for a fact that the schema of latest version couldn't be different from original table, is there any other reason that this exception gets thrown?

**Comment by brkyvz** [comment]
@absognety This error would be thrown if the schema of your Delta table changes in an incompatible way after you define your dataframe. Incompatible being: columns being dropped, nullability being relaxed, etc. Do you have writes to your table that make such changes?

**Comment by absognety** [comment]
yeah we are using `overwriteSchema=true` to accommodate the new fields that are generated as part of the process, we mostly deal with JSON data structure that we flatten into CSVs so schema evolution is expected too often.

**Comment by gpuma** [comment]
We also ran into this issue after adding a boolean field to the source table but retrying the job fixed it :shrug:

**Comment by absognety** [comment]
@brkyvz  so what I understand is say there is deltatable X, which is created and written as delta format by a certain job in an application, lets assume there is another application which is reading this X doing some transformations (columns addition, fixing NULLs etc) and writing to same delta location. with `overwriteSchema=True` so when we try to read this X again - This exception gets thrown? can we reproduce it this way?

**Comment by absognety** [comment]
restarting the cluster in databricks fixes the issue sometimes, so like I said its intermittent - Ideally it should be reproducible if the schema of delta table changed in incompatible way, I mean everytime we try to read it and call some action like `display` or `show` this exception must be thrown, but that's not the case.

**Comment by absognety** [comment]
closing this issue for now, as it's not reproducible and we stopped observing it after taking care of writes that affect the original table schema.

**Comment by zsxwing** [comment]
@ramankr44 Your case is an issue with [Identify columns](https://github.com/delta-io/delta/issues/1072) which we will support very soon. However, since it's not in open source yet, we cannot really fix anything. Could you open up a Databricks support ticket](https://www.databricks.com/support) instead?

**Comment by zsxwing** [comment]
> I have introduced this two columns modified_timestamp, created_timestamp after creating the dataframe.

@ramankr44  Sorry. Please ignore my above comment. You can follow the suggestion in the error message:
```
The schema of your Delta table has changed in an incompatible way since your DataFrame or
DeltaTable object was created. Please redefine your DataFrame or DeltaTable object.
```

**Comment by ramankr44** [comment]
I've created new datframe using previous dataframe with the help of withColumn, but still I'm getting the same error.

**Comment by zsxwing** [comment]
>  previous dataframe

You would need to create the entire DataFrame from the scratch. In other words, you need to re-run `spark.read.format("delta")...`.

**Comment by ramankr44** [comment]
here the thing is have created a database db1 from there I am inserting the data into another table of 2nd database db2 and in this one also introducing some new columns, and after that converting this table into a dataframe, at later part Itried to introduce two another column of timestamp and then I got this error
