### ISSUE TITLE
Manifest file for my delta table

### ISSUE THREAD

**Issue by dggs123** [delta-io/delta#70]
Hi, Is there a way that I could create a manifest file for my delta table, to use hive's `SymlinkTextInputFormat`. I want to query my delta table using presto.

Thanks

**Comment by tdas** [comment]
This is currently supported on Databricks Delta. We are hoping to bring this support to OSS soon.

**Comment by marmbrus** [comment]
+1 we should add this feature.  I created an issue with more details at #76.  Linking and closing this duplicate.
