### ISSUE TITLE
 java.lang.NoClassDefFoundError: com/xxx/shaded/io/delta/tables/DeltaTable$

### ISSUE THREAD

**Issue by xichenAiguang** [delta-io/delta#708]
I have a library in Databricks cluster, and this library has an API looks like below

>   def checkRange(deltaPath : String, endTime: String): Unit ={
    val d = io.delta.tables.DeltaTable.forPath(deltaPath)
}

when I call this API from notebook, I always get below error, does anyone have insight how to fix it? Thanks

**java.lang.NoClassDefFoundError: com/xxx/shaded/io/delta/tables/DeltaTable$,**

I execute it on Azure Databricks, and runtime version is 7.3 LTS (includes Apache Spark 3.0.1, Scala 2.12)

**Comment by tdas** [comment]
Are you adding the OSS Delta Lake maven dependency into the JAR running in Databricks clusters? Databricks already has Delta baked in and puting the OSS Delta jars in the classpath can cause dependency issues

**Comment by xichenAiguang** [comment]
Thansk @tdas ,  I'd like to use  Databricks provided jar (io.delta.tables) at runtime ,  do you know what I have to configure for that?

**Comment by zsxwing** [comment]
@xichenAiguang the problem you hit is you have some shade rule that rewrites `io.delta.tables.DeltaTable$` in your code to `com/xxx/shaded/io/delta/tables/DeltaTable$`. If you remove this rule and make sure you don't have the oss delta jar in your final uber jar, it should work in Databricks.

**Comment by zsxwing** [comment]
Closing this as there is no update.
