### ISSUE TITLE
support for external table in AWS 

### ISSUE THREAD

**Issue by gourav-sg** [delta-io/delta#73]
Hi,
users building data lake in AWS, or in other systems, use EXTERNAL TABLES quite a lot. This gives their solutions high flexibility. For example having either a personal metastore or using Glue datacatalog. 

It will be great if delta support as a storage class was included for HIVE metastores as well. I think we can and do read data using HIVE or SPARK directly from DELTA write locations, but it does give us duplicates, because its just reading the parquet files.

Regards,
Gourav

**Comment by tdas** [comment]
We are working towards improving our table support in OSS so that we can run all Delta table operations directly on table names defined in Hive metastore. The challenge is to add the necessary customizations in Apache Spark to make DDLs work with Delta's setup.

**Comment by rtjarvis** [comment]
This is important for your use case and web be happy to contribute. How far have you got?

**Comment by pranavanand** [comment]
We are still working on this and are waiting for the Spark 3.0. This should ideally come out in the Delta Lake 0.7.0 release.

**Comment by gourav-sg** [comment]
HI,

thanks a ton Pranav, its a great news.


Thanks and Regards,
Gourav Sengupta

**Comment by tdas** [comment]
the table support is being tracked by this issue - #85

**Comment by kadprad** [comment]
I am trying to use delta lake using AWS DMS and Glue. Could you help me find relevant posts.

**Comment by gourav-sg** [comment]
Hi,
I use EMR (never found any reason valid enough to use AWS glue ETL,
ofcourse we use GLUE Datacatalog) and install delta in it as a part of
bootstrap actions.

Except for EMR 5.29 I think delta works fine in the rest. The latest
release of Delta works fine using EMR 6.1.0.

There is a chance that AWS team might suggest to use HUDI, but personally I
have found that HUDI's API's are too confusing for me to work with, and
even more confusing to change/ debug.

Best of luck

Regards,
Gourav

**Comment by zsxwing** [comment]
This has been released in Delta 0.7.0 on Spark 3.0. See #85

**Comment by gourav-sg** [comment]
beautiful. Thanks a ton for this. I have been using some of those features
with a smile.

Regards,
Gourav Sengupta
