### ISSUE TITLE
Support changes such as column drop and rename in the Delta protocol

### ISSUE THREAD

**Issue by dennyglee** [delta-io/delta#731]
Improve the Delta protocol to support changes such as column drop and rename.

**Comment by milesgranger** [comment]
Any activity/outlook for this?

**Comment by zsxwing** [comment]
The protocol change is done by https://github.com/delta-io/delta/commit/282fc689467a31938114e4e1e0d452e0bd6b0aaf

#732 will track the work to leverage the new protocol change to support Spark’s column drop and rename commands.

**Comment by milesgranger** [comment]
Thank you. :)
