### ISSUE TITLE
Update Delta to support Apache Spark 3.2

### ISSUE THREAD

**Issue by dennyglee** [delta-io/delta#733]
With the upcoming Spark 3.2 release, ensure Delta can support the latest release.

**Comment by zsxwing** [comment]
Resolved by https://github.com/delta-io/delta/commit/5571d95966e3b03c4699dcfa1a5cd86bb16447dc

We will make a release soon.

**Comment by ghostdogpr** [comment]
This is awesome~ Would that be possible to cross-build for 2.13 since Spark 3.2 supports it?

**Comment by zsxwing** [comment]
@ghostdogpr Yep. #823 is updating the code for Scala 2.13

**Comment by george-zubrienko** [comment]
Hi,
I see [v1.1.0](https://github.com/delta-io/delta/releases/tag/v1.1.0) release is ready, I'm curious if there will be a compiled jar on Maven like for [v1.0.0](https://mvnrepository.com/artifact/io.delta/delta-core), or we'll have to switch to compiling ourselves for a while?

And thanks for all the great work you are doing!
