### ISSUE TITLE
Time travel doesn't work if spark.sql.session.timeZone is set to 'UTC+x:00'

### ISSUE THREAD

**Issue by neednlab** [delta-io/delta#735]
Spark configuration spark.sql.session.timeZone 'UTC+xx:00' works, but spark.sql.session.timeZone 'UTC+x:00' does not.

![1628165040](https://user-images.githubusercontent.com/41602171/128346852-74721391-b9a2-4060-a68d-ee09abbfd721.png)

![image](https://user-images.githubusercontent.com/41602171/128347046-72d60e96-487b-4f1d-bcfd-f44abc1b5812.png)

**Comment by Yaohua628** [comment]
I think spark has the strict timezone format `(+|-)HH’, ‘(+|-)HH:mm` (2 **H**s):
https://spark.apache.org/docs/latest/sql-ref-syntax-aux-conf-mgmt-set-timezone.html

**Comment by scottsand-db** [comment]
Closing since this is functioning as expected.
