### ISSUE TITLE
Improve SQL syntax for MERGE

### ISSUE THREAD

**Issue by dnskr** [delta-io/delta#738]
Existing SQL syntax (see [here](https://docs.delta.io/latest/delta-update.html#upsert-into-a-table-using-merge) and [here](https://docs.microsoft.com/en-us/azure/databricks/spark/latest/spark-sql/language-manual/delta-merge-into)) for **MEGRE** could be improved by adding an alternative for  `ON <merge_condition>`

**Main assumption**
In common cases target and source tables have the same column names used in `<merge_condition>` as keys.
For example `ON target.id = source.id` or `ON target.name = source.name AND target.surname = source.surname`
It would be more convenient to use `ON COLUMNS (id)` and `ON COLUMNS (name, surname)` or similar instead.
The same approach is used for [JOIN](https://spark.apache.org/docs/latest/sql-ref-syntax-qry-select-join.html) where `join_criteria` syntax is `ON boolean_expression | USING ( column_name [ , ... ] )`

**Improvement proposal**
Syntax
```sql
MERGE INTO target_table_identifier [AS target_alias]
USING source_table_identifier [<time_travel_version>] [AS source_alias]
ON { <merge_condition> | COLUMNS ( column_name [ , ... ] ) }
[ WHEN MATCHED [ AND <condition> ] THEN <matched_action> ]
[ WHEN MATCHED [ AND <condition> ] THEN <matched_action> ]
[ WHEN NOT MATCHED [ AND <condition> ]  THEN <not_matched_action> ]
```
Example
```sql
MERGE INTO target
USING source
ON COLUMNS (name, surname)
WHEN MATCHED THEN
    UPDATE SET *
WHEN NOT MATCHED THEN
    INSERT *
```

**Comment by Yaohua628** [comment]
Hi Denis, thanks for the suggestion, it would be nice to have it!!
Could you open a JIRA issue (or maybe a PR) in the spark community (see: https://spark.apache.org/contributing.html)? We don't parse MERGE ourselves in OSS delta.

**Comment by dnskr** [comment]
Thanks @Yaohua628!
I have created the improvement issue https://issues.apache.org/jira/browse/SPARK-36472. I don't have experience in Spark internals to make a PR.
Should this issue be closed?

**Comment by tdas** [comment]
I doubt this syntax improvement will be supported by Spark. MERGE has a clear SQL standard, and I am not sure if something like USING is supported in that. We have been able to convince Spark to support UPDATE SET * and INSERT * (completely outside the SQL standard) only because of the major usability improvement that it gives. But for something smaller like this, I doubt we will be able to convince Spark community to adopt this non-standard approach.

**Comment by dnskr** [comment]
I agree, it's preferable to not have something what violates standart. However, from my point of view it is a common practice to extend SQL standart to make an improvement. Looks like it is true for MERGE statement, for example in [MS SQL](https://docs.microsoft.com/en-us/sql/t-sql/statements/merge-transact-sql?view=sql-server-ver15#syntax) and [DB2](https://www.ibm.com/docs/en/db2/11.5?topic=statements-merge).
I don't have a strong opinion, but it would be great to initiate a discussion and consider it at least.

**Comment by dnskr** [comment]
Closing in favor of the ticket created in Spark JIRA https://issues.apache.org/jira/browse/SPARK-36472
