### ISSUE TITLE
the example An error occurred

### ISSUE THREAD

**Issue by study-day** [delta-io/delta#744]
![image](https://user-images.githubusercontent.com/38400198/128840157-ee94a91d-4f61-4a71-a795-07b8debfa9d9.png)
the code like this ,but it is error,How can i fix it

https://docs.delta.io/latest/quick-start.html#conditional-update-without-overwrite

```
// Upsert (merge) new data
Dataset<Row> newData = spark.range(0, 20).toDF();

deltaTable.as("oldData")
  .merge(
    newData.as("newData"),
    "oldData.id = newData.id")
  .whenMatched()
  .update(
    new HashMap<String, Column>() {{
      put("id", functions.col("newData.id"));
    }})
  .whenNotMatched()
  .insertExpr(
    new HashMap<String, Column>() {{
      put("id", functions.col("newData.id"));
    }})
  .execute();

deltaTable.toDF().show();
```

**Comment by Yaohua628** [comment]
Why you `toString` it? It requires a `Column` not a `String`

**Comment by study-day** [comment]
because
```
def insertExpr(values : java.util.Map[_root_.scala.Predef.String, _root_.scala.Predef.String])
```

and The following code is correct
```
                .insertExpr(
                        new HashMap<String, String>() {{
                            put("_c0", functions.col("changedData._c0").toString());

```

**Comment by study-day** [comment]
https://docs.delta.io/latest/quick-start.html#update-table-data 

This is an obvious mistake
![image](https://user-images.githubusercontent.com/38400198/128956800-47dcc43b-e64e-4de8-9e60-e73cb435bf5b.png)
