### ISSUE TITLE
CREATE IF NOT EXISTS TABLE events????

### ISSUE THREAD

**Issue by study-day** [delta-io/delta#752]
![image](https://user-images.githubusercontent.com/38400198/128991553-c83953c5-9846-45b0-be95-1637670ae37f.png)
https://docs.delta.io/latest/delta-batch.html#create-a-table
This is a not funny bug？？？？

**Comment by xuqianlong** [comment]
CREATE TABLE  IF NOT EXISTS events (
  date DATE,
  eventId STRING,
  eventType STRING,
  data STRING)
USING DELTA
"TABLE  " after "CREATE "

**Comment by study-day** [comment]
then， The official document is wrong, please modify it
