### ISSUE TITLE
What is the relationship between the delta lake table and the hive table?

### ISSUE THREAD

**Issue by study-day** [delta-io/delta#757]
What is the relationship between the delta lake table and the hive table?
Now that the data is in hive, if it exists on detlalake, how do you perform related queries with the previous data?

**Comment by jaceklaskowski** [comment]
Please use [delta forum](https://groups.google.com/g/delta-users) for this and other questions about Delta Lake.

**Comment by study-day** [comment]
i'm sorry .I find I can not visit https://groups.google.com/g/delta-users .  
Do you know if there are any related blogs that explain this issue？If you know, please send it to me, thank you
