### ISSUE TITLE
SELECT max(version) FROM (DESCRIBE HISTORY delta.`/delta/test1`) error

### ISSUE THREAD

**Issue by study-day** [delta-io/delta#759]
spark.sql("SELECT max(version) FROM (DESCRIBE HISTORY delta.`/delta/test1` )").show();
Exception in thread "main" org.apache.spark.sql.catalyst.parser.ParseException:
missing ')' at 'delta'(line 1, pos 43)

== SQL ==
SELECT max(version) FROM (DESCRIBE HISTORY delta.`/delta/test1`)
-------------------------------------------^^^

        at org.apache.spark.sql.catalyst.parser.ParseException.withCommand(ParseDriver.scala:255)
        at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parse(ParseDriver.scala:124)

**Comment by study-day** [comment]
I guess this syntax is wrong. what do you think? Did delta do more parsing?

**Comment by study-day** [comment]
DESCRIBE HISTORY delta./delta/test1 is ok and  SELECT max(version) FROM (DESCRIBE HISTORY delta./delta/test1) is error
+-------+--------------------+------+--------+--------------------+--------------------+----+--------+---------+-----------+--------------+-------------+--------------------+------------+
|version|           timestamp|userId|userName|           operation| operationParameters| job|notebook|clusterId|readVersion|isolationLevel|isBlindAppend|    operationMetrics|userMetadata|
+-------+--------------------+------+--------+--------------------+--------------------+----+--------+---------+-----------+--------------+-------------+--------------------+------------+
|      3|2021-08-13 14:41:...|  null|    null|              DELETE|{predicate -> ["(...|null|    null|     null|          2|          null|        false|{numRemovedFiles ...|        null|
|      2|2021-08-13 14:30:...|  null|    null|              UPDATE|{predicate -> (ev...|null|    null|     null|          1|          null|        false|{numRemovedFiles ...|        null|
|      1|2021-08-13 14:22:...|  null|    null|               WRITE|{mode -> Append, ...|null|    null|     null|          0|          null|         true|{numFiles -> 1, n...|        null|
|      0|2021-08-13 11:58:...|  null|    null|CREATE OR REPLACE...|{isManaged -> fal...|null|    null|     null|       null|          null|         true|                  {}|        null|
+-------+--------------------+------+--------+--------------------+--------------------+----+--------+---------+-----------+--------------+-------------+--------------------+------------+

**Comment by zsxwing** [comment]
This is a limitation of Spark. `DESCRIBE HISTORY` is a Spark command. Its result cannot be used as a subquery. You can use DataFrame API as a workaround, such as

```
sql("DESCRIBE HISTORY delta.`/delta/test1`").select("max(version)")
```

**Comment by study-day** [comment]
thanks ,by the way ，https://docs.delta.io/latest/index.html ，I have found several errors in the documentation。 How to submit pr to modify them, where to submit? I did not find in the github repo。
