### ISSUE TITLE
Concurrent streaming to a delta table and compaction leads to exception: org.apache.spark.sql.delta.ConcurrentAppendException

### ISSUE THREAD

**Issue by sinichkin** [delta-io/delta#761]
https://stackoverflow.com/questions/68758331/exception-org-apache-spark-sql-delta-concurrentappendexception-files-were-adde

**Comment by zsxwing** [comment]
Which Delta Lake version are you using?

**Comment by eran-levy** [comment]
@scottsand-db I see its written in the stackoverflow comments - scalaMajorVersion=2.12 scalaMinorVersion=11 SPARK_VERSION=3.1.1 DELTA_VERSION=1.0.0 KAFKA_VERSION=2.3.1

**Comment by dennyglee** [comment]
Thanks, @eran-levy  - to help with the flow, I've responded to the original SO question and the results of the analysis can be pushed back here into GitHub.  HTH!

**Comment by aish-war** [comment]
Hi, @scottsand-db @dennyglee 
was the above issue solved? I too am facing almost the same issue. I'll attach 2 screenshots that'll help u understand the issue, as u see I am running two spark session parallely, trying to update/insert in the same delta table but on
different partitions, partitioned on "site", and it still throws "ConcurrentAppendException". Hope u understood what I am trying to convey. Could u kindly help me here,? I have also attached the ss of the exception too.

delta==0.4.2
delta-spark==1.0.0
deltalake==0.5.6
pyspark==3.1.1 

![Screenshot from 2022-04-07 13-09-34](https://user-images.githubusercontent.com/66881571/162262465-3967d309-00d7-49b1-86da-2cd598580b45.png)
![Screenshot from 2022-04-07 13-11-50](https://user-images.githubusercontent.com/66881571/162262466-2d4d2f1a-901d-4c69-9b93-f30d716bf293.png)

**Comment by scottsand-db** [comment]
Hi @aish-war thanks for your question, we will take a look at your error msg.

**Comment by tdas** [comment]
this is a complex issue! the exception that you posted... which merge query hit that issue .. the merge query on site "UNIV" or site "BAPT"?

**Comment by tdas** [comment]
also.. it might be helpful for us to repro the issue our side for deeper debugging. if you can repro this issue locally... could have package this into a self-runnable code + instructions that we can execute?

**Comment by AthulJustin** [comment]
@tdas @scottsand-db
Hi guys any updates on the query raised?/

**Comment by scottsand-db** [comment]
Hey @AthulJustin. Still looking. Sorry we've been busy working on the release of Delta Lake 1.2. Should have an answer for you in the next few days.

**Comment by scottsand-db** [comment]
Hi @AthulJustin. This will take some time to debug. So far I've reproduced on Delta Lake 1.0 and 1.1.

**Comment by AthulJustin** [comment]
Thanks @scottsand-db and @tdas . This issue is kind of like the top priority issue for us . Its been haunting us for like a month.

**Comment by sree-inapp** [comment]
@tdas @scottsand-db @aish-war @AthulJustin 

Hello everyone! I'd like to know whether there has been any progress on this issue. We are also dealing with the same issue. I haven't been able to come up with any solutions.

TIA

**Comment by scottsand-db** [comment]
@sree-inapp and @AthulJustin - sorry, things have been very busy with the recent release of Delta Lake 1.2.0 and the upcoming Delta Lake 1.2.1. TD and I have time scheduled this week to investigate this issue. Thanks for your patience.

**Comment by scottsand-db** [comment]
(sorry accidentally closed)

**Comment by sree-inapp** [comment]
Hi @scottsand-db  @tdas  were you able to look into this issue? we are still stuck on this.
Awaiting your response.

**Comment by aish-war** [comment]
> Hi @scottsand-db @tdas were you able to look into this issue? we are still stuck on this. Awaiting your response.

same here.

**Comment by AthulJustin** [comment]
Hi @scottsand-db @tdas Awaiting your response.

**Comment by MintuJohnsontj** [comment]
Hi @scottsand-db @tdas
Is there any solution to this problem? I am also facing the same issue.

**Comment by vivekInapp** [comment]
Hi @scottsand-db @tdas
Is there any solution to this problem? I am also facing the same issue.

**Comment by fathimajafir** [comment]
Hi is there any solution to the problem?  we are also facing this issue

**Comment by scottsand-db** [comment]
Hi @aish-war, so in your example you provided, changing how you create the source table, e.g.
```python
df = dup_table.toDF().filter("acc_num=='6723952'")
```

to

```python
df = dup_table.toDF().filter("acc_num=='6723952' AND site='BAPT'")
```

solves the problem.

Can you show me how you are create the source tables in production?

**Comment by aish-war** [comment]
@scottsand-db will definitely check this out. thanks for responding.

**Comment by scottsand-db** [comment]
@AthulJustin @MintuJohnsontj @fathimajafir can you please all give me more details on
- how you are generating target table
- how you are generating source table
- merge condition

**Comment by scottsand-db** [comment]
@aish-war To be clear, the issue here was that your source DataFrame was built off of / directly referenced your target table.
```python
source = target.toDF().filter("acc_num=='3198639'")
```

In this case, you should save your source to a temporary table first, and then read from that table during your merge.

This was an issue because, during the merge, despite your merge condition which was correctly partitioned, it was re-generating the source (and looking for that unique `acc_num`). For all spark knows, the results to that source query might have changed, so it needs to re-scan the entire table to look for rows that match that `acc_num`. Since it had to scan the entire table, this is why you are getting concurrent append exceptions.

**Comment by aish-war** [comment]
@scottsand-db the issue indeed was wrt to the way we were creating the the new/updated record. thank you.

**Comment by scottsand-db** [comment]
@aish-war great, glad I could help!
