### ISSUE TITLE
How to test the transaction of delta lake, or how to manually commit the transaction,？

### ISSUE THREAD

**Issue by study-day** [delta-io/delta#763]
How to test the transaction of delta lake, or how to manually commit the transaction,？
I cant visit the discuss 。
有没有qq群，微信群，钉钉群，或者可以访问的邮件列表？

**Comment by zsxwing** [comment]
Delta Lake doesn't provide transaction APIs right now. Do we have any use cases that require this?

**Comment by study-day** [comment]
Thanks for your reply。Not yet, I just want to test it.
