### ISSUE TITLE
python quick start example is broken

### ISSUE THREAD

**Issue by dmoore247** [delta-io/delta#766]
The [python example](https://docs.delta.io/latest/quick-start.html#python) is not copy-paste ready.
It suffers from wrong namespace on builder = and there is a double `spark =`

The better example is:
```
from delta import *

builder = SparkSession.builder.appName("MyApp") \
    .config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension") \
    .config("spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog")

spark = configure_spark_with_delta_pip(builder).getOrCreate()
```

**Comment by yijiacui-db** [comment]
Thanks for fixing this @dmoore247 !

**Comment by simondmorias** [comment]
This should not have been closed it is still incorrect.

**Comment by zsxwing** [comment]
@simondmorias Thanks! Yep, we haven't deployed the fixed docs. Reopening this.

**Comment by zsxwing** [comment]
Closing this. This has been fixed.
