### ISSUE TITLE
Hi, we are facing the same issue **'module not found: io.delta#delta-core_2.12;1.0.0**' and we have **spark-3.1.2-bin-hadoop3.2**

### ISSUE THREAD

**Issue by kumaran-chandrababu** [delta-io/delta#771]
Hi, we are facing the same issue **'module not found: io.delta#delta-core_2.12;1.0.0**' and we have **spark-3.1.2-bin-hadoop3.2**
Any help on how do we resolve this issue and run the below command successfully? 
**pyspark --packages io.delta:delta-core_2.12:1.0.0 --conf "spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension" --conf "spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog"**

![image](https://user-images.githubusercontent.com/21185078/131542094-1088b3e6-cd03-4f7e-a0ba-c667bfd6c953.png)

_Originally posted by @kumaran-chandrababu in https://github.com/delta-io/delta/issues/63#issuecomment-909400364_

**Comment by zsxwing** [comment]
@kumaran-chandrababu Looks like it's because repo1.maven.org blocked your ip address. Could you try google mirror such as 
```
pyspark --packages io.delta:delta-core_2.12:1.0.0 --repositories https://maven-central.storage-download.googleapis.com/maven2/ --conf "spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension" --conf "spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog"
```

**Comment by kumaran-chandrababu** [comment]
> @kumaran-chandrababu Looks like it's because repo1.maven.org blocked your ip address. Could you try google mirror such as
> 
> ```
> pyspark --packages io.delta:delta-core_2.12:1.0.0 --repositories https://maven-central.storage-download.googleapis.com/maven2/ --conf "spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension" --conf "spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog"
> ```

Hi, Thanks for you reply, I tried that too but still not working as per below. I've attached the complete screenshot of exception below.

![image](https://user-images.githubusercontent.com/21185078/131639967-621b342e-df94-40b1-b389-9add76e059f0.png)
![image](https://user-images.githubusercontent.com/21185078/131640033-abe3cf3a-aedc-4917-88fa-c9081a7022f2.png)

**Comment by zsxwing** [comment]
Does your machine have the internet access? Could you try to access the link in the same machine manually?

**Comment by kumaran-chandrababu** [comment]
> Does your machine have the internet access? Could you try to access the links in the logs on the same machine manually?

Yes do we have the internet access and the links here are properly showing up in the browser. As a workaround, we now manually downloaded the Jars and Pom files locally and setting up the spark config via pySpark code,  so delta works fine now for reading/ writing into delta locally., however, when we try to connect to Azure Data Lake Gen2 as per the delta documentation, we are now getting this exception as below. Kindly assist.

![image](https://user-images.githubusercontent.com/21185078/132322623-02258e7e-0bf9-4216-9220-358001707ba8.png)

![image](https://user-images.githubusercontent.com/21185078/132322888-b823317d-87ca-45a6-9030-1ae62283e8ab.png)

![image](https://user-images.githubusercontent.com/21185078/132323141-7f9e9436-a828-41b6-b728-0bc7fb631bdd.png)

**Comment by zsxwing** [comment]
Closing this as the delta jar loading issue is resolved. The Azure issue is tracked in #777
