### ISSUE TITLE
delta table merge not matching on null value in source key

### ISSUE THREAD

**Issue by HamzaJosh** [delta-io/delta#780]
I have a merge statement 

target_dt.alias("target").merge(source = source_deduped_df.alias("source"), condition = match_condition).whenMatchedUpdate(set = update_columns).whenNotMatchedInsert(values = insert_columns).execute()
    target_dt.vacuum()
    target_df = target_dt.toDF()

when this runs and if there are values with null in the matching column, it creates a new row and does not merge on null value, any suggestions on how to resolve? I cannot eliminate nulls from source :(

**Comment by zsxwing** [comment]
What's your `match_condition `? Most of SQL expressions will return `null` when any value in the expression is `null`. If you would like [null safe comparison](https://spark.apache.org/docs/3.1.2/sql-ref-null-semantics.html#comparison-operators-), you can use `source.c1 <=> target.c1`

**Comment by rdurbano** [comment]
I got the same issue when I executed the MERGE Command and in the conditon clause I compare a value with null value.
The merge not understood this as different, my workaround for this problem was use the coalesce in the merge condition replacing null for the value of data type of the compare, exemple: coalesce ( columnInt , 0) OR coalesce (columnString , '')

**Comment by zsxwing** [comment]
@rdurbano could you provide the MERGE condition? As I mentioned above, Spark SQL follows the SQL standard which return `null` when any value in the expression is `null` (e.g., if you use `source.c1 = target.c1`, any `null` value will make the expression returns `null` and it will be considered as not match). If you would like [null safe comparison](https://spark.apache.org/docs/3.1.2/sql-ref-null-semantics.html#comparison-operators-), you can use source.c1 <=> target.c1

**Comment by rdurbano** [comment]
Thanks, yes it's the same behavior that occurs in SQL engine. 
I will use the <=> to compare.

**Comment by zsxwing** [comment]
Closing this as it's an expected behavior.
