### ISSUE TITLE
Lacking support for DataFrameWriter's "maxRecordsPerFile" option?

### ISSUE THREAD

**Issue by noslowerdna** [delta-io/delta#781]
It doesn't appear that the "maxRecordsPerFile" DataFrameWriter option, e.g. `df.write.option("maxRecordsPerFile", 10000)` is supported when using the "delta" format. However the behavior can still be achieved by setting the `spark.sql.files.maxRecordsPerFile` configuration property in the SparkConf.

If verified and not considered a bug, could this be a simple enhancement to implement?

**Comment by scottsand-db** [comment]
Thanks for bringing this to our attention. We will look into this.
