### ISSUE TITLE
Incomplete records read from Delta Table

### ISSUE THREAD

**Issue by VijaybabuNakkonda** [delta-io/delta#804]
Dear Team,

Few delta tables were created last year (23-Nov-2020) and records were getting merged on a daily basis. When the table was queried, we see that half of the partitions are missed to read by delta driver. We can see the partitioned folder, but these folders are not read by delta driver.

What could be the root cause? Highly appreciate your help.

Cluster used to run merge query: 7.3 LTS (includes Apache Spark 3.0.1, Scala 2.12)

When queried over partial version history, see no delete operation. Also the Merge operationMetrics do not have any deleted rows.

Thanks and Regards,
Vijay

**Comment by dennyglee** [comment]
Hi @VijaybabuNakkonda - this appears to be a Databricks-specific question, could you please ask your question in [Delta Users Slack](https://dbricks.co/delta-users-slack) > databricks-delta channel or contact Databricks support.

Saying this, as these are long-running Delta tables, if you have been doing any overwrites, updates, deletes, or merges - it's possible that these partitions are only used for time travel purposes.

**Comment by dennyglee** [comment]
Hi @VijaybabuNakkonda please do raise this issue in the other channels so we can help.  But please note, when Delta Lake performs any non-append operations - such as overwrites, updates, or merges - new files added which allows for time travel and helps ensure consistency. For more on the topic, please refer to [Unpacking the Transaction Log](https://databricks.com/discover/diving-into-delta-lake-talks/unpacking-transaction-log).  

I'll close this issue per other channels but please re-open if appropriate.  Thanks!

**Comment by VijaybabuNakkonda** [comment]
Thanks for closing the issue @dennyglee 

For someone facing same kind of issue. I found the potential root cause. When the delta transaction is failed merge operation in this case, old delta log versions are being deleted, causing the incomplete delta read operation.

**Comment by dennyglee** [comment]
Thanks for the update @VijaybabuNakkonda - could we find a time to chat via Slack later this week?  If this is true, then this is a potential bug.
