### ISSUE TITLE
Python / SQL api for Merge Into

### ISSUE THREAD

**Issue by ronflomin** [delta-io/delta#82]
Hi,
I have seen in Databricks' website that there is option to use merge into command.

Is it available? 
Can I use it with Python api or only with sql?

**Comment by tdas** [comment]
I am working on the Scala APIs for Merge into right now (#42). Python APIs will come soon after that. 
SQL APIs, unfortunately, will take a bit longer because Apache Spark currently does not have any support for parsing and analyzing MERGE command and it will take longer for the Spark community to address that. Until then we are hoping that Python/Scala/Java APIs would be good enough for the Delta community.

**Comment by ronflomin** [comment]
Hi, 
How can I find your code?

**Comment by tdas** [comment]
We will make a PR soon, maybe next week.

**Comment by ronflomin** [comment]
Great!
I have another question regarding the merge functionality:
How are you planning to implement it? What is your strategy?

**Comment by tdas** [comment]
At a high level the strategy will involved two scans on the data.
1. The first scan will use the MERGE condition in an inner join between source dataframe and target Delta table to find which files have data matching the condition and therefore will need to be updated.
2. The second scan will do an outer join between the source and only those identified matching files in the target table. The output of the outer join will be processed to appropriately modify the data based on the matched/not matched update/delete/insert clauses and write out a new set of files with merged data.

**Comment by ronflomin** [comment]
I see, thank you.
But how are you planning to delete the origin rows.

What I mean is that you can't really update the data of the parquet file, so I assume that you are just adding the new files based on existing data and the matched and not matched condition, but who can you remove the old rows?

**Comment by tdas** [comment]
Good question! We are just going to rewrite the entire file into a new file
such that we write the new/modified rows and copy the existing rows that
are supposed to stay unchanged. And this new file replaces the old file.
That's what we are going to do for all Update and Delete as well.

**Comment by ronflomin** [comment]
Intersting.
Do you think that your strategy will work even in huge tables?(dozens of billions of rows?).

Because every time you do a full scan of the table and you join it with another dataframe.

**Comment by tdas** [comment]
There are definitely a whole bunch performance improvements we can do on top of this basic idea. Our goal is to add a basic version to this project and then over time keep improving with the community.

**Comment by ronflomin** [comment]
I see, sounds great.

Looking forward to your PR.
