### ISSUE TITLE
How to create a custom function table with spark sql

### ISSUE THREAD

**Issue by xuqianlong** [delta-io/delta#838]
how to use spark sql to create a table which are a special type of columns whose values are automatically generated based on a user-specified function over other columns in the Delta table.

**Comment by zsxwing** [comment]
Do you mean using [Generated Columns](https://docs.delta.io/latest/delta-batch.html#use-generated-columns) in a SQL command? We don't support it right now as Spark SQL parser doesn't support the syntax. But you can use our Scala or Python APIs to create such table (Check the above link).

**Comment by xuqianlong** [comment]
> Do you mean using [Generated Columns](https://docs.delta.io/latest/delta-batch.html#use-generated-columns) in a SQL command? We don't support it right now as Spark SQL parser doesn't support the syntax. But you can use our Scala or Python APIs to create such table (Check the above link).

ok,thank you
