### ISSUE TITLE
[Document] Create table example in doc is incorrect

### ISSUE THREAD

**Issue by zjffdu** [delta-io/delta#845]
The example here is incorrect. https://docs.delta.io/latest/delta-batch.html#create-a-table

```
CREATE IF NOT EXISTS TABLE events (
  date DATE,
  eventId STRING,
  eventType STRING,
  data STRING)
USING DELTA
```

It should be

```
CREATE TABLE IF NOT EXISTS events (
  date DATE,
  eventId STRING,
  eventType STRING,
  data STRING)
USING DELTA
```

**Comment by zjffdu** [comment]
BTW, where's the repo of delta doc ?

**Comment by zsxwing** [comment]
Thanks for reporting this. This doc will be updated soon.

> BTW, where's the repo of delta doc ?

Currently it's not in a git repo. We are working on making it become a github project so that it's easier to maintain.

**Comment by zsxwing** [comment]
The doc has been fixed
