### ISSUE TITLE
Unable to query delta table version from Athena with SQL

### ISSUE THREAD

**Issue by GabrielAmazonas** [delta-io/delta#855]
Hello Delta team, I would like to clarify if the above scenario is actually a possibility.

Here are our current scenario steps:

Tooling Version:

- AWS Glue - 3.0
- Python version - 3
- Spark version - 3.1
- Delta.io version -1.0.0

From AWS Glue jobs running PySpark code, we make several overwrite operations to a delta table, as follows:

`df.write.format("delta").mode("overwrite").save(target_s3_path)`

The operation succeeds with no issues.

Also, we were able to run successfully the following operations:

```
 deltaTable = DeltaTable.forPath(spark, target_s3_path)

 fullHistoryDF = deltaTable.history()    # get the full history of the table

 lastOperationDF = deltaTable.history(1) # get the last operation
    
 preLastOperationDF = deltaTable.history(2)
```

    
    
Those were also successful and we were able to read its content and check the multiple versions of the delta table that were written.

Here is the key concern of the issue:
From pyspark code, we had no issues reading any of the table versions specifically, as follows:

` spark.read.format("delta").option("versionAsOf", 2).load(target_s3_path)`

We would like to run a very similar SQL query through Athena instead, in order to retrieve a specific version of a table, for example:

`SELECT * FROM "delta_db"."delta_table" VERSION AS OF 2;`

But running this syntax in athena results in the following error:
`line 1:71: mismatched input 'AS'. Expecting: '(', ',', 'CROSS', 'EXCEPT', 'FULL', 'GROUP', 'HAVING', 'INNER', 'INTERSECT', 'JOIN', 'LEFT', 'LIMIT', 'NATURAL', 'OFFSET', 'ORDER', 'RIGHT', 'TABLESAMPLE', 'UNION', 'WHERE', <EOF>`

Obs.: The manyfest file creation step and the CREATE EXTERNAL TABLE from athena step described in https://docs.delta.io/latest/presto-integration.html#presto-and-athena-to-delta-lake-integration were also executed prior to the above SQL query attempt

Any clarification regarding the matter would be really appreciated!
Thanks in advance!

**Comment by fedsp** [comment]
I upvote this

**Comment by zsxwing** [comment]
AFAIK, the `VERSION AS OF` syntax is not supported by Presto/Athena. https://github.com/prestodb/presto/pull/16843 is building a native Presto connector which will support time travel like `select * from mytable@v123`.

**Comment by fedsp** [comment]
And there is any other SQL syntax that allow time travel? (using SQL statements only)

**Comment by zsxwing** [comment]
Spark or Presto? For Spark you can watch #128. For Presto, it's better to raise the request to the Presto community. Spark and Hive will support time travel syntax in the next version:
- https://issues.apache.org/jira/browse/SPARK-37219
- https://issues.apache.org/jira/browse/HIVE-25344

**Comment by fedsp** [comment]
My usecase uses presto, more specifically the presto custom version that runs on aws athena.

**Comment by GabrielAmazonas** [comment]
> AFAIK, the `VERSION AS OF` syntax is not supported by Presto/Athena. [prestodb/presto#16843](https://github.com/prestodb/presto/pull/16843) is building a native Presto connector which will support time travel like `select * from mytable@v123`.

Thanks for commenting - Just tested the above syntax in Athena, and the result was as follows:

`SELECT * FROM "delta_db"."delta_table"@v17`

line 1:62: mismatched input '@'. Expecting: ',', '.', 'AS', 'CROSS', 'EXCEPT', 'FOR', 'FULL', 'GROUP', 'HAVING', 'INNER', 'INTERSECT', 'JOIN', 'LEFT', 'LIMIT', 'NATURAL', 'OFFSET', 'ORDER', 'RIGHT', 'TABLESAMPLE', 'UNION', 'WHERE', <EOF>, <identifier>

**Comment by zsxwing** [comment]
> Just tested the above syntax in Athena, and the result was as follows:

https://github.com/prestodb/presto/pull/16843 is still in progress.

**Comment by GabrielAmazonas** [comment]
@dennyglee , thanks for tagging the issue! Here's the response from the AWS support team ( Just in case it helps somebody else in a similar situation) :
"
Hello Gabriel,

Thank you for contacting AWS Premium Support. I understand that you were not able to query the previous version in delta lake using Athena.

After taking the case offline, I have reviewed the delta lake docs, Athena docs internal and external but was not able to find any information hinting the ability to query previous version of data using Athena. However, the only way I have found is by not updating the manifest file i.e., if the manifest file is not updated Athena will refer to old version of data. As per the docs you provided, automatic manifest update can be disabled by

ALTER TABLE delta.`<path-to-delta-table>` SET TBLPROPERTIES(delta.compatibility.symlinkFormatManifest.enabled=true)

However, I have not found any way to query older copy of data using Athena like in Spark.

We value your feedback. Please share your experience by rating this correspondence using the AWS Support Center link at the end of this correspondence. Each correspondence can also be rated by selecting the stars in top right corner of each correspondence within the AWS Support Center.

Best regards,
Manu G.
Amazon Web Services
"

**Comment by dennyglee** [comment]
Hi @GabrielAmazonas 

Please note that the manifest method itself isn't really designed for time travel per se - the manifest contains the list of files that are comprised of a table.  You could presumably create a manifest based on a previous version of the table but that is not supported.

Saying this, as soon as we have the Presto and Trino connectors completed, as @zsxwing noted, this will include the syntax needed for Presto and Trino to be able to perform time travel queries from Delta.  We will also follow up with the Athena team to see incorporate these connectors.

HTH!
Denny

**Comment by dennyglee** [comment]
Closing this issue; please re-open if this issue if any other questions.
