### ISSUE TITLE
Register Vacuum in the table history

### ISSUE THREAD

**Issue by tdas** [delta-io/delta#868]
In Databricks Delta, Vacuum operation is recorded in the delta log, but not in OSS delta.

https://delta-users.slack.com/archives/CJ70UCSHM/p1639536627227800

This tracks the OSS work to make it work in oss Delta.

**Comment by YannByron** [comment]
@tdas that will be great if can release this feature in OSS delta.
In my case, i need to trace the whole lifecycle of the files by capture the delta log's update.

**Comment by zsxwing** [comment]
@YannByron are you interested in working on this?

**Comment by YannByron** [comment]
> @YannByron are you interested in working on this?

sure. Let me take up this.

**Comment by keen85** [comment]
Hi everyone,
will this log entry for `VACUUM` also contain some [operational metrics](https://docs.delta.io/latest/delta-utility.html#operation-metrics-keys), like number/size of deleted files?
If so, would it be possible to **_have those operational metrics also as return value of the VACUUM operation_** itself?
Currently (at least in Delta 1.2) it does not return anything but only [writes to the console](https://github.com/delta-io/delta/blob/2e068af8d0bf5ae8ecbe36e2e8f3937966d5b2b9/core/src/main/scala/org/apache/spark/sql/delta/commands/VacuumCommand.scala#L282:L283) some entries like "Deleted 298 files and directories in a total of 6368 directories."

**Comment by YannByron** [comment]
@keen85 yes. In this pr (https://github.com/delta-io/delta/pull/1451) , number/size of deleted files will be returned as the output.
