### ISSUE TITLE
Parquet column encryption support for Delta

### ISSUE THREAD

**Issue by RobindeGrootNL** [delta-io/delta#870]
Recently, parquet added support for columnar/modular encryption in version parquet-mr 1.12 ([IBM](https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=scripts-parquet-encryption), [GitHub](https://github.com/apache/parquet-mr/blob/master/CHANGES.md)), meaning that only the footer file and certain columns of the parquet file are encrypted, minimising encrypt/decrypt overhead while keeping sensitive columns safe. Since Delta is built on top of parquet files and this encryption method became available in Spark 2.3.0 (which the latest Delta version supports), I was wondering if Delta already supports this due to being built on the parquet format or if there is a way to make it work. For my application that would be the perfect combination! (incrementally adding rows while keeping some columns encrypted to keep PII safe).

`df.write.option("parquet.encryption.footer.key", "k1").option("parquet.encryption.column.keys", "k2:DeviceName,image_id").parquet(STORE_PATH`

This is how it works with spark dataframes in Databricks (which is what I am using). I tried to do something very similar for Delta as follows:

`df.write.option("parquet.encryption.footer.key", "k1").option("parquet.encryption.column.keys", "k2:DeviceName,image_id").format("delta").mode("overwrite").save(STORE_PATH_DELTA)`

This did work but the Delta table was able to be opened from a cluster not having the encryption keys, meaning the encryption did not actually work. I also tried to use DeltaTable.convertToDelta() on the encrypted parquet files (both in scala spark and PySpark) and this also did not work as the Delta table was not encrypted.

Any help with getting it to work with Delta would be highly appreciated, but learning that this is no (yet) supported and that there is no workaround would also be helpful since I can then look at different options. Thanks in advance!

**Comment by zsxwing** [comment]
Delta doesn't support encryption even if parquet supports. A Delta table contains data files and transaction logs. The transaction logs are in json format, we will also create parquet checkpoint to optimize the transaction log reading. But the json files will not be encrypted even if parquet files are encrypted.

Will enabling the encryption in the storage system layer be a sufficient workaround for you?

**Comment by RobindeGrootNL** [comment]
Thank you for the very fast response. I understand how the way Delta works makes it difficult/impossible to support this type of encryption (and was already fearing this would be the case, but nothing ventured nothing gained :) ).

I will indeed look at such other solutions, though this would've been a beautiful one considering EU regulation (Schrems 2.0 etc.). Again thank you for the response, I'll close the issue now that my questions have been answered!

**Comment by SomanathSankaran** [comment]
@zsxwing can we encrypt the data files alone

**Comment by anthonyhungnguyen** [comment]
Can we reopen this request?

**Comment by samzys** [comment]
hi all, Could we consider revisiting this topic for further discussion? I have some ideas in mind:

Is it possible to implement Parquet's built-in encryption feature for the data files?
Perhaps we could apply the identical footer key encryption configuration to secure the entire metadata file (the JSON file).
If anyone has suggestions or guidance, especially regarding specific sections of the code base we should concentrate on, it would be greatly beneficial as we explore this option.
