### ISSUE TITLE
MERGE fails when Dataframe has an Array<Struct> column

### ISSUE THREAD

**Issue by omardoma** [delta-io/delta#875]
I have a PySpark Dataframe with some column transforms that look like that:

```python
df.withColumn('offices', F.array(
  F.struct(
    F.col('OfficeAddress').alias('office_address'),
    F.col('OfficeEmail').alias('office_email'),
    F.col('OfficeName').alias('office_corporate_name'),
    F.col('OfficePhone').alias('office_phone_number')
  )
))
```

The transform itself works fine with the correct output, however, when used in a pipeline utilizing MERGE, it fails and throws the following confusing error:

> pyspark.sql.utils.AnalysisException: cannot resolve 'transform(new_data.agent_offices, lambdafunction(new_data.agent_offices[namedlambdavariable()], namedlambdavariable(), namedlambdavariable()))' due to data type mismatch: cannot cast array<struct<office_address:string,office_email:string,office_corporate_name:string,office_phone_number:string>> to array<struct<office_address:string,office_email:string,office_corporate_name:string,office_phone_number:string>>;

The types are exactly the same and it says cannot cast T to T.

The MERGE code looks something like that:

```python
def upsert_data(df, batch_id):
  delta_table = DeltaTable.forPath(spark, TABLE_PATH)
  deduped_df = df.withColumn('row_number', F.row_number().over(Window.partitionBy(F.col('id')).orderBy(F.col('timestamp').desc()))) \
                 .where('row_number = 1') \
                 .drop('row_number')
  delta_table.alias('data') \
       .merge(deduped_df.alias('new_data'), 'data.id = new_data.id') \
       .whenMatchedUpdateAll('data.timestamp < new_data.timestamp') \
       .whenNotMatchedInsertAll() \
       .execute()

df.writeStream \
  .format('delta') \
  .trigger(once=True) \
  .option('checkpointLocation', CHECKPOINT_PATH) \
  .foreachBatch(upsert_data) \
  .outputMode('update') \
  .start()
```

Happens on Databricks Runtime 9.1 LTS, 10.1 & 10.2 Beta

**Comment by tdas** [comment]
Since this is reproducible on Databricks Delta, could you find a support ticket with Databricks. It will be helpful to dig deeper specifically in your setup. There maybe some invisible differences (e.g. nullability) that may be causing this, but the invisible in the error message.

Alternatively, can you print the full json of the deduped_df schema and the target table schema? and then compare them. printing the json can highlight differences that invisible in the plan string representation in the error message.

**Comment by omardoma** [comment]
Thank you for the suggestions, I have opened a ticket with Databricks and will post an update with the findings and whether there is a bug indeed or not as soon as we get somewhere in the debugging.

**Comment by omardoma** [comment]
I am still waiting on Databricks Support feedback, however I have went ahead and compared the JSON schema of the 
Delta Table and the `deduped_df` :

<img width="1050" alt="Screen Shot 2021-12-22 at 1 32 55 PM" src="https://user-images.githubusercontent.com/25301162/147093385-d284c058-c231-4af6-9f24-1c0f4f4df9fb.png">


As you can see they are identical, which hints that there might be a bug in the MERGE logic that compares the schemas.

**Comment by omardoma** [comment]
One thing to mention as well is that I have tried toggling the `spark.databricks.delta.schema.autoMerge.enabled` option and running in each mode but it didn't help.
I have also tried deleting the table altogether and running the pipeline from scratch, but it also didn't help.

**Comment by tdas** [comment]
Since this is a Databricks issue, I dont want to ask for details that might be PII or proprietary in this public forum. Please make sure to add stack traces, and if possible a reproducible example (e.g., notebook) to that Databricks ticket. Alternatively, if you can reproduce this issue locally as standalone example using delta OSS, then we can take a look as well.

**Comment by otosky** [comment]
@omardoma did you ever determine the root cause here?  I've recently experienced the same issue on DBR 9.1LTS & 10.3 in a Structured Streaming job, but have not been able to reproduce the issue with test data.

**Comment by omardoma** [comment]
@otosky Unfortunately not. We were tight on time to get a pipeline released, so I had to workaround it by using a UDF instead of native spark array functions for now.

**Comment by yijiacui-db** [comment]
This issue was root-caused and fixed. You can use the latest DBR releases or OSS Delta to test. cc: @omardoma @otosky
