### ISSUE TITLE
Spark task failure with ClassCastException [C cannot be cast to [J, at org.apache.spark.unsafe.memory.HeapMemoryAllocator.allocate

### ISSUE THREAD

**Issue by arunbenoyv** [delta-io/delta#894]
We were using spark 3.0.0 and delta lake 0.7.0 after upgrading to Spark 3.2.0 and delta 1.1.0, we can see the following exception (under load of 100K events)

Caused by: java.lang.ClassCastException: [C cannot be cast to [J, at org.apache.spark.unsafe.memory.HeapMemoryAllocator.allocate(HeapMemoryAllocator.java:58) , at org.apache.spark.memory.TaskMemoryManager.allocatePage(TaskMemoryManager.java:314)

Details provided in stackoverflow
https://stackoverflow.com/questions/70664397/spark-task-failure-with-classcastexception-c-cannot-be-cast-to-j-at-org-apach

**Comment by zsxwing** [comment]
Could you create an issue for Spark ( https://issues.apache.org/jira/browse/SPARK )? This should be a Spark bug.

**Comment by zsxwing** [comment]
Thanks! Could you post the Spark jira link here for future reference and close this ticket after that?

**Comment by arunbenoyv** [comment]
Issue link in Spark JIRA : https://issues.apache.org/jira/browse/SPARK-37892

**Comment by zsxwing** [comment]
Thanks for creating the ticket! I'm closing this for now
