### ISSUE TITLE
Delta protocol cant be recovered from databricks generated table.

### ISSUE THREAD

**Issue by warrenronsiek** [delta-io/delta#896]
I'm trying to remove a couple partitions from a delta table in Databricks and then write to it from EMR, but when I do I get the following error:

```
User class threw exception: java.lang.IllegalStateException: 
The protocol of your Delta table couldn't be recovered while Reconstructing version: 1. Did you manually delete files in the _delta_log directory? Set spark.databricks.delta.stateReconstructionValidation.enabled to "false" to skip validation.
```
When I know that no such deletion has occurred. 

Steps:

1. start with a working delta table that I insert data into every day and deep copy it:
```
val oldtable = DeltaTable.forPath("s3://oldbucket/oldpath/")
oldtable.clone("s3://newtable/newpath/", false, true)
```
2. Repartition the data. I have verified that this works - I checked manually and I can read/compute stats on this table.
```
val newtable = DeltaTable.forPath("s3://newtable/newpath/")
newtable
  .toDF
  .drop("bad_partition")
  .repartition($"date")
  .write.format("delta")
  .mode("overwrite")
  .option("overwriteSchema", "true")
  .partitionBy("date") 
  .save("s3://newtable/newpath/")
newtable.vacuum()
```
All these commands happen within databricks.

But then I try to write to the same table from EMR:
```
val dTable = DeltaTable.forPath(writePath)
dTable.as("previous")
  .merge(df.repartition(partitionColNames.map(n => col(n)) : _*).as("new"), mergeCondition)
  .whenNotMatched()
  .insertAll()
  .whenMatched()
  .updateAll()
  .execute()
```
I get the previous exception. My EMR cluster is single master, and there are no other jobs writing to the table at the same time - the copy and the write happen sequentially. The read/write versions of the new table and the old table are the same.

I've tried repairing the table with FSCK REPAIR TABLE  and all sorts of permutations on copying/repartitioning but the error persists. Searched all over but haven't seen this issue anywhere else. Raised the issue internally with Databricks and they said I should come here.

**Comment by scottsand-db** [comment]
Hi @warrenronsiek. Thanks for making this issue. We will take a look and get back to you.

**Comment by zsxwing** [comment]
@warrenronsiek Since you hit the problem in Databricks platform, could you fire a Databricks support ticket instead? Then Databricks support team can chat with you to gather more information. For issues like this, we may need to check the content in your table's `_delta_log` folder. Don't want to ask you to post the content in a public forum as it may contain sensitive data.

**Comment by warrenronsiek** [comment]
@zsxwing , I did raise an issue with them. After a little back and forth, they told me to raise an issue here. You are saying I should go back to them?

WRT the `_delta_log` isn't it just metadata about files? Metadata about files isn't sensitive AFAIK.

**Comment by zsxwing** [comment]
> WRT the `_delta_log` isn't it just metadata about files? Metadata about files isn't sensitive AFAIK.

If you are okay to share all of the content in `_delta_log`, it would be fine. Just a reminder that the metadata may contain table schema, partition column values and file stats (file stats will be generated from the table data)

**Comment by zsxwing** [comment]
By the way, does the error only happen when you run the code in EMR? Does it happen if you run the same code in Databricks?

**Comment by warrenronsiek** [comment]
The error happens when I try to write to the table from EMR. Presumably, that would happen if I tried to read from it as well. From inside Databricks I can read from the table no problem.

**Comment by warrenronsiek** [comment]
Actually, I think this might be a permissions issue. I'll get back to you on Monday.

**Comment by warrenronsiek** [comment]
@zsxwing / @scottsand-db , Ok so I'm 90% certain that this is a permissions issue. When I try to access the ACL of the databricks written file I'm not allowed to do that. Despite Databricks writing with "BucketOwnerFullControl" its not actually giving me full control of the files. 

I'm closing this issue, but it seems that at some point an IAM permissions failure and is translating into a `IllegalStateException` which is misleading. That might be something to change, but its not why this ticket was opened.
