### ISSUE TITLE
Make Delta compile with mvn

### ISSUE THREAD

**Issue by shenh062326** [delta-io/delta#90]
We have used Delta, but we use mvn as a compilation tool in our company. If we can make Delta compile with mvn, it will be more friendly.

**Comment by marmbrus** [comment]
I think it is unlikely that we will change as most of Apache Spark and Delta development is done with SBT.  It is the tool most of the developers prefer.

However, you should be able use to releases of Delta with Maven without ever having to interact with SBT. See the docs for instructions [on how to Delta to your maven pom file](https://docs.delta.io/latest/quick-start.html#maven). Does that help?

**Comment by shenh062326** [comment]
Thanks for your comments, but what I want is to add maven build file to Delta, just like Spark, it can build with maven.

**Comment by tdas** [comment]
Can you elaborate on why do you want to do that? As @marmbrus pointed out for most purposes of using Delta, you can use Maven dependencies directly. So what is your goal here?

**Comment by shenh062326** [comment]
We not only use Delta, but also do some development based on Delta, so we hope that Delta can be compiled by maven like spark.

**Comment by zsxwing** [comment]
Closing this old ticket as we don't have any plan to support the maven build.
