### ISSUE TITLE
Table Delta in Athena

### ISSUE THREAD

**Issue by JosefinaArayaTapia** [delta-io/delta#901]
When creating a table in Athena and reading it from Spark (EMR) I get the following error : 

`Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 80.0 failed 4 times, most recent failure: Lost task 0.3 in stage 80.0 (TID 449, ip-172-31-22-178.ec2.internal, executor 2): java.lang.RuntimeException: s3://<path>/BDA/DELTA/CLIENTE/_symlink_format_manifest/PERIODO=202001/manifest is not a Parquet file. expected magic number at tail [80, 65, 82, 49] but found [117, 101, 116, 10]
`

If I perform the same sql query from Athena there are no problems.

**Comment by zsxwing** [comment]
The table reference created in Athena cannot be used by Spark. You can create a new table reference to point to the same storage location for Spark, and use this new table name in Spark.

**Comment by zsxwing** [comment]
The question was answered. Closing this. Feel free to re-open it if you have further questions.
