### ISSUE TITLE
Should the `AddFiles` from `DELETE` have `dataChange=true`?

### ISSUE THREAD

**Issue by praateekmahajan** [delta-io/delta#906]
As title. Noticed internally that we need to perform GDPR deletes on our delta table which is a streaming source, however on performing the delete, several files will be rewritten. And from our experiment the _new files_ that are added do not have `dataChange=false` which means the streaming will pick them up again ([per this](https://github.com/delta-io/delta/blob/0d07d094ccd520c1adbe45dde4804c754c0a4baa/core/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSource.scala#L229-L232)).

```scala

import org.apache.spark.sql.{functions=>F}


val sourceTable = "test_delete_change_data"

spark.sql(s"DROP TABLE IF EXISTS $sourceTable")
// Set to false so we can control how many files we create
spark.sql("set spark.databricks.delta.optimizeWrite.enabled = false;")
spark.sql("set spark.databricks.delta.autoCompact.enabled = false;")
spark.sql("set spark.databricks.delta.properties.defaults.autoOptimize.optimizeWrite = false;")
spark.sql("set spark.databricks.delta.properties.defaults.autoOptimize.autoCompact = false;")

val _ = spark.range(100)
        .repartition(4) // To create 4 files only
        .write.format("delta")
        .mode("overwrite")
        .saveAsTable(sourceTable)

val checkpointLocation = spark.sql(s"DESCRIBE DETAIL $sourceTable").select("location").collect().head.getString(0)


// This display shows original files
display(spark.read.json(s"${checkpointLocation}/_delta_log/00000000000000000000.json").filter(F.col("add").isNotNull).select("add.*"))

// Perform the delete
display(spark.sql(s"DELETE FROM $sourceTable WHERE id % 20 == 0"))

// This shows the file added from the second commit
display(spark.read.json(s"${checkpointLocation}/_delta_log/00000000000000000001.json").filter(F.col("add").isNotNull).select("add.*"))

```

Sorry if I missed something totally obvious.

**Comment by tdas** [comment]
The strict definition of `dataChange` field is to specify whether the file add/remove actually made semantic changes to the data. It is set to `false` for all add/remove files in a commit ONLY when data is just rearranged in the table, and no semantic changes made contents of the table. Delete operation does make semantic changes, thats why dataChange must be set to true. 

To solve your usecase of reading only changes, you should use [Change Data Feed](https://docs.databricks.com/delta/delta-change-data-feed.html). This is currently only in Databricks Delta but we are considering open sourcing this.

**Comment by praateekmahajan** [comment]
Thanks for the reply! 
CDF Makes sense, most of our streaming pipelines predate CDF (we'll be moving to it pretty soon now). We had implemented our _own CDF_ to bypass `MERGE INTO` in our streaming sources which also causes reprocessing of already processes rows. However that doesn't solve the `DELETE` case.

Semantically it makes sense that `dataChange = false` implies "no semantic changes made contents of the table", however one would imagine there is a middle ground between "no semantic changes" and "reprocess all the data for streaming source because we don't know if it's a semantic change".. something like "intentional semantic changes which need not be reprocessed". But I guess that's easier said than done, and adding another boolean (or a variation) causes a bit more complexity.

Feel free to close this issue, as I understand it's a feature not a bug, and we could probably open another issue if need be about having something like `intentionalDataChange` 😄 !

**Comment by tdas** [comment]
You are right about extending the protocol to accommodate the middle ground, and the complexity that comes with it. That's why took a different approach with CDF. Hope that helps to solve your problem :)

Closing this issue
