### ISSUE TITLE
Create GitHub issue and pull request templates

### ISSUE THREAD

**Issue by zsxwing** [delta-io/delta#917]
Currently we don't GitHub issue and pull request templates. It would be great to add them to help Delta users report issues and contribute code.

Template examples:
- https://github.com/apache/spark/blob/master/.github/PULL_REQUEST_TEMPLATE
- https://github.com/netty/netty/tree/4.1/.github
- https://github.com/line/armeria/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by ahlag** [comment]
@zsxwing 
Is it possible to help out with this issue? I am still a beginner.

**Comment by ahlag** [comment]
@zsxwing 
Okay thank you for the guidance! Let me get to it.

**Comment by ahlag** [comment]
@zsxwing 

I have done research on a few pull request templates. Please share with me your thoughts on this PR. You can find my pull request in this [PR](https://github.com/delta-io/delta/pull/942#related-issue). In the meantime, I'll work on the issue template.

Reference:
1. https://gitlab.com/autowarefoundation/autoware.auto/AutowareAuto/-/merge_requests/1346#notes-for-reviewer
2. https://github.com/autowarefoundation/autoware.universe/blob/tier4/proposal/.github/PULL_REQUEST_TEMPLATE.md?fbclid=IwAR3QTvDiHb88yT_UqQmf5z7aiOQNaudPi1Sh-p4zrefs6yvjbqw8OFKbL4o
3. https://github.com/line/armeria/blob/master/.github/PULL_REQUEST_TEMPLATE.md
4. https://github.com/netty/netty/blob/4.1/.github/ISSUE_TEMPLATE.md
5. https://github.com/apache/spark/blob/master/.github/PULL_REQUEST_TEMPLATE
