### ISSUE TITLE
DescribeDeltaDetailsCommand doesn't call DeltaLog.update

### ISSUE THREAD

**Issue by zsxwing** [delta-io/delta#921]
DescribeDeltaDetailsCommand doesn't call `DeltaLog.update` after `DeltaLog.forTable`: https://github.com/delta-io/delta/blob/1fcb1dacc8d4ec671cd499676bb61d55d343cc2a/core/src/main/scala/org/apache/spark/sql/delta/commands/DescribeDeltaDetailsCommand.scala#L79

Hence it may return a stale result if `DeltaLog.forTable` returns a cached `DeltaLog`.

**Comment by stikkireddy** [comment]
@zsxwing the change i am assuming is to call a simple `deltaLog.update()`. 

How would you test this? I notice that the DeltaLog startTransaction seems to be calling an update. Does this happen when potentially an entirely different spark cluster/client creates a transaction and this detail will return a stale result due it just fetching from the cached log?

**Comment by zsxwing** [comment]
> Does this happen when potentially an entirely different spark cluster/client creates a transaction and this detail will return a stale result due it just fetching from the cached log?

Right. To simulate this, we can write a test case like this:

```
create a delta table

val deltaLog = DeltaLog.forTable(spark, ...) // Keep the current DeltaLog
DeltaLog.clearCache() // Remove the above DeltaLog from the cache

sql("desc detail ...") // Cache a new DeltaLog

val txn = deltaLog.startTransaction()
val newMetadata = txn.snapshot.metadata.copy(configuration = metadata.configuration ++ Map("foo" -> "bar"))
txn.commit(newMetadata, DeltaOperations.ManualUpdate)

Now run desc detail again to verify we can see the new added table properties.
```

**Comment by dragongu** [comment]
@zsxwing  I am a new Delta user and  ready to tackle the issue, Can you assign it to me? thanks

**Comment by zsxwing** [comment]
@dragongu done. Thanks for the contribution!

**Comment by zsxwing** [comment]
Fixed by #1133

**Comment by dragongu** [comment]
Why was it closed, but not merged?

**Comment by zsxwing** [comment]
@dragongu the fix has been merged to master: https://github.com/delta-io/delta/commit/32c3681f37a01d10565c21b70e1296bba0b2ea25

We don't use GitHub merge button to merge PRs so that the status of a PR will always be `closed`. You can see the bottom in the PR which should have a comment showing which commit contains the change.
