### ISSUE TITLE
Support for per-column statistics generation on Delta Lake

### ISSUE THREAD

**Issue by scottsand-db** [delta-io/delta#923]
## Overview
This is the official issue to track interest, feature requests, and progress being made on per-column statistics generation in Delta Lake. This issue is the first part to the solution of “File skipping using columns stats” as outlined on the Delta OSS 2022 H1 roadmap [here](https://github.com/delta-io/delta/issues/920).

Statistics generation is a prerequisite for actual data skipping. First we must write the per-file statistics into the Delta Log, and only then can we leverage those statistics to safely skip files during reads.

## Requirements
Per-column statistics generation means the following: during data writes, we keep track of basic statistics (minimum, maximum, etc.) on a per-file level for all columns, including nested columns.

Since this statistics generation will likely slightly impact data write overhead, users should easily be able to enable/disable this feature, and it should also be tunable (i.e. specify for how many columns that statistics should be collected).

## Design Sketch
Please see the attached Google Document [here](https://docs.google.com/document/d/14Tesce--T6b6O8qqyCiFYTBx_xzp3gDPYFFpmEVDcAE/edit?usp=sharing) outlining the proposed, and subject to change, basic design sketch.

## Future Work
After this issue is resolved, we should actually read these per-file statistics at query planning time to implement file skipping.

**Comment by tdas** [comment]
this will be awesome. pinning this issue.

**Comment by Kimahriman** [comment]
One thing that would be nice is being able to specifically choose which fields you collect stats on

**Comment by scottsand-db** [comment]
Hey @Kimahriman - the API I've proposed uses `DATA_SKIPPING_NUM_INDEXED_COLS` - so you set which first `N` columns you would like to collect stats for. Would this work for you?

If not, what sort of API do you have in mind to specifically choose which fields we collect stats on?

**Comment by Kimahriman** [comment]
In my case not super well, because we have a lot of nested data and it'd be hard to control the order of all the fields I'd care about most.

As for API, not really sure. Either something with schema metadata (I think that's how generated columns work?) that could maybe part of the table builder API or something? Or some table property that's just a list of paths of fields that gets checked during the stats collection process? Only very briefly scanned the initial PR

**Comment by scottsand-db** [comment]
@Kimahriman why don't you make an OSS issue about this, and we can see what other community members think about possible different APIs? We can always add this feature in a future PR.

**Comment by Kimahriman** [comment]
> t possible different APIs? We can always add this feature in a future PR.

Sounds good, definitely doesn't need to be part of the initial release, just a nice to have I thought about
