### ISSUE TITLE
Worse Upsert / Deduplication Performance in comparison to "plain" Spark

### ISSUE THREAD

**Issue by GRBurst** [delta-io/delta#935]
Hey 👋 

we are currently investigating switching from "plain" spark to using your delta lake which sounds like it suits us.

Our processing and current approach to deal with deduplication (not real duplicates but similar semantics) and keep the latest duplicate record is as follows:

1. New data is read from json
2. New data is processed / refined
3. All current data is read from target location
4. Data is deduplicated by combining current data with new data with `union`, sorting it with a window function and drop all records except the newest
5. Deduplicated data is written to a cache
6. Data is written to final target location

By using delta lake, we can replace (4.), (5.) and (6.) with an upsert statement like this:
```scala
val current = "current"
val new = "updates"

    deltaTable
      .as(current)
      .merge(
        newData.as(new),
        uniqueFields.map(key => s"$current.$key = $new.$key").mkString(" AND ")
      )
      .whenMatched("$current.date < $new.date")
      .updateAll()
      .whenNotMatched()
      .insertAll()
      .execute()
```

This results in the expected data (so we get the same data from both pipelines). However, using delta lake with an upsert like above is about 1.5 - 2 times slower than our current approach. The `whenMatched` clause is a bit more complex but roughly speaking is the translated version of the sorting in (4.).

Some more context about the environment:
- AWS EMR 6.5.0
- Spark 3.1.2
- Scala 2.12
- Delta Lake 1.0.0
- There is a relatively small number of files on the delta lake side (above referred to as target location)
- We have tried to disable Adaptive Query Execution (enabled is faster)
- For broadcast join to work we have increased the size to 4GB (in)
- Our test cluster consists of 16 execution nodes, new data is in the magnitude of 1GB and whole magnitude of 100GB with a few million records.

Is it usually the case that the performance decreases because of the additional overhead? I honestly expected a negligible overhead or even a performance increase (since not all data has to be read for the upsert and afterwards copied over).

Any suggestions how this can be improved or pointers on what to double check?

Happy to hear from you :-)

**Comment by scottsand-db** [comment]
Hi @GRBurst - are you partitioning your table? If so, are any of these partition columns part of the `uniqueFields`?

**Comment by scottsand-db** [comment]
You can also repost this question in the [Delta Users Slack](delta-users.slack.com)#deltalake-oss channel

**Comment by scottsand-db** [comment]
You can also check out the [performance tuning](section) of the delta lake docs to see if any of those tips are applicable to you (since I don't know enough about your schema / partitioning)

**Comment by GRBurst** [comment]
Hey @scottsand-db, thanks for your response! :+1: 

This was a bit off my radar, so took a while for me to answer. So yes, the data is partitioned fields that are part of `uniqueFields`. In some use-cases `uniqueFields` contains more fields than the partition fields and sometimes not. 

I did performance tuning already and measures before I wrote the issue here (and it improved the performance slightly).
However, if a the new data contains a lot of duplicates, the performance decreases quite a bit.

On a few performance measures, I could see that if new data is approx the same as current data (so consist of basically only duplicates), the approach using DeltaLake as described is approx 1.6x slower than doing `(newData union currentData).dedupliate` approach (step 4. onwards in the description).

**Comment by GRBurst** [comment]
We can live with this, so it is not a show stopper - but it is still a bit unfortunate ;-)

I guess for such a use case, when data is not toooo big and there are a lot of dupicates, spark is just better with the union approach instead of using (broadcast) joins here.

**Comment by tdas** [comment]
@GRBurst thank you for comparing performance between these 2 approaches. It complete makes sense for the your specific size of data, you can do something that is faster than the merge implementation, which was designed to decent for any amount of data and may not be the best for smaller changes. There is definitely scope for improving our merge as well. For that it would be good to know the details of your workload. Would be able to share the metrics generated by merge operation as visible in the `describe history` command after running the merge? 

That will help us debug the performance bottleneck in our merge for your workload. Also, if you want to learn more about how merge works you can [take a look at this talk](https://www.youtube.com/watch?v=7ewmcdrylsA) (sorry for the shameless plug :) ). The metrics would help us understand which phase of the merge operation is the bottleneck.

**Comment by scottsand-db** [comment]
@GRBurst just following up on this. As TD asked,

> it would be good to know the details of your workload. Would be able to share the metrics generated by merge operation as visible in the describe history command after running the merge?
