### ISSUE TITLE
delta/PROTOCOL.md is vague w.r.t. the schema of checkpoint files

### ISSUE THREAD

**Issue by JFinis** [delta-io/delta#940]
I'm trying to use the spec to implement a reader, but [the spec](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#checkpoint-schema) is too vague on what the schema of a checkpoint file is supposed to be. Here are points that are not specified:

* Which columns does a checkpoint file contain. The spec only gives _an example_ of what columns it contains for _a specific table_, but it doesn't mention whether any possible checkpoint files will have exactly these columns for any conceivable table. Definition by example is nice, but at least a short sentence whether all files will look that way or in what way they can differ would be necessary to implement a reader that can read all allowable checkpoint files.
* Are implementations allowed to add further columns to a checkpoint file? I have seen columns named 'cdc' and 'commitInfo' in the wild, but they are not mentioned in the spec. Are readers supposed to allow and ignore all columns that are not in the spec and assume that they will never change the semantics of the delta lake?
* Is column lookup in the checkpoint file supposed to be by name or by position? I.e., say I have a checkpoint file whose first column is 'metaData' and second column is 'txn'. This order is different from the order in the spec (but I do have such a file). Is this a valid checkpoint file? I guess the answer is yes, but for a spec, it would be nice to be precise here.

**Comment by zsxwing** [comment]
@JFinis These are good points. Thanks! Are you interested in submitting a PR to improve the spec?

**Comment by scottsand-db** [comment]
@JFinis just following up :) would you like to make a quick fix for this?

**Comment by JFinis** [comment]
@scottsand-db @zsxwing Given that this is a spec and implementations already exist, I have a hard time proposing a fix here, as I honestly don't know what the desired semantics is supposed to be. Of course, I could just pick the answer I like most for all my questions, but that might mean that the spec gets specced in such a way that implementations don't conform to it anymore.

I guess it might therefore be more beneficial if someone who has deeper knowledge in the reference implementation proposes a wording that makes at least that implementation adhere to the spec.

**Comment by scottsand-db** [comment]
Closing as this is also duplicated in https://github.com/delta-io/delta/issues/1284. There, I have clarified the checkpoint schema. Anyone is welcome to assign that issue to themselves and update the PROTOCOL.md. Thanks!
