### ISSUE TITLE
Delta LogStore Refactor - AzureLogStore

### ISSUE THREAD

**Issue by scottsand-db** [delta-io/delta#953]
Refactor [AzureLogStore](https://github.com/delta-io/delta/blob/master/core/src/main/scala/org/apache/spark/sql/delta/storage/AzureLogStore.scala) to Java for the new delta-storage artifact.

For the project overview, requirements, and how to contribute, please see the https://github.com/delta-io/delta/issues/951.

**Comment by ksree** [comment]
Hi @scottsand-db , I would like to give this a try.

**Comment by scottsand-db** [comment]
@ksree awesome. let me know when the PR is ready for review. thanks!

**Comment by ksree** [comment]
@scottsand-db  I raised a separate [PR](https://github.com/delta-io/delta/pull/993)  to include writeWithRename method from HadoopFileSystemLogStore.java . I will test it part of AzureLogStore implementation. Let me know if that makes sense.

**Comment by scottsand-db** [comment]
@ksree awesome! Taking a look.

**Comment by ksree** [comment]
@scottsand-db Any idea when [PR-993](https://github.com/delta-io/delta/pull/993) will be merged? This issue is dependant on that one.

**Comment by scottsand-db** [comment]
Hopefully today :) It's on my todo list, thanks for following up!

**Comment by scottsand-db** [comment]
@ksree merged

**Comment by ksree** [comment]
@scottsand-db [PR]( https://github.com/delta-io/delta/pull/1003) is ready for review.

**Comment by vkorukanti** [comment]
Closed via https://github.com/delta-io/delta/commit/f3add0beba00327b83b0de24823b1c043288aaf5
