### ISSUE TITLE
Delta LogStore Refactor - DelegatingLogStore

### ISSUE THREAD

**Issue by scottsand-db** [delta-io/delta#954]
Refactor [DelegatingLogStore](https://github.com/delta-io/delta/blob/master/core/src/main/scala/org/apache/spark/sql/delta/storage/DelegatingLogStore.scala) to Java for the new delta-storage artifact.

For the test, you should be able to make `DelegatingLogStoreSuite` be an abstract class (`DelegatingLogStoreSuiteBase`) and create both Internal and Public child implementations.

Each child could implement a method to instantiate the right LogStore, e.g. to replace the `new DelegatingLogStore()` call inside of `testDelegatingLogStore`.

A similar example to this is [LineCloseableIteratorSuite](https://github.com/delta-io/delta/blob/master/core/src/test/scala/org/apache/spark/sql/delta/storage/LineClosableIteratorSuite.scala)

For the project overview, requirements, and how to contribute, please see the https://github.com/delta-io/delta/issues/951.

**Comment by scottsand-db** [comment]
I'll take this

**Comment by vkorukanti** [comment]
Closed via https://github.com/delta-io/delta/commit/c068f5abd6146f8d94e87b29cddb6af51a6b6d44
