### ISSUE TITLE
Delta LogStore Refactor - LocalLogStore

### ISSUE THREAD

**Issue by scottsand-db** [delta-io/delta#955]
Refactor [LocalLogStore](https://github.com/delta-io/delta/blob/master/core/src/main/scala/org/apache/spark/sql/delta/storage/LocalLogStore.scala) to Java for the new delta-storage artifact.

For the project overview, requirements, and how to contribute, please see the https://github.com/delta-io/delta/issues/951.

**Comment by PhVHoang** [comment]
Hi @scottsand-db , I would like to give it a try. Could you please assign me to this issue?

And a small question, Is there any reason why `writeWithRename` method from `HadoopFileSystemLogStore.scala` is not bring to that of `java` version? 

https://github.com/delta-io/delta/blob/master/core/src/main/scala/org/apache/spark/sql/delta/storage/HadoopFileSystemLogStore.scala#L113

**Comment by scottsand-db** [comment]
@PhVHoang awesome, thanks! I have assigned the ticket to you. I didn't add `writeWithRename` in the initial implementation since I didn't have any concrete child classes to test it at that time.

Want to make a standalone PR that adds it?

**Comment by scottsand-db** [comment]
@PhVHoang sounds good.

**Comment by PhVHoang** [comment]
@scottsand-db sure, I’ll raise a PR after this one is merged.

**Comment by scottsand-db** [comment]
@PhVHoang it was merged

**Comment by PhVHoang** [comment]
@scottsand-db I raised a PR to resolve this issue. 
Please take a look at it. Thanks so much.

**Comment by vkorukanti** [comment]
Closed via https://github.com/delta-io/delta/commit/fe5e3d7aa7aa71d89b15635fb8db6e76499fd6c0
