### ISSUE TITLE
Delta LogStore Refactor - GCSLogStore

### ISSUE THREAD

**Issue by scottsand-db** [delta-io/delta#956]
Refactor [GCSLogStore](https://github.com/delta-io/delta/blob/master/contribs/src/main/scala/io/delta/storage/GCSLogStore.scala) to Java for the new delta-storage artifact.

This also includes moving the tests from `GCSLogStoreSuite` to class `PublicGCSLogStoreSuite` inside of `LogStoreSuite`. See the contributing section in the project issue below.

Also, as the referenced contributing section states, leave the existing Scala file and Scala test suite alone for now.

For the project overview, requirements, and how to contribute, please see the https://github.com/delta-io/delta/issues/951.

**Comment by ksree** [comment]
Hi @scottsand-db  I will give this a try.

**Comment by ksree** [comment]
@scottsand-db GCSLogsStore calls org.apache.spark.sql.delta.util.DeltaFileOperations.runInNewThread and that calls org.apache.spark.util.ThreadUtils.runInNewThread. How do we get rid of this spark dependency? Create a new standalone utils class?

**Comment by scottsand-db** [comment]
@ksree for now, just create a java implementation of `ThreadUtils.runInNewThread` as a private static method inside of GCSLogStore. if we ever need to expose this method to other logstores, we can expose it as a public util then.

**Comment by scottsand-db** [comment]
@ksree any update? We'd like to get this in for Delta Lake 1.2, so the sooner this is in the better.

If needed, I can also implement this. Let me know.

**Comment by ksree** [comment]
@scottsand-db Sorry for the delay. I will raise a WIP branch soon, to get the runInNewThread implementation reviewed.

**Comment by ksree** [comment]
https://github.com/delta-io/delta/pull/1024

**Comment by ksree** [comment]
#1024

**Comment by ksree** [comment]
@scottsand-db Could you please review if https://github.com/delta-io/delta/pull/1024 is the right approach on implementing the runInNewThread. 
We will need to find out if the GCS Hadoop connector issue is fixed, so that we can get rid of the new thread hack.

**Comment by ksree** [comment]
Thanks @scottsand-db  for the detailed review.
