### ISSUE TITLE
is it safe to use delta with hadoop-aliyun and Aliyun OSS object storage?

### ISSUE THREAD

**Issue by Dieken** [delta-io/delta#965]
Hi,  

I'm testing delta with hadoop-aliyun to create Delta table on Aliyun OSS:

https://hadoop.apache.org/docs/stable/hadoop-aliyun/tools/hadoop-aliyun/index.html

This document mentions some warnings, eg. delete() and rename() are not atomic.  I checked git repositories of Hudi and Iceberg, they have explicit support for Aliyun OSS, but Delta code is purely neutral to cloud service providers, so I want to confirm, is it safe to use Delta with hadoop-aliyun and Aliyun OSS object storage?

Thanks!

**Comment by zsxwing** [comment]
@YannByron Do you know how to use OSS Delta Lake on Aliyun?

**Comment by YannByron** [comment]
@Dieken @zsxwing 
As far as i know, OSS supports atomic rename for single object in non-multi-version, not directory. The OSS team is working on the multi-version case. 
And also, there is OSS-HDFS that support all the syntax of HDFS, including the atomic rename for both single-file and directory.

**Comment by Dieken** [comment]
This is how I use OSS Delta Lake on Aliyun,  I don't use OSS-HDFS because I wouldn't like to buy another service.

```sh
## hadoop-aliyun and its dependencies:
##      hadoop-aliyun-3.3.1.jar aliyun-sdk-oss-3.4.1.jar jdom-1.1.jar jettison-1.1.jar stax-api-1.0.1.jar aliyun-java-sdk-*.jar
##  Delta Lake jar:
##      delta-core_2.13-1.1.0.jar
 
##  Spark 3.2.1 from https://www.apache.org/dyn/closer.lua/spark/spark-3.2.1/spark-3.2.1-bin-hadoop3.2-scala2.13.tgz

jars=$(echo *.jar | sed -e 's/ /,/g')
spark-sql --jars "$jars" \
  --conf spark.hadoop.fs.AbstractFileSystem.oss.impl=org.apache.hadoop.fs.aliyun.oss.OSS \
  --conf spark.hadoop.fs.oss.impl=org.apache.hadoop.fs.aliyun.oss.AliyunOSSFileSystem \
  --conf spark.hadoop.fs.oss.endpoint=oss-cn-shenzhen-internal.aliyuncs.com \
  --conf spark.hadoop.fs.oss.accessKeyId=XXXXXXX \
  --conf spark.hadoop.fs.oss.accessKeySecret=YYYYYYY \
  --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension \
  --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog
 

CREATE TABLE IF NOT EXISTS t (id INT, name STRING, age INT) USING delta LOCATION 'oss://my-bucket/my-delta-table';
 
INSERT INTO t VALUES (1, "hello", 10), (2, "world", 20);
```

I checked the Delta data directory, seems Delta doesn't use sub directory to store data and meta data,  so I guess it's safe to use plain OSS with hadoop-aliyun + delta-core,  right?

**Comment by YannByron** [comment]
@Dieken  I don't know how to use OSS directly without OSS-HDFS for now. Maybe I'll follow up this asap.

**Comment by Dieken** [comment]
> @Dieken I don't know how to use OSS directly without OSS-HDFS for now. Maybe I'll follow up this asap.

Thanks!   You can create a simple Java project with pom.xml containing `hadoop-aliyun:3.3.1`,  then use `mvn dependency:copy-dependencies` to get those jar files,  and use the command above to try delta on Aliyun OSS.

**Comment by scottsand-db** [comment]
@Dieken what's the status of this issue? If you consider it resolved, please close this issue. Else, let me know how I can help further :)

**Comment by Dieken** [comment]
@scottsand-db 

Thanks for your checking!   I want a confirmation whether delta is safe to **directly** use hadoop-aliyun to read/write Aliyun OSS.  Seems @YannByron **implicates** it's safe with OSS-HDFS wrapper service over Aliyun OSS.

https://github.com/delta-io/delta/blob/v1.1.0/core/src/main/scala/org/apache/spark/sql/delta/storage/DelegatingLogStore.scala#L155

It explicitly supports Amazon and Azure object store,  but not mention Aliyun OSS.

**Comment by zsxwing** [comment]
@YannByron do you know which LogStore implementation can work with Aliyun OSS?

**Comment by zsxwing** [comment]
Given this is a question to the vendor rather than the Delta Lake project, I'm going to close this.
