### ISSUE TITLE
Delta Storage loads all Hadoop dependencies

### ISSUE THREAD

**Issue by Kimahriman** [delta-io/delta#967]
This may already be being tracked, but noticed this while trying to test things out on master. delta-storage depends on `hadoop-common` and not as a provided dependency, so if you `spark-shell --packages io.delta:delta-core_2.12:1.2.0-SNAPSHOT` it will load Hadoop and all the things it depends on.

**Comment by zsxwing** [comment]
@Kimahriman Good catch. Do you want to submit a simple fix?

**Comment by Kimahriman** [comment]
I assume making it provided is the fix, but wasn't sure if this would be a problem for future non-spark usages of the new module

**Comment by zsxwing** [comment]
Yep. We want to use provided. For non Spark usages, people still need to pick up the Hadoop version that support their storage system.
