### ISSUE TITLE
[DOCS] Unfinished sentence in delta-batch.html

### ISSUE THREAD

**Issue by jaceklaskowski** [delta-io/delta#977]
At the bottom of https://docs.delta.io/1.1.0/delta-batch.html#dataframe-options there is:

> You can find the details of the Hadoop file system configurations for your storage in _.

Note the hanging `_`. No idea where it comes from but surely the sentence is not finished.

**Comment by scottsand-db** [comment]
@jaceklaskowski thanks for bringing this to out attention. Looking into it.

**Comment by vkorukanti** [comment]
Changes are staged for 1.2
