### ISSUE TITLE
HDFSLogStore.java catch and throw exception mismatch

### ISSUE THREAD

**Issue by PhVHoang** [delta-io/delta#978]
I noticed that in this below code
https://github.com/delta-io/delta/blob/master/storage/src/main/java/io/delta/storage/HDFSLogStore.java#L130
```java
catch (org.apache.hadoop.fs.FileAlreadyExistsException e) {
                throw new FileNotFoundException(path.toString());
}
```
The catch block catches `FileAlreadyExistsException` but throws `FileNotFoundException`.
I think it should also throws `FileAlreadyExistsException`. Do I misunderstand the situation there?

**Comment by zsxwing** [comment]
Good catch. Thanks for raising the issue. Feel free to send a PR to fix it 😄

**Comment by PhVHoang** [comment]
Hi @zsxwing 
I just created a PR to fix it. Please review if you have time.
