### ISSUE TITLE
Spark 3.1.3 with Hadoop 3.2.2 Delta 1.0.1:java.lang.NumberFormatException: For input string: "100M"

### ISSUE THREAD

**Issue by KunWuLuan** [delta-io/delta#987]
I have the current situation:

Delta table located in S3
I want to write this table.
spark version 3.1.3 and hadoop 3.2.2

`        
SparkSession spark = SparkSession.builder()
      .appName("spark_kafka_s3")
      .master("local[2]") 
      .config("spark.jars.packages", "io.delta:delta-core_2.12:1.0.1")
      .config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension")
      .config("spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog")
      .getOrCreate();
`
I try to read message from kafka and write the analysis results in to S3
`
head.coalesce(1).writeStream()
                .format("delta")
                .option("checkpointLocation",path +  "/checkpoint/" + headTableName)
                .option("mergeSchema", "true")
                .outputMode("append")
                .partitionBy("ds", "hh")
                .start(path + "/" + headTableName);
`
My script is like this
`
bin/spark-submit --master spark://server01:xxx --packages io.delta:delta-core_2.12:1.0.1,com.amazonaws:aws-java-sdk-pom:1.11.1034,org.apache.hadoop:hadoop-aws:3.2.2 --conf "spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog" --conf "spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension" --class org.example.App /root/x/out/artifacts/x/x.jar 1
`

I got error like this:
![image](https://user-images.githubusercontent.com/30817980/157198504-a6fd1bfe-34d1-4c56-a2e1-15d7c3bb1d95.png)

I have read the issue #639 https://github.com/delta-io/delta/issues/639
However, Delta 1.01 is proposed to support Spark 3.1.x.
So I have no idea how to solve the problem. 
Greatful for anyone potentially encountering the same issue.

**Comment by zsxwing** [comment]
You have an invalid value `100M` in some config. You can search `100M` in your code, hadoop configuration file or system environment to find out that.

**Comment by KunWuLuan** [comment]
There is a property in core-default.xml of hadoop-common 3.2.2:
<img width="884" alt="image" src="https://user-images.githubusercontent.com/30817980/157356002-fe509f0f-7b8d-41e6-976a-637cda84ea41.png">


my maven is like this:
![image](https://user-images.githubusercontent.com/30817980/157356030-7283100b-9eb0-4186-918c-b488fb2a6da7.png)


where $hadoop.version=3.2.2

When I tried to debug, I found the problem:
![image](https://user-images.githubusercontent.com/30817980/157354805-544121ae-0891-4628-ad6c-652b3488a957.png)

Program crashed in the parseLong.
After I overwrite the property through:

sparkContext.hadoopConfiguration().set("fs.s3a.multipart.size","104857600");

I got another problem. T_T
![image](https://user-images.githubusercontent.com/30817980/157355904-00a891ab-c365-4ec4-aa44-957f2f7fdbb1.png)




Is this problem related to the hadoop version?

**Comment by zsxwing** [comment]
Where did you download Spark? My hunch is your Spark is not compatible with Hadoop 3. You can find the compatible package in https://spark.apache.org/downloads.html

**Comment by KunWuLuan** [comment]
First I tried spark 3.1.3 with hadoop 2.7, then I tried spark 3.1.3 with hadoop 3.2.2. They all failed.
Finally I tried spark 3.1.3 without hadoop, this time I get no crash. Thank you very much.

**Comment by zsxwing** [comment]
Great to hear that you solved the problem. Yep, if you have Hadoop installed, Spark without hadoop is the right one to use. Closing this one as it's solved.
